### ISSUE TITLE
Unit Testing specific actions

### ISSUE THREAD

**Issue by craigwillis85** [elastic/elasticsearch-php#1002]
Looking at the README, it suggests that you can mock the Elastic Client to run some "unit tests".

I'm aware that the "body" will return whatever is in the json file supplied in the `MockHandler`

Is there a way though to actually run things like:

    $response = $this->client->search([
         'index' => 'my_index',
         'type' => 'my_type',
         'body' => [
                [
                    'query' => [
                        'simple_query_string' => [
                            'fields' => ['name'],
                            'query' => 'Bob'
                        ]
                    ]
                ]
            ]
        ]);

i.e. to be able actually run ES specific methods on the data? It seems pretty redundant, unless you create a json file for each type of action/test case

Thanks

**Comment by ezimuel** [comment]
If you don't want to create a json file, tou can use the `php://memory` stream to pass the `body`.
For instance, something like this:
```php
require 'vendor/autoload.php';

use GuzzleHttp\Ring\Client\MockHandler;
use Elasticsearch\ClientBuilder;

$body = [
    'query' => [
        'simple_query_string' => [
            'fields' => ['name'],
            'query' => 'Bob'
        ]
    ]
];
$stream = fopen('php://memory', "w+");
fwrite($stream, json_encode($body));
rewind($stream);

$mock = new MockHandler([
  'status' => 200,
  'transfer_stats' => [
     'total_time' => 100
  ],
  'body' => $stream,
  'effective_url' => 'localhost'
]);
$builder = ClientBuilder::create();
$builder->setHosts(['somehost']);
$builder->setHandler($mock);
$client = $builder->build();

$response = $client->search([
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [ $body ]
]);
var_dump($response);
/*
array(1) {
  ["query"]=>
  array(1) {
    ["simple_query_string"]=>
    array(2) {
      ["fields"]=>
      array(1) {
        [0]=>
        string(4) "name"
      }
      ["query"]=>
      string(3) "Bob"
    }
  }
}
*/
fclose($stream);
```

**Comment by craigwillis85** [comment]
Thanks @ezimuel for the feedback.

I guess I'm a little confused as to why do this at all? 

If I create the $body array and even if I called `search()`, `update()` etc it will return the same array. 

So, correct me if I'm wrong, but what is it actually testing? Is it just testing that the ES Client can be mocked, because everything else seems a little pointless as it isn't testing anything of actual value.

Thanks

**Comment by ezimuel** [comment]
@craigwillis85 the idea of `GuzzleHttp\Ring\Client\MockHandler` is to have a class that acts like a real client without doing the HTTP connection. This can be useful for unit testing, since you don't want to test the connection itself but the behaviour of your Client.

A real use case can be to mock real HTTP responses from Elasticsearch. If you store a response from Elasticsearch in a json file, you can use this `MockHandler` to test your code with the predefined response without running Elasticsearch again.
This is actually something I'm considering to speed up the integration test that I'm running against a Elasticsearch node, see [here](https://travis-ci.org/elastic/elasticsearch-php/jobs/655720880#L434).

**Comment by craigwillis85** [comment]
@ezimuel I get that it won't be doing any HTTP calls. I guess I thought it would "act" like real HTTP responses. i.e. I put a full index of data in JSON, run `search()` with a query and it actually searched the JSON. 

Instead it, just returns the whole "body", which I understand tests the Client, but in practice only needs to be done once (as you pass in the body and the Client returns the same body, every single time). 

I guess I'll go down the JSON HTTP responses and maybe have a CI env that actually makes HTTP calls to ES (faked data) to make sure that it actually works

**Comment by ezimuel** [comment]
I'm closing this issue. Let me know if you want to reopen for mode information or discussion.

**Comment by anam-hossain** [comment]
@ezimuel is there any way to mock multiple requests in one call?

Is it possible something like the Guzzle [HandlerStack](http://docs.guzzlephp.org/en/stable/testing.html)?

```php
$response1 = [
  'status' => 200,
  'transfer_stats' => [
     'total_time' => 100
  ],
  'body' => $stream,
  'effective_url' => 'localhost'
];

$response2 = [
  'status' => 200,
  'transfer_stats' => [
     'total_time' => 100
  ],
  'body' => $stream,
  'effective_url' => 'localhost'
];

$mock = new MockHandler([
   $response1,
   $response2
]);
```
