### ISSUE TITLE
Prefix search instead of multi-match

### ISSUE THREAD

**Issue by nicolasvahidzein** [elastic/elasticsearch-php#1009]
Hello, i posted on SO to get some feedback as i was not able to find docs on here to execute a search that would match partial strings:

[https://stackoverflow.com/questions/60716639/how-to-implement-elastic-search-in-laravel-for-auto-complete](url)

Can point me to the place where i can see how prefix search is done in ES for laravel please?

Thanks.

**Comment by ezimuel** [comment]
You can use [wildcard query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html) in order to search for partial strings.

For instance, if you want to search for documents where the `user` field contains a term that begins with `ki` and ends with `y` (example [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html#wildcard-query-ex-request)):

```php
use Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()->build(); // instance of Elasticsearch\Client
$result = $client->search([
    'body' => [
        'query' => [
            'wildcard' => [
                'user' => [
                    'value' => 'ki*y' // here the wildcard query
                ]
            ]
        ]
    ]
]);

```
In the Laravel [blog post](https://madewithlove.com/how-to-integrate-elasticsearch-in-your-laravel-app-2019-edition/) that you reported, you need to change the `App\Articles\ElasticsearchRepository::searchOnElasticsearch()` function with the wildcard query.

If you need to search for multiple fileds using wildcard, you can use also the [filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html#query-filter-context-ex) option.

**Comment by nicolasvahidzein** [comment]
Hello @ezimuel i tried your way but it returns no results. You do not attach the model in your query i noticed. And even when i do it returns nothing.

```

		$client = ClientBuilder::create()
		->setHosts(config('services.search.hosts'))
		->build();
		
		
		
		// using wildcard query
		$items2 = $client->search([
			'index' => $model->getSearchIndex(),
            'type' => $model->getSearchType(),
			'body' => [
				/* 
				'query' => [
                    'multi_match' => [
                        'fields' => ['brand', 'name^5', 'description'],
                        'query' => $query,
                    ],
				],
				 */
				
				'query' => [
					'wildcard' => [
						'user' => [
							'value' => $query.'*' //wildcard
						]
					]
				]
				
			]
		]);
		
```

**Comment by ezimuel** [comment]
@nicolasvahidzein you need to change the `user` field with the one that you are looking for. This was just an example extracted from the Elasticsearch documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html). As you noticed, I didn't specify also the `index` and the `type` but you did correctly in your code.

Question: do you want to use the same Laravel code presented in the [blog post](https://madewithlove.com/how-to-integrate-elasticsearch-in-your-laravel-app-2019-edition/)? In this case I guess you should use [query string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) changing the `App\Articles\ElasticsearchRepository::searchOnElasticsearch()` as follows:

```php
private function searchOnElasticsearch(string $query = ''): array
{
    $model = new Article;

    $items = $this->elasticsearch->search([
        'index' => $model->getSearchIndex(),
        'type' => $model->getSearchType(),
        'body' => [
            'query' => [
                'query_string' => [
                    'fields' => ['title^5', 'body', 'tags'],
                    'query' => $query . '*',
                ],
            ],
        ],
    ]);

    return $items;
}
```
You can also omit to add the `'*'` to `$query` and pass it directly in the `$query` parameter.
I hope this will help you.

**Comment by nicolasvahidzein** [comment]
Thank you so much @ezimuel.

I modified it like this:

```
$items = $this->elasticsearch->search([
			'index' => $model->getSearchIndex(),
			'type' => $model->getSearchType(),
			'body' => [
				
				//this helped a lot
				// https://stackoverflow.com/questions/60716639/how-to-implement-elastic-search-in-laravel-for-auto-complete
				
				//multi-match query
				/* 'query' => [
					'multi_match' => [
						'fields' => ['brand', 'name^5', 'description'],
						'query' => $query,
					],
				], */
				
				//wildcard search
				'query' => [
					'wildcard' => [
						'name' => [
							'value' => $query.'*' //wildcard
							// 'value' => 'be*' //wildcard
						]
					]
				]
				
			],
		]);
```

and now it works with partial searches BUT guess what another problem. Now once i typed "bear na" it gives no more results. It seems like a

**Comment by nicolasvahidzein** [comment]
Nevermind @ezimuel i got it to work with your example of query_string!!!!!!!!!!!!!!!!!!!

You are so kind and wonderful, we got it to work perfectly as i needed. 

Thank you thank you thank you!!! Can i buy you a coffee?

**Comment by ezimuel** [comment]
Thanks for you kind words. I'm happy to help. Thanks for the virtual coffee!

**Comment by jihadadulrazaqjasim** [comment]
Dears,
I want to do something like below link:
https://www.youtube.com/watch?v=ZDCBXX4S7uQ

explanation:

I want to search against multiple indices same like above using query strings, but I also want the index names that it's field matched with the searched text, and then I want to highlight matched text inside each index (document of index),

please your support, it's very important for me, thanks a lot.
