### ISSUE TITLE
SQL query support

### ISSUE THREAD

**Issue by thomasdv** [elastic/elasticsearch-php#1019]
Is there a way to run SQL queries from PHP client or in general run queries against a custom endpoint?

**Comment by philkra** [comment]
Hi @thomasdv,

> run SQL queries

Are you referring to the [SQL endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest-overview.html) in Elasticsearch? If so, yes the Client contains a method to query the SQL endpoint in Elasticsearch [SqlNamespace](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/SqlNamespace.php)

> run queries against a custom endpoint

The Client covers all endpoints to Elasticsearch, can you please explain your use case a bit?

**Comment by thomasdv** [comment]
Hi @philkra,

thanks. I have installed elasticsearch/elasticsearch v7.6.1 and there is no SqlNamespace.

I use Open Distro - would it work there too? They use _opendistro/_sql endpoint and I don't know if there are any other major differences that would be incompatible with this library.

Thanks again.

**Comment by ezimuel** [comment]
@thomasdv the `SqlNamespace` is part of XPack support that will be added in **7.7 release**, planned later this week. If you want to try right now you can use the `7.7` branch, you can install using the following composer command:
```bash
composer require elasticsearch/elasticsearch:7.7.x-dev
```

**Comment by ezimuel** [comment]
@thomasdv this library supports Elasticsearch and not Open Distro. The SQL endpoint (and syntax) is different and will not work for Open Distro.
