### ISSUE TITLE
Support for iteration over composite aggregation responses

### ISSUE THREAD

**Issue by jgough** [elastic/elasticsearch-php#1024]
There doesn't seem to be an automatic way to iterate over composite aggregation responses:
https://www.elastic.co/guide/en/elasticsearch/reference/7.6/search-aggregations-bucket-composite-aggregation.html

This is done by taking the _after_key_ field and then feeding it back to the next request via the _after_ parameter - much like the scroll API.

Would be a very useful feature to have this rather than having to manually pass these around and keep making queries.

**Comment by magical-travvo** [comment]
We're having the same issue, it would be good to be able to do this without creating something external to Elasticsearch, which would defeat the purpose of using Watcher.

**Comment by Renrhaf** [comment]
Hi & thank you for your work on this useful library. Could you give me a hint on how to use this feature with the current version of the module ? Thanks !
