### ISSUE TITLE
Wrong exception parameters

### ISSUE THREAD

**Issue by HorvathPeterHub** [elastic/elasticsearch-php#1035]
### Summary of problem or feature request

There are situations when the ES gives back null as error reason. In such situations the expected exception cannot be created because of a PHP TypeError.

### Code snippet of problem

Response from the server:
```json
 string(151) "{"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}"
```

And the failing code snippet:
src\Elasticsearch\Connections\Connection.php:702
```php
return new $errorClass($error['error'], (int) $response['status'], $original);
```

The $error variable contains:
```php
array(2) {
  'error' =>
  array(3) {
    'root_cause' =>
    array(1) {
      [0] =>
      array(2) {
        ...
      }
    }
    'type' =>
    string(31) "master_not_discovered_exception"
    'reason' =>
    NULL
  }
  'status' =>
  int(503)
}
```

Since the exception constructor expects the first parameter to be a string, and an array is passed, if gives a TypeError.

I think the if branch above at line 683 should handle this case, but since the isset() gives false for an existing but null-containing variable, it jumps to the next elseif.

### System details

- Operating System: Debian
- PHP Version: 7.4.6
- ES-PHP client version: 7.4.1.
- Elasticsearch version: 7.4.2

**Comment by ezimuel** [comment]
This issue has been resolved in `elasticsearch-php` 7.5.0, see https://github.com/elastic/elasticsearch-php/commit/f148afa19e91960fd5bd8a13a199d539e59f3d95. You can use the latest 7.5.x release, that is [7.5.1](https://github.com/elastic/elasticsearch-php/releases/tag/v7.5.1), since you are using Elasticsearch 7.4.2.
