### ISSUE TITLE
Guzzle ClientErrorResponseException when I try to index a new row through eloquent.

### ISSUE THREAD

**Issue by miguelmsoler** [elastic/elasticsearch-php#1041]
### Summary of problem or feature request

I'm working in an old Laravel 5 project. Elasticsearch server is ver. 2.3.3 and elasticsearch-php is 1.1. I read in the docs that they are compatible.

The site is up and running since 2017 at least. But after some changes I can not save values using Eloquent since I get a Guzzle\Http\Exception\ClientErrorResponseException.

It's strange, because the reason why this exception appears seems to be that elasticsearch is trying to get the data instead of indexing it. The reported url is  http://search.******.***/******/winwins/59.

I know I'm saving the record, because if I follow the stacktrace after the exception I get to #28 /home/forge/***.***/backend/app/Http/Controllers/WinwinController.php(551): Illuminate\Database\Eloquent\Model->save()

Do you know what could have gone wrong? Should I update to 2.0 version?

### Code snippet of problem
My observer is:

```php
class ESWinwinObserver {

    private $elasticsearch;

    public function __construct(Client $elasticsearch) {
        $this->elasticsearch = $elasticsearch;
    }

    public function created(Winwin $winwin) {
        $this->elasticsearch->index([
            'index' => 'winwins',
            'type' => 'winwins',
            'id' => $winwin->id,
            'body' => $winwin->toArray()
        ]);
        Log::info('Indexed ww');
    }

    public function updated(Winwin $winwin) {
        $this->elasticsearch->index([
            'index' => 'winwins',
            'type' => 'winwins',
            'id' => $winwin->id,
            'body' => $winwin->toArray()
        ]);
    }

    public function deleted(Winwin $winwin) {
        $this->elasticsearch->delete([
            'index' => 'winwins',
            'type' => 'winwins',
            'id' => $winwin->id
        ]);
    }
}

```

### System details

- Operating System: Linux
- PHP Version: 5.6.99-hhvm
- ES-PHP client version: 1.1 (composer.json has ~1.0)
- Elasticsearch version: 2.3.3

**Comment by ezimuel** [comment]
@miguelmsoler we are not supporting anymore elasticsearch-php `1.x` or `2.x`. That said, we suggest to use elasticsearch-php 2.x with the following composer configuration:
```json
"require": {
    "elasticsearch/elasticsearch": "~2.0"
}
```
