### ISSUE TITLE
Mock multiple responses

### ISSUE THREAD

**Issue by anam-hossain** [elastic/elasticsearch-php#1043]
Guzzle Mock Handler supports mocking multiple responses using HandlerStack. Is there anything similar for the Ring MockHandler. I have a controller which currently running two queries to ElasticSearch. 

Is there a way to test two requests to Elastic search? 

I can see, I can only test one request using the following:
https://github.com/elastic/elasticsearch-php/issues/589#issuecomment-306335931

Guzzle mock handler with multiple requests:
http://docs.guzzlephp.org/en/stable/testing.html

**Comment by ezimuel** [comment]
@anam-hossain I see that `GuzzleHttp\Ring\Client\MockHandler` supports array as well in the constructor, see [here](https://github.com/ezimuel/ringphp/blob/master/src/Client/MockHandler.php#L23). You can try to pass multiple reponses (not requests) as follows:

```php
use GuzzleHttp\Ring\Client\MockHandler;
use Elasticsearch\ClientBuilder;


$handler = new MockHandler(
    [
        'status' => 200, 
        'transfer_stats' => [
            'total_time' => 100
        ], 
        'body' => fopen('somefile.json')
    ],
    [
        'status' => 200, 
        'transfer_stats' => [
            'total_time' => 150
        ], 
        'body' => fopen('somefile2.json')
    ],
);
$builder = ClientBuilder::create();
$builder->setHosts(['somehost']);
$builder->setHandler($handler);
$client = $builder->build();
```
Let me know if this solve your use case, thanks!

**Comment by anam-hossain** [comment]
@ezimuel Thank you for the reply. I did a test with multiple responses. It seems the error goes away but second response returning an empty result.

```php
    $responses = ['{"foo1": "bar1"}', '{"foo2": "bar2"}'];
      
        $result = [];

        foreach ($responses as $response) {
            $result[] = [
                'status' => $status,
                'transfer_stats' => [
                    'total_time' => 100,
                ],
                'body' => fopen('data://text/plain,' . $response, 'r'),
                'effective_url' => 'localhost'
            ];
        }

        $handler = new MockHandler($result[0], $result[1]);

        $builder = ClientBuilder::create();
        $builder->setHosts(['somehost'])->setHandler($handler);

        $client = $builder->build();

        dd($client->search([]), $client->search([]));
```

**Output:**

```
^ array:1 [
  "foo1" => "bar1"
]
^ []
```

**Comment by wotta** [comment]
Since this ticket has been open for quite some time I hope somebody does actually has found out a way how to do this.

Would be much appreciated to learn how to properly handle multiple responses.

**Comment by imdhemy** [comment]
Hello there!

I joined the party late, hope this is useful for you.

I wrote these utils to help mock ES, you can find there how to mock multiple requests/responses.

- [For ES 7.x](https://github.com/imdhemy/es-testing-utils/tree/7.x)
- [For ES 8.x](https://github.com/imdhemy/es-testing-utils/tree/8.x)

You can add it as a dev dependency or just follow the code and use it in your tests.
