### ISSUE TITLE
Is there a way to supply http headers using elasticsearch-php?

### ISSUE THREAD

**Issue by ptrknow** [elastic/elasticsearch-php#1053]
In Perl, for example, I can do something like this

```perl
my $e = Search::Elasticsearch->new(
       default_headers => { 'custom_header' => 'content' }
);
```

Can I achieve something similar using elasticsearch-php?

**Comment by ezimuel** [comment]
Yes, you can speficy custom headers globally or for each request.

**As global option, as part of the client options**
```php
use Elasticsearch\ClientBuilder;

$clientBuilder = ClientBuilder::create();
$params = [
    'client' => [
        'headers' => [
            'Foo' => 'Bar' // header name => value
        ]
    ]
];
$clientBuilder->setConnectionParam($params);
$client = $clientBuilder->build();
```

**Or for each request**
```php
// example of get endpoint
$params = [
    'index' => 'test',
    'id'    => 1,
    'client' => [
        'headers' => [
            'Foo' => 'Bar' // header name => value
        ]
    ]
];
$response = $client->get($params);
```

**Comment by ptrknow** [comment]
Thank you for the help.

Unfortunately, your way of specifying didn't work. I have gone through other issues and, by trial-and-error, found that the following way works:
```Perl
$params = [
    'client' => [
	'curl' => [
		CURLOPT_HTTPHEADER => [
			'Content-type: application/json',
			'Header: Value'
		]
	]
   ]
];
```

I don't quite get the technical difference between your way and the above way though.

**Comment by DanielFrancois** [comment]
Hi just adding this for people reaching this thread as I did:
`// example of get endpoint
$params = [
    'index' => 'test',
    'id'    => 1,
    'client' => [
        'headers' => [
            'Foo' => ['Bar'] // header name => value
        ]
    ]
];
$response = $client->get($params);`

Header value(s) must be an array to work: https://github.com/guzzle/RingPHP/blob/5e2a174052995663dd68e6b5ad838afd47dd615b/src/Client/CurlFactory.php#L296

**Comment by oshell** [comment]
> Thank you for the help.
> 
> Unfortunately, your way of specifying didn't work. I have gone through other issues and, by trial-and-error, found that the following way works:
> 
> ```perl
> $params = [
>     'client' => [
> 	'curl' => [
> 		CURLOPT_HTTPHEADER => [
> 			'Content-type: application/json',
> 			'Header: Value'
> 		]
> 	]
>    ]
> ];
> ```
> 
> I don't quite get the technical difference between your way and the above way though.

this worked for me.
I needed it for doing basic auth using base64 encoded string like this

```
          $basicAuth = base64_encode($user . ":" . $password);
            $params = [
                'client' => [
                    'curl' => [
                        CURLOPT_HTTPHEADER => [
                            'Content-type: application/json',
                            "Authorization: Basic $basicAuth"
                        ]
                    ]
                ]
            ];

            $clientBuilder->setConnectionParams($params);
```

setting `user` and `pass` within hosts, did not work for me
