### ISSUE TITLE
Facets error

### ISSUE THREAD

**Issue by Aberbin96** [elastic/elasticsearch-php#1060]
Hello, I try to use facets in my search function, but not working. You can help me here:

```
$params = Array ( 
  [body] => Array ( 
    [query] => Array ( 
      [match_all] => stdClass Object ( ) 
    ) 
    [facets] => Array ( 
      [short_name] => Array ( 
        [type] => value 
        [name] => all_name 
        [sort] => Array ( 
          [count] => desc 
        ) 
        [size] => 5 
      )
    ) 
  ) 
  [index] => test
)
$response = app()->elasticSearch->search($params);
```

When I run this code only show:
Unknown key for a START_OBJECT in [facets].","line":1,"col":36

- PHP Version: 7.1
- Elasticsearch version: "elasticsearch/elasticsearch": "7.8.0",

**Comment by ezimuel** [comment]
Facets has been replaced by [Aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-aggregations.html) since Elasticsearch 1.0. If you want to aggregate the field `all_name` in your example you can use the following parameters:

```php
$params = [
    'index' => 'test',
    'body' => [
        'query' => [
            'match_all' => (object) []
        ],
        'aggs' => [
            'short_name' => [
                "terms" => [
                    "field" => "all_name",
                    "size" => 5
                ]
            ]
        ]
    ]
];

$result = $client->search($params);
```

**Comment by ianengelbrecht** [comment]
@ezimuel there is facet documentation for version 7.10 at [elastic.co/guide/en/app-search/current/facets.html](https://www.elastic.co/guide/en/app-search/current/facets.html). So I'm unclear whether I should use facets or aggregations if both are available.

**Comment by ezimuel** [comment]
@ianengelbrecht the documentation that you pointed out is for `Elastic App Search` and not `Elasticsearch`.
