### ISSUE TITLE
Incorrect documentation in Ignoring exception section

### ISSUE THREAD

**Issue by retnek** [elastic/elasticsearch-php#1071]
Hi,

I've found a minor typo in your documentation here:
https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/per_request_configuration.html#_ignoring_exceptions
I think there's no MissingDocument404Exception rather Missing404Exception.
You can check this in github also: https://github.com/elastic/elasticsearch-php/search?q=MissingDocument404Exception

Cheers!

**Comment by ezimuel** [comment]
@retnek thanks for reporting this. May you want to send a PR for fixing the documentation page https://github.com/elastic/elasticsearch-php/blob/7.x/docs/per-request-configuration.asciidoc ?
Let me know, thanks!
