### ISSUE TITLE
sort name in elasticsearch by php

### ISSUE THREAD

**Issue by netwons** [elastic/elasticsearch-php#1079]
im can not sort by name?

```$params=[
    			'index'=>'pets',
    			'type'=>'bird',
    			'body'=>[
    				'query'=>[
    					'bool'=>[
    						'must'=>[],
    						'filter'=>[
    							'range'=>[
	    							'registered'=>[
	    							'gte' => "2020-10-01", 
	    							'lte' => "2020-11-30"]
	    						]
    						]
    					]
    				],
    				'sort'=>[
    					'name'=>[
    						'order'=>'asc'
    					]
    				]
    				
    			]
    		];```

**error:**

**Elasticsearch\Common\Exceptions\BadRequest400Exception
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}],"type":"search_phase_execution_exception","reason":"all**

**Comment by ezimuel** [comment]
Which endpoint (API) are you using here?

**Comment by netwons** [comment]
no api
im use package elasticsearch/elasticsearch in laravel

**Comment by science695** [comment]
@netwons this error is coming back from the elastic server, and seems to be an issue with your mapping.

It is saying that fields of type 'text' are not indexed in a way that you can sort on them.

You may want to look at a different type, or a subfield that holds the beginning of the text field for sorting.

**Comment by ezimuel** [comment]
@netwons I'm sorry but we cannot help on specific question about Laravel. As suggested by @netwons, this can be an issue with your mapping. For more information about mapping I suggest to have a look at Elasticsearch documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html).
