### ISSUE TITLE
Coroutine internal error: Object of class Swoole\Curl\Handler could not be converted to int

### ISSUE THREAD

**Issue by webchen** [elastic/elasticsearch-php#1082]
env:
swoole 4.5.9
while using "curl_init", it becomes to the "\swoole\curl\handler", and it can not convert to int

curl should be coroutine, please fix it, thanks.

error code:
    private function checkoutEasyHandle()
    {
        // Find an unused handle in the cache
        if (false !== ($key = array_search(false, $this->ownedHandles, true))) {
            $this->ownedHandles[$key] = true;
            return $this->handles[$key];
        }
        // Add a new handle
        $handle = curl_init();
   **$id = (int) $handle;    // this line**
        $this->handles[$id] = $handle;
        $this->ownedHandles[$id] = true;
        return $handle;
    }

trace: 

#0 /vendor/ezimuel/ringphp/src/Client/CurlHandler.php(110): Swoft\Error\DefaultErrorDispatcher->handleError(8, 'Object of class...', '/var/www/swoft/...', 110, Array)
#1 /vendor/ezimuel/ringphp/src/Client/CurlHandler.php(84): GuzzleHttp\Ring\Client\CurlHandler->checkoutEasyHandle()
#2 /vendor/ezimuel/ringphp/src/Client/CurlHandler.php(68): GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray(Array)
#3 /vendor/ezimuel/ringphp/src/Client/Middleware.php(30): GuzzleHttp\Ring\Client\CurlHandler->__invoke(Array)
#4 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(260): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array)
#5 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(236): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest('POST', '/user_center/_d...', Array, '{"@timestamp":"...', Array, Object(Elasticsearch\Transport))
#7 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1637): Elasticsearch\Transport->performRequest('POST', '/_d...', Array, Array, Array)
#8 /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(829): Elasticsearch\Client->performRequest(Object(Elasticsearch\Endpoints\Index))
#9 /app/Helper/ESHelper.php(125): Elasticsearch\Client->index(Array)

**Comment by science695** [comment]
@webchen Are you posting an issue in a Guzzle dependency in the elasticsearch-php project?

Is this something that needs to be updated in ezimuel/ringphp?

**Comment by ezimuel** [comment]
@webchen I'm sorry but we don't support Swoole at the moment. We are working on the next major release of `elasticsearch-php` and we will try to test it using async/coroutine support, e.g. swoole.
