### ISSUE TITLE
PHP Version Support

### ISSUE THREAD

**Issue by reedy** [elastic/elasticsearch-php#1083]
Hello!

I'd like to request an update/clarification to https://github.com/elastic/elasticsearch-php#php-version-requirement about the PHP versions supported.

<img width="871" alt="Screenshot 2020-12-01 at 13 20 21" src="https://user-images.githubusercontent.com/67615/100745971-fa953600-33d7-11eb-8876-c963b142b34f.png">

The table doesn't use semver (and it shouldn't necessarily), but `>= 7.0.0` and `>= 7.1.0` would suggest to me that ES-PHP 6.0 and 7.0 *technically* support PHP 8.0, (which is obviously out now as a stable release!) but it doesn't, and can be confirmed by looking at https://github.com/elastic/elasticsearch-php/blob/6.x/composer.json#L16 which as `^7.0` and https://github.com/elastic/elasticsearch-php/blob/7.x/composer.json#L16 which has `^7.1`. And `^7.0` basically means `>=7.0.0 <8.0.0` etc.

Anything we can do for clarification? As I'm sure there are going to be people coming along and thinking PHP 8 should work...

Thanks!

**Comment by Radiergummi** [comment]
Most probably, it will be enough to update the version requirement to `>=7.1|^8.0` and release a patch for it.

**Comment by ezimuel** [comment]
@reedy when you read `PHP >= 7.1.0` this means the minimum PHP requirement, until the next major. I'll improve the table in the README.md to be more clear. If you have any suggestion you can send a PR, thanks!

**Comment by reedy** [comment]
Like I say, if it was semver syntax, I'd agree. But 8.0.0 >= 7.1.0... And many projects are using basically that syntax in their composer.json to include support for PHP 8.0

**Comment by ezimuel** [comment]
PHP Version Requirement
----
Version 7.x can be used starting from PHP version 7.1. In addition, it requires the native JSON
extension to be version 1.3.7 or higher.

PHP 8 is supported starting from `elasticsearch-php` 7.11.

| Elasticsearch-PHP Branch | PHP Version |
| ----------- | ------------------------ |
| >= 7.11.0, < 8.0.0  | >= 7.1.0, < 9.0.0        |
| >= 7.0.0,  < 7.11.0 | >= 7.1.0, < 8.0.0        |
| 6.x         | >= 7.0.0, < 8.0.0        |
| 5.x         | >= 5.6.6, < 8.0.0        |
| 2.x         | >= 5.4.0, < 7.0.0        |
| 0.4, 1.x    | >= 5.3.9, < 7.0.0        |

@reedy, @Radiergummi  is this matrix version more clear?

**Comment by Radiergummi** [comment]
@ezimuel that looks clear as day, thank you! I originally implied that PHP 8 support should simply be granted for the 7.x branch (given that it technically only requires a patch and wouldn't have to be explicitly listed), but then again I'm not involved with the project yet. So 7.11 it is :)

**Comment by ezimuel** [comment]
@Radiergummi Since each elasticsearch-php `7.y` client works with all the `7.x` Elasticsearch versions where x <= y, I don't need to backport the change for PHP 8 in the previous client versions.

**Comment by dakorpar** [comment]
any ETA on 7.11 release?

**Comment by ezimuel** [comment]
We are going to release 7.11 soon, it should happen this month.

**Comment by volkv** [comment]
> We are going to release 7.11 soon, it should happen this month.

We still really hope so :)
Thanks!

**Comment by adithyasrinivasan** [comment]
Sorry to be that person, but any luck?

I'm waiting on support for PHP8 so other libraries that [arbeitnow](https://arbeitnow.com) uses can update to it :)

Thanks!

**Comment by ezimuel** [comment]
@adithyasrinivasan, @volkv we are going to release 7.11 it very soon! Unfortunately, we had some delay.

**Comment by ezimuel** [comment]
I just released `elaticsearch-php` [7.11.0](https://github.com/elastic/elasticsearch-php/releases/tag/v7.11.0) that supports PHP 8.

**Comment by adithyasrinivasan** [comment]
Thanks @ezimuel - appreciate it, can't wait to upgrade!

**Comment by ezimuel** [comment]
Thanks to all the [contributors](https://github.com/elastic/elasticsearch-php/graphs/contributors)!

**Comment by fghamsary** [comment]
We are still using v6.7.2 because of compatibility issue in our application, but this version is not compatible with PHP 8.
I'm doing some tests and I'll create a PullRequest as soon as I've corrected the couple problems which are in the code.
I've already forked and started the work, if anybody else is interested:
https://github.com/fghamsary/elasticsearch-php

**Comment by ezimuel** [comment]
@fghamsary and @xvilo you can update to [v6.8](https://github.com/elastic/elasticsearch-php/releases/tag/v6.8.2) that is compatible with PHP 8.
