### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by reedy** [elastic/elasticsearch-php#1084]
Following on from the clarification requested in https://github.com/elastic/elasticsearch-php/issues/1083 and https://github.com/elastic/elasticsearch-php/issues/1028 as the next major release...

Is the elasticsearch-php 8.0 release going to have PHP 8 support?

**Comment by reedy** [comment]
It was a question brought up in https://github.com/ruflin/Elastica/pull/1799#issuecomment-727873863 to help them work out when to do a ruflin/Elastica release with PHP 8.0 support too; which is not so helpful if elasticsearch-php doesn't support it in a release :)

**Comment by sebsel** [comment]
Note that before `elastic/elasticsearch-php` can be upgraded, the dependency `cpliakas/git-wrapper ~2.0` must be updated to support PHP 8 too.

**Comment by reedy** [comment]
> Note that before `elastic/elasticsearch-php` can be upgraded, the dependency `cpliakas/git-wrapper ~2.0` must be updated to support PHP 8 too.

Looks like a bump to `~3.0.3` would suffice (along with any code changes as appropriate). 3.0.2 still has `^7.2` for PHP support

**Comment by sebsel** [comment]
Yes, that does seem to work. After that there is only the problem of `phpunit/phpunit ^7.5`, with phpunit 8 having you add `: void` after all `setUp()` `tearDown()` methods on tests and some other deprecations.

**Comment by sebsel** [comment]
Linking this PR up for discoverability: https://github.com/elastic/elasticsearch-php/pull/1063

**Comment by reedy** [comment]
> Yes, that does seem to work. After that there is only the problem of `phpunit/phpunit ^7.5`, with phpunit 8 having you add `: void` after all `setUp()` `tearDown()` methods on tests and some other deprecations.

Dropping PHP 7.1 support would help here... 7.1 has been EOL for about a year at this point

And PHPUnit 7 doesn't support PHP 7.4 either (and is EOL itself too)

PHPUnit 8 supports PHP 7.2, PHP 7.3, PHP 7.4, PHP 8.0

https://phpunit.de/supported-versions.html

Time to file another task

**Comment by michaeldnelson** [comment]
I'm sorry if this has been covered somewhere already.  Is there an ETA on PHP 8 support or are we in a wait and see situation?  I foolishly started a port of my existing codebase and missed this dependency.

**Comment by ezimuel** [comment]
PHP 8 is supported in `7.x` branch. I'll ship this it in 7.11 release, when Elasticsearch 7.11 will be released.
Regarding PHP 7.1 support we need to have it until Elasticsearch 8.

**Comment by jchenrev** [comment]
Will PHP support be backported to elasticsearch-php 6.x ? 
Still using ES 6.

**Comment by jchenrev** [comment]
OK for anyone interested, I found the answer here https://github.com/elastic/elasticsearch-php/issues/1083#issuecomment-747315216, 
which is PHP 8 support won't be backported to elasticsearch-php 6.x and 5.x

**Comment by jitheshjs983** [comment]
Hi
i upgraded my php version to 8 , **tamayo/laravel-scout-elastic** version to 8.1 and **elasticsearch/elasticsearch** version to 8.0
After that i'm getting some error saying **Please install the Elasticsearch PHP client: elasticsearch/elasticsearch** in **LaravelScoutElasticProvider.php line 42**

I can see that the error is throwing because the class is not loading **ClientBuilder**

Can anyone help me on this ?

**Comment by masoud-me** [comment]
> Hi i upgraded my php version to 8.0.17 , **tamayo/laravel-scout-elastic** version to 8.1 and **elasticsearch/elasticsearch** version to 8.0 After that i'm getting some error saying **Please install the Elasticsearch PHP client: elasticsearch/elasticsearch** in **LaravelScoutElasticProvider.php line 42**
> 
> I can see that the error is throwing because the class is not loading **ClientBuilder**
> 
> Can anyone help me on this ?

I have same issue

**Comment by reedy** [comment]
https://github.com/elastic/elasticsearch-php/blob/8.0/src/ClientBuilder.php exists in the branch..

```
reedy@ubuntu64-web-esxi:~/1084$ composer init

                                            
  Welcome to the Composer config generator  
                                            


This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [reedy/1084]: 
Description []: 
Author [Reedy <reedy@wikimedia.org>, n to skip]: 
Minimum Stability []: 
Package Type (e.g. library, project, metapackage, composer-plugin) []: 
License []: 

Define your dependencies.

Would you like to define your dependencies (require) interactively [yes]? Yes
Search for a package: elasticsearch/elasticsearch
Info from https://repo.packagist.org: #StandWithUkraine
Enter the version constraint to require (or leave blank to use the latest version): 8.0
Search for a package: 
Would you like to define your dev dependencies (require-dev) interactively [yes]? no
Add PSR-4 autoload mapping? Maps namespace "Reedy\1084" to the entered relative path. [src/, n to skip]: n 

{
    "name": "reedy/1084",
    "require": {
        "elasticsearch/elasticsearch": "8.0"
    },
    "authors": [
        {
            "name": "Reedy",
            "email": "reedy@wikimedia.org"
        }
    ]
}

Do you confirm generation [yes]? yes
Would you like to install dependencies now [yes]? yes
Loading composer repositories with package information
Updating dependencies
Lock file operations: 14 installs, 0 updates, 0 removals
  - Locking elastic/transport (v8.3.0)
  - Locking elasticsearch/elasticsearch (v8.0.0)
  - Locking guzzlehttp/guzzle (7.4.5)
  - Locking guzzlehttp/promises (1.5.1)
  - Locking guzzlehttp/psr7 (2.4.0)
  - Locking php-http/discovery (1.14.3)
  - Locking php-http/httplug (2.3.0)
  - Locking php-http/promise (1.1.0)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/log (3.0.0)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking symfony/deprecation-contracts (v3.1.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
  - Downloading psr/log (3.0.0)
  - Downloading php-http/promise (1.1.0)
  - Downloading php-http/httplug (2.3.0)
  - Downloading php-http/discovery (1.14.3)
  - Downloading elastic/transport (v8.3.0)
  - Downloading elasticsearch/elasticsearch (v8.0.0)
  - Installing psr/log (3.0.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing symfony/deprecation-contracts (v3.1.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing guzzlehttp/psr7 (2.4.0): Extracting archive
  - Installing guzzlehttp/promises (1.5.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.4.5): Extracting archive
  - Installing php-http/promise (1.1.0): Extracting archive
  - Installing php-http/httplug (2.3.0): Extracting archive
  - Installing php-http/discovery (1.14.3): Extracting archive
  - Installing elastic/transport (v8.3.0): Extracting archive
  - Installing elasticsearch/elasticsearch (v8.0.0): Extracting archive
2 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
reedy@ubuntu64-web-esxi:~/1084$ php -a
Interactive shell

php > require "vendor/autoload.php";
php > echo class_exists( 'Elastic\\Elasticsearch\\ClientBuilder' );
1
```

And when installed via composer, seems to work fine too....

**Comment by hkulekci** [comment]
> > Hi i upgraded my php version to 8.0.17 , **tamayo/laravel-scout-elastic** version to 8.1 and **elasticsearch/elasticsearch** version to 8.0 After that i'm getting some error saying **Please install the Elasticsearch PHP client: elasticsearch/elasticsearch** in **LaravelScoutElasticProvider.php line 42**
> > I can see that the error is throwing because the class is not loading **ClientBuilder**
> > Can anyone help me on this ?
> 
> I have same issue

@jitheshjs983 @masoud-me @reedy  As I check on the composer file of that [library](https://github.com/ErickTamayo/laravel-scout-elastic/blob/master/composer.json), the elasticsearch required as development (`require-dev`). May it be related to this? What do you think?

**Comment by reedy** [comment]
Probably..

The instructions do say to do `composer require elasticsearch/elasticsearch` - https://github.com/ErickTamayo/laravel-scout-elastic#install-elasticsearch-php-client which just feels weird. especially when it's in `require-dev` as you say.

It's definitely not a bug in this library, anyway.
