### ISSUE TITLE
Drop PHP 7.1 support in ES-PHP 8.0?

### ISSUE THREAD

**Issue by reedy** [elastic/elasticsearch-php#1086]
As mentioned in https://github.com/elastic/elasticsearch-php/issues/1084

PHP 7.1 is EOL for about a year now. Can we drop support for it?

To cover properly PHP 7.4/8.0 in PHPUnit we need to upgrade to PHPUnit 8.0, which also drops 7.1 support

https://phpunit.de/supported-versions.html

**Comment by reedy** [comment]
Though it looks like with https://github.com/elastic/elasticsearch-php/pull/1063 having `"phpunit/phpunit": "^7.5 || ^8.5 || ^9.3",` doesn't necessarily cause compatability issues...

**Comment by ezimuel** [comment]
@reedy I know that 7.1 is EOL but I cannot drop 7.1 support since this will be a breaking change. I'm working on #1063 and we can use different versions of PHPUnit using the or (`||`) operator in composer.

**Comment by reedy** [comment]
Bumping to 8 is a major version... So that's the kind of time you do a breaking change :)

**Comment by ezimuel** [comment]
@reedy I cannot remove the support of PHP 7.1 until I'll release `elasticsearch-php` 8.0.0. This will happen in 2021, since the version of the PHP client must be aligned with the release schedule of [Elasticsearch](https://github.com/elastic/elasticsearch). 
We will support PHP 8 starting from `elasticsearch-php` 7.11.0. Maybe I was not enough clear in my previous comment, sorry.

**Comment by grizzm0** [comment]
> @reedy I know that PHP 7.1 is EOL but I cannot drop 7.1 support since this will be a breaking change. I'm working on #1063 and we can use different versions of PHPUnit using the or (`||`) operator in composer.

Bumping the PHP version to 7.4 is not really considered a BC break. People on 7.1 will keep getting the prior version that is compatible with their environment. 

Some references on this matter
* https://sebastiandedeyne.com/composer-semver-and-underlying-dependency-changes/
* https://github.com/Ocramius/ProxyManager/issues/455
* https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html
