### ISSUE TITLE
HTTP authentication always try to authorize instead of reusing the Authorization header.

### ISSUE THREAD

**Issue by nignatov** [elastic/elasticsearch-php#110]
Hi Zachary,

I'm using the library with digest HTTP authentication and noticed that for each request to Elasticsearch it tries to authenticate which cause additional requests. 
For example lets imagine I've three blocks on my website visualizing something from Elasticsearch and this blocks are independent  from each other. This is causing use to send three different requests to Elasticsearch and if I have HTTP Authentication for Elasticsearch it causes 6 requests instead of 3 because the first request doesn't include the Authorization header, the server than return 401 and then the client send the Authorization header. 
Is there a easy way to reuse the Authorization header from first request or this is not possible at the moment? If not possible do you have any plans to implement such behavior. 
Thanks in advance.

**Comment by ezimuel** [comment]
Outdated issue. I can reopen it  if still an issue.
