### ISSUE TITLE
SSL cert error

### ISSUE THREAD

**Issue by warroyo** [elastic/elasticsearch-php#111]
I am receiving the following error when trying to use the DELETE API.

`Elasticsearch\\Common\\Exceptions\\TransportException","message":"SSL certificate problem: self signed certificate in certificate chain","file":"\pathto\/vendor\/elasticsearch\/elasticsearch\/src\/Elasticsearch\/Connections\/AbstractConnection.php","line":312`

in my config file I am setting the verification to false. this is working for everything except delete.

update:
I have done some research and it seems that the curl_opt - CURLOPT_SSL_VERIFYPEER is not getting set to false, is there a way to pass this using a config file to the elastic search client?

**Comment by jihadadulrazaqjasim** [comment]
I came up with the same error as this thread, how to disable it when building the connection  like so:

```        $client = ClientBuilder::create()
            ->setHosts([config('elastic.host')])
            ->setSSLVerification(false)
            ->setBasicAuthentication(config('elastic.user'), config('elastic.password'))
            ->build();
            ```
