### ISSUE TITLE
elasticsearch/elasticsearch 6.8.0 removes some classes, and doesn't leave aliases behind

### ISSUE THREAD

**Issue by reedy** [elastic/elasticsearch-php#1112]
### Summary of problem or feature request

Downstream tasks: https://phabricator.wikimedia.org/T276854, https://phabricator.wikimedia.org/T276320 and https://github.com/ruflin/Elastica/issues/1908

Mentioned on https://github.com/elastic/elasticsearch-php/commit/2da5f9337a269113954a84fe8e79ea6843f0e7c3

In 6.8, at least `Elasticsearch\Endpoints\Indices\Aliases\Update` disappeared. Therefore trying to instantiate it fails: `Error from line 451 of /var/www/html/w/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Index.php: Class 'Elasticsearch\Endpoints\Indices\Aliases\Update' not found`

 There is seemingly supposed to be an alias left behind, but that doesn't seem to have happened. Other classes seemingly disappeared too, without aliases being left.

### Code snippet of problem

https://github.com/ruflin/Elastica/blob/6.x/lib/Elastica/Index.php#L451

```php
use Elasticsearch\Endpoints\Indices\Aliases\Update;

$endpoint = new Update();
```

### System details

- Operating System: n/a
- PHP Version: n/a
- ES-PHP client version: 6.8.0
- Elasticsearch version: n/a

**Comment by ezimuel** [comment]
Just released [6.8.1](https://github.com/elastic/elasticsearch-php/releases/tag/v6.8.1) that fixes the issue.
