### ISSUE TITLE
Throw a ElasticsearchCommonExceptionsBadRequest400Exception When create a query

### ISSUE THREAD

**Issue by jetdky** [elastic/elasticsearch-php#1127]
### Summary of problem or feature request

Throw a ElasticsearchCommonExceptionsBadRequest400Exception When create a query

### Code snippet of problem
I created a new query using the following code,  occasionally throwing an exception like this

error type： Fatal error
error msg： Uncaught ElasticsearchCommonExceptionsBadRequest400Exception: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {n  "bool" : {n    "must" : [n      {n        "terms" : {n          "question_id" : [n            4102612,n            4102611,n            4102610,n            4102609,n            4102607,n            4102601,n            4102575,n            4102572,n            4102571,n            4102570,n            4102568,n            4102566,n            4102563,n            4102562,n            4102561,n            4102560,n            4102559,n            4102557,n            4102546,n            4102545,n            4102544,n            4102543,n            4102542,n            4100546,n            4100545,n            4100544,n            4100543,n            4100541,n            4083892,n            4083891,n            4083890,n            4083889,n            4083888,n            4083886,n            4082480,
time： 2021-04-19 15:22:44
location： /.../vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:637

and the PHP code is as follows
```php
$search_params = [
                        'index' => $es->index_name,
                        'size' => $pagesize,
                        'from' => $limit,
                        'body' => [
                            'query' => [
                                'bool' => [
                                    'must' => [
                                        [
                                            'terms' => [
                                                'question_id' => $id_list
                                            ]
                                        ],
                                        [
                                            'term' => [
                                                'type' => 'goods'
                                            ]
                                        ],
                                        [
                                            'term' => [
                                                'cid' => $cid
                                            ]
                                        ],
                                        [
                                            'match' => [
                                                'content' => $keyword
                                            ]
                                        ]
                                    ]
                                ]
                            ],
                            'sort' => [
                                '_score'=>'desc'
                            ]
                        ]
                    ];
                    $tiku_list = $es->client->search($search_params);
```
It happens occasionally, but in most cases it doesn't. No reason was found.
Maybe there was an error converting PHP array to JSON ?

### System details

- Operating System: CENTOS6
- PHP Version 7.0.4
- ES-PHP client version 7.12
- Elasticsearch version 7.5

**Comment by ezimuel** [comment]
@jetdky first of all, apologies for the delayed response. 
It seems the error is in the `question_id` terms.You are using a `$id_list` array here, do you know the size of this array?  Elasticsearch has a limit of [65,536 terms](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#:~:text=By%20default%2C%20Elasticsearch%20limits%20the,use%20the%20terms%20lookup%20parameters.) for a query.

If you want to check the HTTP request and response sent by `elasticsearch-php` you can enable logging with the following code:
```php
use Elasticsearch\ClientBuilder;
use Monolog\Handler\StreamHandler;
use Monolog\Logger;

$logger = new Logger('name');
$logger->pushHandler(new StreamHandler('elasticsearch-php.log', Logger::DEBUG));

$client = ClientBuilder::create()
    ->setLogger($logger)
    ->build();   
```
You can check the HTTP request and response in `elasticsearch-php.log`.
I used [monolog](https://github.com/Seldaek/monolog) library as PSR-3 logger. You can install it using composer:
```
composer require monolog/monolog
```

**Comment by jetdky** [comment]
It's ok, thank you for your reply very much! My error here may be the size of the array, I limit the array size now
