### ISSUE TITLE
[6.8.x] ForceMerge renamed to Forcemerge

### ISSUE THREAD

**Issue by kbond** [elastic/elasticsearch-php#1131]
### Summary of problem or feature request

`Elasticsearch\Endpoints\Indices\ForceMerge` was renamed to `Elasticsearch\Endpoints\Indices\Forcemerge` [here](https://github.com/elastic/elasticsearch-php/commit/2da5f9337a269113954a84fe8e79ea6843f0e7c3#diff-c4834c4ebd492607a0af1ab55c7575c6a84323f8be87ca6f7f8833cf4ffc2675).

Reference: https://github.com/ruflin/Elastica/pull/1947#issuecomment-804969412 & https://github.com/ruflin/Elastica/pull/1948

**Comment by ezimuel** [comment]
Using the new code generator there were some naming issue. This happened because in the past the API endpoints has been created manually. I'll try to fix this issue with a new patch release `6.8.2` soon. I'm sorry for the inconvenient.

**Comment by kbond** [comment]
> I'm sorry for the inconvenient.

No worries whatsoever! 🙂

**Comment by deguif** [comment]
Thanks @ezimuel
I will wait for 6.8.2 and relaunch tests on the 6.x version of ruflin/elastica

**Comment by timonf** [comment]
@ezimuel When can we expect `6.8.2`?

**Comment by ezimuel** [comment]
@kbond, @deguif can you review the PR https://github.com/elastic/elasticsearch-php/pull/1151 ? Thanks!

**Comment by ezimuel** [comment]
Just released [v6.8.2](https://github.com/elastic/elasticsearch-php/releases/tag/v6.8.2) including #1151 fix.
