### ISSUE TITLE
What about upgrading to doctrine/inflector v2.X ?

### ISSUE THREAD

**Issue by jul6art** [elastic/elasticsearch-php#1135]

**Comment by ezimuel** [comment]
@jul6art we are not using anymore `doctrine/inflector`, I removed from composer (https://github.com/elastic/elasticsearch-php/commit/289c7ed2f2c5dcffa264a470ee191dc2f6fd7918). Moreover, I also removed `symfony/yaml` since we are using `ext-yaml`. Thanks for the notice!
