### ISSUE TITLE
ElasticStack Kibana

### ISSUE THREAD

**Issue by bsteelekuk** [elastic/elasticsearch-php#1136]
### System details

- Operating System - CentOS 7/RedHat Ent ?
- PHP Version 7.3.27
- ES-PHP client version - Latest
- Elasticsearch version - Latest

**Comment by ezimuel** [comment]
@bsteelekuk what's the issue here? Can you give me more information? Thanks.

**Comment by bsteelekuk** [comment]
Hello,


Thanks for getting back to me. We are developing an application that uses ElasticStack for dashboarding and machine learning. You have a client for PHP that we are using to integrate with ElasticSearch. We are already creating indexes and injecting documents into those index etc..


However, we also want to be able to create index patterns in Kibana and create kibana/canvas workbooks and then add elements onto those workbooks etc.... Is there a PHP client for Kibana just as there is for ElasticSearch? and if so then how powerful is it? Could I have tight integration with Kibana/Canvas from my PHP application?


Thanks,

Brian



________________________________

**Comment by ezimuel** [comment]
@bsteelekuk unfortunately, we don't have a PHP client for Kibana. Kibana itself offers a REST API which is ideal for creating an integration or automating certain aspects of configuration and deployment. You can read about the API [here](https://www.elastic.co/guide/en/kibana/master/api.html). 
If you want to use the Kibana API from PHP, I suggest to use [elastic-transport-php](https://github.com/elastic/elastic-transport-php) or [Guzzle](https://github.com/guzzle/guzzle) libraries to facilitate the HTTP requestes building.

**Comment by bsteelekuk** [comment]
Hi,


Given that you have developed the native PHP client for ElasticSearch to simplify the use of its APIs do you think your will do the same for Kibana in the future please?


Thanks,

Brian



________________________________

**Comment by ezimuel** [comment]
We would like to offer a PHP client for Kibana but this is not in our plan at the moment. I'll try to update this issue with any news in the future. Thanks.

**Comment by bsteelekuk** [comment]
OK thanks 😊



Brian Steele - Technical Development Lead

Tel:    01782 752369
Email:          ***@***.******@***.***>
Web:    www.kedronuk.com<http://www.kedronuk.com>


***@***.***<http://www.kedronuk.com>
[ISO 27001]<http://>  [ISO 9001] <http://>


***@***.***<https://ss-usa.s3.amazonaws.com/c/308479063/media/112036040ebf74bc0216650354871878/Secure%20Environments.pdf>

For Technical Support, please login to our Support Portal<http://www.kedronuk.com/company/support>

________________________________
