### ISSUE TITLE
Multiple Must within Should clause does not work

### ISSUE THREAD

**Issue by Hmastery** [elastic/elasticsearch-php#1152]
### Summary of problem or feature request

I would like to achieve the following query with ElasticSearch :
product_shipper = $shipper AND ((product_type = product and price>0) OR (product_type = product_variation and price=0))

### Code snippet of problem

So here is my query: 

```php
"query"=> [
                    "bool"=> [
                        "must"=> [
                            [
                            "bool"=> [
                                "should" => [
                                    [
                                        "bool"=> [
                                            "must"=> [
                                                [ "match" => [ "product_type" => "product" ] ],
                                                [ "range"=>['price'=>['gt'=>0]]],
                                            ]
                                        ],
                                        "bool"=> [
                                            "must"=> [
                                                [ "match" => [ "product_type" => "product_variation" ] ],
                                                ['range'=>['price'=>['lte'=>0]]]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ],
                        [ 'match' => [ 'product_shipper' => $shipper ] ],
                        ]
                    ]
               ]

```

The issue is that the second bool/must overwrite the first one and the first one is ignored, if I revert there order the results change, in the pasted code I only have results where product_shipper = $shipper and product_type = product_variation and price > 0

### System details

- Operating System
- PHP Version : 7
- ES-PHP client version : ^7.0
- Elasticsearch version 7.11

**Comment by Unifex** [comment]
Are you sure you have formed your query right?  Your 2 "bool" keys are at the same level so the last one will alway 'win'.
```php
"should" => [
    [
        "bool"=> [
            "must"=> [
                [ "match" => [ "product_type" => "product" ] ],
                [ "range"=>['price'=>['gt'=>0]]],
            ]
        ],
    ],
    [
        "bool"=> [
            "must"=> [
                [ "match" => [ "product_type" => "product_variation" ] ],
                ['range'=>['price'=>['lte'=>0]]]
            ]
        ]
    ]
]
```

**Comment by Hmastery** [comment]
I am not, but I posted this example on both stackoverflow, elasticsearch
forum and this github and you're the first to mention that there might be
an issue in its form.
The documentation is pretty bad when it comes to not straightforward
things, could you give me a hand so that I close this ticket ?

Thanks !!

**Comment by Unifex** [comment]
> The documentation is pretty bad when it comes to not straightforward

I've been struggling with this too. :/ Don't get me started on mapping.  I can rant for ages on that... ;)

> could you give me a hand so that I close this ticket ?

This is the edit above in the context of your query.
```php
"query"=> [
    "bool"=> [
        "must"=> [
            [
            "bool"=> [
                "should" => [
                    [
                        "bool"=> [
                            "must"=> [
                                [ "match" => [ "product_type" => "product" ] ],
                                [ "range"=>['price'=>['gt'=>0]]],
                            ]
                        ],
                    ],
                    [
                        "bool"=> [
                            "must"=> [
                                [ "match" => [ "product_type" => "product_variation" ] ],
                                ['range'=>['price'=>['lte'=>0]]]
                            ]
                        ]
                    ]
                ]
            ]
        ],
        [
          'match' => [ 'product_shipper' => $shipper ] ],
        ]
    ]
]

**Comment by Hmastery** [comment]
@Unifex Thank you very much man... Damn, they should put more complex examples like this one. An issue in one bracket and there is no error sent back, just weird search results.

Testing queries is a hell of a job ^^.

You rock!

**Comment by mfn** [comment]
This is one of the reasons I'm using https://github.com/ruflin/Elastica -> not necessary for _accessing_ ES but I use it's builder capabilities, which can prevent the stupid errors I would otherwise also create more often 😄
