### ISSUE TITLE
Invalid url generated with request additional `/`

### ISSUE THREAD

**Issue by piotranon** [elastic/elasticsearch-php#1160]
### Summary of problem or feature request

Client is calling a request to URL : `localhost:9200//prod_9/_search`,
and should be calling a request to URL : `localhost:9200/prod_9/_search`
the additional slash is added after a connection URL, or before the created URL,
and searching for product without index is working fine but with index the additional `/` is generating an error so elasticsearch is not searching in specified index `prod_9` its trying to search with type of `prod_9`

### Code snippet of problem

```php
$params = [
                'index' => 'prod_9',
                'body'  => [
                    'query' => [
                        'match' => [
                            'uuid' => $uuid
                        ]
                    ]
                ],
                "ignore_unavailable" => true,
];
$client = \Elasticsearch\ClientBuilder::fromConfig(
            [
                'hosts'     => [env('ELASTIC_MAIN_URL','localhost:9200')],
                'retries'   => 1,
            ]
        );
$client->search($params);
```

### It can be fixed in `Elasticsearch\Endpoints\Search` in `getURI()` by removing first slash in each operation

maybe possible sollution
```php
public function getURI(): string
    {
        $index = $this->index ?? null;
        $type = $this->type ?? null;
        if (isset($type)) {
            @trigger_error('Specifying types in urls has been deprecated', E_USER_DEPRECATED);
        }

        if (isset($index) && isset($type)) {
            return "$index/$type/_search";
        }
        if (isset($index)) {
            return "$index/_search";
        }
        return "_search";
    }
```
### To debug check
`$connection`,`$uri` in `Elasticsearch\Transport::performRequest()` line ~ 109

### System details

- Operating System Windows 10
- PHP Version PHP 7.4.22
- ES-PHP client version v6.8.2
- Elasticsearch version 7.11.2

**Comment by ezimuel** [comment]
@piotranon I just noticed that you are using v6.8.2 of `elasticsearch-php` with Elasticsearch 7.11.2. You should use `elasticsearch-php` v7.11 or above. Can you update the library and let us know? Thanks.

**Comment by piotranon** [comment]
save problem with newer version

**Comment by piotranon** [comment]
So i figured out that i had problem with url passed to host in client builder it had `/` at the end.
to close
