### ISSUE TITLE
Concurrent requests

### ISSUE THREAD

**Issue by petericebear** [elastic/elasticsearch-php#1161]
### Summary of problem or feature request

Is it possible to fire searches in a concurrent way?
With Guzzle you can make a connection pool which will handle the requests in a concurrent way.

This is also being used in the Laravel Framework described here:
https://laravel.com/docs/8.x/http-client#concurrent-requests

And example with Guzzle Pool:
https://gist.github.com/wzed/d9273719e54e78da4a6a63d4fc9e2606

I am using the Laravel approach with building the requests by hand, but would be great is the client supports it first party.

**Comment by ezimuel** [comment]
@petericebear yes, we support future (async) request: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/future_mode.html.
You can basically execute all the HTTP calls and store it in an array of futures. The HTTP call will be executed without blocking the code. When you will read the responses or use the `wait()` function you will force the response (blocking the code). Here an example from the documentation:
```php
$client = ClientBuilder::create()->build();
$futures = [];

for ($i = 0; $i < 1000; $i++) {
    $params = [
        'index'  => 'test',
        'id'     => $i,
        'client' => [
            'future' => 'lazy'
        ]
    ];
    $futures[] = $client->get($params);     //queue up the request
}

foreach ($futures as $future) {
    // access future's values, causing resolution if necessary
    echo $future['_source'];
}
```
