### ISSUE TITLE
SmartSerializer - error when using gzip

### ISSUE THREAD

**Issue by wronaBartosz** [elastic/elasticsearch-php#1162]
### Summary of problem or feature request

After adding 'Accept-Encoding' => ['gzip, deflate'], to client headers there are problems with response decoding. SmartSerializer can't handle gziped response

### Code snippet of problem
```php
    private function decode($data)
    {
        if ($data === null || strlen($data) === 0) {
            return "";
        }

        $result = @json_decode($data, true);

        // Throw exception only if E_NOTICE is on to maintain backwards-compatibility on systems that silently ignore E_NOTICEs.
        if (json_last_error() !== JSON_ERROR_NONE && (error_reporting() & E_NOTICE) === E_NOTICE) {
            $e = new JsonErrorException(json_last_error(), $data, $result);
            throw $e;
        }

        return $result;
    }
```

**Comment by ezimuel** [comment]
@wronaBartosz can you provide a code example to reproduce the error? Moreover, which version of PHP, Elasticsearch and `elasticsearch-php` are you using? Thanks!
