### ISSUE TITLE
SSL Certificate problem

### ISSUE THREAD

**Issue by realtebo** [elastic/elasticsearch-php#1174]
### Summary of problem or feature request

I got an error of this type

"error" => GuzzleHttp\Ring\Exception\RingException {#1909 ▼
    #message: "cURL error 60: SSL certificate problem: self signed certificate in certificate chain"
    #code: 0
    #file: "C:\laragon\www\mk-frontend\vendor\ezimuel\ringphp\src\Client\CurlFactory.php"

### Code snippet of problem

We are using your package through the wrapper laravel-elasticsearch

### System details

- Operating System: windows 10
- PHP Version: 7.4
- ES-PHP client version: what ?
- Elasticsearch version: I don't know, we are calling a elasticsearch hosted instance using `"https://a875b0fe......eu-central-1.aws.cloud.es.io

Postman can do an api call without problems
Also, from the same system, using git bash for windows, I can use curl to succesfully call to this instance

This problem is happening to me only since 2 days, but I've no idea of how to diagnose the source of the problem

Is there a way to ask your package to skip SSL validation

**Comment by ezimuel** [comment]
@realtebo you can disable the SSL verification form the client build using the `setSSLVerification(false)` function, as follows:
```php
$client = ClientBuilder::create()
    ->setSslVerification(false)
    ->build();
```
Of course, this is not the recommended settings. I suggest to have a look at the [SSL configuration](https://www.elastic.co/guide/en/elasticsearch/client/php-api/master/connceting.html#ssl-encryption) section of the manual.

**Comment by realtebo** [comment]
I suppose it was a config problem on the remote server of hosted elastic search instance. We reenabled ssl verification 2 days ago and all works. I still cannot understand why only this library was complaining about the self signed certificate; postman, curl, browser, and other tools (either web) do not see aything of wrong in the certificate. 
I close.
