### ISSUE TITLE
includePortInHostHeader not usable via fromConfig 

### ISSUE THREAD

**Issue by huanes** [elastic/elasticsearch-php#1176]
### Summary of problem or feature request

The `ClientBuilder` `includePortInHostHeader()` method is not accessible when using `fromConfig()` as only `set`-prefixed methods are applicable in `fromConfig`.

As I am using a wrapper package for Laravel Scout that uses the `fromConfig` method, I can't initiate the Client myself so it's a bit of an issue.

**Comment by ezimuel** [comment]
@huanes I sent a new PR ( #1181 ) for fixing the issue.

**Comment by ezimuel** [comment]
Fixed in #1181
