### ISSUE TITLE
Switch to MIT license for 8.0 release

### ISSUE THREAD

**Issue by technige** [elastic/elasticsearch-php#1180]
This issue signals our intention to switch to [MIT](https://opensource.org/licenses/MIT) licensing for the official Elasticsearch client for PHP, as of its 8.0 release.

The project is currently dual licensed under both [Apache 2.0](https://opensource.org/licenses/Apache-2.0) and [LGPL 2.1](https://opensource.org/licenses/LGPL-2.1). This dual-licensing situation was introduced in 2014 to achieve license compatibility for GPL-licensed projects, following [a discussion opened by Drupal](https://github.com/elastic/elasticsearch-php/issues/126).

On reviewing the project today, however, and [looking at licensing across the wider PHP ecosystem](https://blog.exussum.co.uk/licence.html), we have observed that we can further simplify the situation for users. By replacing these two licenses with the single MIT license (used across ~60% of PHP projects) we can achieve GPL-compatibility under a single, permissive license, and also align better with the PHP community at large.

**Comment by ezimuel** [comment]
First usage of MIT in `elasticsearch-php` [v8.0.0-alpha](https://github.com/elastic/elasticsearch-php/releases/tag/v8.0.0-alpha).
