### ISSUE TITLE
AbstractLogger must be compatible error

### ISSUE THREAD

**Issue by RobertEcker** [elastic/elasticsearch-php#1186]
### Summary of problem or feature request

`Fatal error: Declaration of Psr\Log\AbstractLogger::emergency(Stringable|string $message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = []) in C:\wamp\www\vendor\elasticsearch\elasticsearch-php\vendor\psr\log\src\LoggerTrait.php on line 23`

I removed string|\Stringable in LoggerTrait.php and NullLogger.php
then it worked

### System details
- Windows 10
- 8.1.1
- ES-PHP latest
- ElasticSearch
    "number" : "7.16.1",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "5b38441b16b1ebb16a27c107a4c3865776e20c53",
    "build_date" : "2021-12-11T00:29:38.865893768Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"

**Comment by ezimuel** [comment]
@RobertEcker this sounds like a composer dependency issue with [psr/log](https://github.com/php-fig/log) PSR-3 interface standard. Did you try to execute `composer update` on your project? Let me know if this will solve the issue, thanks.

**Comment by sunchuo** [comment]
Problem 1
    - Root composer.json requires elasticsearch/elasticsearch ^7.16 -> satisfiable by elasticsearch/elasticsearch[v7.16.0].
    - elasticsearch/elasticsearch v7.16.0 requires psr/log ^1|^2 -> found psr/log[1.0.0, ..., 1.1.4, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by tacman** [comment]
Yep, is there any way to also support psr/log v 3?  

To reproduce this error, simply change composer.json to include

    "psr/log": "^1|^2|^3"

then composer install --dev and php vendor/bin/phpunit

FWIW, I'm running PHP 8.1, not sure if that's more strict on return types.

**Comment by technige** [comment]
@tacman There are already a couple of other issues/PRs mentioning psr/log v3. We are currently reviewing the change.

**Comment by ezimuel** [comment]
The support of `psr/log 3` has been introduced in `elasticsearch-php` [v7.17.0](https://github.com/elastic/elasticsearch-php/releases/tag/v7.17.0)
