### ISSUE TITLE
elasticsearch-php 8.0.0-RC2 PHP Fatal error:  Uncaught Elastic\\Elasticsearch\\Exception\\ArrayAccessException: The array is reading only in /vendor/elasticsearch/elasticsearch/src/Response/Elasticsearch.php:211

### ISSUE THREAD

**Issue by chongshengdz** [elastic/elasticsearch-php#1203]
PHP Fatal error:  Uncaught Elastic\\Elasticsearch\\Exception\\ArrayAccessException: The array is reading only in /vendor/elasticsearch/elasticsearch/src/Response/Elasticsearch.php:211

**Comment by ezimuel** [comment]
@chongshengdz can you paste the code example that are using? Thanks. If you try to update or unset the array response it will throw the `ArrayAccessException` by design, you can see the [code](https://github.com/elastic/elasticsearch-php/blob/8.0/src/Response/Elasticsearch.php#L204-L222) here.

**Comment by chongshengdz** [comment]
> @chongshengdz can you paste the code example that are using? Thanks. If you try to update or unset the array response it will throw the `ArrayAccessException` by design, you can see the [code](https://github.com/elastic/elasticsearch-php/blob/8.0/src/Response/Elasticsearch.php#L204-L222) here.

below is the code for testing connection of elasticsearch

    public function connectionStatus(){
        $this->load->language($this->module_path);
        $this->load->library('search_plus');
        $json = array();
        try {
            $json = $this->search_plus->client->info();
            $json['message'] = $this->language->get('text_connection_success');
            $json['status'] = true;
        } catch (Exception $e) {
            $json['status'] = false;
            $json['error']['message'] = $e->getMessage();
        }
        echo json_encode($json);
    }

**Comment by chongshengdz** [comment]
public function ping(){
        return $this->client->cat()->indices();
    }

**Comment by chongshengdz** [comment]
Elastic\\Elasticsearch\\Response\\Elasticsearch->offsetSet()

**Comment by chongshengdz** [comment]
@ezimuel

**Comment by ezimuel** [comment]
@chongshengdz the new `elasticsearch-php` 8.0 client returns an instance of [Response\Elasticsearch](https://github.com/elastic/elasticsearch-php/blob/8.0/src/Response/Elasticsearch.php) foreach endpoint call. In your code base, the `$json` is an instance of that class.
```php
try {
    $json = $this->search_plus->client->info();
```
You can access `$json` as array because `Response\Elasticsearch` implements the [ArrayAccess](https://www.php.net/manual/en/class.arrayaccess.php) interface of PHP.
But you cannot override the values, this is why you get the `ArrayAccessException` exception.

In the previous version 7.x of `elasticsearch-php` the response was just an array and you could modify it. We changed this behaviour using an [immutable object](https://medium.com/hackernoon/5-benefits-of-immutable-objects-worth-considering-for-your-next-project-f98e7e85b6ac). This is by design, since we want to encapsulate (protect) the response object from Elasticsearch.

That said, you can still extract the response body as array (with the same result of `7.x`), using the `asArray()` method, as follows:
```php
try {
    $result = $this->search_plus->client->info();
    $json = $result->asArray();
    $json['message'] = $this->language->get('text_connection_success');
    $json['status'] = true;
} catch (Exception $e) {
    $json['status'] = false;
    $json['error']['message'] = $e->getMessage();
}
```

**Comment by ezimuel** [comment]
@chongshengdz we released [v8.0.0](https://github.com/elastic/elasticsearch-php/releases/tag/v8.0.0) in the meantime.

**Comment by chongshengdz** [comment]
> 
Below is the js code, can you help check if there is anything wrong?


    function checkConnection() {
        $.ajax({
            type:'post',
            url:'index.php?route=extension/module/search_plus/connectionStatus&user_token={{ user_token}}',
            dataType: "json",
            beforeSend: function() {
                $("#connection-status").html('<div class="alert alert-info"><i class="fa fa-spinner fa-pulse "></i> Connecting...</div>');
            },
            complete: function() {
               $(".alert").delay(6000).fadeOut("slow");
           },
           success: function(json) {
            if (json['status']) {
                $("#connection-status").html('<div class="alert alert-success"><i class="fa fa-check-circle"></i> ' + json['message'] +  json['version']['number'] +'<button type="button" class="close" data-dismiss="alert">&times;</button></div>');
            }
            if (json['error']) {
                $("#connection-status").html('<div class="alert alert-danger"><i class="fa fa-close"></i> {{text_connection_failed}}' + json['error']['message'] +'<button type="button" class="close" data-dismiss="alert">&times;</button></div>');
            }
          }
        });
    }

**Comment by ezimuel** [comment]
@chongshengdz I'm sorry but this is a Javascript code not related with `elasticsearch-php` project. 
Did you solve the issue in the PHP code using the `asArray()` function as mentioned [here](https://github.com/elastic/elasticsearch-php/issues/1203#issuecomment-1077518209)?

**Comment by chongshengdz** [comment]
> 

@ezimuel yes, it works fine now, many thanks for your help.
