### ISSUE TITLE
8.1 Branch not up2date and so `^8.0@dev` version delivers an older version state then 8.0.0

### ISSUE THREAD

**Issue by alexander-schranz** [elastic/elasticsearch-php#1204]
### Summary of problem or feature request

If you are using composer and have set your minimum stability to `dev` it will test the library or package against the latest version like we are doing here: https://github.com/handcraftedinthealps/ElasticsearchDSL/blob/80c890fa528c39699efdc119e8d26afb2b589cd3/composer.json#L43

But as there is a `8.1` branch, composer detects that branch as the latest version and test against that one. There are 2 possiblities to fix this problem. 

1. renaming `8.1` branch to `next` or something else
2. keep the `8.1` branch up2date with the changes of `8.0`

### Code snippet of problem

```json
{
    "require": {
        "elasticsearch/elasticsearch": "^8.0"
    },
    "minimum-stability": "dev"
}
```

```
composer update
```

### System details

- Operating System: Mac OS, Github CI, ...
- PHP Version 8, 8.1, 
- ES-PHP client version ^8.0@dev
- Elasticsearch version 8

**Comment by ezimuel** [comment]
@alexander-schranz just updated the `8.1` branch with the lastet `8.0`. Let me know if this solve the issue, thanks!
