### ISSUE TITLE
Searching with search_type

### ISSUE THREAD

**Issue by nmalcolm** [elastic/elasticsearch-php#121]
Hi,

I've read the docs and looked through the source code, but there doesn't seem to be any way to search using search_type. The raw query would be:

```
curl -XPOST "http://localhost:9200/website/_search?search_type=count" -d '{
    "facets": {
        "count_by_type": {
            "terms": {
                "field": "_type"
            }
        }
    }
}'
```

Is there something like this available in the PHP api? If not, it would be great to see this in the future. :)

**Comment by sdstyles** [comment]
I have a bug in Elasticsearch 1.4.1 I've added $params['search_type'] = 'count'; to my query and it's returning 0 results.
