### ISSUE TITLE
Problem with psr/log depency on Laravel 9.6.0

### ISSUE THREAD

**Issue by ResetButton** [elastic/elasticsearch-php#1210]
Hello!

I can't install package on Laravel 9.6.0. with this problem

`Problem 1
    - elasticsearch/elasticsearch[v8.0.0, ..., 8.1.x-dev] require elastic/transport ^8.0 -> satisfiable by elastic/transport[v8.0.0-rc1, ..., 8.x-dev].
    - elasticsearch/elasticsearch v8.0.0-rc2 requires elastic/transport >=8.0.0-rc4 -> satisfiable by elastic/transport[v8.0.0-rc4, v8.0.0, 8.x-dev, 9999999-dev].
    - elasticsearch/elasticsearch[v8.0.0-alpha, ..., v8.0.0-rc1] require elastic/transport >=8.0.0-rc3 -> satisfiable by elastic/transport[v8.0.0-rc3, v8.0.0-rc4, v8.0.0, 8.x-dev, 9999999-dev].
    - elasticsearch/elasticsearch 8.x-dev requires psr/log ^1|^2 -> found psr/log[1.0.0, ..., 1.1.4, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - elastic/transport[dev-master, v8.0.0-rc1, ..., 8.x-dev] require psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires elasticsearch/elasticsearch ^8.0 -> satisfiable by elasticsearch/elasticsearch[v8.0.0-alpha, ..., 8.x-dev].`

I tried other versions ^8 with no luck and meet same problem - it seems composer.json in not updated, but https://github.com/elastic/elasticsearch-php/blob/master/composer.json contains "psr/log": "^1|^2|^3"

**Comment by ezimuel** [comment]
@ResetButton I think the issue is in the [elastic/elastic-transport-php](https://github.com/elastic/elastic-transport-php/blob/8.x/composer.json#L19) composer since we have the dependency of `psr/log` to `^1.1`. In `elasticsearch/elasticsearch` we have `^1|^2|^3` and if your composer.lock chosen `^3` this will conflict. The solution is to release `elastic/elastic-transport-php` 8.0.1 with `"psr/log": "^1|^2|^3"`.

**Comment by ezimuel** [comment]
@ResetButton I just released `elastic/elastic-transport-php` [v8.0.1](https://github.com/elastic/elastic-transport-php/releases/tag/v8.0.1) with the support of `psr/log` v1, 2 and 3. This should fix the issue. Let me know, thanks!

**Comment by ResetButton** [comment]
Yes, all is OK now, thanks for quick reply
