### ISSUE TITLE
Missing section "Unit Testing using Mock a Elastic Client"

### ISSUE THREAD

**Issue by gnumoksha** [elastic/elasticsearch-php#1212]
[This commit](https://github.com/elastic/elasticsearch-php/commit/aeb7aaacdd6a6fc8791a0be91cfc2544c9db346f) removed the section regarding mocking the client. So, what is the new way to mock the client?

**Comment by ezimuel** [comment]
@gnumoksha thanks for reporting this! I just added the section [Mock the Elasticsearch client](https://github.com/elastic/elasticsearch-php/#mock-the-elasticsearch-client) in the README.
