### ISSUE TITLE
PHP 8.1 - Elastic cloud getting error : Not a valid Json: Control character error, possibly incorrectly encoded

### ISSUE THREAD

**Issue by waleedfaridworkland** [elastic/elasticsearch-php#1213]
Hello,

We are upgrading to Elastic Cloud, upgrading to PHP 8.1 and the latest ElasticSearch package.

Up until version 7.17.0 things seem to be working fine.

But using any package 8.0.0 and above is throwing the above mentioned error.

Building client as follows : 

$this->client = ClientBuilder::create()
                        ->setElasticCloudId(env('CLOUD_ID'))
                        ->setApiKey(env('CLOUD_API_KEY'))
                        ->build();

Doing something as simple as 

$response = $this->client->info();
echo $response['version']['number'];

Throws the error.

Not a valid Json: Control character error, possibly incorrectly encoded
Elastic\Transport\Exception\
InvalidJsonException
in [/var/www/html/vendor/elastic/transport/src/Serializer/JsonSerializer.php ](https://github.com/elastic/elasticsearch-php/issues/new)(line 73)

Any search query also returns the same error.

If I output the $response variable, I get an ElasticSearch PSR7 Response object with a StatusCode 200.

Something like 

Elastic\Elasticsearch\Response\Elasticsearch {
  #response: Nyholm\Psr7\Response {
    -reasonPhrase: "OK"
    -statusCode: 200
    -headers: array:8
    -headerNames: array:8
    -protocol: "1.1"
    -stream: Nyholm\Psr7\Stream
  }
}
 
PHP Version - PHP 8.1.4
OS - UBUNTU Debian GNU/Linux 11 (bullseye)
ES-PHP client version - 8.0.0 and above
Elasticsearch version - Elastic cloud - v8.1.0

Any help would be appreciated. 
Thank you

**Comment by ezimuel** [comment]
@waleedfaridworkland I'm trying to reproduce the issue. I'm using PHP `8.1.4`, elasticsearch-php `v8.0.1`, Ubuntu Linux  `20.04`, Elastic Cloud with an instance of Elasticsearch `8.1.2`. I just tried the following example and it works, the output is `8.1.2`:

```php
require 'vendor/autoload.php';
use Elastic\Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()
    ->setElasticCloudId('xxx')
    ->setApiKey('yyy')
    ->build();

$response = $client->info();
echo $response['version']['number'];
```
Can you paste the `cloud_response.json` file produced by the following script?
```php
$response = $client->info();
file_put_contents('cloud_response.json', $response->asString());
```
Thanks!

**Comment by waleedfaridworkland** [comment]
Hey ezimuel thanks for the response!

This is what I get from $response->asString();

�|��N�0D���(�&����nY ���D�D7~ǩ��T�w�	��s�|^Ah��a�	Bm{����4\�n|�dW^�Pd瘪P�Q`���TJ1K��^�)���Q���m$o�d�p��������<�ǽ|S�n��d�
��F�����U!x㖺;��V���Ø\C_Ob��by�d�*I�'��*�P,!�U��B�ln�M!J"��b���1������-���u#����{��\ZY�����n�Սoʣ�d��fNW�hwZ04��/����Rc���2}��7���m���޶�u��.�J�x�.�/�����E4

Or if I do dd instead, I get

b"\x1Fï\x08\x00\x00\x00\x00\x00\x00\x00|æ╦N├0\x14D¸²è(Ù&▓ØçÒnY ┴\x02íéD┘D7~\x10\vÃ®\x12╗ÑT²w‗Çè\x08\t´ýÖsþÄ|^\x05Ahíæa░\tBm{\x07û╦\x08²£4\Å\x0En|´dW^ØPd\x14þÿ¬\fPÜQ`\x02¬îá\x02TJ1K­\x12¾^ï)Ó¯¾Q¦\x02Ã█m$o▄¯ü¥d¤p£═\x07┘§║Áú´<▄Ã¢|S╔n\x02ï\x18Ãd‗´òÎFö╩└íØU!\x15xÒû║;ÝþVóÕ´├ÿ\x05\C_Obéàby┴dü*\x10I×\x03'\x08Ë\x1CÇ*ÆP,!ôU╩þBÎl\x01n×M\x10!\x11J"┬×\x08ÌÓbô▒ÿ1£\x12ûª┼Ù\x12Û-ý¹║u#¿└¶‗{ñ±\ZY■Û\x1F▓\x18┼Þçn┤ıìo╩ú¯d╔█f\x0FNW┌hwZ04ã¶/ñ¡É\x1F RcÊðÝ2}éâ7úÝ▄mÎ·ÓÌÂÃuá┌.ÏJÞx\x1D«.½/\x00\x00\x00  \x03\x00õõ╩E4\x02\x00\x00

**Comment by ezimuel** [comment]
@waleedfaridworkland it seems the response is not a valid JSON. Can you put the file in a [gist](https://gist.github.com/) and copy the link here? Thanks!

**Comment by priitperna** [comment]
Are there any updates on this? I'm having the same issue.

**Comment by waleedfaridworkland** [comment]
@priitperna No. Until this is resolved, I just downgraded to ES-php client package version 7.17.0. That one works.

**Comment by waleedfaridworkland** [comment]
@ezimuel The PHP application runs as a Kubernetes pod on Google Kubernetes Engine which has a load balancer managed by Google. 
We also use nginx ingress.

**Comment by priitperna** [comment]
I'm running it from my local env using Docker. PHP version is 8.0.17. No proxy or load balancer.

To me it seems that the problem is with decoding the response. When decoding the response body manually in `Elastic\Elasticsearch\Client::sendRequest()`, then it decodes to a correct json.
This returns the correct json: `gzdecode($response->getBody())`

**Comment by waleedfaridworkland** [comment]
I concur with priitperna. I also ran my application locally using Docker no proxy, no load balancer and faced the same issue. 
PHP 8.1.4, Laravel/lumen framework : 9.0.2

**Comment by sincorecom** [comment]
I'm not sure if this is related. But I was having the exact same issue running Laravel 9.0.2 and PHP 8.1. I was able to fix this by removing "symfony/http-client" as a required package. I happened to install it for use with Mailgun but after removing it everything went back to normal.

**Comment by waleedfaridworkland** [comment]
@sincorecom You are right the issue is related to this package. 
I have a different package installed, which installs symfony/http-client as a dependency, removing that package stops causing the issue.
I can't remove the package in question on production though since it is an important one.

**Comment by waleedfaridworkland** [comment]
@sincorecom @priitperna @ezimuel 

If the package "symfony/http-client" is intalled in the application, then explicitly setting the http client when building the elastic client solves the issue, like so :

            $this->client = ClientBuilder::create()
                            ->setHttpClient(new \GuzzleHttp\Client)
                            ->setElasticCloudId(***)
                            ->setApiKey(***)
                            ->build();

**Comment by use-the-fork** [comment]
> @sincorecom @priitperna @ezimuel
> 
> If the package "symfony/http-client" is intalled in the application, then explicitly setting the http client when building the elastic client solves the issue, like so :
> 
> ```
>         $this->client = ClientBuilder::create()
>                         ->setHttpClient(new \GuzzleHttp\Client)
>                         ->setElasticCloudId(***)
>                         ->setApiKey(***)
>                         ->build();
> ```

Thanks for this! Worked perfect for me as well!

**Comment by ezimuel** [comment]
@waleedfaridworkland thanks for showing the issue and the solution. I'll have a look more deply since this is related to the [HTTPlug](http://httplug.io/) autodiscovery feature [here](https://github.com/elastic/elastic-transport-php/blob/master/src/TransportBuilder.php#L53). Maybe I can remove it, and use `Guzzle` as default.
