### ISSUE TITLE
class_alias cause  include 40 file, when not use project 

### ISSUE THREAD

**Issue by yanqibin** [elastic/elasticsearch-php#1224]
PHP 7.1  ，window or linux  (disable opcache)

AFTER I install   the client 
`composer require elasticsearch/elasticsearch`
I found  
- \elasticsearch\elasticsearch\src\autoload.php
```
foreach ($classesToAlias as $original => $alias) {
    if (!class_exists($alias, false)) {
        class_alias($original, $alias);
    }
}
```
class_alias cause include  40 files, it  use 0.008 seconds;
When I don't use this project ,it still include   files。
is batter to include   files，when I use  this  project ?

**Comment by ezimuel** [comment]
@yanqibin which version of `elasticsearch-php` are you using? The `src/autoload.php` is needed for BC with elasticsearch-php 7.4.1, for aliasing to the previous endpoint class names. If you are not using the project you can remove the dependency from your `composer.json` file.
The new `elasticsearch-php` version 8 does not use anymore this `src/autoload.php`.

**Comment by yanqibin** [comment]
thankyou  ,      "elasticsearch/elasticsearch": "^7.11"

**Comment by yanqibin** [comment]
thankyou  ,      "elasticsearch/elasticsearch": "^7.11"

**Comment by yanqibin** [comment]
thankyou  ,      "elasticsearch/elasticsearch": "^7.11"
