### ISSUE TITLE
Elasticsearch\Common\Exceptions\Curl\CouldNotConnectToHost cURL error 7:

### ISSUE THREAD

**Issue by ajrpayne** [elastic/elasticsearch-php#1225]
We are using SimpleConnectionPool, multiHandler, future mode off, to index single documents, not using bulk(Can't change this currently). During periods of high ingest we get the below error.

``
Elasticsearch\Common\Exceptions\Curl\CouldNotConnectToHost
cURL error 7:
``

With no further details as to what the curl 7 error is. Everything seems to be running normally on elasticsearch, and the requests continue to flow as normal after the period of high ingest. Hoping to find some direction here.

### System details

- Operating System
- PHP Version 8.1.6
- ES-PHP client 7.17
- Elasticsearch version 7.17

**Comment by ezimuel** [comment]
@ajrpayne the `cURL error 7` is [Failed to connect() to host or proxy](https://curl.se/libcurl/c/libcurl-errors.html). Are you using a proxy/firewall? 
If you have this issue only in high traffic scenario I think this can be related to the time wait TCP settings. I found an interesting discussion about this issue [here](https://stackoverflow.com/questions/32212207/curle-couldnt-connect-during-heavy-workload-tens-of-thousands-of-requests-per-m). How many connections do you see in high ingest scenario using `netstat` command?
A possible fix is to set the `tcp_tw_reuse` to `1` but this can affect the TCP especially using NAT.
```bash
sudo sysctl -w net.ipv4.tcp_tw_reuse=1
```
The `tcp_tw_reuse` allow to reuse `TIME_WAIT` sockets for new connections when it is safe from protocol viewpoint. [Here](https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux) you can read a very detailed explanation of this settings.
Changing this settings can be dangerous, you can definitely try if the PHP application is isolated from other services. A better aprroach maybe is to scale your PHP application using another server. In this way, you can spread the HTTP connections using multiple sources.
