### ISSUE TITLE
Dynamic hosts configuration

### ISSUE THREAD

**Issue by zamazan4ik** [elastic/elasticsearch-php#1239]
### Summary of problem or feature request
Hi!

In our current on-premise ElasticSearch (ES) setup we have configured load balancer (LB) before our ES cluster. So clients are connecting to LB and then requests are routed to each ES node (with a round-robin strategy).

AFAIK, nowadays there is no need to use a dedicated LB before the ES (e.g. an answer from SO: https://stackoverflow.com/questions/66098115/elasticsearch-cluster-load-balancing-best-practices), since clients should have some built-in load balancing capabilities.

`elasticsearch-php` has a `hosts` configuration, with which during the startup I can provide set of ES nodes, and they will be used for making the requests to ES.

My questions are the following:

1. Does `elasticsearch-php` use only provided in the configuration ES nodes? Can it retrieve active ES nodes during the initial connection to the ES cluster and then use retrived nodes, not a provided one from `hosts` field? Such an option will help with introducing new nodes into the cluster without the adding new hosts into the client's config.
2. What is the strategy for load-balancing between the provided hosts on the client side? Round-robin?
3. If some ES node becomes temporarily unavailable, does `elasticsearch-php` continues to send requests to the unavailable ES node?

Thanks in advance!

### System details

- Operating System: Linux
- PHP Version: 8.1
- ES-PHP client version: latest
- Elasticsearch version: 7.17

**Comment by ezimuel** [comment]
@zamazan4ik the answer depends on the `elasticsearch-php` version that you are using, 7.x or 8.x. This because for `elasticsearch-php` v8 we rewrote the client from scratch.
I see that you are using Elasticsearch 7.17 so I guess you are using `elasticsearch-php` v7.17.0, right?

**Comment by zamazan4ik** [comment]
@ezimuel yes, you are right. However, I am also interested about the current behavour for the 8.x versions as well.

**Comment by ezimuel** [comment]
For `elasticsearch-php` v7:

1. It is possible to use the [SniffingConnectionPool](https://www.elastic.co/guide/en/elasticsearch/client/php-api/7.17/connection_pool.html#_sniffingconnectionpool) to configure the client to sniff the node configuration during the connection. You need to specify one or more node in the hosts and then the client will execute the [Cluster State API](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/cluster-state.html) to re-assign the cluster hosts.
2. We support different strategies for managing the [connection pool](https://www.elastic.co/guide/en/elasticsearch/client/php-api/7.17/connection_pool.html). By default, we apply a round-robin algorithm using the [StaticNoPingConnectionPool](https://www.elastic.co/guide/en/elasticsearch/client/php-api/7.17/connection_pool.html#_staticnopingconnectionpool_default) strategy. If you want you can also implement your strategy, using the [ConnectionPoolInterface](https://github.com/elastic/elasticsearch-php/blob/v7.17.0/src/Elasticsearch/ConnectionPool/ConnectionPoolInterface.php).
3. No, it marks the node as dead and according to the ConnectionPool strategy it can be also resurrected (eg. after 60 seconds).

As I mentioned in `elasticsearch-php` v8 we rewrote the library from scratch using [PSR](https://www.php-fig.org/psr/) standards (PSR-3, PSR-7, PSR-18, etc). Right now we don't support all the previous ConnectionPool strategies of version 7. Actually, we renamed `ConnectionPool` in `NodePool` and we splitted the HTTP transport implementation in a separate project that is [elastic-transport-php](https://github.com/elastic/elastic-transport-php).

Regaring `elasticsearch-php` v8:

1. We don't have an implementation like the `SniffingConnectionPool`, the only implementation available at the moment is `Elastic\Transport\NodePool\SimpleNodePool` that uses round-robin as  with a static hosts list. We can definitely implement a strategy like `SniffingConnectionPool`.
2. Yes, the strategy used by default is Round-Robin but you can implement your custom strategy using the [SelectorInterface](https://github.com/elastic/elastic-transport-php/blob/master/src/NodePool/Selector/SelectorInterface.php).
3. Same behaviour of v7, by default we don't try to resurrect a dead node, if dead we remove the host in the list. We offer also an [ElasticsearchResurrect](https://github.com/elastic/elastic-transport-php/blob/master/src/NodePool/Resurrect/ElasticsearchResurrect.php) to resurrect a dead node using the ping API of Elasticsearch.

**Comment by zamazan4ik** [comment]
@ezimuel Thank you a lot! Would be awesome, if you add this information somewhere into the documentation. For future users will be much easier to find this information in the documentation and not in Github issues.

**Comment by ezimuel** [comment]
@zamazan4ik all the information are already in the official documentation, for 7.x [here](https://www.elastic.co/guide/en/elasticsearch/client/php-api/7.17/connection_pool.html) and for 8.x [here](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/node_pool.html).

**Comment by zamazan4ik** [comment]
@ezimuel thank you a lot! I do not know how I have missed this part of the documentation. I think the issue can be closed now.
