### ISSUE TITLE
StickyRoundRobinSelector starts with second host

### ISSUE THREAD

**Issue by mariancerny** [elastic/elasticsearch-php#1242]
### Summary of problem or feature request

When a list of multiple hosts is configured, `randomizeHosts` is disabled and `StickyRoundRobinSelector` is used the first connection goes to the second host (instead to the first one).

e.g. hosts:
- host1
- **host2**
- host3
- host4

Are tried in this order: **host2**, host3, host4, host1

### Code snippet of problem

From `StickyRoundRobinSelector::select()`:

        if ($connections[$this->current]->isAlive()) {
            return $connections[$this->current];
        }   

Because the first connection is not alive (yet), the first connection is skipped first time when `select()` is called.

### System details

elasticsearch-php v7.10.0

**Comment by ezimuel** [comment]
@mariancerny sorry for the delay, I'm looking into it right now.

**Comment by imdhemy** [comment]
I think it works as expected for the first connection, but it doesn't cover the following case:

**Given**
We have 3 connections, `A`, `B`, `C`.

| Connection | State   |
|------------|---------|
| A          | ❌ Dead  |
| B          | ❌ Dead  |
| C          | ✅ Alive |

**When**
Trying to select a connection.


**Then**
We should get the `✅ C` connection.

**Actual Behavior**
We get the (Dead) `❌ B` connection instead.

What do you think? @ezimuel

**Comment by ezimuel** [comment]
@mariancerny I just sent this PR https://github.com/elastic/elasticsearch-php/pull/1253 to fix the issue. I did a depth code analysis and I found that we assumed `false` for `isAlive` at the beginning. I changed this behaviour, now is `true` by default. Let me know if this works for you, thanks!

**Comment by mariancerny** [comment]
@ezimuel Thank you for the fix. Looks good to me. +1 for the test!
The PR has been approved so feel free to close this issue now or once it is merged.
Thanks again!

**Comment by ezimuel** [comment]
Fixed with #1253 and released in [v7.17.1](https://github.com/elastic/elasticsearch-php/releases/tag/v7.17.1)
