### ISSUE TITLE
vendor/ezimuel/ringphp/src/Exception/ConnectException.php  failed to open stream: Too many open files  

### ISSUE THREAD

**Issue by pnajithkumar** [elastic/elasticsearch-php#1244]
### Summary of problem or feature request

Hi,

We are getting an exception randomly as follows when we perform the indexing. While checking the logs on the elastic search server not finding any error info. 

."..vendor/ezimuel/ringphp/src/Exception/ConnectException.php): failed to open stream: Too many open files "

Could you please advise where could be the problem?

Thanks,
Ajith

### System details

- Operating System : ubuntu
- PHP Version: 7
- ES-PHP client version :7
- Elasticsearch version : 7.16

**Comment by ezimuel** [comment]
@pnajithkumar this can be a limit of the ubuntu environment that you are using. Every operating system only allows for a certain number of open files/handles/sockets. In Linux you can run the following commands to check this setting:
```bash
ulimit -n
```
You can increase this settings to `65535`. If you want to test in your current session yu can just execute the command:
```bash
ulimit -n 65535
```
To save this as permanent change you need to edit `/etc/sysctl.conf ` with sudo permission (in this example I use vim but you can use any editor, e.g. nano):
```bash
sudo vim /etc/sysctl.conf
```
and add the following line:
```
fs.file-max = 65535
```
Then run the following command to apply the change:
```bash
sudo sysctl -p
```
Let me know if this solved the issue, thanks!

**Comment by pnajithkumar** [comment]
Thanks for the response @ezimuel. So this limit should be added in the elastic search server OR the client from where we request for the indexing?  The exception details that we are getting from client exception message. 

include(/var/www/.../vendor/ezimuel/ringphp/src/Exception/ConnectException.php): failed to open stream: Too many open files  

Thanks you.

**Comment by mfn** [comment]
@pnajithkumar the client server, from where you perform the requests

**Comment by pnajithkumar** [comment]
Thank you @mfn .

**Comment by ezimuel** [comment]
@pnajithkumar do you solved the issue? Thanks.

**Comment by pnajithkumar** [comment]
@ezimuel, we did the config changes you mentioned, but the server configuration is still showing the old limit when we run the "ulimit -n". So we are still trying to find why the config not changing. Any suggestions appreciated. 
Thank you

**Comment by ezimuel** [comment]
@pnajithkumar if you execute:
```bash
sudo ulimit -n 65535
```
and after you execute:
```bash
ulimit -n
```
you still see the old value and not 65535? Maybe this [discussion](https://askubuntu.com/questions/162229/how-do-i-increase-the-open-files-limit-for-a-non-root-user) can help.

**Comment by ezimuel** [comment]
@pnajithkumar I'm closing this issue. If you need more assistance I can reopen it, thanks.
