### ISSUE TITLE
why id is always required when I use the document creating api

### ISSUE THREAD

**Issue by Torontototokyo** [elastic/elasticsearch-php#1246]
### System details

- Operating mac m1
- PHP 8.0
- ES-PHP client 7.17
- Elasticsearch 7.17

**Comment by ezimuel** [comment]
@Torontototokyo if you refer to the `index()` API, you can also do not specify the `id` and let Elasticsearch create one for you.
Here an example where I index the document `{'foo':'bar'}` with and without an `id`:
```php
$document = [
    'foo' => 'bar'
];

$result = $client->index([
    'index' => 'test',
    'body' => $document
]);

echo $result['_id']; // ID created by Elasticsearch (eg. 4X1gpYIB7ip_OwKMI3e9)

$result = $client->index([
    'id' => 'baz',
    'index' => 'test',
    'body' => $document
]);

echo $result['_id']; // baz
```

**Comment by Torontototokyo** [comment]
very clear,thanks

**Comment by ezimuel** [comment]
@Torontototokyo if you are looking for other example of `elastcsearch-php` I suggest to have a look at  https://github.com/elastic/elasticsearch-php-examples

**Comment by Torontototokyo** [comment]
> @Torontototokyo if you are looking for other examples of `elastcsearch-php` I suggest to have a look at  https://github.com/elastic/elasticsearch-php-examples
ok,thanks
