### ISSUE TITLE
No PSR-18 clients found. Make sure to install a package providing "psr/http-client-implementation"

### ISSUE THREAD

**Issue by M-Brico** [elastic/elasticsearch-php#1252]
### Summary of problem or feature request

We've upgraded our Dev Elastic deployment to 8.4 and in the process of looking at whether our service implementation needs an update.

Looking through the documentation it appears not but I'm getting

`Http\Discovery\Exception\NotFoundException: No PSR-18 clients found. Make sure to install a package providing "psr/http-client-implementation". Example: "php-http/guzzle7-adapter". in Http\Discovery\Psr18ClientDiscovery::find() (line 27 of /var/www/html/vendor/php-http/discovery/src/Psr18ClientDiscovery.php).`

There seems to be no mention of this in the App Search docs. I even installed with dependencies. 

### Code snippet of problem

```php
 protected function connect(): void {
    $elastic_client = new Client([
      'host' => $this->getApplicationHost(),
      'app-search' => [
        'token' => $this->getApiToken(),
      ],
    ]);

    $this->appSearch = $elastic_client->appSearch();
  }
```

### System details

- PHP Version 8.0
- ES-PHP client version 8.4
- Elasticsearch version 8.4

**Comment by M-Brico** [comment]
Ah I think I've posted in the wrong repo - apologies

**Comment by ezimuel** [comment]
@M-Brico yes, for App Search the repository is https://github.com/elastic/enterprise-search-php
