### ISSUE TITLE
License incompatibility

### ISSUE THREAD

**Issue by Crell** [elastic/elasticsearch-php#126]
This library is currently Apache 2 licensed.  While there's nothing wrong with that itself per se, it is not compatible with GPLv2.  (This is a well-known and long standing annoyance.)  That means no one working on a GPL codebase can use this library. :frowning: 

With the Drupal project adopting Guzzle 4 in Drupal 8 as a standard component, I would _love_ to be able to push Drupal developers to use Elasticsearch more over Solr.  The license incompatibility, though, means I have to tell them to not even look at it.  Is there any way to switch the license to MIT or BSD, or maybe dual-license Apache2/GPL?  

I know a number of other libraries have made that switch for increased license compatibility, as there's a ton of very-active GPL PHP projects around (including the big-3, Drupal/Joomla/Wordpress, all of whom are GPLv2+).  As is, none of them can use this library.

**Comment by ezimuel** [comment]
@Crell is the Drupal license still in conflict with Apache 2? As you know we added the double license using Apache 2 and LGPL v2.1. I'm wondering if the latest is still needed, I would like to simplify the licensing using only Apache 2. Let me know, thanks!

**Comment by Crell** [comment]
I am no longer involved with Drupal, but Apache2 is and will always be incompatible with GPLv2.  It is inbound compatible with GPLv3 (according to FSF at least), but Drupal has made it clear it is unlikely to ever move to GPLv3 because corporations want their loopholes.

Honestly, I find Apache2 a pointless license for web software these days.  GPLv3 provides the same protections and more for developers, and neither provide any protection at all for the end user (who is the original intended beneficiary of Free Software).  LGPLv3 is a reasonable middle ground if you want a single license.

**Comment by ezimuel** [comment]
@Crell thanks for the feedback!
