### ISSUE TITLE
406 Not Acceptable: {"error":"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported","status":406}

### ISSUE THREAD

**Issue by rockyru** [elastic/elasticsearch-php#1262]
### Summary of problem or feature request

I am getting this error
![image](https://user-images.githubusercontent.com/13403945/198621820-2b393fc3-508d-4157-bc7f-778b3e3fbe1a.png)

### System details

- Operating System: ubuntu 18.4
- PHP Version: 8.1.11
- ES-PHP client version: 8.4
- Elasticsearch version: 7.10

**Comment by ezimuel** [comment]
@rockyru I see you are using Elasticserach server version 7.10 and `elasticserch-php` version 8.4. You must use `elasticsearch-php` version 7. I sugget to use the latest of the 7 branch that is [7.17.1](https://github.com/elastic/elasticsearch-php/releases/tag/v7.17.1).
Let me know if you need more help, thanks.

**Comment by rockyru** [comment]
hi @ezimuel , I've used the latest on the 7 branch that is 7.17.1 and can confirm that it's working. Thank you!
