### ISSUE TITLE
Search endpoint is using method POST instead of GET, or how can I set the request method

### ISSUE THREAD

**Issue by amorellp** [elastic/elasticsearch-php#132]
Hi again.
I want to use the client to run a query like this:

$ curl -XGET 'localhost:9200/aaa/bbb/_search?q=*'

and I did it this way:

$params = array();
$params['index'] = 'aaa';
$params['type']  = 'bbb';
$params['body']['query']['match']['title'] = "white";
$results = $client->search($params);

The problem is that instead of a GET, the used method was a POST, as can be seen in these lines extracted from the log:

[2014-09-19 09:02:45] log.DEBUG: Request Body ["{\"query\":{\"match\":{\"title\":\"white\"}}}"]...
[2014-09-19 09:02:45] log.WARNING: Request Failure: {"method":"POST","uri":"http://127.0.0.1:9100/aaa/bbb/_search","headers":{"host":["127.0.0.1:9100"],"user-agent":["Guzzle/3.9.2 curl/7.38.0 PHP/5.6.0-1"],"content-length":[37]},"HTTP code":"{\"status\":403,\"message\":\"Forbidden. Not authorized.\"}",...

The difference is important to me, because I only allow queries using the GET methods. In the javascript client, I solved the problem using "method: 'GET'" in the request.

Is there something similar in the php client?

Even if there is not an equivalent to the javascript method parameter, I wonder that the search is using the POST method. In class AbstractEndpoint, the performRequest method is called using the factory method $this->getMethod():

abstract class AbstractEndpoint
{
...
    public function performRequest()
    {
        $result = array();

        try {
            $result =  $this->transport->performRequest(
                $this->getMethod(),
                $this->getURI(),
                $this->params,
                $this->getBody()
            );
        }...
...

which in the case of the search endpoint is returning GET:

class Search extends AbstractEndpoint
{
...
    protected function getMethod()
    {
        return 'GET';
    }
...
}

Bye.

**Comment by polyfractal** [comment]
Closing due to age, and this feature was added:

**Comment by vrkansagara** [comment]
@polyfractal  This issue still persist with "elasticsearch/elasticsearch": "^7.0"

**Comment by vrkansagara** [comment]
yes @polyfractal  We need some way to another optional parameter to set http method with `->serch()`  and for such equivalent issues.

I just wanted to make sure that developer has full controller over http method to override it. So they filter on security side as well.
