### ISSUE TITLE
Why require `guzzlehttp/guzzle` while `elastic/transport` is client agnostic?

### ISSUE THREAD

**Issue by ruudk** [elastic/elasticsearch-php#1337]
### Summary of problem or feature request

Maybe I'm missing something, but why does this package [depend](https://github.com/elastic/elasticsearch-php/blob/6b79336b8d2d4037a7b07b2465574b00e2c770f2/composer.json#L18) on `guzzlehttp/guzzle` while `elastic/transport` can support any PSR client?

**Comment by ezimuel** [comment]
We decided to simplifying the usage of this library offering a default client, and we choose Guzzle. If you want, you can change the HTTP client using the `setHttpClient()` function of the client builder, [here the documentation](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/http-client.html#http-client).

**Comment by ruudk** [comment]
I understand, but the fact that you require it as a dependency doesn't make sense to me. I think that you want to improve the Developer Experience to automatically require it, but people that pull in this dependency know how to also require a suggested HTTP client. It should be in `suggests` so that people can freely choose without pulling in Guzzle. I hope you can reconsider it ☺️

**Comment by ezimuel** [comment]
@ruudk thanks for your feedback, I agree from a technical point of view but from a product perspective this simplify the process. The majority of the users use guzzle. The only disadvantage is having guzzle installed even if you don't use it, and this is a rare case. That said, we can reconsider it in the next major release if the user scenarios and requirements will change.
