### ISSUE TITLE
Match all

### ISSUE THREAD

**Issue by paulhuisman** [elastic/elasticsearch-php#135]
Hi there,

Sorry for asking, but can anyone tell me if there's a match_all method available to just get 'latest' 10 items in index?

Something like this:
`
POST /documents/_search
{
   "query": {
      "match_all": {}
   }
}
`

**Comment by tzoori7** [comment]
works for me...

$searchParams['index'] = 'YOUR_INDEX';
$searchParams['type'] = 'YOUR_TYPE';
$searchParams['body']['query']['match_all'] = array();

**Comment by abraaoz** [comment]
If you are getting the error "[match_all] query malformed, no start_object after query name":
```php
$client = new Elasticsearch\Client();
$params = [
  'index' => 'documents',
  'body' => [
    'match_all' => (object)[] // this cast is necessary!
  ]
];
$results = $client->search($params);
```

**Comment by dfutrille** [comment]
> If you are getting the error "[match_all] query malformed, no start_object after query name":
> 
> ```
> $client = new Elasticsearch\Client();
> $params = [
>   'index' => 'documents',
>   'body' => [
>     'match_all' => (object)[] // this cast is necessary!
>   ]
> ];
> $results = $client->search($params);
> ```

Excellent!! This works for me!!!

**Comment by nfsecurity** [comment]
> > If you are getting the error "[match_all] query malformed, no start_object after query name":
> > ```
> > $client = new Elasticsearch\Client();
> > $params = [
> >   'index' => 'documents',
> >   'body' => [
> >     'query' =>  [
> >         'match_all' => (object)[] // this cast is necessary!
> >     ]
> >   ]
> > ];
> > $results = $client->search($params);
> > ```
> 
> Excellent!! This works for me!!!

This works for me too, thanks!
