### ISSUE TITLE
Ability to Execute _enrich Policy and Utilize JSON File Attachments in Bulk Operations with elasticsearch-php SDK

### ISSUE THREAD

**Issue by yesee-yongb-xu** [elastic/elasticsearch-php#1355]
### Summary of problem or feature request

Hello,

I am reaching out to inquire about some functionalities in the elasticsearch-php SDK:

Is it possible to execute an _enrich policy using a command similar to POST /_enrich/policy/A/_execute within the SDK?
Can I perform bulk operations using the POST _bulk endpoint with attached JSON files?
I am looking forward to understanding how to utilize these features (if supported) within the elasticsearch-php SDK. Your guidance would be highly appreciated.

Thank you!

### System details

- Operating System:Ubuntu22.04
- PHP Version:PHP8.1
- ES-PHP client version:8.9.0
- Elasticsearch version:8.9.0

**Comment by ezimuel** [comment]
@yesee-yongb-xu sorry for my late reply. Here an example using [execute enrich policy API](https://www.elastic.co/guide/en/elasticsearch/reference/current/execute-enrich-policy-api.html):
```php
use Elastic\Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()
    ->setHosts(['put here the Elasticsearch URL'])
    ->build();

$params = ['name' => 'A'];

// Execute enrich policy API
$response = $client->enrich()->executePolicy($params);
```
And here an example of [bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) with 3 JSON files. Please note, in this example I'm using `_id` equal to 1, 2 and 3.
```php
$files = [ 'file1.json', 'file2.json', 'file3.json'];

$params = [
    'index' => 'put here name of the index',
    'body' => []
];
$i = 1;
foreach ($files as $file) {
    $json = json_decode(file_get_contents($file), true);
    $params['body'][]= [
        'index' => [
            '_id' => $i++
        ]
    ];
    $params['body'][] = $json;
}
$response = $client->bulk($params);
```
Let me know if you need more help.

**Comment by yesee-yongb-xu** [comment]
Wow, I am unable to locate this use in the elasticsearch-php SDK file.
Thank you,i will try it.
