### ISSUE TITLE
No query registered for [missing] => query bool must

### ISSUE THREAD

**Issue by LeStef** [elastic/elasticsearch-php#136]
Hello,

When i try execute the php code below, it returns 

[Guzzle\Http\Exception\ClientErrorResponseException]  
  Client error response  
  [status code] 400  
  [reason phrase] Bad Request  
  [url] http://localhost:9200/gnagna/news/_search

nested: QueryParsingException[[gnagna] No query registered for [missing]]

Here is the code

$body = array(
            'query' => array("bool" => array(
                "must" => array(
                    array(
                        "range" => array(
                            "metaData.indexationDate" => array(
                                "gte" => "2014-09-24 10:00:00",
                                "lte" => "2014-09-24 10:05:00"
                            )
                        )
                    ),
                    array(
                        "missing" => array(
                            "field" => "metaData.scores.fbScore"
                        )
                    )
                )
            )),
            'size' => 50,
            'sort' => array(
                'metaData.indexationDate' => array(
                    'order' => 'desc'
                )
            )
        );
        $request = array(
            'index' => "tbm_fr",
            'type' => "news",
            'body' => $body,
        );
        $results = Es::search($request);

We are using the 1.3.0 version of Elasticsearch and the 1.2.2 version of the client.

Furthermore, the structure of the query seems correct.

Best regards,

**Comment by jiangliuer326442** [comment]
no [query] registered for [filtered]

**Comment by jiangliuer326442** [comment]
It says no [query] registered for [filtered]

**Comment by polyfractal** [comment]
Filtered query does not exist in Elasticsearch 5.x anymore.  It was deprecated in 2.x, and removed in 5.x

**Comment by abhishek5678** [comment]
Also it is not working in 2.x.so how can i solve this problem help me and also tell me what is the new feature in 5.x

**Comment by abhishek5678** [comment]
same things will be showing like that no query registered for filtered so give me that proper example with mappings
