### ISSUE TITLE
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.

### ISSUE THREAD

**Issue by maximepvrt** [elastic/elasticsearch-php#1364]
### Summary of problem or feature request

https://github.com/php-http/message-factory

### System details

- Operating System
- PHP Version
- ES-PHP client version
- Elasticsearch version

**Comment by ezimuel** [comment]
I opened #1367 but I've an issue with PHP 7.4. I need to figure out how to fix it. Anyway, we will probably end the support for PHP 7.4 at the end of the year.
