### ISSUE TITLE
`Response\Elasticsearch::offsetGet()` return type declaration

### ISSUE THREAD

**Issue by AnnaNtagiou** [elastic/elasticsearch-php#1384]
### Summary of problem or feature request

There is a deprecation notice for the `Response\Elasticsearch::offsetGet()` related to the return type.

### Code snippet of problem

```
Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Elastic\Elasticsearch\Response\Elasticsearch" now to avoid errors or add an explicit @return annotation to suppress this message.
```

### System details

- PHP Version: 8.2
- ES-PHP client version: 7.17
- Elasticsearch version: 8.11

**Comment by ezimuel** [comment]
@AnnaNtagiou why are you using `elasticsearch-php` 7.17 with Elasticsearch 8? You should upgrade the client to version 8, using `"elasticsearch/elasticsearch": "^8"` in composer. If you need more information on upgrade to version 8, you can read this [notes](https://github.com/elastic/elasticsearch-php/blob/8.0/BREAKING_CHANGES.md).
