### ISSUE TITLE
Need a new Release 6.8.3

### ISSUE THREAD

**Issue by aistisstramkauskas** [elastic/elasticsearch-php#1386]
Hello, could you please make a new release `6.8.3` to from `6.8` branch to rollout `psr/log` [v2/3 compatibility](https://github.com/elastic/elasticsearch-php/commit/f3e0336ba95fdcd2e7aca73f7e8d29b3b301879c)?

Thank you in advance!

**Comment by ezimuel** [comment]
I'm sorry but we do not provide new features for 6.x versions. Which version of Elasticsearch server are you using? Maybe you can upgrade to `elasticsearch-php` v7 or v8.

**Comment by meze** [comment]
Yes, it's needed to support php 8.3.x, the fix is already in 6.8.x branch, we just need a new version tag

**Comment by ezimuel** [comment]
Just released [v6.8.3](https://github.com/elastic/elasticsearch-php/releases/tag/v6.8.3). Thanks @aistisstramkauskas and @meze for the patience.
