### ISSUE TITLE
failed to get the last sort using search_after

### ISSUE THREAD

**Issue by chongshengdz** [elastic/elasticsearch-php#1408]
$lastHit = end($results['hits']['hits']);
the above line getting the below error, please help.
PHP Notice: Indirect modification of overloaded element of Elastic\Elasticsearch\Response\Elasticsearch has no effect
i am using elasticsearch-php version 8.13.0
@ezimuel  help, please

**Comment by ezimuel** [comment]
Commented in https://github.com/elastic/elasticsearch-php/issues/1404#issuecomment-2177822582
