### ISSUE TITLE
will elasticsearch-php pre-open the urls on the page when I visit it?

### ISSUE THREAD

**Issue by chongshengdz** [elastic/elasticsearch-php#1410]
I wrote an extension using elasticsearch-php to search my seo urls for my website.
but when I turn on the extension, the port 80 goes up rapidly.
when i turn off the extension, everything goes normal.
will elasticsearch-php pre-open the urls on the page when I visit it?

**Comment by chongshengdz** [comment]
port 80 being flooded by thousands of connections when I turn on elasticsearch-php

**Comment by chongshengdz** [comment]
When I turn on elasticsearch, it produces hundreds thousands of TIME_WAIT connections

tcp6       0      0 ::1:58056               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:46180               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:46380               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:36806               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:58086               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:46880               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:44800               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:48880               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:43580               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:47980               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:38380               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:35180               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:39580               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:49180               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:34480               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:53807               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:53880               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:46480               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:38092               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:59280               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:58808               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:58070               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:58018               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:39806               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:52809               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:54804               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:53802               ::1:9200                TIME_WAIT   -
tcp6       0      0 ::1:52280               ::1:9200                TIME_WAIT   -

**Comment by ezimuel** [comment]
@chongshengdz the `elasticsearch-php` uses port 9200 by default for connecting to Elasticsearch but only when an endpoint is executed, e.g. `$client->info()`.

Which version of `elastic/elasticsearch-php` and PHP are you using? 
Can you show me the initialization code of the `Elastic\Elasticsearch\Client`? 
Are you using the `ClientBuilder`?

Let me know, thanks.

**Comment by chongshengdz** [comment]
> [@chongshengdz](https://github.com/chongshengdz) the `elasticsearch-php` uses port 9200 by default for connecting to Elasticsearch but only when an endpoint is executed, e.g. `$client->info()`.
> 
> Which version of `elastic/elasticsearch-php` and PHP are you using? Can you show me the initialization code of the `Elastic\Elasticsearch\Client`? Are you using the `ClientBuilder`?
> 
> Let me know, thanks.

it is because elasticsearch doesn't work like MySQL or MariaDB, all search requests are from http requests.
if too many elasticsearch http search requests, vps server cannot handle it.
