### ISSUE TITLE
"Type: illegal_argument_exception Reason: "Fielddata is disabled on [pageCategory] in [elastic_web_index]. Text fields are not optimised for operations that require per-document field data like aggregations

### ISSUE THREAD

**Issue by anujlattice** [elastic/elasticsearch-php#1412]
eason: "all shards failed" CausedBy: "Type: illegal_argument_exception Reason: "Fielddata is disabled on [pageCategory] in [sitecore_elastic_web_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [pageCategory] in order to load field data by uninverting the inverted index. Note that this can use significant memory." CausedBy: "Type: illegal_argument_exception Reason: "Fielddata is disabled on [pageCategory] in [sitecore_elastic_web_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [pageCategory] in order to load field data by uninverting the inverted index. Note that this can use significant memory.""" ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.

 var result3 = client.Search<ElasticSearchResultItem>(s => s
      .Query(q => q.Term(P => P.Name.ToLowerInvariant(), query.QueryText.ToLowerInvariant())
             && q.Term(P => P.Title.ToLowerInvariant(), query.QueryText.ToLowerInvariant())
             && q.Term(P => P.Description.ToLowerInvariant(), query.QueryText.ToLowerInvariant()))
      .Aggregations(ag => ag
         .Terms("PageCategory", term => term
         .Field(field => field.PageCategory)
         .Size(int.MaxValue))));

**Comment by ezimuel** [comment]
@anujlattice the code that you provide looks like C# using the NEST client, this is the repository for the PHP client. You should open this issue in https://github.com/elastic/elasticsearch-net/issues. Thanks.
