### ISSUE TITLE
json_decode potentially throws E_NOTICE due to integer overflow

### ISSUE THREAD

**Issue by bezhermoso** [elastic/elasticsearch-php#145]
When dealing with unusually high/low scores, `json_decode` throws an `E_NOTICE`: `Notice: json_decode(): integer overflow detected`

In my case it was caused by this part of the JSON response: 

``` javascript
{..."sort":["Test",0,null,-9223372036854775808]}]}}
```

This may not be an issue to some server configurations, but some may encounter this problem. This would be negligible in production servers where error reporting is turned off, but this causes problems in dev environments.

**Comment by designermonkey** [comment]
Sorry to be a pain @polyfractal, but this is happening to me in `1.4.1`

**Comment by polyfractal** [comment]
@designermonkey do you mean the client is throwing an exception, or not throwing one?

The "fix" was to throw an explicit exception if E_NOTICE is on, otherwise continue with old behavior (letting PHP throw an E_NOTICE) so that bwc was maintained.  Not a great solution, but there you go :)

**Comment by designermonkey** [comment]
All I get is a php E_NOTICE for every result that overflows. Obvs it's only locally, but thought I should at least mention it.
