### ISSUE TITLE
More robust json handling

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch-php#151]
It appears that the json_\* functions are far buggier than I imagined.  Nette has a good class which handles json encoding/decoding and all the weird edge cases:

http://phpfashion.com/how-to-encode-and-decode-json-in-php
https://github.com/nette/utils/blob/master/src/Utils/Json.php

Some of the fixes we can ignore, since we only support down to PHP 5.3.9.  Nette is BSD/GPL dual licensed, so it should be compatible. 

This will have to be a 2.0 breaking change, since it will introduce new exceptions that were silently ignored previously.

Related to #146

**Comment by philkra** [comment]
lib version no longer supported
