### ISSUE TITLE
initial setup woes

### ISSUE THREAD

**Issue by sr1234** [elastic/elasticsearch-php#153]
Hi Zachary,

I had pinged Drew about the issue we were having getting setup and started using es-php and you asked me to submit a ticket in the repo so here I am. :)

Basically we have an application we are building using Yii (1.1).  

We installed ES with composer, added the autoloader to our code:

require 'vendor/autoload.php';

then we tried instantiating:

$params = array();
$params['hosts'] = array (
    'http://our_ip:9200'  
);

$client = new Elasticsearch\Client($params);

And we tried 

$params = array();
$params['body']  = array('testField' => 'abc');

$params['index'] = 'my_index';
$params['type']  = 'my_type';
$params['id']    = 'my_id';

// Document will be indexed to my_index/my_type/my_id
$ret = $client->index($params);

from instructions at http://www.elasticsearch.org/guide/en/elasticsearch/client/php-api/master/_indexing_operations.html

Of course we gave the index, type and my_id actual values to put into the index.

We just get a 500 error.  

I should let you know that we can access our ES installation with Marvel and Sense no problem.  We are running in an AWS environment.   Only one test ES node right now.  We just want to be able to index and search from our app first, before getting into more complex configurations.

We have tried a number of different approaches.  The code seems to execute fine, till it reaches the line:
$ret = $client->index($params);

After which it breaks.

We have also tried different types of operations, like for instance just creating an index.  Same thing happens.  I'm not sure if we are missing a step in our overall configuration of the es-php client.  Your docs mention Pimple.... Not sure if we have to use that or not.

I apologize for the sparseness of info here.  Not sure what else I can give you that can help to troubleshoot.

Many thanks in advance for any help you can provide.

Regards,
Sam

**Comment by vishparshav** [comment]
Hi sr1234,
I am facing the same problem. I have installed es on aws machine and trying to connect it through my local computer but facing this problem. Installed es client using composer. I have gone through the post but could not understand how you fixed the issue. So please help me out it I am new to aws and es.

**Comment by polyfractal** [comment]
@vishparshav Can you paste your code and the error message that you are seeing?

**Comment by vishparshav** [comment]
Hi Zach,
Thanks for the reply. It was resolved.

On Thu, Feb 12, 2015 at 7:18 PM, Zachary Tong <notifications@github.com>
wrote:

> @vishparshav <https://github.com/vishparshav> Can you paste your code and
> the error message that you are seeing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch-php/issues/153#issuecomment-74072674>
> .
>



-- 
Regards,

Vishesh Parshav

**Comment by mmeans** [comment]
Hi - I am having a similar issue, but I am not sure I understand how the issue was fixed.

In my Laravel project, I have:  

  $params = array();
  $params['hosts'] = array ('http://...);
  $ret = $client->index($params);

and I get back the error as shown above.

"hosts" is not a valid parameter. Allowed parameters are: "consistency", "op_type", "parent", "percolate", "refresh", "replication", "routing", "timeout", "timestamp", "ttl", "version", "version_type", "ignore", "custom", "curlOpts"

Any help would be appreciated.  Thank you.
