### ISSUE TITLE
Lock down guzzle (and all dependencies) Latest guzzle that passes requirements breaks client

### ISSUE THREAD

**Issue by swarajban** [elastic/elasticsearch-php#155]
I have been using the elasticsearch client the last few weeks with no problems. I just did a fresh re-install of composer dependencies and I started getting this error:

```
[14-Nov-2014 21:02:37 UTC] PHP Fatal error:  Class 'Guzzle\Http\Client' not found in /elabs/www/mindmeld-api-v2/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Common/DICBuilder.php on line 345
```

`composer.json` for elasticsearch-php has `"guzzle/http": "~3.7"` as the dependency. It should be locked down because the latest guzzle/http that matches (3.9.2) has a different namespace for the HTTP client and breaks the DICBuilder (and likely other) classes

~ Swaraj

**Comment by slamkajs** [comment]
Currently experiencing this issue.  It occurred after an update fro Debian 7 to Debian 8.  Another machine running Ubuntu 13.10 has no issue.  Running a diff on the composer.lock files brings no differences.  Find the composer.lock at the following link: http://pastebin.com/CmMGXgEw

OS: Debian 8
PHP Version: 5.6.7-1
CakePHP Version: 2.5.8
