### ISSUE TITLE
add curl's connection timeout parameter to the php client 

### ISSUE THREAD

**Issue by nivpenso** [elastic/elasticsearch-php#170]
There is no an easy way to set a connection timeout to the php client.

You can watch the issue here:
http://stackoverflow.com/questions/25491110/set-connect-timeout-of-elasticsearch-php-client/25522782#25522782

i suggest to add a parameter named "connection_timeout" that will indicate the curl's connection timeout to the elasticsearch cluster

**Comment by polyfractal** [comment]
This can be done on a per-configuration basis in ES-PHP 2.0: https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_per_request_configuration.html#_curl_timeouts
