### ISSUE TITLE
Build auto-generated API documentation

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch-php#174]
The set of endpoints available in ES makes it impractical to document every endpoint individually.  However, most endpoints are well annotated with doc blocks comments, so an auto-generated API documentation would prove useful for people that understand the basics of how the client is used, but are looking for a particular endpoint.

Popular generators:
- [phpDocumentor](http://www.phpdoc.org/)
- [ApiGen](http://apigen.org/)
- [DoxyGen](http://www.stack.nl/~dimitri/doxygen/index.html)

I have zero preference, although I've used phpDoc a bit in the past.  The biggest hurdle will be integrating with the doc build system, which currently renders AsciiDoc into HTML.  Will probably need to find a way to bypass the AsciiDoc generation and just upload straight HTML

**Comment by fprochazka** [comment]
Apigen :+1:

**Comment by TomasVotruba** [comment]
@fprochazka is correct (e.g. [Doctrine API](http://www.doctrine-project.org/api/orm/2.4/class-Doctrine.ORM.EntityRepository.html))

@polyfractal I'm just about to release new stable. If you need some help with implementation, let me know.

**Comment by polyfractal** [comment]
@TomasVotruba Awesome, thanks!  I'll ping you once I start working on this...need to sort out some hosting logistics internally first.  It looks like our existing doc infrastructure will be difficult to integrate with, since it is built entirely around AsciiDoc.

**Comment by jerrac** [comment]
I was just wondering why there weren't any api docs... :)

On a related note, in the phpdoc comments, why are there no descriptions of what the function is supposed to do? Or what you can/should put in the $params array options?

For example, I was just figuring out how to get the detailed status information about a specific, existing, snapshot. The equivalent of:

```
curl -XGET "localhost:9200/_snapshot/my_backup/snapshot_1/_status"
```

I saw ```Elasticsearch\Namespaces\SnapshotNamespace::status()``` and figured that I could pass the snapshot name to it, and get what I wanted. That didn't work. What I really wanted was ```Elasticsearch\Namespaces\SnapshotNamespace::get()``` method. Which did work. 

From the looks of the code, not having that kind of documentation was a deliberate decision. If so, what is the reasoning behind it?

Anyway, I'd love to see "This is the function you want to use when you want the equivalent of curl -XGET 'localhost:9200/_blah/lbah?pretty'." in the phpdoc comments. If it's actually a good idea...

**Comment by polyfractal** [comment]
> On a related note, in the phpdoc comments, why are there no descriptions of what the function is supposed to do? Or what you can/should put in the $params array options?

A few reasons, some good, some not-so-good :)  In general, the phpdocs for each Namespace method are supposed to be documented with all the available parameters.  For example, the [`GetMapping` API](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/IndicesNamespace.php#L146-L148) lists two parameters (`index`, `type`), which correspond to the Elasticsearch URL:

```
curl -XGET localhost:9200/$index/_mapping/$type
```

These API endpoints are generated in part from the [REST API Spec](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/api) (e.g. the spec for [GetMapping](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/api/indices.get_mapping.json))

The reason that endpoints don't have english descriptions is that there are 150+ endpoints and no one has hand-annotated the REST spec yet.  And I haven't hand-annotated the PHP client yet either.  Largely, the name of the endpoint corresponds to the name in the Elasticsearch documentation (e.g. [Get Mapping API](http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html) == GetMapping)

That's not necessarily a good reason, but it's the main reason :)  

I would love someone forever if they wanted to start submitting PR's that improved the documentation (wink wink :D)

### Snapshot namespace
Now, with that said, it looks like the snapshot namespace isn't properly annotated.  The params field in each docblock should also list the URI parameters like `$snapshot` and `$repository`.  That's a documentation bug, and should be fixed :)

As an aside, if you wanted:

```
curl -XGET "localhost:9200/_snapshot/my_backup/snapshot_1/_status"
```

The `SnapshotNamespace::status()` endpoint was infact the one you wanted.  You can [see the URL builder here]([https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Snapshot/Status.php#L80-L84]):

```php
$uri = "/_snapshot/_status";
if (isset($repository) === true) {
    $uri = "/_snapshot/$repository/_status";
} elseif (isset($repository) === true && isset($snapshot) === true) {
    $uri = "/_snapshot/$repository/$snapshot/_status";
}
```

That corresponds to the [Elasticsearch Snapshot Status API](http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_snapshot_status)

The endpoint you ended up using, `SnapshotNamespace::get()`, corresponds to the [Get Snapshot API](http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_monitoring_snapshot_restore_progress) (also called "Snapshot Info", similar to how there is Nodes Stats / Nodes Info APIs)

**Comment by polyfractal** [comment]
Added some autogenerated docs for the namespaces/endpoints.  This is mainly to help the end-user.

I still want to generate robust documentation for the entire client, but unfortunately that looks like it's going to take some work massaging the output into asciidoc.  Or talking to the infra team to host non-asciidoc docs.

Regardless, this is a nice first step :)

**Comment by Byakkun** [comment]
Something that the documentation should improve on is generating the return values and thrown exceptions for the API endpoints. I get why there aren't descriptions for each mapped endpoint but having the return values types and especially what they can end up throwing really can end up a big help. I've seen in the source code that the client endpoint methods are build dynamically, so I was wondering if anyone knows a good way have the generated docs for them inherit the thrown exceptions of their specific implementation? 

If anyone with experience in writing library code and documentation for this kind of situations and can point me in the right direction I can pick up this task and have a pull request in a few weeks.

**Comment by polyfractal** [comment]
We can add return values to the API reference docs, although they will largely be `array`.  The vast majority of endpoints just return an associative array (e.g. the decoded JSON value).  The exception are endpoints that use [BooleanRequestWrapper](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php), which are basically the `exist` endpoints.  Those return true/false.

As far as exceptions, all endpoints return the same set of possible exceptions.  I agree we should list them out, but I'm not sure we need to define it for each endpoint since they are all identical.  Basically, no exception is thrown unless we are trying to talk to Elasticsearch, and we only talk to Elasticsearch when you invoke an endpoint.  So all endpoints throw the same exceptions (be it a 4xx level "syntax error" or 5xx level "no nodes" or "cluster is broken" type error)

Will happily accept contributions to make the docs and/or doc generation better!  It was a rather slapdash effort to just get them up in some form... plenty of room for improvement.

The docs are generated with Sami.  The [config is here](https://github.com/elastic/elasticsearch-php/blob/master/util/docsConfig.php) and the [theme/template is here](https://github.com/elastic/elasticsearch-php/tree/master/util/docstheme)

**Comment by ezimuel** [comment]
I'm working on some automation tool for updating the documentation and all the API endpoints. Closing this issue at the moment.
