### ISSUE TITLE
Memleak

### ISSUE THREAD

**Issue by tfe2012** [elastic/elasticsearch-php#204]
If you try import dbdump (5-10GB)

write code like: 

foreach ($reader as $key => $document) {
            $manager->getConnection()->bulk('index', $document['_type'], $data);

            if (($key + 1) % $bulkSize == 0) {
                $manager->commit();
            }
        }

memory usage grow very quickly .

Then i comment this line  

https://github.com/elastic/elasticsearch-php/blob/756161b2256aa62ceabac27eb9fa2ce539098dc8/src/Elasticsearch/Connections/GuzzleConnection.php#L214

memory stop growing

**Comment by polyfractal** [comment]
So that line saves the last request (so you can check it afterwards for debugging and logging) as well as logging a message about the request.  If logging is disabled, the message is blackholed by Monolog.

Are you unsetting the bulk data after each request?  It's a common problem to build a bulk, send it, then continue adding to the same bulk object without unsetting it first.  This will cause the bulk request to grow exponentially (as well as potentially duplicating data), which causes the "last request info" to also grow exponentially.

```php
$params = [
  'index' => 'my_index',
  'type' => 'my_type'
];

foreach ( ... ) {

  $params['body'][] = ['index' => [] ];
  $params['body'][] = [
    'my_field' => 'abc'
  ];

  if (($key + 1) % $bulkSize == 0) {
    $responses = $client->bulk($params);

     // Unset the bulk and the response to free memory
    unset($responses);
    unset($params['body']);
  }
}

```

**Comment by polyfractal** [comment]
Ping?

**Comment by tfe2012** [comment]
it's my code example 

```php
 /**
     * Flushes the current query container to the index, used for bulk queries execution.
     */
    public function commit()
    {
        $this->bulkQueries = array_merge($this->bulkQueries, $this->bulkParams);
        $this->client->bulk($this->bulkQueries);
        $this->client->indices()->flush();

        $this->bulkQueries = [];
        $this->bulkParams = [];

        $this->bulkQueries = [];

        echo memory_get_usage(true) . "\n";
    }
```

   999/170717 [>---------------------------]   0%74186752
   1999/170717 [>---------------------------]   1%125304832
   2999/170717 [>---------------------------]   1%162004992
   3999/170717 [>---------------------------]   2%196345856
   4999/170717 [>---------------------------]   2%PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted

**Comment by polyfractal** [comment]
Ok, thanks for the code snippet, that helps.  How large of bulks are you sending?  It looks like you are sending ~1000 docs ... do you know how big (in physical bytes) each of those bulks are?

Do you have logging enabled?  I'm thinking that perhaps the default no-logging Monolog handler is queuing up a bunch of operations and causing an OOM.

I'll dig out the profiler and start looking at memory usage.

**Comment by tfe2012** [comment]
~1000 docs about 10 MB

**Comment by tautrimas** [comment]
Hi, @polyfractal. We are working together with @tfe2012 on the same project at ONGR.

We are running Symfony project with Monolog enabled which is set to log only ERROR and above level.

Our config:

```yaml
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
```

We will try disabling logger or passing a dummy one. Can you replicate the issue, @polyfractal?

**Comment by polyfractal** [comment]
I did some digging and the problem basically boils down to your `fingers_crossed` Monolog logger.  By default, it retains an [infinite buffer](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/FingersCrossedHandler.php#L92), which means it will continue to queue up log messages until the activation is triggered.  The ES-PHP client logs the entire request and response under DEBUG.  Which means that every 10mb bulk request, and it's equally large response, will be queued up in the FingersCrossed logger.  If you never activate FingersCrossed (e.g. via an ERROR), you'll queue forever.

The behavior is not present when you add a buffer size to Monolog, disable the logger or use a non-queuing handler like StreamHandler.  Note: the buffer size in this case needs to be very small, since it only takes a few 10mb bulk requests to blow out your memory ;)

So your solutions are basically:

1. Disable Logging while bulk indexing
2. Don't use FingersCrossed
3. Use FingersCrossed with a finite (and smallish) buffer
4. Change your handler stream so that DEBUG messages are not buffered (not quite sure if this is possible)
5. Get more memory ;)

#### Test results:

```
--------------------------------------------------
No Logging

1000) Bulk size: 10.530502319336 mb -- Mem: 32.75 mb
2000) Bulk size: 10.519982337952 mb -- Mem: 43.5 mb
3000) Bulk size: 10.519982337952 mb -- Mem: 33.75 mb
4000) Bulk size: 10.519982337952 mb -- Mem: 33.75 mb
5000) Bulk size: 10.519982337952 mb -- Mem: 33.75 mb
6000) Bulk size: 10.519982337952 mb -- Mem: 33.5 mb
7000) Bulk size: 10.519982337952 mb -- Mem: 33.5 mb
8000) Bulk size: 10.519982337952 mb -- Mem: 33.5 mb
9000) Bulk size: 10.519982337952 mb -- Mem: 33.5 mb

--------------------------------------------------
With Default Logging

1000) Bulk size: 10.530502319336 mb -- Mem: 44.25 mb
2000) Bulk size: 10.519982337952 mb -- Mem: 44.25 mb
3000) Bulk size: 10.519982337952 mb -- Mem: 44.25 mb
4000) Bulk size: 10.519982337952 mb -- Mem: 44.25 mb
5000) Bulk size: 10.519982337952 mb -- Mem: 44.25 mb
6000) Bulk size: 10.519982337952 mb -- Mem: 44.25 mb
7000) Bulk size: 10.519982337952 mb -- Mem: 44.25 mb
8000) Bulk size: 10.519982337952 mb -- Mem: 44.25 mb
9000) Bulk size: 10.519982337952 mb -- Mem: 44.25 mb

--------------------------------------------------
With FingersCrossed Logging

1000) Bulk size: 10.530502319336 mb -- Mem: 55 mb
2000) Bulk size: 10.519982337952 mb -- Mem: 65.75 mb
3000) Bulk size: 10.519982337952 mb -- Mem: 76.5 mb
4000) Bulk size: 10.519982337952 mb -- Mem: 87.25 mb
5000) Bulk size: 10.519982337952 mb -- Mem: 98 mb
6000) Bulk size: 10.519982337952 mb -- Mem: 108.75 mb
7000) Bulk size: 10.519982337952 mb -- Mem: 119.5 mb
8000) Bulk size: 10.519982337952 mb -- Mem: 130.25 mb
9000) Bulk size: 10.519982337952 mb -- Mem: 141 mb

--------------------------------------------------
With FingersCrossed Logging -- Finite buffer

1000) Bulk size: 10.530502319336 mb -- Mem: 33.25 mb
2000) Bulk size: 10.519982337952 mb -- Mem: 44 mb
3000) Bulk size: 10.519982337952 mb -- Mem: 44 mb
4000) Bulk size: 10.519982337952 mb -- Mem: 44 mb
5000) Bulk size: 10.519982337952 mb -- Mem: 35 mb
6000) Bulk size: 10.519982337952 mb -- Mem: 34.75 mb
7000) Bulk size: 10.519982337952 mb -- Mem: 34.75 mb
8000) Bulk size: 10.519982337952 mb -- Mem: 34.75 mb
9000) Bulk size: 10.519982337952 mb -- Mem: 34.75 mb
```

#### Test Code

```php
public function testMemLeak() {

    echo "--------------------------------------------------\n\n";
    echo "No Logging\n";

    $es = new \Elasticsearch\Client([
        'hosts' => ['localhost:9200'],
        'logging' => false
    ]);
    $this->performBulk($es);


    echo "\n\n--------------------------------------------------\n\n";
    echo "With Default Logging\n";

    $es = new \Elasticsearch\Client([
        'hosts' => ['localhost:9200'],
        'logging' => true
    ]);
    $this->performBulk($es);

    echo "\n\n--------------------------------------------------\n\n";
    echo "With FingersCrossed Logging -- Default settings\n";

    $logger    = new Logger('log');
    $stream    = new StreamHandler("log.log", Logger::DEBUG);
    $fingersCrossed = new FingersCrossedHandler($stream, new ErrorLevelActivationStrategy(Logger::ERROR));

    $logger->pushHandler($fingersCrossed);

    $es = new \Elasticsearch\Client([
        'hosts' => ['localhost:9200'],
        'logging' => true,
        'logObject' => $logger
    ]);
    $this->performBulk($es);

    echo "\n\n--------------------------------------------------\n\n";
    echo "With FingersCrossed Logging -- Finite buffer\n";

    $logger    = new Logger('log');
    $stream    = new StreamHandler("log.log", Logger::DEBUG);
    $fingersCrossed = new FingersCrossedHandler($stream, new ErrorLevelActivationStrategy(Logger::ERROR), 3);

    $logger->pushHandler($fingersCrossed);

    $es = new \Elasticsearch\Client([
        'hosts' => ['localhost:9200'],
        'logging' => true,
        'logObject' => $logger
    ]);
    $this->performBulk($es);
}

public function performBulk($es) {
    if (function_exists('memprof_enable')) {
        echo "Enabling Profiling\n";
        memprof_enable();
        $dump = fopen("dump.out", "a");
    }

    $bulk = [
        'index' => 'test',
        'type' => 'data'
    ];

    $es->indices()->delete(['index' => 'test', 'ignore' => 404]);
    $es->cluster()->health(['wait_for_status' => 'yellow']);

    for ($i = 0; $i < 10000; $i++) {
        $bulk['body'][] = ['index' => []];
        @$bulk['body'][] = [
            'some_field' => $this->randomTokens(1000, 10)
        ];

        if ($i % 1000 == 0 && $i != 0) {
            $es->bulk($bulk);

            $size = strlen(json_encode($bulk['body'])) / 1024 / 1024;
            $memSize = memory_get_usage(true) / 1024.0 / 1024.0;

            unset($bulk['body']);
            //$bulk['body'] = [];

            echo "$i) Bulk size: $size mb -- Mem: $memSize mb\n";
            ob_flush();

            if (function_exists('memprof_enable')) {
                fwrite($dump, print_r(memprof_dump_array(), true));
            }
        }
    }

    if (function_exists('memprof_enable')) {
        memprof_dump_callgrind(fopen("callgrind.out", "w"));
        fflush($dump);
        fclose($dump);
    }
}

function randomTokens($tokens, $length)
{
    $result = '';
    for ($i = 0; $i < $tokens; $i++) {
        $result .= bin2hex(openssl_random_pseudo_bytes($length / 2)) . ' ';
    }
    return $result;
}
```

**Comment by tautrimas** [comment]
Hello, @polyfractal. After clean investigation, we no longer see substantial memory leak as previously observed by @tfe2012. In the future, we will be very aware of your `fingers_crossed` finding.

**Comment by polyfractal** [comment]
Sounds good :)  

Closing, feel free to reopen if you have further problems!

**Comment by addione** [comment]
if you have characters like this
"""""Å å Ä ä Ả ả Ḁ ḁ Ấ ấ Ầ ầ Ẩ ẩ Ȃ ȃ Ẫ ẫ Ậ ậ Ắ ắ Ằ ằ Ẳ ẳ Ẵ ẵ Ặ ặ Ā ā Ą ą Ȁ ȁ Ǻ ǻ Ȧ ȧ Á á Ǟ ǟ Ǎ ǎ À à Ã ã Ǡ ǡ Â â Ⱥ ⱥ Æ æ Ǣ ǣ Ǽ ǽ Ɐ Ꜳ ꜳ Ꜹ ꜹ Ꜻ ꜻ Ɑ """""

in your data set and indexing through elasticsearch-PHP the data set will not be indexed happend with me 

user encoding to UTF8 that will help
