### ISSUE TITLE
Return Property

### ISSUE THREAD

**Issue by charuag** [elastic/elasticsearch-php#210]
Is there any way to get property name in elasticsearch. Like for eg. My document is:
```
"hits": [
{
"_index": "index1",
"_type": "car",
"_source"
    "field1": "Red",
    "field2": {
        "field21": {
            "field22" : "Model Name"
        },
    "field3": "Car Color is red."
    },
},
{
"_index": "index2",
"_type": "car",
"_source"
    "field1": "Blue",
    "field2": {
        "field21": {
            "field22" : "Model Name"
        },
    "field3": "Car Color is blue."
    },
}
```
If I search for say "red", it should return "field1" and "field3" instead of returning complete document.

**Comment by polyfractal** [comment]
[Highlighting](http://www.elastic.co/guide/en/elasticsearch/reference/1.3/search-request-highlighting.html) will probably do what you want.  It will highlight the field(s) that had matching terms, as well as which terms actually matched.

You'll still get the entire source document back.  If you don't want the document itself, you can filter it out with [_source filtering](http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html) by excluding everything (e.g. exclude: *)

**Comment by charuag** [comment]
Thanks! This worked!
