### ISSUE TITLE
$client->scroll() via Guzzle CurlMulti ignore basic auth params

### ISSUE THREAD

**Issue by zerozh** [elastic/elasticsearch-php#214]
I setup nginx as frontend proxy with http basic auth. So the endpoint looks like `http://user:pass@esproxy.example.com:80` .

Follow the [guide](http://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_search_operations.html#_scan_scroll) , I dump some data from the server via scan/scroll, then it throw exceptions.

    [Guzzle\Http\Exception\ClientErrorResponseException]
    Client error response
    [status code] 401
    [reason phrase] Unauthorized
    [url] http://esproxy.example.com/_search/scroll/SCROLLID?scroll=30s

As it is usual in first request `$client->search()`, but throw exceptions on `$client->scroll()`. I run and investigate it.

for `$client->search()`

    > POST /MYINDEX/_search?search_type=scan&scroll=30s&size=50 HTTP/1.1
    Host: esproxy.example.com
    Content-Type: application/json
    User-Agent: Guzzle/3.9.3 curl/7.37.1 PHP/5.6.6
    Authorization: Basic abcdef...
    Content-Length: 26

    * upload completely sent off: 26 out of 26 bytes
    < HTTP/1.1 200 OK
    ... 

for `$client->scroll()`

    > GET /_search/scroll/SCROLLID?scroll=30s HTTP/1.1
    Host: esproxy.example.com
    User-Agent: Guzzle/3.9.3 curl/7.37.1 PHP/5.6.6

    < HTTP/1.1 401 Unauthorized
    ...

It forgot `Authorization`!

**Comment by polyfractal** [comment]
Could you paste your client initialization code, and the code executing the search / scroll?

Also, I just tagged `v1.3.4`, which includes a commit that fixes an inline auth bug:  https://github.com/elastic/elasticsearch-php/commit/e94d27ac35b7f269bdcef96850fb3e620542db9b  The  commit originally went into master, but I forgot to cherry-pick it into 1.0.  Depending on how your setting up the client, you may have been affected by this bug.

**Comment by zerozh** [comment]
```php
    $client = new Elasticsearch\Client(['hosts'=>['http://user:pass@esproxy.example.com:80']]);


    $params = array(
            "search_type" => "scan",    // use search_type=scan
            "scroll" => "30s",          // how long between scroll requests. should be small!
            "size" => 50,               // how many results *per shard* you want back
            "index" => "imeidb",
            "body" => array(
                "query" => array(
                    "match_all" => array()
                )
            )
        );

        $docs = $client->search($params);   // Execute the search
        $scroll_id = $docs['_scroll_id'];   // The response will contain no results, just a _scroll_id

// Now we loop until the scroll "cursors" are exhausted
        while (\true) {
          
            // Execute a Scroll request
            $response = $client->scroll(
                array(
                    "scroll_id" => $scroll_id,  //...using our previously obtained _scroll_id
                    "scroll" => "30s"           // and the same timeout window
                )
            );

            // Check to see if we got any search hits from the scroll
            if (count($response['hits']['hits']) > 0) {
                // If yes, Do Work Here

                foreach ($response['hits']['hits'] as $item) {
                    $result = $item['_source'];
                    $this->info($result);
                }

                // Get new scroll_id
                // Must always refresh your _scroll_id!  It can change sometimes
                $scroll_id = $response['_scroll_id'];
            } else {
                $this->info("Finished.");
                break;
            }
        }

```

**Comment by polyfractal** [comment]
Could you upgrade to `v1.3.4`?  I think that auth bug may be affecting you, although I'm still a bit perplexed by how search and scroll have different results (they use the same code path, should either both work or both fail)

**Comment by zerozh** [comment]
Cool! It works!

**Comment by polyfractal** [comment]
Ah, great!  Sorry again about that, the commit has been "live" for months, but didn't get applied to 1.0 until like last week.  Whoops! :)
