### ISSUE TITLE
composer cant install 2.0

### ISSUE THREAD

**Issue by monotek** [elastic/elasticsearch-php#219]
i just wanted to try version 2.0 but i cant install via composer.

I get the following error:

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package elasticsearch/elasticsearch could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Using ~1.0 instead of ~2.0 in composer.json works as expected.

**Comment by polyfractal** [comment]
Oops, that's my fault, I forgot to add the minimum-stability flag to the README.  Will correct it in a second.

Since 2.0 is still in beta, you need to append `@beta` to the requirement:

```json
{
   "require": {
       "elasticsearch/elasticsearch": "~2.0@beta"
   }
}
```
