### ISSUE TITLE
Plans for a DSL wrapper?

### ISSUE THREAD

**Issue by mfn** [elastic/elasticsearch-php#221]
I've done a few PHP implementations and always reached soon a point where I wished there was a way to escape from the array-hell somehow to keep my sanity straight ;-)

Are there any plans to provide PHP code baked wrappers around the ES DSL? I.e. wrappers for all the query/filter types? So instead of writing endless nested arrays I can use things like `new BoolFilter`, `addShould`, etc.? Maybe a separate package event (it doesn't necessarily need to depend on the current client anyway).

Thanks

**Comment by simplechris** [comment]
:+1: This is something that I would also be interested in, I see that other supported languages are starting to get high level DSL wrappers built atop the official clients (e.g. https://github.com/elastic/elasticsearch-dsl-py) So, it'd be great to form a similar wrapper for PHP.

https://github.com/ruflin/Elastica has had a reasonably decent OO query builder for a while, but it's arguably too abstract and can sometimes lead to more confusion than dealing with the 'array-hell' you describe.

Perhaps this is something for the community to focus on after [2.0.0](https://github.com/elastic/elasticsearch-php/tree/2.0) is completed and merged? Or is there already something planned, @polyfractal?

**Comment by polyfractal** [comment]
Nothing officially planned atm.  :(

I would love to see a higher-level DSL, but I'm afraid a lot of my energy is going into the [Aggs 2.0](https://github.com/elastic/elasticsearch/issues/9876) functionality in ES core right now.  I'm not sure if/when I'd be able to work on a DSL.

If the community wanted to work on a DSL that'd be great... one of the goals of the "low-level client" project was to provide a robust framework that more expressive APIs could be built on top of.  ES-PHP should (theoretically) allow the DSL to focus on API and abstraction instead of HTTP calls and connection pooling.

I'd be happy to help out with a community project, but I don't think I have time to be the driving force behind a DSL at the moment.

**Comment by mfn** [comment]
No worries and thanks for the update.

I was aware of Elastica but didn't realize it's DSL actually. I'd say it's exactly what I was looking for here, so ... :-)

**Comment by martiis** [comment]
@mfn Another DSL alternative that we have made ;) https://github.com/ongr-io/ElasticsearchBundle

**Comment by saimaz** [comment]
@polyfractal you may check https://github.com/ongr-io/ElasticsearchDSL it's standalone OO query builder for elasticsearch-php.

**Comment by polyfractal** [comment]
Nice @martiis and @saimaz!

I just added a "Community DSLs and Integration" page to the docs (https://github.com/elastic/elasticsearch-php/commit/1e230a45d3e3c58d07ded7712c83c02af6cc5f1c), should be live the next time our docs cron regenerates the site.  Feel free to send a PR if you want the text describing the project to be changed (I just lifted the readme intro paragraph)

**Comment by jdc18** [comment]
All those options depend on symfony, I am using laravel and I would not like to mix symfony and laravel, are there other alternatives

**Comment by polyfractal** [comment]
@jdc18 There are two Laravel facades/integrations that I'm aware of, see the docs:  https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_community_integrations.html#_laravel

**Comment by jdc18** [comment]
@polyfractal thanks a lot

**Comment by polyfractal** [comment]
Closing, still no future plans for a DSL.

**Comment by mfn** [comment]
I've been using https://github.com/ruflin/Elastica successfully for the last few years, so one may argue "it already exists, why re-invent".

**Comment by polyfractal** [comment]
FWIW, there's a good chance that, eventually, some day, Elastica will use ES-PHP as the "driver client".  So the nice high-level DSL from Elastica, the low-level API from ES-PHP. :)
