### ISSUE TITLE
Guzzle options are not being honored

### ISSUE THREAD

**Issue by warroyo** [elastic/elasticsearch-php#226]
I am attempting to set the HTTP version to 1.0 (so that a connection will be closed immediately, but it does not seem to be honored. below are my settings when I instantiate the client.

       $this->params = array(
          'hosts' => array(
              'myhost:443'
          ),
          'connectionParams' => array('auth' => array(
                  'user',
                  $_ENV['ES_pass'],
                  'Basic'
              )
          ),
          'guzzleOptions' => array(
              \Guzzle\Http\Client::SSL_CERT_AUTHORITY => false,
              'version'=>'v1.0'
          ),
          'logging' => true,
          'logPath' => '/pathto/log',
          'logLevel' => 'Log\LogLevel::DEBUG'
      );

Guzzle Docs:

    $client = new Client('https://api.twitter.com/{version}', array(
    'version'        => 'v1.1',
    'request.options' => array(
        'headers' => array('Foo' => 'Bar'),
        'query'   => array('testing' => '123'),
        'auth'    => array('username', 'password', 'Basic|Digest|NTLM|Any'),
        'proxy'   => 'tcp://localhost:80'
     )
    ));

**Comment by polyfractal** [comment]
To be honest, I'm not sure why `version` isn't being honored.  Other guzzle parameters are being honored, for example:

```php
$params = [
    'hosts' => ['127.0.0.1:1234'],
    'guzzleOptions' => [
        'version'=>'v1.0',
        'request.options' => [
            'headers' => ['Foo' => 'Bar']
        ]
    ]
];

$client = new Elasticsearch\Client($params);

try {
    $client->index(['index' => 'test', 'type' => 'test', 'id' => 'test', 'body' => []]);
} catch (\Exception $e) {

}
```

```shell
# spin up a netcat listen server
$ nc -l -v -k 1234

PUT /test/test/test HTTP/1.1
Host: 127.0.0.1:1234
Content-Type: application/json
User-Agent: Guzzle/3.9.3 curl/7.39.0 PHP/5.5.20
Foo: Bar                             # <----- Note header being added
Content-Length: 2

{}
```

Notice the presence of "Foo: Bar" in the headers.  Without digging into the Guzzle code closer, I'm not sure why that particular parameter isn't working.  If you want to force HTTP/1.0, I'd personally just use the raw curl option.  I'd probably forbid connection reuse explicitly too (which would also work for HTTP/1.1):

```php
$params = [
    'hosts' => ['127.0.0.1:1234'],
    'guzzleOptions' => [
        'curl.options' => [
            CURLOPT_FORBID_REUSE => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_0
        ]
    ]
];

$client = new Elasticsearch\Client($params);

try {
    $client->index(['index' => 'test', 'type' => 'test', 'id' => 'test', 'body' => []]);
} catch (\Exception $e) {

}
```

```shell
nc -l -v -k 1234

PUT /test/test/test HTTP/1.0  # <----- Note HTTP/1.0
Host: 127.0.0.1:1234
Content-Type: application/json
User-Agent: Guzzle/3.9.3 curl/7.39.0 PHP/5.5.20
Content-Length: 2

{}
```

**Comment by warroyo** [comment]
CURLOPT_FORBID_REUSE did the trick! thank you!

**Comment by polyfractal** [comment]
Happy to help.  Will keep working on the other ticket :)
