### ISSUE TITLE
Uncaught exception on elastic search Failed connect to localhost:9200; No error

### ISSUE THREAD

**Issue by DamPe88** [elastic/elasticsearch-php#228]
I'm new to Elastic search.I have downloaded ES using composer and i am trying build a simple search file using ES.
But whenever i try to execute the file,it gives the following error.
Uncaught exception 'Elasticsearch\Common\Exceptions\Curl\CouldNotConnectToHost' with message 'Failed connect to localhost:9200; No error'

This is where i have created the object from ES Class.

$es = new Elasticsearch\Client([
	'hosts' => ['localhost']

	]);
Then I'm trying to pass the field data to the indexing like thsi.
$indexed = $es->index([
			'index' => 'articles',
			'type' => 'article',
			'body' =>[

					'title' =>$title,
					'body' =>$body,
					'tags' =>$tags
					]

		]);
Any reason for this kind of error.

**Comment by knut** [comment]
Have you installed and started Elasticsearch on your computer? 

See: https://www.elastic.co/downloads/elasticsearch

If you're just getting started you probably also want to install the head-plugin which allows you to easily inspect your data in your browser.

See: http://mobz.github.io/elasticsearch-head/

**Comment by DamPe88** [comment]
@knut :bow:  you saved my day
