### ISSUE TITLE
multisearch return NULL instead of array

### ISSUE THREAD

**Issue by reva2** [elastic/elasticsearch-php#23]
For some request msearch() method return NULL instead array of responses. 

Small sample:

``` php
$params = array(
    'hosts' => array('127.0.0.1'),
    'connectionClass' => '\Elasticsearch\Connections\CurlMultiConnection',
    'connectionParams' => array(
        'curlOpts' => array(
            CURLOPT_HTTPHEADER => array('Connection: keep-alive', 'Keep-Alive: 300')
        )
    )
);
$elastic = new \Elasticsearch\Client($params);

$params = array(
    'index' => 'Ads',
    'body' => array(
        array('type' => 'DefManagedBids'),
        array(
            'fields' => array('g', 'hta', 'cap', 'cTtl'),
            'query' => array(
                'filtered' => array(
                    'filter' => array(
                        'and' => array(
                            array('term' => array('sc' => 9000081)),
                            array('terms' => array('adtypes' => array('image_26', 'richmedia_26'))),
                            array('term' => array('countries' => 'HK')),
                            array('term' => array('languages' => 'LG')),
                            array('terms' => array('keywords' => array(
                                '348a448a51d1e0f0f5eee42337d12adc',
                                '8f99e430f3167d6bf65e0beb23896276',
                                '9336ebf25087d91c818ee6e9ec29f8c1',
                                'ee2a23af409b352d8f1819405bc770b2',
                                'ee8147f3ad132c3495314bb77fefa274',
                                'f3aa047479dae4b554c381ccbc2f5019',
                                'fe325cf304ee9155d513be1044bf064b',
                                'dbab14a2fd9a474f5aa30b06f130b368'
                            )))
                        )
                    )
                )
            )
        ),
        array('type' => 'DefRonBids'),
        array(
            'fields' => array('g', 'hta', 'cap', 'cTtl'),
            'query' => array(
                'filtered' => array(
                    'filter' => array(
                        'and' => array(
                            array('terms' => array('adtypes' => array('image_26', 'richmedia_26'))),
                            array('term' => array('countries' => 'HK')),
                            array('term' => array('languages' => 'LG')),
                            array('terms' => array('keywords' => array(
                                '348a448a51d1e0f0f5eee42337d12adc',
                                '8f99e430f3167d6bf65e0beb23896276',
                                '9336ebf25087d91c818ee6e9ec29f8c1',
                                'ee2a23af409b352d8f1819405bc770b2',
                                'ee8147f3ad132c3495314bb77fefa274',
                                'f3aa047479dae4b554c381ccbc2f5019',
                                'fe325cf304ee9155d513be1044bf064b',
                                'dbab14a2fd9a474f5aa30b06f130b368'
                            )))
                        )
                    )
                )
            )
        )
    )
);

$result = $elastic->msearch($params);
```

If I perform the same request with curl it show correct response:

```
{"responses":[{"took":0,"timed_out":false,"_shards":{"total":2,"successful":2,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}},{"took":0,"timed_out":false,"_shards":{"total":2,"successful":2,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}]}
```

If I perform the same request with other values for search criteria it work properly and return array of responses for each query.

Please let me know if you need additional details.

**Comment by gayathrimanohar** [comment]
I'm using your elasticsearch code based php mysql. It's working fine. I have to implement the multisearch (mean msearch) concept on project.I have tried more steps for developing the msearch but i could not complete.

Multisearch concept:

single query can search the data on both two index type. One type have no conditions and to listed data.another have to search the data with conditions.finally combine the results and show on page.

1.common index with two types like(my_index / type1,type2)

2. type1 :- To search the title data with no conditions

3. type2 :- To search the title data with  conditions


shows the result with pagination
Note : Already i tried bool query but doesn't work 

Please guide me to complete the project.
public function Msearch($query)
    {
        $client = $this->elasticclient;
        $result = array();

        $i = 0;

        $params = [
		
			 
          'index' => 'cricsearch',
          
              'body'  => [
    ['type' => 'cricnews','scroll' => '30s'],
    ['query' => ['match' => ['title'=> $query]]],

    ['type' => 'cricvideos','scroll' => '30s'],['size'  => 0,'query' => ['match' => ['title'=> $query]]],
	],
	];
          //  print_r($event_id);
		  try {
        $query                 = $client->msearch($params);
		
        $hits                  = sizeof($query['hits']['hits']);
		print_r($hits);
        $hit                   = $query['hits']['hits'];
        $result['searchfound'] = $hits;
        while ($i < $hits) {

            $result['result'][$i] = $query['hits']['hits'][$i]['_source'];

            $i++;
        }
	
  
	
        return  $result;
		  }
		  catch (Exception $e) {
    echo $e->getMessage();
}
    }
