### ISSUE TITLE
Filter data from field name on elasticsearch-PHP 

### ISSUE THREAD

**Issue by DamPe88** [elastic/elasticsearch-php#233]
I have written an index on Elasticsearch with following fields.

    $indexData = [
    'index' => 'profiles',
    'type' => 'profile',
    'body' =>[
                            'id' => $data->id,
                            'first_name' => (string)$data->first_name,
                            'last_name' => (string)$data->last_name,
                            'phone_mobile' => $data->phone_mobile,
                             'phone_work' => $data->phone_work,
                            'company_name' => $data->company_name,   
                         ]
                   ];
        $indexed = $profileElastic->addIndex($indexData);
I have managed to filter them using "more_like_this". But i need to filter them using the Field Name.

Example: Searching value is : 456 and field is:phone_mobile. Scenario: First i Need to check that 'phone_mobile' column is blank or not, if it is not blank, then check whether 'phone_mobile' column has the value '456',if it is true, return the corresponding Data Set.

If it is 'phone_mobile' field is blank, then i need to check 'phone_work' is null or not.if null return empty,otherwise continue the checking.

hope i have explained clearly.
Thanks in Advance for any help

**Comment by polyfractal** [comment]
Closing in favor of discussion over at the Elastic forums: https://discuss.elastic.co/t/filter-data-from-field-name-on-elasticsearch-php/268/24
