### ISSUE TITLE
Bulk Indexing example not working

### ISSUE THREAD

**Issue by karimzah** [elastic/elasticsearch-php#236]
So I have ES-PHP 2.0 installed and I am trying the bulk index example, I am getting error
messages, I don't know what I am doing wrong as I just copied and pasted the example.

The normal indexing works but it is very slow when doing 100k rows.

Version of ES I am using is "number" : "1.4.4", "lucene_version" : "4.10.3", "name" : "Katie Power",

Error messages:
<pre>
PHP Fatal error:  Uncaught exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message '{"error":"ActionRequestValidationException[Validation Failed: 1: type is missing;2: type is missing;]","status":400}' in /vagrant_data/htdocs/research/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:525
Stack trace:
#0 /vagrant_data/htdocs/research/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(208): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /vagrant_data/htdocs/research/vendor/react/promise/src/FulfilledPromise.php(24): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /vagrant_data/htdocs/research/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /vagrant_data/htdocs/research/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 / in /vagrant_data/htdocs/research/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 525

Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message '{"error":"ActionRequestValidationException[Validation Failed: 1: type is missing;2: type is missing;]","status":400}' in /vagrant_data/htdocs/research/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:525
Stack trace:
#0 /vagrant_data/htdocs/research/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(208): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /vagrant_data/htdocs/research/vendor/react/promise/src/FulfilledPromise.php(24): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /vagrant_data/htdocs/research/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /vagrant_data/htdocs/research/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 / in /vagrant_data/htdocs/research/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 525
</pre>

<code>
function zktest()
{
    $client = \Elasticsearch\ClientBuilder::create()->build();
    $params = [];

    for ($i = 0; $i <= 100000; $i++) {
        $params['body'][] = array(
            'index' => array(
                'index' => 'my_index',
                'type' => 'my_type',
                '_id' => $i
            )
        );

        $params['body'][] = [
            'my_field' => 'my_value',
            'second_field' => 'some more values'
        ];

        // Every 1000 documents stop and send the bulk request
        if ($i % 1000) {
            $responses = $client->bulk($params);

            // erase the old bulk request
            $params = [];

            // unset the bulk response when you are done to save memory
            unset($responses);
        }
    }
}
</code>

any ideas?

**Comment by polyfractal** [comment]
Argh, sorry, it's a typo in the example.  The "action metadata" portion should use `_index` and `_type`, not `index` / `type`.  E.g.

```php
$params['body'][] = array(
        'index' => array(
            '_index' => 'my_index',
            '_type' => 'my_type',
            '_id' => $i
        )
    );
```

I just updated the example, sorry about that!

**Comment by karimzah** [comment]
Thanks !

**Comment by aAmanRoy** [comment]
hey  I using elastic search 2.0 , on click search i get this error ,please resolve this thanks in advance .

Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\Missing404Exception' with message '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"test","index":"test"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"test","index":"test"},"status":404}' in /var/www/html/test.com/public_html/elasticsrch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:602 Stack trace: #0 /var/www/html/test.com/public_html/elasticsrch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(273): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array) #1 /var/www/html/test.com/public_html/elasticsrch/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #2 /var/www/html/new.legalpu in /var/www/html/test.com/public_html/elasticsrch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 602

**Comment by Feysar** [comment]
For my was: user and password 

$client = \Elasticsearch\ClientBuilder::create()
    ->setHosts(['http://user:password@localhost'])
    ->build();
