### ISSUE TITLE
utf8  encoding problem using the php api

### ISSUE THREAD

**Issue by algking** [elastic/elasticsearch-php#238]
when I used the curl to index some doc which contains some chinese:
curl -XPUT 'http://localhost:9200/news/article/101' -d '{title:"某些中文 }'
curl -XGET 'http://localhost:9200/news/article/101'

here is the result:
{"_index":"news","_type":"article","_id":"101","_version":1,"found":true,"_source":{title:"某些中文"}}%

it works fine.

but,when used the php api 

$es_document =
        array(
        'index' => 'news',
        'type'  => 'article',
        'body'  => array(
            'title' =>  "某些中文",
        ));
$es_client = new Elasticsearch\Client();
$es_client -> index($es_document);

here is the query result 
{"_index":"news","_type":"article","_id":"AU1_Vz3LunK7zBa9WA8H","_version":1,"found":true,"_source":{"title":"\u67d0\u4e9b\u4e2d\u6587"}}%

Any advice ?

elasticsearch 1.5 , php 5.5.24

**Comment by simplechris** [comment]
If I understand this issue correctly, then this isn't anything to worry about. In PHP [`json_encode()`](http://se2.php.net/json_encode) escapes unicode chars by default.

**Comment by algking** [comment]
Yes，it's still correctly encoded. Thanks.

**Comment by liucr** [comment]
I have meet the same problem, but I don't know how to resolve it.
I try the english sentence, but it don't work properly. still no result to return.
