### ISSUE TITLE
How to use static scripts in update?

### ISSUE THREAD

**Issue by pepez** [elastic/elasticsearch-php#240]
I have a script placed in config/scripts and it works fine via curl. But I get an error if I try the same with PHP client:
ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[dynamic scripting for [groovy] disabled]

More details:
http://stackoverflow.com/questions/30509129/elasticsearch-static-script-in-update-syntax

**Comment by polyfractal** [comment]
Are you sure the client is talking to the same node as the curl command?  Also make sure the script is in the `config/script` directory for all nodes in your cluster.  Or something like a misspelling, wrong case, etc.

Basically, if ES can't find the compiled script (e.g. `deleteField`) it interprets the string as a groovy script...which won't run because it is disabled.  For example:

Create the script:

```shell
$ touch config/scripts/deleteField.groovy

[2015-05-28 15:13:51,850][INFO ][script] [Tarantula] compiling script file [/Users/tongz/Downloads/elasticsearch-1.5.0/config/scripts/deleteField.groovy]
```

Add a doc and update (note version change):
```json
POST shop/product/2509
{
  "foo" : "bar"
}

POST /shop/product/2509/_update
{
  "script" : "deleteField"
}
```
```json
{
   "_index": "shop",
   "_type": "product",
   "_id": "2509",
   "_version": 2
}
```

But try with a non-existing script:

```json
POST /shop/product/2509/_update
{
  "script" : "do_not_exist"
}
```
```json
{
   "error": "ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[dynamic scripting for [groovy] disabled]; ",
   "status": 400
}
```

This is replicated in PHP too:

```php
$params['hosts'] = array ('localhost:9200');
$client = new Elasticsearch\Client($params);

$updateParams = array();
$updateParams['index'] = 'shop';
$updateParams['type']  = 'product';
$updateParams['id']  = '2509';


echo "Existing Script:\n";
$updateParams['body'] = array(
    'script' =>  'deleteField'
);
$response = $client->update($updateParams);
print_r($response);


echo "\n\nMissing Script:\n";
$updateParams['ignore'] = 400;  // Just to suppress the error for pretty-printing
$updateParams['body'] = array(
    'script' =>  'do_not_exist'
);
$response = $client->update($updateParams);
print_r($response);
```
```php
Existing Script:
Array
(
    [_index] => shop
    [_type] => product
    [_id] => 2509
    [_version] => 3
)


Missing Script:
{"error":"ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[dynamic scripting for [groovy] disabled]; ","status":400}

```

**Comment by pepez** [comment]
It turned out that the PHP application config was changed to point to a different ES instance where there was no script file. Sorry for the trouble.
