### ISSUE TITLE
Receiving Guzzle\Http\Exception\ClientErrorResponseException when attempting to delete non-existent index

### ISSUE THREAD

**Issue by Erutan409** [elastic/elasticsearch-php#241]
Is the elasticsearch php library intentionally not catching exceptions being thrown by the guzzle library when/if non-existent items are attempted to be worked on?  The first instance (I haven't tested other functions) was when I tried to delete an index that had already been deleted.

I'd expect to be able to catch elasticsearch exceptions for cases like the aforementioned so that I can perform other logic on said case.

**Comment by polyfractal** [comment]
The client catches Guzzle exceptions and wraps them in client-specific exceptions.  For example:

```php

// Catch exceptions
$params = [
  'index' => 'absent_index'
];

try {
  $results = $client->search($params);
} catch (Missing404Exception $e) {
  print_r($e->getMessage());
}

// Or ignore and handle yourself
$params = [
  'index' => 'absent_index',
  'ignore' => 404
];
$results = $client->search($params);
print_r($results);
```

The Guzzle exception is the "root cause", so it is generally what you see when xdebug or similar print the exception.

**Comment by Erutan409** [comment]
```php
try {
	var_dump((new \Elasticsearch\Client)->indices()->create(array("index"=>"test")));
	// var_dump((new \Elasticsearch\Client)->indices()->delete(array("index"=>"test")));
} catch (Missing404Exception $e) {
	print_r($e->getMessage());
}
```

On first execution:

    array(1) {
      ["acknowledged"]=>
      bool(true)
    }

On second execution:

    Fatal error: Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
    [status code] 400
    [reason phrase] Bad Request
    [url] http://localhost:9200/test' in %FOLDER%\vendor\guzzle\guzzle\src\Guzzle\Http\Exception\BadResponseException.php:43 
    
    Stack trace:
    #0 %FOLDER%\vendor\guzzle\guzzle\src\Guzzle\Http\Message\Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
    #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #2 %FOLDER%\vendor\symfony\event-dispatcher\Symfony\Component\EventDispatcher\EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #3 %FOLDER%\vendor\symfony\event-dispatcher\Symfony\Component\EventDispatcher\EventD in %FOLDER%\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\GuzzleConnection.php on line 277

Furthermore:

```php
try {
	// var_dump((new \Elasticsearch\Client)->indices()->create(array("index"=>"test")));
	var_dump((new \Elasticsearch\Client)->indices()->delete(array("index"=>"test")));
} catch (Missing404Exception $e) {
	print_r($e->getMessage());
}
```

On first execution:

    array(1) {
      ["acknowledged"]=>
      bool(true)
    }

On second execution:

    Fatal error: Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
    [status code] 404
    [reason phrase] Not Found
    [url] http://localhost:9200/test' in %FOLDER%\vendor\guzzle\guzzle\src\Guzzle\Http\Exception\BadResponseException.php:43
    
    Stack trace:
    #0 %FOLDER%\vendor\guzzle\guzzle\src\Guzzle\Http\Message\Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
    #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #2 %FOLDER%\vendor\symfony\event-dispatcher\Symfony\Component\EventDispatcher\EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    #3 %FOLDER%\vendor\symfony\event-dispatcher\Symfony\Component\EventDispatcher\EventDis in %FOLDER%\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\GuzzleConnection.php on line 271

Am I still doing something wrong or am I misunderstanding your explanation?

After I added the ignore property to the array, it returns a JSON object with the same verbage, but I still wrote up this response, making sure that the library is behaving as intended.

It just seems odd that it wouldn't throw an elasticsearch exception, since the request started with said library.

**Comment by polyfractal** [comment]
Gah, sorry, my fault.  I misread your original message and gave you the wrong exception to catch.  You'll need `BadRequest400Exception` instead:

```php
try {
    var_dump((new \Elasticsearch\Client)->indices()->create(array("index"=>"test")));
    // var_dump((new \Elasticsearch\Client)->indices()->delete(array("index"=>"test")));
} catch (BadRequest400Exception $e) {
    print_r($e->getMessage());
}
```
```
{"error":"IndexAlreadyExistsException[[test] already exists]","status":400}
```

Currently, the client only catches/wraps exceptions that correspond with the status code.  Because ES exceptions are not structured (yet), and sometimes not even JSON, the best the client can do is wrap status code exceptions and give you the error message to parse.  So you can catch the `400` here, then check the message to see what to do next.

> After I added the ignore property to the array, it returns a JSON object with the same verbage, but I still wrote up this response, making sure that the library is behaving as intended.

Yep, this is working as intended.  The `ignore` parameter is just a convenience -- some people don't want to catch exceptions, or want to silently ignore certain exceptions without adding exception handling boilerplate.  Ignore just suppresses the exception and gives you the response.

> It just seems odd that it wouldn't throw an elasticsearch exception, since the request started with said library.

Yeah, that's just an annoying quirk to how PHP dumps exceptions.  It will unwrap and display the inner-most exception, which happens to be the original Guzzle exception.  The actual exception being thrown is an ES-PHP exception, which wraps guzzle.  You can confirm it via:

```php
try {
    var_dump((new \Elasticsearch\Client)->indices()->create(array("index"=>"test")));
    // var_dump((new \Elasticsearch\Client)->indices()->delete(array("index"=>"test")));
} catch (\Exception $e) {
    echo 'instanceof Elasticsearch\Common\Exceptions\BadRequest400Exception: '
        .($e instanceof BadRequest400Exception ? "true" : "false")."\n";
    echo 'instanceof Elasticsearch\Common\Exceptions\ElasticsearchException: '
        .($e instanceof ElasticsearchException ? "true" : "false")."\n";
    echo 'instanceof Guzzle\Http\Exception\Guzzle ClientErrorResponseException: '
        .($e instanceof ClientErrorResponseException ? "true" : "false")."\n\n";
    
    
    $e = $e->getPrevious();
    echo 'instanceof Elasticsearch\Common\Exceptions\BadRequest400Exception: '
        .($e instanceof BadRequest400Exception ? "true" : "false")."\n";
    echo 'instanceof Elasticsearch\Common\Exceptions\ElasticsearchException: '
        .($e instanceof ElasticsearchException ? "true" : "false")."\n";
    echo 'instanceof Guzzle\Http\Exception\Guzzle ClientErrorResponseException: '
        .($e instanceof ClientErrorResponseException ? "true" : "false")."\n\n";
}
```

Which shows that the outer exception is ES-PHP, while the inner is Guzzle:

```
instanceof Elasticsearch\Common\Exceptions\BadRequest400Exception: true
instanceof Elasticsearch\Common\Exceptions\ElasticsearchException: true
instanceof Guzzle\Http\Exception\Guzzle ClientErrorResponseException: false

instanceof Elasticsearch\Common\Exceptions\BadRequest400Exception: false
instanceof Elasticsearch\Common\Exceptions\ElasticsearchException: false
instanceof Guzzle\Http\Exception\Guzzle ClientErrorResponseException: true
```

**Comment by Erutan409** [comment]
Thank you for the informative answer.  After trying what you stated is the correct exception to catch, it STILL gave me the same error on 2nd attempts for each action.  However, until the exceptions are structured, I'll opt to use the ignore flag and run my responses through a parser.

So, with all that said, would you like me to close this issue?  From what I can tell, it's still technically not working, even with the suggestion you last gave.

Thanks!

**Comment by polyfractal** [comment]
Hmm, weird... the catch *should* work.  

- Are you using XDebug or something similar?
- Can you try a full `catch (Elasticsearch\Common\Exceptions\BadRequest400Exception $e)` to make sure it isn't a namespace issue
- If that doesn't work, can you try the more generic `ElasticsearchException`
- If none of the above works, what does this say:

```php
try {
    var_dump((new \Elasticsearch\Client)->indices()->create(array("index"=>"test")));
} catch (\Exception $e) {
  echo get_class($e);
}
```
- What version of ES-PHP are you using?

**Comment by Erutan409** [comment]
The full namespace did the trick.  Thank you, sir!

**Comment by polyfractal** [comment]
Awesome!  I dunno why to be honest, but sometimes I find the namespace imports get a bit wonky.
