### ISSUE TITLE
Check if a value (lets say x1) exist between (y2) and (z2) in ES

### ISSUE THREAD

**Issue by JugalSA** [elastic/elasticsearch-php#244]
Hi, i have an index having nested fields 
"open_now": [
                  {
                     "open_id": "1",
                     "close_id": "49",
                     "start_slot": "8:00 AM",
                     "end_slot": "8:00 PM",
                     "day": "Monday"
                  },
                  {
                     "open_id": "1",
                     "close_id": "49",
                     "start_slot": "8:00 AM",
                     "end_slot": "8:00 PM",
                     "day": "Tuesday"
                  },
                  {
                     "open_id": "1",
                     "close_id": "49",
                     "start_slot": "8:00 AM",
                     "end_slot": "8:00 PM",
                     "day": "Wednesday"
                  }.......etc etc

I have an id as an input lets say 12, i want to check if this is between open_id and close_id.
Hope to receive a favorable reply.

**Comment by polyfractal** [comment]
You can determine if your value is between those two fields by using two Range filters (each looking at one field).  You then combine those with a Bool, and put that inside of a Nested filter.  And finally, that Nested filter goes inside a Filtered query:

```json
{
  "query": {
    "filtered": {
      "filter": {
        "nested": {
          "path": "open_now",
          "filter": {
            "bool": {
              "must": [
                {
                  "range": {
                    "open_now.open_id": {
                      "gte": 12
                    }
                  }
                },
                {
                  "range": {
                    "open_now.close_id": {
                      "lte": 12
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

That will return all documents where at least one of the nested docs matches your criteria.  If you need which nested doc actually matched, you can use the [Inner Hits API](https://www.elastic.co/guide/en/elasticsearch/reference/1.x/search-request-inner-hits.html)

**Comment by JugalSA** [comment]
Thank you very much..that worked..
