### ISSUE TITLE
Fatal error: Class 'ClientBuilder' not found

### ISSUE THREAD

**Issue by ebradham** [elastic/elasticsearch-php#246]
Any reason why I would get this?

I'm running the 2.0.  Installation worked great, but I get this error for this line of code:

Fatal error: Class 'ClientBuilder' not found

$client = ClientBuilder::create()->build();

**Comment by polyfractal** [comment]
Probably a namespacing issue.  See:  https://github.com/elastic/elasticsearch-php/issues/193#issuecomment-111107067

I need to update the examples / tutorial to include a proper namespace, just haven't had a chance yet today. :)

**Comment by 4selin** [comment]
still no update in this tutorial https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_quickstart.html#_installation

**Comment by polyfractal** [comment]
Here you go :)

https://github.com/elastic/elasticsearch-php/commit/6f9fc99732bf739ba941f91f89962f1a72d21bf4
https://github.com/elastic/elasticsearch-php/commit/b91ab4ad046ca4046a99125400103a275b7194d4
