### ISSUE TITLE
Bulk Indexing Error Message : %s% is not a valid parameter. Allowed parameters are: %s%

### ISSUE THREAD

**Issue by blaxroze** [elastic/elasticsearch-php#247]
Hello,
I have a problem about bulk indexing.
I have created analysis and mapping, but this error is appear when I try to bulk indexing my data.
Can you help me what is the problem with my code?
Thanks.

Elasticsearch_error
<pre>
object(Elasticsearch\Common\Exceptions\UnexpectedValueException)[321]
  protected 'message' => string '"id" is not a valid parameter. Allowed parameters are: "consistency", "refresh", "replication", "type", "client", "custom"' (length=122)
  private 'string' (Exception) => string '' (length=0)
  protected 'code' => int 0
  protected 'file' => string 'D:\xampp\htdocs\lisento\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Endpoints\AbstractEndpoint.php' (length=107)
  protected 'line' => int 245
  private 'trace' (Exception) => 
    array (size=21)
      0 => 
        array (size=6)
          'file' => string 'D:\xampp\htdocs\lisento\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Endpoints\AbstractEndpoint.php' (length=107)
          'line' => int 97
          'function' => string 'checkUserParams' (length=15)
          'class' => string 'Elasticsearch\Endpoints\AbstractEndpoint' (length=40)
          'type' => string '->' (length=2)
          'args' => 
            array (size=1)
              0 => 
                array (size=1)
                  'id' => string '1234567890' (length=10)
</pre>

My_mapping
<pre>
[
	"mappings" => [
		"twitter" => [
				"properties" => [
					"tweet_id" => [ "type" => "long" ],
					"tweet_text" => [
						"type" => "string",
						"fields" => [
							"raw" => [ "type" => "string", "index" => "no" ],
							"text" => [ "type" => "string", "analyzer" =>  "tweet_text_autocomp_analyzer" ],
							"std" => [ "type" => "string", "analyzer" =>  "tweet_text_std_analyzer" ]
						],
					],
					"tweet_date" => ["type" => "date","format" => "Y-M-d H:m:s" ],
					"favorited_count" => [ "type" => "integer" ],
					"retweet_count" => [ "type" => "integer" ],
					"place" => [ "type" => "string" ],
					"url" => [ "type" => "string" ],
					"hashtags" => [
						"type" => "nested",
						"fields" => [
							"hashtag" => [ "type" => "string" ]
						],
					],
					"campaign_id" => [ "type" => "long" ],
					"user_id" => [ "type" => "long" ],
					"screen_name" => [ "type" => "string" ]
				]
			]
		]
]
</pre>

My_data
<pre>
{
      "user_id": 117093939,
      "screen_name": "",
      "campaign_id": "1234567890",
      "tweet_id": 609287367120150000,
      "tweet_text": "Oberyn's scattered skull  #GameOfThronesFood",
      "tweet_date": "2015-06-12 16:13:22",
      "favorited_count": 0,
      "retweet_count": 0,
      "url": ""
    },
    {
      "user_id": 491504312,
      "screen_name": "",
      "campaign_id": "1234567890",
      "tweet_id": 609287361751610000,
      "tweet_text": "RT @alex_backes: Buffalo Wildlings #GameOfThronesFood @midnight",
      "tweet_date": "2015-06-12 16:13:21",
      "favorited_count": 0,
      "retweet_count": 43,
      "url": ""
    },
    {
      "user_id": 745355136,
      "screen_name": "",
      "campaign_id": "1234567890",
      "tweet_id": 609287345951610000,
      "tweet_text": "RT @CMPunk: Jon snow cones! @midnight #GameOfThronesFood",
      "tweet_date": "2015-06-12 16:13:17",
      "favorited_count": 0,
      "retweet_count": 203,
      "url": ""
    }
}
</pre>

My_bulk_code
<pre>
for ($j = 0; $j <= $i; $j++) {
	$params ['body'][] = array(
		'index' => array(
			'index' => $appconfig['ES_INDEX'],
			'type' => $index["type"],
			'_id' => $j,
			'body' => $index["docs"]
		),
	);

	// Every 1000 documents stop and send the bulk request
	if ($j % 1000) {
		$responses = $client->bulk($params);

		// erase the old bulk request
		$params = array();

		// unset the bulk response when you are done to save memory
		unset($responses);
	}
}			
</pre>

**Comment by polyfractal** [comment]
The bulk syntax is a little different.  You need to split up "actions" and "metadata".  The JSON is:

```json
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }
{ "field1" : "value1" }
```

So translated into PHP:

```php
for ($j = 0; $j <= $i; $j++) {
  $params['body'][] = array(
      'index' => array(
          '_index' => $appconfig['ES_INDEX'],
          '_type' => $index["type"],
          '_id' => $j,
      )
  );

  $params['body'][] = array(
      // Document data goes here
  );

  // Every 1000 documents stop and send the bulk request
  if ($j % 1000) {
      $responses = $client->bulk($params);

      // erase the old bulk request
      $params = array();

      // unset the bulk response when you are done to save memory
      unset($responses);
  }
}
```

Notice that first we add an array that has `_index`, `_type`, `_id`.  Then we add a new array which holds the document data.  These will be serialized into two JSON lines separated by new lines, and the process repeats.

**Comment by blaxroze** [comment]
I followed your instructions and got the same error. "id" is not a valid parameter.

<pre>
$params['body'][] = array(
    'index' => array(
        '_index' => $appconfig['ES_INDEX'],
        '_type' => $index["type"],
        '_id' => $j,
    )
);

$params['body'][] = $index["docs"];
</pre>

**Comment by polyfractal** [comment]
Can you paste your complete code, and a dump of the document?  There must be something wrong with your doc syntax, or the API call.  E.g this code snippet works fine:

```php
$client = new Elasticsearch\Client();

$i = 1000;
$appconfig['ES_INDEX'] = 'test';
$index["type"] = 'test';
$index["docs"] = [
    'field' => 'value'
];


for ($j = 0; $j <= $i; $j++) {
    $params['body'][] = array(
        'index' => array(
            '_index' => $appconfig['ES_INDEX'],
            '_type' => $index["type"],
            '_id' => $j,
        )
    );

    $params['body'][] = $index["docs"];

    // Every 1000 documents stop and send the bulk request
    if ($j % 1000) {
        $responses = $client->bulk($params);
        print_r($responses);

        // erase the old bulk request
        $params = array();

        // unset the bulk response when you are done to save memory
        unset($responses);
    }
}
```
ES logs:
```
[2015-06-16 16:57:56,017][INFO ][cluster.metadata         ] [Quentin Quire] [test] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2015-06-16 16:57:56,148][INFO ][cluster.metadata         ] [Quentin Quire] [test] update_mapping [test] (dynamic)
```
PHP output:
```
Array
(
    [took] => 2
    [errors] => 
    [items] => Array
        (
            [0] => Array
                (
                    [index] => Array
                        (
                            [_index] => test
                            [_type] => test
                            [_id] => 0
                            [_version] => 3
                            [status] => 200
                        )
                )
             .....
```

**Comment by blaxroze** [comment]
This code success with one dimension array.
<pre>
$client = ClientBuilder::create()->build();
        $i = 15;
        $appconfig['ES_INDEX'] = 'test';
        $index["type"] = 'tweets';
        $index["docs"] = [
            "user_id" => 720034193,
            "screen_name" => "",
            "user_name" => "Eduardo Sanchez",
            "campaign_id" => "12345678902",
            "tweet_id" => 610952431179010000,
            "tweet_text" => "RT @LordSnow: Pizza of Thrones #GameOfThronesFood http:\\/\\/t.co\\/qQwGZJ6wMQ",
            "tweet_date" => "2015-06-17 06:29:45",
            "favorited_count" => 0,
            "retweet_count" => 896,
            "url" => "",
            "hashtags" => [
              [
                "hashtag" => "GameOfThronesFood"
              ]
            ]
        ];


        for ($j = 0; $j <= $i; $j++) {
            $params['body'][] = array(
                'index' => array(
                    '_index' => $appconfig['ES_INDEX'],
                    '_type' => $index["type"],
                    '_id' => $j,
                )
            );

            $params['body'][] = $index["docs"];

            // Every 1000 documents stop and send the bulk request
            if ($j % 1000) {
                $responses = $client->bulk($params);
                print_r($responses);

                // erase the old bulk request
                $params = array();

                // unset the bulk response when you are done to save memory
                unset($responses);
            }
        }
</pre>

And the result is 201 not 200.
<pre>
Array
(
    [took] => 1
    [errors] => 
    [items] => Array
        (
            [0] => Array
                (
                    [index] => Array
                        (
                            [_index] => test
                            [_type] => tweets
                            [_id] => 15
                            [_version] => 1
                            [status] => 201
                        )

                )

        )

)
</pre>

**Comment by blaxroze** [comment]
There is exception in this code
<pre>
$client = ClientBuilder::create()->build();
        $i = 15;
        $appconfig['ES_INDEX'] = 'test';
        $index["type"] = 'tweets';
        $index["docs"] = [[
            "user_id" => 720034193,
            "screen_name" => "",
            "user_name" => "Eduardo Sanchez",
            "campaign_id" => "12345678902",
            "tweet_id" => 610952431179010000,
            "tweet_text" => "RT @LordSnow: Pizza of Thrones #GameOfThronesFood http:\\/\\/t.co\\/qQwGZJ6wMQ",
            "tweet_date" => "2015-06-17 06:29:45",
            "favorited_count" => 0,
            "retweet_count" => 896,
            "url" => "",
            "hashtags" => [
              [
                "hashtag" => "GameOfThronesFood"
              ]
            ]
        ],
        [
            "user_id" => 1379328618,
            "screen_name" => "",
            "user_name" => "Ninja de l'oreiller",
            "campaign_id" => "12345678902",
            "tweet_id" => 610902882280290000,
            "tweet_text" => "RT @LordSnow: Pizza of Thrones #GameOfThronesFood http:\\/\\/t.co\\/qQwGZJ6wMQ",
            "tweet_date" => "2015-06-17 03:12:51",
            "favorited_count" => 0,
            "retweet_count" => 896,
            "url" => "",
            "hashtags" => [
              [
                "hashtag" => "GameOfThronesFood"
              ]
            ]
        ]];


        for ($j = 0; $j <= $i; $j++) {
            $params['body'][] = array(
                'index' => array(
                    '_index' => $appconfig['ES_INDEX'],
                    '_type' => $index["type"],
                    '_id' => $j,
                )
            );

            $params['body'][] = $index["docs"];

            // Every 1000 documents stop and send the bulk request
            if ($j % 1000) {
                $responses = $client->bulk($params);
                print_r($responses);

                // erase the old bulk request
                $params = array();

                // unset the bulk response when you are done to save memory
                unset($responses);
            }
        }
</pre>

<pre>
Array
(
    [took] => 4
    [errors] => 1
    [items] => Array
        (
            [0] => Array
                (
                    [index] => Array
                        (
                            [_index] => test
                            [_type] => tweets
                            [_id] => 15
                            [status] => 400
                            [error] => MapperParsingException[Malformed content, must start with an object]
                        )

                )

        )

)
</pre>

**Comment by polyfractal** [comment]
You are getting an exception because this line:

```php
$params['body'][] = $index["docs"];
```

expects a single document.  You are giving it the entire array of documents.  Again, the bulk API syntax looks like this:

```json
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }
{ "field1" : "value1" }

**Comment by polyfractal** [comment]
You are getting an exception because this line:

```php
$params['body'][] = $index["docs"];
```

expects a single document.  You are giving it the entire array of documents.  Again, the bulk API syntax looks like this:

```json
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }
{ "field1" : "value1" }
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "2" } }
{ "field1" : "value1" }
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "3" } }
{ "field1" : "value1" }
```

So you need to supply a new document each time through the loop.  Something like:

```php
for ($j = 0; $j <= $i; $j++) {
            $params['body'][] = array(
                'index' => array(
                    '_index' => $appconfig['ES_INDEX'],
                    '_type' => $index["type"],
                    '_id' => $j,
                )
            );

            $params['body'][] = $index["docs"][$i]; // <-- Notice we are only adding one doc each time!

            // Every 1000 documents stop and send the bulk request
            if ($j % 1000) {
                $responses = $client->bulk($params);
                print_r($responses);

                // erase the old bulk request
                $params = array();

                // unset the bulk response when you are done to save memory
                unset($responses);
            }
        }
```

**Comment by blaxroze** [comment]
Ah!! It makes sense now. But I think its $j not $i.

<pre>
for ($j = 0; $j <= $i; $j++) {
            $params['body'][] = array(
                'index' => array(
                    '_index' => $appconfig['ES_INDEX'],
                    '_type' => $index["type"],
                    '_id' => $j,
                )
            );

            $params['body'][] = $index["docs"][$j]; // <-- Because 1 body for 1 array.

            // Every 1000 documents stop and send the bulk request
            if ($j % 1000) {
                $responses = $client->bulk($params);
                print_r($responses);

                // erase the old bulk request
                $params = array();

                // unset the bulk response when you are done to save memory
                unset($responses);
            }
        }
</pre>

**Comment by polyfractal** [comment]
Closing :)
