### ISSUE TITLE
index child type documents in Elasticsearch

### ISSUE THREAD

**Issue by istiakk** [elastic/elasticsearch-php#248]
I have a JSON rss-feed which is actually an array. So I am indexing data in the elasticsearch like ..

    **foreach (.....) {
                    $doc["title"] = $obj['title'];
                    .....
                  }**

Here I am taking the title and saving it as a "title" in Elasticsearch, but now I actually have to save at as a "short-title" under the property of "title", here is an example...

    **["title"]=>
          array(1) {
            ["short-title"]=>
            string(71) "hello world"
          }**

I am indexing at elasticsearch like **$doc["title"] = $obj['title'];** . 
So how should i save this as "short-title" a property of "title" in PHP.

I am working on Symfony and indexing in elasticsearch.

Can anyone help me to fix this issue.

**Comment by polyfractal** [comment]
You'll likely need either an [Inner Object](https://www.elastic.co/guide/en/elasticsearch/guide/current/complex-core-fields.html#object-arrays) or a [Nested Object](https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-objects.html), which will need to be defined in your mapping ahead of time.

Alternatively, if there is only one "short title" per document, I'd probably just make it a regular field.  So you'd have both "title" and "short-title".  Only use nesting when you have a one-to-many relationship you are trying to express.

**Comment by istiakk** [comment]
Thank you for your quick and useful replay. I actually writing it to use this in a running environment where field name "title"  should have a another field name "stitle". So "stitle" i can't make it as a field. "stitle" have to be a field inside of "title" field.

foreach ($xml->file as $obj) {
$doc = array();
$doc["description"] = (string) $obj->desctiption;

I am writing like so, so when i try to follow the inner object like so 
$doc{"title": ["stitle"]} = (string) $obj->short-title;

it gives php error. and nexted object i guess will not fix my issue since i should name it like "title" and a property of title should be "stitle". 

Can you kindly try to fix this issue ...

**Comment by polyfractal** [comment]
Not entirely certain I understand your question, but you can use associative arrays in PHP to build the structure:

```php
$doc['title'] = [
  'stitle' => (string) $obj->short-title
];
```

**Comment by istiakk** [comment]
Thank you, that actually solve my problem ...
