### ISSUE TITLE
Better/more secure way to install with composer?

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch-php#251]
Currently in our documentation, we recommend people [install the PHP client with composer](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_quickstart.html) by piping a downloaded script into PHP.  That seems bad.  The download is not secured by HTTPS and there is no verification of the downloaded script.  Even if not done as an admin account, this seems like a bad idea. Is there no better way to recommend installing the client?

**Comment by polyfractal** [comment]
Yah, that's a good point.  The instructions can be tweaked to use SSL:

```
curl -sS https://getcomposer.org/installer | php
```

But I don't think there is a way to verify the download (Composer doesn't seem to publish hashes or anything).  Perhaps we can add a note pointing them to the [manual downloads](https://getcomposer.org/download/) if they want to install the phar themselves?

We should also note that this is only required if Composer is not already installed...many places will have a global copy of Composer already on the system somewhere.

**Comment by joshuar** [comment]
There also seems to be some discussion around this in the Composer repo here:

https://github.com/composer/composer/issues/3047

**Comment by polyfractal** [comment]
Closing, PR was merged :)
