### ISSUE TITLE
Abstracting scrolled responses with PHP Iterators

### ISSUE THREAD

**Issue by arturom** [elastic/elasticsearch-php#258]
Currently, it's possible to [scroll through search results](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_search_operations.html#_scan_scroll) using `$client->search()` and then `$client->scroll()` 

This pattern has come up repeatedly for me to export data in a background process. It would be nice to have a way to abstract it. A  solution would be to use PHP's [Iterator interface](http://www.php.net/manual/en/class.iterator.php). I've come up with two separate iterator classes: One iterator would be used iterate over every "page" of results and one to iterate over every individual hit.

```php
$client = new Elasticsearch\Client($config);

$search_params = array(
    'search_type' => 'scan',
    'scroll'      => '5m',
    'index'       => 'twitter',
    'size'        => 1000,
    'body'        => array(
        'query' => array(
            'match_all' => new StdClass
        )
    )
);

$pages = new Elasticsearch\Iterators\PageIterator($client, $search_params);
$hits = new Elasticsearch\Iterators\HitIterator($pages);

// Sample usage of iterating over hits
foreach($hits as $hit) {
    // do something with this hit. For example: write to a CSV, update a database, etc..
    echo $hit['_id'], PHP_EOL;
}
// Sample usage of iterating over scrolled responses
foreach($pages as $page) {
    // do something with this hit. For example: copy its data to another index, etc...
    echo count($page['hits']['hits']), PHP_EOL;
}

```
I have an implementation of these classes in my forked repo: https://github.com/arturom/elasticsearch-php/commits/iterators

Do you think these classes have a place in this library?

**Comment by polyfractal** [comment]
Wow, this totally slipped through my inbox.  Sorry for the radio silence!

Firstly, I really do like this approach; it fits perfectly with an iterator.  Unfortunately, it cannot be included *directly* in Client for two reasons:  1.0 supports down to PHP 5.3.9, and the client is supposed to be an "un-opinionated" client.  Something like an iterator starts to make opinions about how someone should consume the ES API, which is against the design goals.

BUT, for a long time I've wanted to add a "helper" class that provides utility functions (such as a [bulk helper](https://github.com/elastic/elasticsearch-php/issues/52#issuecomment-36906394)).  It would live outside the client itself (e.g. `\Elasticsearch\Helper\...`) and therefore be 100% opt-in.

I think this would be perfect for a semi-external helper.  Would you be willing to refactor it outside the main client and send a PR?

**Comment by arturom** [comment]
I understand what you mean about this being too opinionated for a this library.

A couple of things:

You mentioned the library should support PHP down to 5.3.9, but I don't see why this would break support. 

I''ll gladly do the refactoring, but I'm not sure how to fit the two classes inside a `Helper` class. I think you might have meant the `\Elasticsearch\Helper` namespace you mentioned. Or maybe there's a design pattern I'm not immediately thinking of. All I can think of right now it to move files around like this:
 - `\Elasticsearch\Iterators\HitIterator` to `\Elasticsearch\Helper\Iterators\SearchHitIterator`
 - `\Elasticsearch\Iterators\PageIterator` to `\Elasticsearch\Helper\Iterators\SearchResponseIterator`

**Comment by polyfractal** [comment]
> You mentioned the library should support PHP down to 5.3.9, but I don't see why this would break support.

Perhaps I'm misreading the PHP docs, but it looks like the Iterator class is PHP 5.5+ ?  http://php.net/manual/en/class.iterator.php

Including it won't break anything, but it's effectively a version-gated feature, which is why I'd prefer it to be a "helper" rather than "main component" of the library (in addition to the opinionated thing).

> All I can think of right now it to move files around like this:

Yep, that's basically all I meant.  :)  I just wanted to get them out of the "main" client namespace.  Sorry, I worded my response poorly!

**Comment by arturom** [comment]
I think it's 5.0.0 . I'm using it in an environment running 5.3.10.
Moving the files will be simple enough. Thanks for clarifying.

**Comment by polyfractal** [comment]
Hahaha, wow, apparently my reading comprehension is abysmal:  docs say `PHP 5 >= 5.0.0`.  5.3.9 is indeed a larger number than 5.0.0.

Ignore that particular point!

**Comment by polyfractal** [comment]
If you get a chance, would it be possible to send another PR that outlines some basic documentation?  A code example and brief description would be fine. 

Thanks again for the PR!

**Comment by polyfractal** [comment]
Gonna close this, since the iterators were merged quite a while ago :)
