### ISSUE TITLE
bulk index creation and indexing json file

### ISSUE THREAD

**Issue by shrutijain27** [elastic/elasticsearch-php#262]
Hi , i m new to elasticsearch . I m creating a bulk index to index a json file. but the script is giving error

/*
Fatal error: Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 400 [reason phrase] Bad Request [url] http://localhost:9200/flipkartlaptopindex' in /home/shruti/91mobiles/www/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43 Stack trace: #0 /home/shruti/91mobiles/www/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response)) #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/shruti/91mobiles/www/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #3 /home/shruti/91mobiles/www/vendor/symfony/event-dispatcher/EventDispatcher.ph in /home/shruti/91mobiles/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php on line 277

*/

below is my php script. please suggest some solution 

<?php

require_once 'init.php';

// Create the index and mappings
$mapping['index'] = 'flipkartlaptopindex'; //mapping code
$mapping['body'] = array(
    'mappings' => array(
        'documents' => array(
            '_source' => array(
                'enabled' => true
            ),
            'properties' => array(
                'doc_name' => array(
                    'type' => 'string',
                    'analyzer' => 'standard'
                ),
                'description' => array(
                    'type' => 'string'
                )
            )
        )
    )
);

    $es->indices()->create($mapping);

    $documentData = file_get_contents('./Catalog_data.json');

    // If the data is json, you can decode it
    $documentData = json_decode($documentData);

    // etc etc.  Depends on what format your input data is

        // Now index the documents
    for ($i = 0; $i <= count($documentData); $i++) {
        $params ['body'][] = array(
        'index' => array(
        'index' => 'flipkartlaptopindex',
        'type' => 'documents',
        '_id' => $i,
        'body' => array(
        $documentData[$i]
        )
        )
        );

    // Every 100 documents stop and send the bulk request
    if ($i % 100) {
            $responses = $es->bulk($params);

    // erase the old bulk request
             $params = array();

    // unset the bulk response when you are done to save memory
            unset($responses);
        }
    }

?>

**Comment by polyfractal** [comment]
Please see the documentation regarding bulk requests:  https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_indexing_operations.html#_bulk_indexing

You need to specify both action / document pairs.
