### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by taq** [elastic/elasticsearch-php#265]
Guys, I was trying how to find it but I couldn't, sorry. Can you give a simple example of how to use a AND operator on such a way that it returns me 'abc def' documents? Thanks!

```
$params['index'] = 'my_index';
$params['type']  = 'my_type';
$params['body']['query']['match']['testField'] = 'abc def';

$results = $client->search($params);
```

**Comment by taq** [comment]
I mean, the complete string 'abc def' and not all the documents with 'abc' or 'def'. :-)

**Comment by arturom** [comment]
Per the [docs here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#_types_of_match_queries), you can try this:
```
$params['index'] = 'my_index';
$params['type']  = 'my_type';
$params['body']['query']['match']['testField'] = array(
  'query'    => 'abc def',
  'operator' => 'and'
);

$results = $client->search($params);
```

**Comment by taq** [comment]
Hey, thanks so much, @arturom , I'll test this here. :+1:

**Comment by taq** [comment]
Worked perfect, thanks! :-)
