### ISSUE TITLE
Escaped document data

### ISSUE THREAD

**Issue by mod3st** [elastic/elasticsearch-php#268]
Hi,

I mixed a little when I noticed that using this library ES stores escaped document body values.
Is this intetional / correct way ?

Ex. I have a string like "/ABC/1234". In ES it's indexed as "\/ABC\/1234". It's a string, so in my opinion shouldn't be escaped.

Escaping data is performed with json_encode method, ex:
https://github.com/elastic/elasticsearch-php/blob/2.0/src/Elasticsearch/Serializers/SmartSerializer.php#L30

Using JSON_UNESCAPED_SLASHES flag would solve this problem.
$data = json_encode($data, JSON_UNESCAPED_SLASHES);

**Comment by polyfractal** [comment]
Yeah, unfortunately we can't support `JSON_UNESCAPED_SLASHES` in the 1.0 branch...since we (again, unfortunately) support down to PHP 5.3.9.  We should add it to 2.0 though, I agree.

Luckily, it really shouldn't have an effect.  Escaping forward slashes isn't necessary, but it isn't illegal either and ES will properly unescape it before indexing.  E.g.:

```json
curl -XPUT "http://localhost:9200/test/test/1" -d'
{
    "url": "/ABC/1234"
}'

curl -XPUT "http://localhost:9200/test/test/2" -d'
{
    "url": "\/ABC\/1234"
}'
```

```json
curl -XGET "http://localhost:9200/test/test/_search"

{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 2,
      "max_score": 1,
      "hits": [
         {
            "_index": "test",
            "_type": "test",
            "_id": "1",
            "_score": 1,
            "_source": {
               "url": "/ABC/1234"
            }
         },
         {
            "_index": "test",
            "_type": "test",
            "_id": "2",
            "_score": 1,
            "_source": {
               "url": "/ABC/1234"
            }
         }
      ]
   }
}
```
