### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by lipsync** [elastic/elasticsearch-php#273]
My code (all dependencies are installed in the same folder using composer):

require 'vendor/autoload.php';
$client = new Elasticsearch\Client();

Catchable fatal error: Argument 1 passed to Elasticsearch\Client::__construct() must be an instance of Elasticsearch\Transport, none given, called in ...... on line 4 and defined in .........../vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php on line 68

Please help

**Comment by polyfractal** [comment]
It looks like you installed the 2.0 beta branch, but are using the initialization method for 1.x

Can you verify that you installed the most recent 1.x version (`1.3.4`)?

**Comment by lipsync** [comment]
yes I installed elasticsearch/elasticsearch": "~2.0@beta

**Comment by polyfractal** [comment]
Ok.  If you want to continue using the beta, the instantiation is a bit different.  It uses a builder pattern to instantiate the client object:

```php
require 'vendor/autoload.php';

$client = ClientBuilder::create()->build();
```

Check out the 2.0 docs to see how to set hosts, etc:  https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_configuration.html

**Comment by revjackstains** [comment]
Having just done a web search for `"Catchable fatal error: Argument 1 passed to Elasticsearch\Client::__construct() must be an instance of Elasticsearch\Transport, none given, called in"`, only one page shows - this one.

I am getting this error on ver. 1.7.1 with two lines of code:

`require 'vendor/autoload.php';

$client = new Elasticsearch\Client();'

Any ideas?
