### ISSUE TITLE
Results without highlighter

### ISSUE THREAD

**Issue by fronterweb** [elastic/elasticsearch-php#281]
Hi,

I'm trying to implement search results with highlighting.
In Sense I got what I need. But when I'm trying reflect this with PHP class,
I've got only results with score, etc. but there's no highlight object.

My query looks like this:
'query' => [
    'multi_match' => 
    'query' => $query,
      'fields' => ['name', 'description]
],
'highlight' => [
    'fields' => [
    'name' => [],
    'description' => []
  ]
]

Does anybody know what I'm doing wrong?

edit: 
okey I founded it. I should set highlight as follow:
'highlight' => [
  'fields' => [ 
     'name' => new \stdClass()
  ]
]

**Comment by polyfractal** [comment]
Yep, beat me to it :)  

The highlighter expects an empty JSON object (or an object with filled parameters).  In PHP, you'll have to use `new \stdClass()`.  Alternatively, you can cast the array to an object:  `(object) []`.

They are equivalent, so you can choose whichever syntax you prefer.

**Comment by polyfractal** [comment]
Closing, feel free to reopen if you have more questions :)

**Comment by lxw0109** [comment]
My code is as follows,
```PHP
 $searchParams['body'] = [
            "query" => [
                "multi_match" => [
                    "query" => $key,
                    "fields" => ["title", "desc"]
                ]
            ],
            "highlight" => [
                "pre_tags" => ["<font color='red'>"],
                "post_tags" => ["</font"],
                "fields" => [
                    "title" => new \stdClass() //title" => []   //NO. 
                ],
                "require_field_match" => true
            ]
        ];
```
But the highlighter  does not work? Anybody helps? Thanks !

**Comment by zschuessler** [comment]
For @lxw0109 and anyone else coming from Google stuck:

I couldn't get any specific key identifiers to work for fields. In addition the `_all` identifier wasn't working. I haven't done much troubleshooting beyond getting the asterisk identifier to work, but could be helpful for others to know that `*` searches all fields as expected (my only use case so far)

My config:

```
$client = \Elasticsearch\ClientBuilder::create()->build();

$params = [
    'index'  => 'autorecall',
    'type'   => 'vehicles',
    'body'   => [
        'query' => [
            'query_string' => [
                'fields' => ['field1', 'field2', 'field3'],
                'query'  => sprintf('*%s*', $query)
            ],
        ],
        'highlight' => [
            'fields' => [
                '*' => new \stdClass()
            ]
        ]
    ]
];

$response = $client->search($params);
```

Using the above configuration, I got a highlight array back on the `hits` response:

```
0 => 
    array (size=6)
      '_index' => string 'my_index' 
      '_type' => string 'my_type' 
      '_id' => string 'my_id' 
      '_score' => float 2
      '_source' => 
        array (size=3)
          'field1' => string 'value1' 
          'field2' => string 'value2'
          'field3' => string 'value3' 
      'highlight' => 
        array (size=2)
          'field1' => 
            0 => '<em>value1</em>
              ...
          'field2' => 
            0 => '<em>value2</em>
```

I'm working with the latest version of this library as of time of this post (ES 5).

Hope that helps someone!
