### ISSUE TITLE
why don't use Guzzle6 with ES 2.0?

### ISSUE THREAD

**Issue by argb** [elastic/elasticsearch-php#282]

**Comment by polyfractal** [comment]
Mainly because the 2.0 branch was started before Guzzle6 was a thing.  :)

I also [wrote about it some here](https://github.com/elastic/elasticsearch-php/issues/193#issuecomment-106006729), regarding future outlook for the next major version.

**Comment by argb** [comment]
@polyfractal Thank you ,I am studying ES hard,thanks for your work.

**Comment by polyfractal** [comment]
Np :)  Once 2.0 is out, I'll be watching Guzzle to see if there are any moves to bump the major version again.  Assuming it starts to settle down (it's been a whirlwind of breaking changes lately), I'd be inclined to base the next major in the latest Guzzle potentially
