### ISSUE TITLE
How to use ValidateQuery class to validate a query?

### ISSUE THREAD

**Issue by harpreetsb** [elastic/elasticsearch-php#284]
How to use ValidateQuery class to validate a query?

**Comment by polyfractal** [comment]
The [Validate API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html) has this syntax:

```shell
curl -XGET 'http://localhost:9200/twitter/tweet/_validate/query' -d '{
  "query" : { ... }
}'
```

So converted to PHP it would look like this:

```php
$client->indices()->validate([
  'index' => 'twitter',
  'type' => 'tweet',
  'body' => [
    'query' => [ /* query here */ ]
  ]
]);
```

So just supply the index, type, and query body.  If you want/need extra params like `explain`, set them as top-level parameters:

```php
$client->indices()->validate([
  'index' => 'twitter',
  'type' => 'tweet',
  'explain' => true,
  'body' => [
    'query' => [ /* query here */ ]
  ]
]);
```

**Comment by harpreetsb** [comment]
well
Fatal error: Call to undefined method Elasticsearch\Namespaces\IndicesNamespace::validate()

**Comment by polyfractal** [comment]
Whoops, that's what I get for typing it out by hand instead of using an IDE.  The [endpoint is called `validateQuery()`, not `validate()`](https://github.com/elastic/elasticsearch-php/blob/1.0/src/Elasticsearch/Namespaces/IndicesNamespace.php#L702).  Sorry about that!

```php
$app->client->indices()->validateQuery($params);
```

**Comment by harpreetsb** [comment]
Thank you, that works
