### ISSUE TITLE
how to implement highlight search result letter by letter?

### ISSUE THREAD

**Issue by argb** [elastic/elasticsearch-php#287]
I implement a autocomplete feature learn from the ES document ,but when I type in letter 'a',the highlighted result is abc,then i type 'ab',highlighted result is still 'abc'.
I found ES official website's autocomplete feature is highlighted letter by letter,not a matched word,and Algolia is same as.
so how to implement that effect?
bellow is my index setting:
$params=[
            'index' => $index,
            'body' => [
                'analysis' => [
                    'filter' => [
                        'autocomplete_filter' => [
                            'type' => 'edge_ngram',
                            'min_gram' => 1,
                            'max_gram' => 20
                        ]
                    ],
                    'analyzer' => [
                        'autocomplete' => [
                            'type' => 'custom',
                            'tokenizer' => 'standard',
                            'filter' => [
                                'lowercase','autocomplete_filter'
                            ]
                        ]
                    ]
                ],
                //'mappings' => $this->mappings
            ]
        ];
bellow is mapping:
'questions' => [
            '_source' =>['enabled'=>true],
            'properties' => [
                'id' => [
                    'type'=>'long',
                    'index' => 'not_analyzed'
                ],
                'title' => [
                    'type' => 'string',
                    //'analyzer' => 'autocomplete'
                    "index_analyzer" => "autocomplete",
                    "search_analyzer" => "standard"
                ],
                'body' => [
                    'type' => 'string',
                    //'analyzer' => 'autocomplete'
                    "index_analyzer" => "autocomplete",
                    "search_analyzer" => "standard"
                ],
                'anonymous' =>[
                    'type' => 'boolean',
                    'index' =>'not_analyzed',
                    //'store' => 'yes'
                ],
                'created_at' => [
                    'type' => "date",
                    'format' => 'YYYY-MM-dd HH:mm:ss',
                    'index' => 'not_analyzed',
                    //'store' => 'yes'
                ],
                'update_at' => [
                    'type' => "date",
                    'format' => 'date_time_no_millis',
                    'index' => 'no',
                    //'store' => 'yes'
                ]
            ]
bellow is search params:
[
            '_source' => [ //control which field contained in _source to show
                'include' =>['id','title','body','location']
            ],
            'query'=>[
                'multi_match'=>[
                    'query'=>$text,
                    'fields'=>['title','body','location']
                ]
            ],
            'highlight' => [
                'order' => 'score',
                'fields' => [
                    'title' => ["term_vector" => "with_positions_offsets"],
                    'body' => ["term_vector" => "with_positions_offsets"],
                    'location' => ["term_vector" => "with_positions_offsets"]
                ]
            ]
        ]

here is the live demo,and is a real project,http://www.bigfeettrip.com/qa/index
in this page,the top input's autocomplete  is implemented with Algolia, and the bottom one is implemented with ES,the basic autocompletion is ok,but the highlighted part is weird,not letter by letter as i type letter by letter,and i send a ajax request every letter.
do you know how did ES official website did to achieve the effect?

**Comment by polyfractal** [comment]
I'm afraid a question of this scope is a bit unrelated to the Elasticsearch-PHP client, since it is largely a question about implementing a feature via Elasticsearch.  I think you'll have better luck posting at the ES Discuss forums:  https://discuss.elastic.co/c/elasticsearch

If you have specific questions about the PHP client I'd be happy to help, but more general questions should be directed to the forums.

**Comment by argb** [comment]
@polyfractal I have solved it.Maybe the ES document and Definitive Guide there is something wrong,I am not sure,but after I exchanged filter and tokenizer's place ,it worked.
