### ISSUE TITLE
Using artax instead of guzzle

### ISSUE THREAD

**Issue by macnibblet** [elastic/elasticsearch-php#29]
Heya cool people of elasticsearch!

Just a random thought i had and thought of doing in my own elasticsearch code before i found this project was to utilize artax (https://github.com/rdlowrey/Artax) to run requests in parallel stuff like searching/count would be pretty neat to be able to have run parallel

**Comment by polyfractal** [comment]
Closing due to age, and no desire to use alternative backends at this point in time :)
