### ISSUE TITLE
Make responses PSR-7 Compliant

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch-php#291]
Making the responses coming out of of Elasticsearch-PHP PSR-7 compliant shouldn't be too difficult, and I think it can be done in a way that doesn't violate the "no opinion" goal of all low-level ES clients (and without breaking bwc)

I'm unsure if the requests can easily be made compliant, but we can explore that avenue as well

**Comment by jeskew** [comment]
:+1: to having requests be PSR-7 compliant (and for having a method that would create a request object and return it to you). That would make it easier to support more kinds of authentication.

**Comment by sagikazarmark** [comment]
Speaking of PSR-7: several [PHP HTTP](https://github.com/php-http) became stable over the past few weeks:

- HTTPlug: a PSR-7 HTTP Client abstraction layer
- Message: several message helper components
- Message Factory: interfaces for PSR-7 Message Factories

**Comment by ezimuel** [comment]
I'm working on a new `elasticsearch-php` client that will be released for the next major (8.0). This will support PSR-7, PSR-18.
