### ISSUE TITLE
Have a doubt in index ,type when calling index() via client object 

### ISSUE THREAD

**Issue by niloyniloy** [elastic/elasticsearch-php#292]
$params['hosts'] = array (
            // Just Domain
     'http://localhost:80'               // SSL to localhost 
    );

     $client = new Elasticsearch\Client($params);

     $params = [
         'index' => '',
         'type' => '',
         'id' => 1 ,
         'body' => [
                     'title' => $_POST['title'],
                     'body' => $_POST['body'],
                     'keyword' => $_POST['keyword']
                     ]
         ];

      $response = $client->index($params);

Here is my code to make an index with elastic search .But My question why should I need to given index , type parameter ? It fetch the url as http://host/index/type . and fetch the url content . 

Can u please explain how this elastic search strategy works here ??

**Comment by polyfractal** [comment]
I'm not sure I understand your question?

Elasticsearch can have multiple indices per cluster, and each index can have multiple types.  These are mechanisms to organize your data and distribute them across the cluster (`indexA` may have 10 shards while `indexB` only has three shards)

**Comment by polyfractal** [comment]
Closing, feel free to reopen if you can provide some more info.
