### ISSUE TITLE
elasticsearch client problem

### ISSUE THREAD

**Issue by Astonmartin** [elastic/elasticsearch-php#295]
Hi im starting with elasticsearch and already installed through brew, also composer, but when im trying to create a client this error come out

vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php on line 68

this is my code

<?php
require 'vendor/autoload.php';
$params = array();
$params['hosts'] = array ('127.0.0.1:9200');

$client = new Elasticsearch\Client($params);

elasticsearch data
{
  "status" : 200,
  "name" : "Dan Ketch",
  "cluster_name" : "elasticsearch_jobivanramossaucedo",
  "version" : {
    "number" : "1.7.1",
    "build_hash" : "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
    "build_timestamp" : "2015-07-29T09:54:16Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by polyfractal** [comment]
It looks like the exception is incomplete...can you paste the whole thing?

Are you using ES-PHP 1.x or 2.x?

**Comment by Astonmartin** [comment]
This is exception complete

Catchable fatal error: Argument 1 passed to Elasticsearch\Client::__construct() must be an instance of Elasticsearch\Transport, array given, called in /Applications/XAMPP/xamppfiles/htdocs/findme/index.php on line 6 and defined in /Applications/XAMPP/xamppfiles/htdocs/Findme/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php on line 68

composer.json

{
    "require": {
        "monolog/monolog": "1.0.*",
        "elasticsearch/elasticsearch": "^2.0"
   
    }
}


PHP Version 5.6.12

**Comment by polyfractal** [comment]
ES-PHP 2.0 has a different method of instantiating the client:

```php
$client = ClientBuilder::create()->build();
```

More details are in the documentation: https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_quickstart.html

**Comment by Astonmartin** [comment]
thanks! i change two start with php 1 and warnings are gone.

**Comment by polyfractal** [comment]
Great :)
