### ISSUE TITLE
How can I use analyizer api

### ISSUE THREAD

**Issue by jianfengye** [elastic/elasticsearch-php#297]
I saw there is an "\Elasticsearch\Endpoints\Indices\Analyze()"  but I don't know how to use it , is there any example for that?

**Comment by duccanh0022** [comment]
Hi, that work for me:
            $params             = [];
            $params['index']    = 'index_tokenizer_vi';
            $params['analyzer'] = 'my_analyzer';
            $params['text']     = 'Công nghệ thông tin Việt Nam';
            $client->indices()->analyze($params) ;

**Comment by ywdblog** [comment]
es7

https://github.com/elastic/elasticsearch-php/issues/931#issuecomment-521293999
