### ISSUE TITLE
"No alive nodes found in your cluster" with version 2.0.0

### ISSUE THREAD

**Issue by martinsik** [elastic/elasticsearch-php#300]
Hi, I'm having problems with connecting to a server running on facetflow.com. cURL under CLI, and `elasticsearch-php` v1.4.1 works fine but v2.0.0, including `dev-master`, throw exception:

```
Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\NoNodesAvailableException' with message 'No alive nodes found in your cluster' in /Users/martin/git/cms_skeleton/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51

Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /Users/martin/elasticsearch-php-test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51

Call Stack:
    0.0005     226392   1. {main}() /Users/martin/elasticsearch-php-test/test/test_es.php:0
    0.0222     610144   2. Elasticsearch\Namespaces\IndicesNamespace->delete(array(1)) /Users/martin/elasticsearch-php-test/test/test_es.php:11
   75.1297     788368   3. Elasticsearch\Endpoints\AbstractEndpoint->resultOrFuture(class GuzzleHttp\Ring\Future\FutureArray) /Users/martin/elasticsearch-php-test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php:175
   75.1297     788648   4. GuzzleHttp\Ring\Future\FutureArray->wait() /Users/martin/elasticsearch-php-test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php:173
```

Code for v 2.0.0:
```php
include __DIR__ . '/../vendor/autoload.php';

$client = \Elasticsearch\ClientBuilder::create()
    ->setHosts(['http://user:@account.west-eu.azr.facetflow.io'])
    ->build();

var_dump($client->indices()->delete([
    'index' => 'my_index',
]));
```
This should at least return an error because the index doesn't exist. I'm running PHP 5.5.27 with cURL 7.43.0 under OS X 10.10.

Here are [their API Limitation](http://support.facetflow.com/kb/elasticsearch/api-limitations). Maybe it has something to do with them banning `_cluster` resource?

My cURL settings from `phpinfo()`:
![screen shot 2015-09-20 at 17 46 22](https://cloud.githubusercontent.com/assets/238765/9981506/944e83d4-5fbf-11e5-878e-1d241591ee7d.png)

Feel free to ask me for any additional settings/dumps.

**Comment by polyfractal** [comment]
Sorry for the delay, was out of town friday.

Hmmm... that is quite odd.  The API limitations shouldn't affect you, since the client is using the default StaticNoPingConnectionPool.  That pool doesn't perform any pinging or cluster state sniffing, it simply tries to access each host individually assuming they are online.

Two ideas to start debugging.  Let's try to manually set the handler, perhaps one of the HTTP handlers is buggy.  Can you try:

```php
$singleHandler  = ClientBuilder::singleHandler();
$multiHandler   = ClientBuilder::multiHandler();

// Try both the $singleHandler and $multiHandler independently
$client = \Elasticsearch\ClientBuilder::create()
    ->setHosts(['http://user:@account.west-eu.azr.facetflow.io'])
    ->setHandler($singleHandler)
    ->build();

```

And let's also see what the last connection details look like, perhaps the Basic Auth functionality is broken and it is mangling the URL:

```php
$client = \Elasticsearch\ClientBuilder::create()
    ->setHosts(['http://user:@account.west-eu.azr.facetflow.io'])
    ->build();

try {
    var_dump($client->indices()->delete([
        'index' => 'my_index',
    ]));
} catch (Exception $e) {
    var_dump($client->transport->getLastConnection()-> getLastRequestInfo());
}
```

Note: the last request info var_dump might be quite large (I haven't tried it with the new RingPHP framework yet, but under the 1.x Guzzle connections it could be very large).  And it will contain your user:pass, so be sure to sanitize it before gisting up :)

Thanks for the help tracking this down!

**Comment by martinsik** [comment]
Hi, sorry for the late response.
I tried `$singleHandler` and `$multiHandler` but they both return the same `NoNodesAvailableException` error as above.
Function `getLastRequestInfo()` returns an empty array `array(0) {}`.

I tried also using `https://` and adding port `443` at the end of host url and it throws `BadRequest400Exception` which I wouldn't expect. I'm actually using `v1.4` with `https` and it works well:
```
#0 /Users/martin/develop/php/es_test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(208): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /Users/martin/develop/php/es_test/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /Users/martin/develop/php/es_test/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /Users/martin/develop/php/es_test/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /Users/martin/develop/php/es_test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(229): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#5 /Users/martin/develop/php/es_test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(150): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /Users/martin/develop/php/es_test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(106): Elasticsearch\Connections\Connection->performRequest('DELETE', '/my_index', Array, NULL, Array, Object(Elasticsearch\Transport))
#7 /Users/martin/develop/php/es_test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(80): Elasticsearch\Transport->performRequest('DELETE', '/my_index', Array, NULL, Array)
#8 /Users/martin/develop/php/es_test/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(173): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#9 /Users/martin/develop/php/es_test/test2.0.php(13): Elasticsearch\Namespaces\IndicesNamespace->delete(Array)
#10 {main}
```

Just to be sure, I tried both `http` and `https` with cURL and they worked.

By the way, you can make a free account at [facetflow.com](https://facetflow.com/) and try by yourself. Maybe there's really something wrong with my configuration.

**Comment by polyfractal** [comment]
Creating an account and will see if I can replicate the problem.

**Comment by polyfractal** [comment]
Figured it out :)

- You were getting a NoNodeAvailable exception because the ES-PHP client uses port 9200 if you don't specify one.  Facetflow doesn't expose 9200, so it was just timing out

- Instead, you have to use `https` and `443` (e.g. `'https://user:@account.west-eu.azr.facetflow.io:443'`).  That didn't work for you either though, because...

- ...apparently, curl cannot parse the partial auth signatures that Facetflow uses.  The inline syntax requires both username:password.  So even if you use the correct URI, curl will fail with a "Bad Hostname" error.  

- I pushed a fix (4b01af81de7dbd393a8d7f2e3f92a7357f9d8d72) which uses the explicit curlopts instead of inline syntax, which seems to satisfy curl and allowed me to talk to Facetflow.  

The fix was tagged in `v2.0.2`...let me know if it works for you!

**Comment by martinsik** [comment]
Hi, I tried `v2.0.2` and it seems fine. Thanks!

**Comment by LucasCambraia** [comment]
I'm trying to connect to amazon elasticsearch endpoint and get the same problem using the version 2.0 of elasticsearch-php, this is my code:   
`$host = ["http://amazon-end-point"];

$clientBuilder = Elasticsearch\ClientBuilder::create();
$clientBuilder->setHosts($host);
$client =	$clientBuilder->build();
		
$params = [
	'index' => 'test',
	'type' => 'type_test',
	'id'=> '1'
];

$response = $client->get($params);`

Always get the error: "No alive nodes found in your cluster", but if I try to connect to the endpoint by curl in command line it works perfectly

I tried everything that i found in google with the same issue, but anything helped me with this problem :(

**Comment by ShaoZeMing** [comment]
laravel 5.3 implement ： php artisan scout:import "XXX\Lesson" 

cmd: error:
 [Elasticsearch\Common\Exceptions\NoNodesAvailableException]
  No alive nodes found in your cluster
There is no way to solve  Think you

**Comment by srinivasmangipudi** [comment]
I am getting the same error. I already have a task running fine with the same config, but when I run another task, it is failing with the following exception:

[Elasticsearch\Common\Exceptions\NoNodesAvailableException]  
  No alive nodes found in your cluster

**Comment by dcdebug** [comment]
@polyfractal Thank you ! it's work !
