### ISSUE TITLE
CurlMultiConnection::performRequest consuming too much memory

### ISSUE THREAD

**Issue by ptetevensky** [elastic/elasticsearch-php#326]
Due to bug in PHP with curl_multi.... functions, curl_multi_remove_handle doesn't free resources and handles with data are accumulated and consuming too much memory, increasing with new handler added. I did tests and added curl_close($transfer['handle']);  just after curl_multi_remove_handle (line 211) and it works fine.

**Comment by ptetevensky** [comment]
I did tests and put logging within the function to log results from memory_get_peak_usage(true). POST data for requests varied between 20-30 MB. Memory consumption started from 20-30 MB (approx. the POST data size) and increased constantly with next handlers added, reaching out to 400 MB. After I added curl_close , memory used by handlers was released and tolerated 20-30 MB (increasing and decreasing), depending on the size of POST data.

**Comment by polyfractal** [comment]
Good find.  I'm on a trip at the moment, but will fix this when I get home.  

Unless you want to send a PR, in which case I'd be happy to merge it :)

**Comment by ptetevensky** [comment]
Created pull request:
https://github.com/elastic/elasticsearch-php/pull/331

**Comment by ptetevensky** [comment]
PR merged. Fixed.
