### ISSUE TITLE
Overhaul the logging output

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch-php#336]
The logged output is inconsistent, noisy and not very structured.  It is also lacking in places: there should be more trace and debug logging of low-level actions, not just warnings/failures.

We should do a complete overhaul of what's logged and make it more consistent, and ideally structured for easy parsing/grep'ing

**Comment by polyfractal** [comment]
Bumping tag, still relevant.

**Comment by ezimuel** [comment]
This is something I'll improve in 8.0.
