### ISSUE TITLE
PromiseInterface not found

### ISSUE THREAD

**Issue by nuttawatkit** [elastic/elasticsearch-php#337]
Fatal error: Interface 'React\Promise\PromiseInterface' not found in ./vendor/react/promise/src/ExtendedPromiseInterface.php on line 6

//$host is aws elastic search endpoint
$client = ClientBuilder::create()
                        ->setHosts($hosts)->setRetries(0)
                        ->build();
$params = [
    'index'=>'store',
    'type'=>'book',
    'body'=>[
        'query'=>[
            'match'=>[
                'id'=>'1'
            ]
        ]
    ]
];
$res = $client->search($params);

I try to connect and search data from AWS endpoint and it showed this error.

**Comment by polyfractal** [comment]
I suspect the dependencies were not installed, since that is a library that the client uses.  Can you share how you installed the client?  Also attaching your `composer.json` and `composer.lock` would be helpful

**Comment by polyfractal** [comment]
Closing due to lack of information, please feel free to reopen if you can provide some more details!
