### ISSUE TITLE
there is no way to specify 'wait_if_ongoing' in php sdk

### ISSUE THREAD

**Issue by jerryladoo** [elastic/elasticsearch-php#339]
I have noticed that `flush` endpoint has an option `wait_if_ongoing`, but I didn't find corresponding option in `flush` method in php sdk. I am wondering how can I use this option with php sdk?

**Comment by polyfractal** [comment]
Just added to the whitelist: https://github.com/elastic/elasticsearch-php/commit/7b9cf8c7fcac781ccca0688fb73591f626fe1a8a

I'll tag and release later today, want to fix up some travis stuff first.  Thanks for the report!

**Comment by jerryladoo** [comment]
@polyfractal thanks mate

**Comment by polyfractal** [comment]
Tagged in `v2.1.3` :)

**Comment by jerryladoo** [comment]
@polyfractal thanks for that, but I still didn't see it in v2.1.3. is there a new method or option I can use for that?

**Comment by polyfractal** [comment]
Should be able to pass it in as a top-level parameter:

```php
$client->indices()->flush([
   'wait_if_ongoing' => true
]);
```

**Comment by jerryladoo** [comment]
thanks @polyfractal
