### ISSUE TITLE
SearchHitIterator could implement \Countable

### ISSUE THREAD

**Issue by murnieza** [elastic/elasticsearch-php#341]
It is quiet easy to implement `\Contable` interface in `SearchHitIterator`. In [`rewind()`](https://github.com/elastic/elasticsearch-php/blob/7b9cf8c7fcac781ccca0688fb73591f626fe1a8a/src/Elasticsearch/Helper/Iterators/SearchHitIterator.php#L55) method we already get full count of documents matching query.

I am willing to create PR for that. Any thoughts?

**Comment by polyfractal** [comment]
++ Would happily accept a PR!
