### ISSUE TITLE
Fatal error with \Elasticsearch\ConnectionPool\StaticConnectionPool

### ISSUE THREAD

**Issue by Nicolas35** [elastic/elasticsearch-php#349]
I'm using this client config :
```
$clientBuilder = \Elasticsearch\ClientBuilder::create();
$clientBuilder->setHosts($GLOBALS['CONFIG']['ELASTICSEARCH_SERVERS']);
$this->_client = $clientBuilder->setRetries(0)->setConnectionPool('\Elasticsearch\ConnectionPool\StaticConnectionPool', [])->build();
```
And randomly i have some PHP Fatal error :
```
PHP Notice:  Trying to get property of non-object in /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 202
PHP Fatal error:  Call to a member function scheduleCheck() on a non-object in /vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 202
```
I finaly found that's a cURL timeout error with the logs :
```
[error] => GuzzleHttp\\Ring\\Exception\\ConnectException Object
[message:protected] => cURL error 28: connect() timed out!
```

Elasticsearch version : 2.0.0
Elasticsearch-php version : 2.0

**Comment by polyfractal** [comment]
Just pushed a fix in https://github.com/elastic/elasticsearch-php/commit/7111277fb71a67484e037067d41c905dfa1fd3a5, thanks for the report!  I'll tag and release in a few minutes...will ping this thread once it is tagged.

**Comment by Nicolas35** [comment]
Still have the problem... :)
In Connection.php on line 202 the $transport object is null.
And i think your fix is to use $transport->scheduleCheck(); instead of $transport->connectionPool->scheduleCheck(); ?... But $transport->connectionPool is public.

Thanks for your reactivity!

**Comment by polyfractal** [comment]
Ah, yes, you're right.  That's what I get for doing code changes before coffee.

I'll break out the debugger in a minute and look closer, $transport shouldn't be null there.  Something must be going wrong in the builder.

**Comment by polyfractal** [comment]
Ah, found the issue...it's a problem with the pinging functionality that gets invoked by `StaticConnectionPool`.  Will push a real fix this time :)

**Comment by polyfractal** [comment]
Ok, so it turned out a bit tricker than I expected.  The architectural setup is showing some problems, namely that everything seems to need a reference to $transport.

For now, this problem can ben fixed by only executing the retry behavior when $transport is not null (which is what we want anyway...it'd be bad to retry and schedule checks on failed ping requests).  But ultimately this is a bit hacky, since the root problem is architectural in nature.

I'll open a ticket, since I'm getting tired of $transport mucking things up.  We'll see about refactoring this in 3.0

**Comment by polyfractal** [comment]
Tagged in `v2.1.3`.  Lemme know if that fixes things for you :)

**Comment by Nicolas35** [comment]
Perfect Sir !

I'm happy to give you some work :p (you was at the Elastic{on} in Paris, no ?)
I'll test that tomorrow and i'll tell you.

Many thanks !

**Comment by Nicolas35** [comment]
Problem fixed ! Thanks :)

**Comment by polyfractal** [comment]
Great!  Happy to hear that.

And no, I'm afraid I wasn't at the Paris Elasticon (although I would have loved to attend!)  Maybe next year :)
