### ISSUE TITLE
dfs_query_then_fetch

### ISSUE THREAD

**Issue by kaelwu** [elastic/elasticsearch-php#352]
when i set the search_type dfs_query_then_fetch 
![image](https://cloud.githubusercontent.com/assets/8181007/11835487/df8d420c-a40e-11e5-838f-52c881e52c83.png)

**Comment by polyfractal** [comment]
Could you paste the relevant code where you are setting the parameter and searching?  And the exception message/trace?

**Comment by polyfractal** [comment]
Closing due to lack of information, please feel free to reopen if you can provide some more details!
