### ISSUE TITLE
Index Operations example invalid

### ISSUE THREAD

**Issue by derekjones** [elastic/elasticsearch-php#354]
The second example [here](https://github.com/elastic/elasticsearch-php/blob/master/docs/index-operations.asciidoc#create-an-index)

Has invalid nesting, putting `properties` inside of `_source` which results in a fatal PHP error.

**Comment by polyfractal** [comment]
Ah, yeah, this is a holdover from 1.x where it was legal (iirc).  I'll fix this when I'm back from holiday, or if you want to send a PR I'll merge that.

Thanks!

**Comment by derekjones** [comment]
Somehow missed the notification in my inbox, @polyfractal, sorry about that, and thanks!

**Comment by polyfractal** [comment]
Np, thanks for the report!
