### ISSUE TITLE
Incorrect handling of the host's path

### ISSUE THREAD

**Issue by elwinar** [elastic/elasticsearch-php#356]
It seems that the `Elasticsearch\Connections\Connection` class handles the host's path wrongly: the path segment of the host is added to the host part of the emitted request, instead of the URI part, which cause the HTTP servers to reject the request as being invalid (see (RFC 2616 - Section 14.23)[http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23] for the definition of the Host field).

I've got a quick fix that you can see here : https://github.com/elwinar/elasticsearch-php/commit/75cd5e5e25141772baa3aea9df9560c112b5309a
However, it don't find tests related to this part of the code (my fix doesn't break any test as far as I know). Did I miss them ?

Note that the 1.X version didn't had this problem, it may be related to the shift in the way the connections are handled.

**Comment by polyfractal** [comment]
Skimming the changes, looks like it's just a bug from the 2.x overhaul.  Want to send a PR?

Don't think you missed any tests...the main bulk of the tests are the ES integration tests, which don't use this functionality.  When the feature was added to 1.x I was probably lazy and didn't add any unit tests.  Sooo... it's not unsurprising that this broke without me noticing.  Oops :)

**Comment by elwinar** [comment]
Done.
Had to do it twice because I botched the first. Monday mornings…

**Comment by elwinar** [comment]
Closing this, as the fix is merged and tagged.
