### ISSUE TITLE
Method Not Allowed

### ISSUE THREAD

**Issue by sumitchawria** [elastic/elasticsearch-php#357]
Hi

I am new to elasticsearch-php.
I am facing problem in starting with this.

**My code is :**

```
<?php	
	require 'vendor/autoload.php';
	use Elasticsearch\ClientBuilder;	
	$client = ClientBuilder::create()->setHosts(["172.31.3.238:80"])->build();	
	$response = '';	
	try{
		$params = [
			'index' => 'new_index'
		]; 
		$response = $client->indices()->create($params);		
	}catch(Exception $e){
		echo "Exception : ".$e->getMessage();
	}
        print_r($response);
	die('End : Elastic Search');
?>
```

**But I am getting errors :**

Exception :
Method Not Allowed

The requested method PUT is not allowed for the URL /new_index.

Please Guide me.
Thanks in advance.

**Comment by polyfractal** [comment]
I think this must be a security/authorization problem on the server. Are you using Shield, or a hosted solution that requires credentials (Found, AWS, ObjectRocket, etc)?  

If I execute the command, it works fine on my end:

```php
Array
(
    [acknowledged] => 1
)

End : Elastic Search
```

**Comment by sumitchawria** [comment]
Thanks polyfractal  for your kind reply.
I figured out the problem was host address.

**Comment by maikap** [comment]
Same Problem  .here is the response `Array ( [request] => Array ( [http_method] => PUT [scheme] => http [uri] => /my_index [body] => {"settings":{"number_of_shards":2,"number_of_replicas":0}} [headers] => Array ( [host] => Array ( [0] => localhost:80 ) [Content-type] => Array ( [0] => application/json ) [Accept] => Array ( [0] => application/json ) ) ) [response] => Array ( [transfer_stats] => Array ( [url] => http://localhost:80/my_index [content_type] => text/html; charset=iso-8859-1 [http_code] => 405 [header_size] => 216 [request_size] => 182 [filetime] => -1 [ssl_verify_result] => 0 [redirect_count] => 0 [total_time] => 0.016 [namelookup_time] => 0 [connect_time] => 0 [pretransfer_time] => 0 [size_upload] => 58 [size_download] => 314 [speed_download] => 19625 [speed_upload] => 3625 [download_content_length] => 314 [upload_content_length] => 58 [starttransfer_time] => 0.016 [redirect_time] => 0 [redirect_url] => [primary_ip] => ::1 [certinfo] => Array ( ) [primary_port] => 80 [local_ip] => ::1 [local_port] => 57769 [error] => [errno] => 0 ) [curl] => Array ( [error] => [errno] => 0 ) [effective_url] => http://localhost:80/my_index [headers] => Array ( [Date] => Array ( [0] => Tue, 19 Sep 2017 01:06:49 GMT ) [Server] => Array ( [0] => Apache/2.4.23 (Win64) PHP/7.0.10 ) [Allow] => Array ( [0] => GET,HEAD,POST,OPTIONS,TRACE ) [Content-Length] => Array ( [0] => 314 ) [Content-Type] => Array ( [0] => text/html; charset=iso-8859-1 ) ) [version] => 1.1 [status] => 405 [reason] => Method Not Allowed [body] => `

**Comment by polyfractal** [comment]
> http://localhost:80/my_index

> Apache/2.4.23 (Win64) PHP/7.0.10

Elasticsearch runs on port 9200 by default.  It looks like you are using port 80, which is talking to an Apache server. :)
