### ISSUE TITLE
Can't deleteMapping

### ISSUE THREAD

**Issue by vuthaihoc** [elastic/elasticsearch-php#360]
I got this response when using deleteMapping function

    local.ERROR: {"found":false,"_index":"taggable","_type":"course","_id":"_mapping","_version":1,"_shards":{"total":2,"successful":1,"failed":0}}

My mapping

    {
       "taggable": {
          "mappings": {
             "course": {
                "properties": {
                   "active_status": {
                      "type": "integer"
                   },....

I'm trying to delete index `taggable`, type `course`

**Comment by polyfractal** [comment]
Can you paste your PHP code?

**Comment by vuthaihoc** [comment]
@polyfractal thank for your reply
Here is my `deleteIndex` function,  `$index` can be `index_a.type_a`

    public function deleteIndex($index)
    {
        $index_type = explode('.', $index);
        try{
            $_index = [
                'index' => $index_type[0],
                ];
            if(count($index_type) > 1){
                $_index['type'] = $index_type[1];
                $this->client->indices()->deleteMapping($_index);
            }else{
                $this->client->indices()->delete($_index);
            }
            return true;
        }catch (\Exception $ex){
            \Log::error($ex->getMessage());
            return false;
        }
    }

**Comment by polyfractal** [comment]
Oh, are you using Elasticsearch 2.0+ ?  Deleting type mappings has been removed in 2.0+:  https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-delete-mapping.html

**Comment by vuthaihoc** [comment]
Thank @polyfractal
