### ISSUE TITLE
Script Based Sorting in ES 2.1 doesn't work

### ISSUE THREAD

**Issue by blaxroze** [elastic/elasticsearch-php#366]
Hi,

I have this params and my sort query doesn't work and this error come up.
<b>Elasticsearch \ Common \ Exceptions \ ServerErrorResponseException (500)
HELP
search_phase_execution_exception: all shards failed</b>

Do I miss something?

<pre>
$params = [
            'index' => $appconfig['ES_INDEX'],
            'body' => [
                "from" => 0,
                "size" => 5,
                "query" => [
                    "filtered" => [
                        "filter" => [
                            "bool" => [
                                "must" => [
                                    [
                                        "query" => [
                                            "match" => [
                                                "text.text" => [
                                                    "query" => $keyword->keyword,
                                                    "type" => "phrase"
                                                ]
                                            ]
                                        ]
                                    ],
                                    [
                                        "range" => [
                                            "created_at" => [
                                                "from" => $campaign->start_date." 00:00:00", 
                                                "to" => $campaign->end_date." 23:59:59"
                                            ]
                                        ]
                                    ],
                                ]
                            ]
                        ]
                    ]
                ],
                "_source" => [
                    "include" => [
                        "id_str",
                        "rt_count",
                        "fav_count",
                    ]
                ],
                "sort" => [
                    "_script" => [
                        "type" => "number",
                        "script" => [
                            "inline" => "doc['rt_count'].value + doc['fav_count'].value",
                        ],
                        "order" => "desc"
                    ]
                ]
            ]
        ];
</pre>

**Comment by polyfractal** [comment]
Dynamic, inline scripting is disabled by default in 2.x (for security reasons).  You'll have to [re-enable dynamic scripting](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/modules-scripting.html#enable-dynamic-scripting), or use static scripts in the `config/scripts` directory.

**Comment by blaxroze** [comment]
I tried static scripts too.

The error is <b>"error":{"root_cause":[{"type":"groovy_script_execution_exception","reason":"failed to run file script [calculate_rtfav] using lang [groovy]"}]</b>

the script is doc['field1'].value + doc['field2'].value
<pre>
"sort" => [
                    "_script" => [
                        "type" => "number",
                        "script" => [
                            "file" => "calculate_rtfav",
                            "params" => [
                                "field1" => "rt_count",
                                "field2" => "fav_count",
                            ]
                        ],
                        "lang" => "groovy",
                        "order" => "desc"
                    ]
                ]
</pre>

**Comment by blaxroze** [comment]
I tried static script too.

there is an err.
No field found for [field1] in mapping with types []

script1 : doc['field1'].value + doc['field2'].value

script1 : doc['field1'].value + doc['field2'].value

mapping 
<pre>
"rt_count": {
              "type": "long"
            },
"fav_count": {
                  "type": "long"
                },
</pre>

query
<pre>
"sort" => [
                    "_script" => [
                        "type" => "number",
                        "script" => [
                            "file" => "calculate_rtfav",
                            "params" => [
                                "field1" => "retweet_count",
                                "field2" => "favorite_count",
                            ]
                        ],
                        "lang" => "groovy",
                        "order" => "desc"
                    ]
                ]
</pre>

**Comment by polyfractal** [comment]
Ah, so if you want to use script parameters, you need to un-quote the variables in the script so it is treated as a variable and not a string.  Try this:

Script:
```
doc[field1].value + doc[field2].value
```

Sort:
```
"sort" => [
    "_script" => [
        "type" => "number",
        "script" => [
            "file" => "calculate_rtfav",
            "params" => [
                "field1" => "retweet_count",
                "field2" => "favorite_count",
            ]
        ],
        "lang" => "groovy",
        "order" => "desc"
    ]
]
```

**Comment by blaxroze** [comment]
it works!!!! thank you so much!

**Comment by polyfractal** [comment]
No problem, happy to help :)  Scripts are tricky at best, especially with all the security configuration stuff.

Goodluck!
