### ISSUE TITLE
 How to check regex is valid or not? 

### ISSUE THREAD

**Issue by vrkansagara** [elastic/elasticsearch-php#367]
Hello

I want to check weather the regex is valid or not using search api and valid api validator.

Can any body help me out that how can I achieve this.

Query type can be : match all , match and some time wildcard.

Tried following things
```
{
"regexp":{
"columnName": {
"value": "\/([A-Z])\\w+\/g",
"flags" : "INTERSECTION|COMPLEMENT|EMPTY",
"max_determinized_states": 20000
}
}
}
```
Thanks.

I have also tried to ask in community [Support here] (https://discuss.elastic.co/t/how-to-check-regex-is-valid-or-not/38854)

**Comment by polyfractal** [comment]
You can use the `validateQuery` api:

```php
$response = $client->indices()->validateQuery([
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [
        'query' => [
            'regexp' => [
                'columnName' => [
                    'value' => '\/([A-Z])\\w+\/g',
                    'flags' => 'INTERSECTION|COMPLEMENT|EMPTY',
                    'max_determinized_states' => 20000
                ]
            ]
        ]
    ]
]);
```

**Comment by polyfractal** [comment]
Closing, feel free to reopen if you have more questions!

**Comment by vrkansagara** [comment]
thanks @polyfractal  it resolved my issued. :+1:
