### ISSUE TITLE
get() call raising exception on missing document

### ISSUE THREAD

**Issue by arski** [elastic/elasticsearch-php#37]
Is this the intended behaviour? I'm asking because if I query ES directly, it would return me a JSON object with exists:false property, but elasticsearch-php seems to throw a 404 error instead.

**Comment by johnarmonk** [comment]
Hello, 

Any way to prevent logging a WARNING with $client->get() and 'ignore' => 404, when the doc id does not exits ?

**Comment by polyfractal** [comment]
@johnarmonk Hmm, unfortunately there is not.  The client still considers it a loggable warning, you're just suppressing the exception with `ignore`

Not sure the best way to handle something like this.  You could implement your own logger that "catches" 404's and suppresses them in the logs.  Anything other than that would require a lot of invasive surgery to omit logging.  Will have to think about it.

**Comment by arayik-yervandyan** [comment]
Hello 

in elasticsearch 2.x  i get this error when i add  'ignore' => 404 parametr 

Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\UnexpectedValueException' with message '"ignore" is not a valid parameter. Allowed parameters are: "fields", "parent", "preference", "realtime", "refresh", "routing", "_source", "_source_exclude", "_source_include", "version", "version_type", "client", "custom", "filter_path"' in elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php on line 245

how can i fix it ?

**Comment by polyfractal** [comment]
Can you paste your complete code snippet?  Sounds like a bug, but I want to verify you are setting the `ignore` parameter correctly :)

What version of ES-PHP are you using?

**Comment by stavarengo** [comment]
Hi @polyfractal.
I'am having the same error. Here is my code.
```
        $client = ClientBuilder::create()->build();
        $params = [
            'index' => 'some_index',
            'type' => 'the_type',
            'id' => 13,
            'ignore' => 404,
            'parent' => 1346,
        ];
        $client->get($params);
```
And this is the version of the PHP elasticsearch library I'am using
```
versions : * v2.1.5
source   : [git] https://github.com/elastic/elasticsearch-php.git c1675245c0a6f789cbb80b3e0b333b9ef521a627
```

**Comment by polyfractal** [comment]
You have to place the `ignore` param inside of the `client` param ([see the docs here](https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_per_request_configuration.html#_ignoring_exceptions)):

Try:

```php
        $client = ClientBuilder::create()->build();
        $params = [
            'index' => 'some_index',
            'type' => 'the_type',
            'id' => 13,
            'client' => [ 
               'ignore' => 404
             ],
            'parent' => 1346,
        ];
        $client->get($params);
```

**Comment by stavarengo** [comment]
You are right.
I could to swear that in the documentation [here](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_per_request_configuration.html) was written the way I did, but no. You're right ;)

**Comment by stavarengo** [comment]
I proposed a file change in the docs here https://github.com/elastic/elasticsearch-php/pull/422 to avoid this misunderstood. 
If you guys think is worth it, please merge.

**Comment by polyfractal** [comment]
++ thanks!  Merged
