### ISSUE TITLE
Mapping for alphabetical order with location

### ISSUE THREAD

**Issue by antondachauer** [elastic/elasticsearch-php#371]
I have a bug in combination with symfony2, distance search and alphabetical sorting. Please take a look on the description on stackoverflow: http://stackoverflow.com/questions/34725089/elasticsearch-mapping-for-alphabetical-order-with-location

Thanks for helping!

**Comment by antondachauer** [comment]
Duplikate of #15986

**Comment by polyfractal** [comment]
Closing, since this is probably better suited to the discussion forums (as mentioned by Clint at the ES repo).  Tickets here should mostly be about issues with or pertaining to the ES-PHP client, while this question seems a more general Elasticsearch question.
