### ISSUE TITLE
how to move one index documents to other index?

### ISSUE THREAD

**Issue by veeruborra** [elastic/elasticsearch-php#379]
I want to move my old index documents to a newly created index in elasticsearch.Iam using scan and scroll type to move my old index documents to new index.But its taking more time to copy from old to new.Is there any easy process to work with it

**Comment by polyfractal** [comment]
Hi, sorry for the delay.

Unfortunately, there is currently no faster way to move documents from one index to another in Elasticsearch.  The only option is to scan/scroll and reindex them.  If you just want a new name, you can use aliases to make a "virtual name" for the index.

**Comment by veeruborra** [comment]
its possible with Elastic dump  [https://github.com/taskrabbit/elasticsearch-dump](url) ..
but it is used only for same mappings type
