### ISSUE TITLE
Flat format for mappings 

### ISSUE THREAD

**Issue by abulhol** [elastic/elasticsearch-php#380]
Hi Zach and Co.,

I am looking for a way to get my index mappings in flat format, so I can present it to users as a table (as Kibana does in the "settings" page (see also my posting here: https://discuss.elastic.co/t/get-mapping-in-flat-format/39855)
Is there any PHP code around that I could use for that? It can probably be done easiest by parsing the mapping JSON recursively and building an associative array along the way.

**Comment by polyfractal** [comment]
Nothing as part of the library, but a snippet like this should get you most of the way there: http://stackoverflow.com/a/9546215

**Comment by abulhol** [comment]
Thanks Zach! I have written something similar in the meantime. Maybe it would be a good addition to the ES PHP client?

**Comment by polyfractal** [comment]
Sorry, I think this would be too opinionated for the library.  The clients have a mandate to remain as low-level and close the API as possible.  Introducing something like this would be a pretty large "opinion" about how things should be done.  I think it belongs in a higher level library built on top of ES-PHP.

Thanks though!
