### ISSUE TITLE
Allow custom curl configuration for entire client

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch-php#382]
Currently, you can configure custom curl options/headers on a per-request basis.  It would be convenient if the same could be specified during client creation, and applied to all requests.

Related #376

**Comment by ride-user** [comment]
+1

**Comment by rayward** [comment]
Would be as simple as allowing the connection params to be configured in the `ClientBuilder` rather than having it hardcoded as an empty array: https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ClientBuilder.php#L428 ?

**Comment by Oliboy50** [comment]
@rayward indeed
So, what is the main issue with that?
