### ISSUE TITLE
$response = $client->index($params); does not return

### ISSUE THREAD

**Issue by cnlopezv** [elastic/elasticsearch-php#393]
I installed, tested and developed some php programs to access elasticsearch in an AWS linux instance and they worked great. Now I need to transfer this development to a local linux machine. I repeated the elastic and php libraries installation, and elastic worked ok, but I cannot have the PHP elastic access working. Testing the simple example programs I see that $response = $client->index($params); just does not return. There is no error message. I retried the composer and php libraries installation but am stuck here. I do not where to look for some hint of the failure....

**Comment by polyfractal** [comment]
When you say "doesn't return", do you mean the indexing command just blocks and the PHP script runs forever?  Does it timeout eventually?  The client (and curl) are configured to timeout after a while, and Elasticsearch will timeout after 60s if there is a problem on the server side.

Is your PHP configured to display errors and warnings?  Can you verify that the libcurl module is installed in your PHP installation.  Also doublecheck SELinux settings, firewalls, etc.

Can you try something like this and paste the output?

```php
$params = [ 
 // set your params here
];

// toggle verbosity
$params['client']['verbose'] = true;

try {
  $response = $client->index($params);
  print_r($response);
catch (Exception $e) {
  $last = $client->transport->getLastConnection()->getLastRequestInfo();
  $last['response']['error'] = [];
  print_r($last);
}
```

**Comment by cnlopezv** [comment]
Thanks for your reply:
after trying your code I get the message:

Curl: Enabled ok
entering response...

it never timeouts.

The full php code is now as follows:

<?php
error_reporting(E_ALL);
echo 'Curl: ', function_exists('curl_version') ? 'Enabled' : 'Disabled';
require 'vendor/autoload.php';
$client = Elasticsearch\ClientBuilder::create()->build();
echo " ok";
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
    'body' => ['testField' => 'abc']
];

// toggle verbosity
$params['client']['verbose'] = true;

try {
  $response = $client->index($params);
  print_r($response);
catch (Exception $e) {
  $last = $client->transport->getLastConnection()->getLastRequestInfo();
  $last['response']['error'] = [];
  print_r($last);
}

?>

php is version 5.5.32 on Centos
What else I can look into?
Regards!
Claudio

**Comment by polyfractal** [comment]
Hmm, I wonder if it's a problem on the server side of things.  Can you tell me about your node and index configuration for Elasticsearch?  Is it a single index, with a few primary shards and two replicas...but hosted on a single machine (e.g. your laptop)?

**Comment by polyfractal** [comment]
Closing due to staleness.  Feel free to reopen if you can provide some more info!

**Comment by morksmail** [comment]
Google lead me here. If $client->index($params); isn't returning, check your logs. I my case it was an out of memory error. Increase the limit and/or make sure the message size is sane.
