### ISSUE TITLE
Is highlight available ?

### ISSUE THREAD

**Issue by Addviso** [elastic/elasticsearch-php#394]
Hello,

Trying to get highlight work in search with no success.
Version is 2.0 on php 5.6

Mapping is : 
```
'_source' => array(
    'enabled' => true
),
'properties' => array(
    'caption' => array(
        'type' => 'string',
        'term_vector' => 'with_positions_offsets',
        'analyzer' => 'french'
    )
)
```

My search is : 
```php
$params['index'] = 'myindex';

$query_params = array(
    'multi_match' => array('query' => $query, 'fields' => array('title', 'caption')),	
);
        
$highlight = array(
    "pre_tags" 	=> array('<mark>'),
    "post_tags" => array('</mark>'),
    'fields' 	=> array('caption' => new \stdClass())
);	

$params['body']['highlight'] = $highlight;
$params['body']['query'] = $query_params;

$client->search($params);
```
Or tried : 

```php
$params['body']['highlight']['pre_tags'] = array('<mark>');
$params['body']['highlight']['post_tags'] = array('</mark>');
$params['body']['highlight']['fields']['caption'] = new \stdClass();
$params['body']['query'] = $query_params;
```

Test in results :
```php
foreach($results as $result) {
    echo $result['_source']['caption'] . '<br>';
}
```
Search in working well, but unable to get searched terms highlighted

**Comment by polyfractal** [comment]
Hmm, are your receiving any errors, or just a lack of highlights?

Can you `print_r($params)` after it is fully constructed?  Sometimes it is easier to spot syntax problems when the whole request is printed together.

You might also try forcing the plain highlighter to see if it is potentially a term vectors problem.  E.g.:

```php
$highlight = array(
    "pre_tags"  => array('<mark>'),
    "post_tags" => array('</mark>'),
    'fields'    => array('caption' => array(
      'force_source' => true
    ))
);  

```

**Comment by Addviso** [comment]
Hello,
I have no errors. 
I did tried  'force_source' => true, with no more success

But I think i've found what I'm not doing right.

If you look at my loop in results, i'm calling : 
$result['_source']['caption']

If I call : 
$result['highlight']['caption'] 

it works. 

Is that correct now ?

Thanks

**Comment by polyfractal** [comment]
Ah, yep.  Highlights go into their own section of the response.
