### ISSUE TITLE
Query on a template

### ISSUE THREAD

**Issue by MaurizioBrioschi** [elastic/elasticsearch-php#402]
### Summary of problem or feature request
I'm trying to make a query on a template but i get **UnexpectedValueException**.
Probably i'm calling the wrong method but i'm not able to find a documentation for this function.

### Code snippet of problem
This is my code:

```php
public function queryTemplate($templateId, array $params)
    {
        return $this->client->getTemplate([
            'id' => $templateId,
            'params' => $params,
        ]);
    }
```
$params is:
```
["query_string"=>"a"]
```
I don't know if the method **getTemplate** is the correct one to get a result using a template but looking into the code seems to have the correct endpoint.

This is the exception i get:
```
Elasticsearch\Common\Exceptions\UnexpectedValueException: "params" is not a valid parameter. Allowed parameters are: "client", "custom", "filter_path"

/srv/exxposed2.vm/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php:245
/srv/exxposed2.vm/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php:97
/srv/exxposed2.vm/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php:1256
```

### System details

- Operating System Ubuntu 
- PHP Version 5.6
- ES-PHP client version 2.0
- Elasticsearch version 2.1

**Comment by polyfractal** [comment]
Ah, yeah, there are a few different types of templates in ES.  Which one are you wanting to use?  I can help you setup the syntax once we figure out which one you need:

- Search Template (where you pre-define a query template then use that at query time: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html)
- Template Query (a query that uses a simple template: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-template-query.html)
- Index templates (a template that controls how new indices are mapped: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html)
- Dynamic templates (a way to dynamically map unknown fields: https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html)

Yaaaay Elasticsearch for having so many templates :)

**Comment by MaurizioBrioschi** [comment]
I have stored a template like index in elasticsearch, to perform a query, so i guess it's a search template.

This is an example of what i store like template:
```
POST /_search/template/test
{
   "query": {
      "match": {
         "namea": "{{query_string}}"
      }
   }
}
```
Thank you very much

**Comment by MaurizioBrioschi** [comment]
I think there is a bug in the code... i will made a pull request...

**Comment by polyfractal** [comment]
Hmm, I don't think those whitelist values are the problem.  The whitelisted values only apply to parameters that go into the URI, while `params` and `id` are body parameters.  You should be able to do this:

```php
$client = Elasticsearch\ClientBuilder::create()->build();

/*
PUT localhost:9200/_search/template/test  <-- `test` is a URI parameter
{
  "query" : { .. }  <-- Anything in the body goes in `body`
}
*/

$response = $client->putTemplate([
    'id' => 'test',  // URI parameter
    'body' => [
        'query' => [
            'match' => [
                'name' => '{{query_string}}'
            ]
        ]
    ]
]);

/*
GET localhost:9200/_search/template  <-- No URI parameters
{
   "id": "test",  <-- Body parameters
   "params": { .. }
}
*/
$response = $client->searchTemplate([
    'body' => [
        'id' => 'test',
        'params' => [
            'query_string' => 'foo'
        ]
    ]
]);
```

I just ran that locally and it works fine.  The key is that anything in the JSON body (the `query` in the first PUT Template request, and `id`/`params` in the Search Template request) need to be encoded inside the `body` array of your request.  

The PHP api is a direct translation from JSON into PHP arrays, so anything in the body needs to be in the `body`

**Comment by MaurizioBrioschi** [comment]
Yes it works... 
i have been stupid to not have thought about it :)

Thanks

**Comment by polyfractal** [comment]
No worries, it can be confusing at times.  When I started to write out the example I made the exact same mistake :)

**Comment by MaurizioBrioschi** [comment]
So probably could be better to add a documentation example for this.
