### ISSUE TITLE
Severity: Error --> Maximum execution time of 180 seconds exceeded

### ISSUE THREAD

**Issue by vrkansagara** [elastic/elasticsearch-php#403]
### Severity: Error --> Maximum execution time of 180 seconds exceeded

I was doing bulk update with a large number of records. After waiting a long time I got following error.
```
Severity: Error --> Maximum execution time of 180 seconds exceeded   <<DIR_PATH>>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Serializers/SmartSerializer.php 30
```
This is serious problem while using this library with huge amount of data so please can you make this issue prioritiese. 

### System details

- Operating System - ` Red Hat Enterprise Linux Server release 7 `
- PHP Version - `PHP 7.0`
- ES-PHP client version - `"elasticsearch/elasticsearch" : "~2.0"`
- Elasticsearch version `2.1`

In advance thank you.

**Comment by polyfractal** [comment]
This is a limitation imposed by your PHP installation/configuration.  Check your `php.ini` to make sure `max_execution_time` is long enough for your scripts to run to completion.  If you are loading/processing large amounts of data (and large JSON blobs) 180 seconds is likely too small for you.

**Comment by vrkansagara** [comment]
Hello @polyfractal .

Thanks for the quick replay.
I will get back once get data. thanks again.

**Comment by polyfractal** [comment]
Closing, feel free to reopen if you have more questions.
