### ISSUE TITLE
nFatal error: Uncaught exception when adding, editing or selecting indice from Drupal

### ISSUE THREAD

**Issue by pribeh** [elastic/elasticsearch-php#410]
### Summary of problem or feature request

I'm having trouble adding, editing, and selecting indices from Drupal using the ElasticSearch Connector module which employs the ES-PHP library (via Composer/Guzzle). I can check that it's running (edit or update) fine from the command line, it still indexes and recalls data through Drupal fine, but whenever I attempt to add, edit or select an index (from within Drupal) I get a 500. When I check HHVM's error log I see Fatal Error: Uncaught exception (see full error below). [I also get a warning within Drupal regarding an invalid argument on line 221 of CurlHandle.php when requesting results but I'm not sure if that is at all related.]

I suspect this has to do with my server configuration (HHVM/NGINX) hence why I'm posting about this here. Looking through the issue queue, I have a feeling someone here may have come across a similar issue using the library and might be able to point me in the right direction to isolate what's wrong with my config or just point out a dumb mistake I've made. I'm new to ES and not a sys-admin. I'm running ElasticSearch 1.7.4 locally on a Linode VPS. 

Here's the error from the log:
```php
\nFatal error: Uncaught exception 'Elasticsearch\\Common\\Exceptions\\Curl\\OperationTimeoutException' with message 'Connection timed out after 3001 milliseconds' in /usr/share/nginx/html/drupal/sites/all/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/AbstractConnection.php:325\nStack trace:\n#0 /usr/share/nginx/html/drupal/sites/all/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(319): Elasticsearch\\Connections\\AbstractConnection->throwCurlException()\n#1 /usr/share/nginx/html/drupal/sites/all/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(206): Elasticsearch\\Connections\\GuzzleConnection->processCurlError()\n#2 /usr/share/nginx/html/drupal/sites/all/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\\Connections\\GuzzleConnection->sendRequest()\n#3 /usr/share/nginx/html/drupal/sites/all/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\\Connections\\GuzzleConnection->performRequest()\n#4 /usr/share/nginx/html/drupal/sites/all/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\\Transport->performRequest()\n#5 /usr/share/nginx/html/drupal/sites/all/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(258): Elasticsearch\\Endpoints\\AbstractEndpoint->performRequest()\n#6 /usr/share/nginx/html/drupal/sites/all/modules/elasticsearch_connector/elasticsearch_connector.module(239): Elasticsearch\\Namespaces\\IndicesNamespace->stats()\n#7 /usr/share/nginx/html/drupal/includes/menu.inc(600): elasticsearch_connector_index_load()\n#8 /usr/share/nginx/html/drupal/includes/menu.inc(771): _menu_load_objects()\n#9 /usr/share/nginx/html/drupal/includes/menu.inc(482): _menu_translate()\n#10 /usr/share/nginx/html/drupal/includes/menu.inc(1765): menu_get_item()\n#11 /usr/share/nginx/html/drupal/includes/menu.inc(1780): menu_get_custom_theme()\n#12 /usr/share/nginx/html/drupal/includes/common.inc(5259): menu_set_custom_theme()\n#13 /usr/share/nginx/html/drupal/includes/bootstrap.inc(2266): _drupal_bootstrap_full()\n#14 /usr/share/nginx/html/drupal/index.php(20): drupal_bootstrap()\n#15 {main}
```

My setup:

- Ubuntu 14.04
- Drupal 7.43
- PHP 5.6
- HHVM 3.13
- ElasticSearch 1.7.4
- ES PHP 2.0
- ElasticSearch Connector (Drupal module) 7 1.0-alpha9
- NGINX 1.8
- MariaDB

My nginx site conf file:

```
server {
    listen   80;
    server_name  pomofo.com;
    access_log  /var/log/nginx/localhost.access.log;
    error_log /var/log/nginx/error.log;
    include hhvm.conf;
    root /usr/share/nginx/html/drupal;
    index index.html index.htm index.php;

## serve imagecache files directly or redirect to drupal if they do not exist.
    location ~* files/styles {
      access_log off;
      expires 30d;
      try_files $uri @drupal;
    }

## serve imagecache files directly or redirect to drupal if they do not exist.
    location ~* ^.+.(xsl|xml)$ {
      access_log off;
      expires 1d;
      try_files $uri @drupal;
    }

## Default location
    location / {
        try_files $uri $uri/ @drupal;
        index  index.php;
    }

    location @drupal {
        rewrite ^/(.*)$ /index.php?q=$1 last;
    }

## Images and static content is treated different
    location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico|xml)$ {
      access_log        off;
      expires           30d;
    }

## Parse all .php file in the /var/www directory
    location ~ \.(hh|php)$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_pass unix:/var/run/hhvm/hhvm.sock;
        fastcgi_index  index.php;
	#rewrite ^ http://www.google.com?q=$document_root$fastcgi_script_name$query_string;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  SCRIPT_NAME      $fastcgi_script_name;
        fastcgi_param  QUERY_STRING     $query_string;
        fastcgi_param  REQUEST_METHOD   $request_method;
        fastcgi_param  CONTENT_TYPE     $content_type;
        fastcgi_param  CONTENT_LENGTH   $content_length;
        fastcgi_intercept_errors        on;
        fastcgi_ignore_client_abort     off;
        fastcgi_connect_timeout 60;
        fastcgi_send_timeout 180;
        fastcgi_read_timeout 180;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }

## Disable viewing .htaccess & .htpassword
    location ~ /\.ht {
        deny  all;
    }
}

upstream backend {
        server 127.0.0.1:9000;
}
```

Thanks for any help you can provide!

**Comment by polyfractal** [comment]
Hmm.  I'm not too familiar with the Drupal connector.  From the ES-PHP client perspective, it looks like it is timing out.  That could be caused by a bad configuration for the host or port, or potentially an issue with firewalls/iptables/etc.

But since you say indexing or retrieving documents works fine... I'm not sure.  If those work, editing/creating/deleting whole indices should work too.

- Can you paste your drupal ES configuration?
- What port is Elasticsearch running on?

@nignatov any thoughts?  Does the drupal connector manage indices differently from docs?

**Comment by pribeh** [comment]
@polyfractal Thanks for looking at this. @nignatov has already been so helpful. 

The port is 9200. My initial thought was it has to be a port/host issue but it does seem weird then that both indexing and retrieving documents are working. 

Sorry, by Drupal ES config do you mean my settings? Or do you mean a configuration that either composer or ES Connector setup to interface with ES PHP?

**Comment by polyfractal** [comment]
Ah, sorry, I meant the ES Connector setup.  Wanted to verify the Elasticsearch host/port settings, and maybe see if there is something else contributing.

Can the ES Connector enable the debug log for the client?  Perhaps we can see what's going on there.  The timeout could potentially be server-related...there are certain operations that can stall/timeout, usually related to not meeting quorums (which I doubt is the case here, but we can check).

Another thought:  Elasticsearch 2.0+ only binds to localhost now, so if your client is connecting through an IP/host rather than the loopback (even if it points to localhost) that could potentially cause a problem

**Comment by pribeh** [comment]
I'm using ES 1.7. Sorry, what is (a) loopback?

I've attached a screen of the UI config from ESC.

![screen shot 2016-04-11 at 2 01 50 pm](https://cloud.githubusercontent.com/assets/690883/14437180/019e0922-ffee-11e5-8d80-953d810c7d81.png)

Below is a readout of Drupal devel debugger output which I'm not sure how to read.

![screen shot 2016-04-11 at 2 01 21 pm](https://cloud.githubusercontent.com/assets/690883/14437194/16bf04aa-ffee-11e5-99ef-e8eaf23adf46.png)

**Comment by nignatov** [comment]
@pribeh did you try to stop the Elasticsearch Connector devel module?
Actually this module override the connector, so it can be that this is the problem. 
Elasticsearch Connector devel module is a quite old one because of luck of time to keep it up to date.

**Comment by pribeh** [comment]
@nignatov Thanks for pointing that out. I just uninstalled it but the issue persists.

**Comment by pribeh** [comment]
Does anyone know if running HHVM in fastcgi mode and using fastcgi_pass unix:/var/run/hhvm/hhvm.sock could have anything to do with this?

@nignatov @polyfractal I forgot to share but this is what I see when I got to admin/config/elasticsearch-connector/clusters/pomo/indices. Obviously, there should be some indices listed here.

![screen shot 2016-04-11 at 2 51 47 pm](https://cloud.githubusercontent.com/assets/690883/14438673/3acd6510-fff5-11e5-9c41-fe71be50c81a.png)

**Comment by polyfractal** [comment]
Hm, maybe?  It appears that [HHVM doesn't support](https://github.com/facebook/hhvm/issues/4374) curl opt 91 (`CURLOPT_DNS_USE_GLOBAL_CACHE`) but your version of the drupal connector toggles it on:  https://github.com/nodespark/elasticsearch_connector/blob/7.x-1.x/elasticsearch_connector.module#L797

Is there a way you can disable that setting?  I'm unsure if that's actually the problem, but it'd be worth checking.

As a note, I'm not aware of the status under HHVM.  The tests are currently failing from what I think is a test-related error (e.g. something in the test runner, not the actual library) but I haven't had a chance to investigate.  So atm, I'd say that any HHVM usage is experimental and untested :)

**Comment by pribeh** [comment]
@polyfractal Thanks for finding that issue about curl opt 91. I don't know why I couldn't find it. I commented out line 797 line in ES_Connector.module and the warning went away! But I still can't select the index. So it's possible that it might only be responsible for the warning and have nothing to do with accessing/editing the indices. I'm not sure what to try next yet but I'll continue to tinker.

In regards to HHVM, I'm seeing more and more php apps being migrated to HHVM so I'm trying to ride the wave ;). I realize it's not the most supported interpreter but the performance/scaling benefit is just so huge and thus far works with almost everything else in my drupal app. Together, elasticsearch, php and hhvm seem to make so much sense.

**Comment by pribeh** [comment]
Okay, so after commenting out CURLOPT_DNS_USE_GLOBAL_CACHE and attempting to access/select/modify an indice through Drupal the fatal error is gone from the error log. This is what shows up now:

<code>Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
Connection timed out after 3001 milliseconds
</code>

**Comment by pribeh** [comment]
Figured it out! The warning definitely pertains to CURLOPT_DNS_USE_GLOBAL_CACHE. But neither the warning, or my config, had anything to do with the timeout and my inability to select/edit indices from within Drupal. I think what happened was when I migrated the data in elasticsearch from my local environment to the live server environment that the indices got corrupt somehow. I'm still not sure how because once I deleted them the real problem went away. Having removed the original indices, I can now add/select/remove new ones no problem from within Drupal. Thanks for your help guys!

**Comment by polyfractal** [comment]
Interesting, good work debugging it!  I'm really not sure what would have caused that timeout on the ES server side.  Corruption issues tend to just throw an exception.  You could try hunting through your ES logs and see if there is anything interesting in there.  Perhaps there was some strange quorum issue or something.

Regardless, glad you got it working! :)

Feel free to reopen or add a new ticket if you run into anymore problems!
