### ISSUE TITLE
Reindexing your data

### ISSUE THREAD

**Issue by neok** [elastic/elasticsearch-php#411]
Looking for method reindex() to accomplish next task 
https://www.elastic.co/blog/changing-mapping-with-zero-downtime#_reindexing_your_data

Are you planning to do this feature?

Or we need to use `bulk` + `scrollsearch` instead?

**Comment by polyfractal** [comment]
I don't have any immediate plans to implement this as a helper.  You could emulate it by using `bulk + scroll` as you mentioned, or use the [SearchResponseIterator and SearchHitsIterator Helpers](https://github.com/elastic/elasticsearch-php/tree/master/src/Elasticsearch/Helper/Iterators) which would make it bit cleaner.

Note: ES 2.3 and 5.0 will have the new `_reindex` API.  I'll be adding that to the client soon: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

**Comment by neok** [comment]
@polyfractal thank you for answer

**Comment by Nexucis** [comment]
I have developped a reindex feature for a personal project. Thus I would like to know whether I can do a pull request to share with you my work on this feature.

**Comment by neok** [comment]
@Nexucis it would be great

**Comment by Nexucis** [comment]
Thanks @neok, I will do my best as soon as a member of elasticsearch will give me a go or not :)

**Comment by polyfractal** [comment]
Hi, sorry for the delay!

Is the reindex functionality self-contained?  I can't add it to the core client, but if it is self-contained and just relies on the features in the core client, we could think about adding it to the `Helpers` namespace.

Go ahead and send a PR and we can take a look :)

**Comment by Nexucis** [comment]
Hi,
Thanks for your answer @polyfractal ! . I'm not shure that my functionality is self-contained. But it will be very easy to remove this feature ! .

I have send a PR and I hope I was doing right !

**Comment by nikhiltri** [comment]
Did this pull request over come through?

**Comment by Nexucis** [comment]
well the pull request is right [here](https://github.com/elastic/elasticsearch-php/pull/418). But as you can see, It's been a while, and maybe, it needs an update
