### ISSUE TITLE
org.elasticsearch.client.transport.NoNodeAvailableException

### ISSUE THREAD

**Issue by s-dhiman** [elastic/elasticsearch-php#413]
### Summary of problem or feature request

org.elasticsearch.client.transport.NoNodeAvailableException 

I tried to run:  
<b> $ curl http://localhost:9200 </b>
response is below:
{
  "name" : "Executioner",
  "cluster_name" : "elasticsearch_sdhiman",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
 
looks here I am missing <b>Status :200 </b>

which seems to cause below exception

Here is stack trace 

2016-04-22 13:03:32,090 [localhost-startStop-1] INFO  ehcache.GrailsEhCacheManagerFactoryBean  - Shutting down EHCache CacheManager
| Error 2016-04-22 13:03:32,092 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is org.elasticsearch.client.transport.NoNodeAvailableException: No node available
Message: Error creating bean with name 'searchableClassMappingConfigurator': Invocation of init method failed; nested exception is org.elasticsearch.client.transport.NoNodeAvailableException: No node available
    Line | Method
->>  262 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by NoNodeAvailableException: No node available
->>  196 | execute   in org.elasticsearch.client.transport.TransportClientNodesService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     73 | execute   in org.elasticsearch.client.transport.support.InternalTransportClusterAdminClient
|    118 | health .  in org.elasticsearch.client.support.AbstractClusterAdminClient
|    124 | installMappings in org.grails.plugins.elasticsearch.mapping.SearchableClassMappingConfigurator
|     51 | configureAndInstallMappings in     ''
|    262 | run       in java.util.concurrent.FutureTask
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
| Error Forked Grails VM exited with error

- Operating System
- PHP Version
- ES-PHP client version
- Elasticsearch version

**Comment by polyfractal** [comment]
Hi.  This looks like a a Java/Grails question?  That would be better answered at [Elasticsearch discussion forums](https://discuss.elastic.co/), or if you think it is a bug, the [main Elasticsearch repository](https://github.com/elastic/elasticsearch).

This repository is for the PHP client and related questions/problems.  :)
