### ISSUE TITLE
Lot of connections in timewait state

### ISSUE THREAD

**Issue by agustincastanio** [elastic/elasticsearch-php#415]
### Summary of problem or feature request
Hi, 
I am getting a lot of connections in "timewait" state and I don't the see the keepalive timer on a Symfony project in a production environment.
I am using the script below to debug this problem. When executed several times (from command line or nginx + php-fpm), I get:

[root@WS4 ~]# php /home/untitled/src/test.php

[root@WS4 ~]# ss -natue | grep 127.0.0.1:9200 | wc -l
486

[root@WS4 ~]# ss -natue | grep 127.0.0.1:920
...
tcp    TIME-WAIT  0      0      127.0.0.1:6963               127.0.0.1:9200                timer:(timewait,,0) ino:0 sk:ffff880726102b00
tcp    TIME-WAIT  0      0      127.0.0.1:6836               127.0.0.1:9200                timer:(timewait,,0) ino:0 sk:ffff88088bef6300
tcp    TIME-WAIT  0      0      127.0.0.1:7282               127.0.0.1:9200                timer:(timewait,38sec,0) ino:0 sk:ffff880726e3eb00
tcp    TIME-WAIT  0      0      127.0.0.1:7235               127.0.0.1:9200                timer:(timewait,30sec,0) ino:0 sk:ffff880726199000
tcp    TIME-WAIT  0      0      127.0.0.1:7087               127.0.0.1:9200                timer:(timewait,11sec,0) ino:0 sk:ffff88062fbc8d00
tcp    TIME-WAIT  0      0      127.0.0.1:7172               127.0.0.1:9200                timer:(timewait,19sec,0) ino:0 sk:ffff8806208b1600
tcp    TIME-WAIT  0      0      127.0.0.1:6862               127.0.0.1:9200                timer:(timewait,,0) ino:0 sk:ffff880653f78500

Could you help me with this, please?

### Code snippet of problem

I am using the example taken from the project documentation to index and retrieve data from elasticsearch.
Composer.json is updated with:

"require": {
	...
	"elasticsearch/elasticsearch": "~2.0"
}

And the script test.php is:
```php
<?php

use Elasticsearch\ClientBuilder;

require '/home/untitled/vendor/autoload.php';

$client = ClientBuilder::create()->build();

$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
    'body' => ['testField' => 'abc']
];

$response = $client->index($params);
print_r($response);

$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id'
];

$response = $client->get($params);
print_r($response);

$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [
        'query' => [
            'match' => [
                'testField' => 'abc'
            ]
        ]
    ]
];

$response = $client->search($params);
print_r($response);

```

### System details
Everything is using its defaults configuration, no tunning:

- Operating System: CentOS 6.5 / CentOS 7.2.1511
- PHP Version: 5.4.45 / 5.6.20
- ES-PHP client version: 2.1.5
- Elasticsearch version: 1.4.4 / 2.3.1

**Comment by polyfractal** [comment]
Is this a problem?  TIME_WAIT is a natural part of the TCP process.

But, that said, are you running anything else on the local server?  Kibana, plugins, marvel, sense, etc?  All of those will open connections to Elasticsearch.  For example, on my server I had 143 time-wait connections.  After shutting down Kibana, it dropped to 0.

The ES-PHP client only opens one connection per-node.  So unless you're re-instantiating the client many times, there really shouldn't be many closing connections from ES-PHP.

**Comment by agustincastanio** [comment]
You are right about that. 
The problem comes when the production platform gets busy and TCP connections start to pile up (10k connections when receiving 110 request/sec).
Also there is an extra delay on the response because TCP handshake.

On the local server I am running ES only. On the production servers: ES, Nginx and PHP-FPM with an static pool of 32 threads. Being PHP the only one able to connect to ES.

I rechecked the app code and client is instantiated only once per node.

Please let me know if there is any more information I could bring to the case.

**Comment by polyfractal** [comment]
Ah, I see.  Hmm.  I'm not sure there is much to be done from the PHP side.  

The client already uses keep-alive connections by default.  Unfortunately, since PHP is a shared-nothing architecture, there's no way to maintain a connection pool between script invocations.  So each page load that re-invokes PHP will cause a new client to be instantiated, and thus create a new connection.  Those will linger until the OS recycles them, and at 100 req/s, you'll build up a fair number waiting to be recycled.

Unless this is a long-running script and I'm mistaken?  I saw you mention symfony, so I'm assuming the client is being used to serve up parts of a web-page?

You could play with the recycle/reuse settings for the TCP stack, but I don't have any experience with that.

**Comment by agustincastanio** [comment]
Your explanation makes sense.
I am already controlling the TCP connections with sysctl on the server side:

net.ipv4.ip_local_port_range=1024 65535
net.netfilter.nf_conntrack_tcp_timeout_time_wait=1
net.ipv4.tcp_tw_reuse=1

So I guess there is nothing more I can do.

Thanks for your help.

**Comment by polyfractal** [comment]
Sorry :(  

I really wish there was a way to share a connection pool in PHP.  I've toyed around with the idea of writing a PHP extension which the client could leverage, but I doubt many people would actually use it (and it opens up a whole can of worms with segfaults, etc).

Feel free to reopen if you think it may be something else.  It's possible there is a bug in the code causing extra connections.  I'll run a few tests on my end to make sure.

**Comment by agustincastanio** [comment]
Thanks again, Zachary.
It would be great to see the results of your tests.
