### ISSUE TITLE
2.3 support

### ISSUE THREAD

**Issue by Tezd** [elastic/elasticsearch-php#419]
### Summary of problem or feature request

Looking forward for support of 2.3. Since there is new functionality introduced like [_update_by_query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) which can help reducing data flow between application and Elasticsearch database.
Is there any plans on releasing support for 2.3 functionality? If no would you accept pull request?

**Comment by polyfractal** [comment]
Absolutely!  I just haven't had a chance to update the client yet.  I'll try to get to it this week, but PRs are certainly welcome if you want to contribute it instead!

Thanks (and sorry for the delay) :)

**Comment by Tezd** [comment]
Thank you for your reply. I would be able to get to it also this week :) Will post here on updates.

**Comment by polyfractal** [comment]
Sounds good! Let me know if you run into any troubles.

The REST-api-spec for update_by_query may be helpful for you too (it lists the endpoint, available parameters to whitelist, etc): https://github.com/elastic/elasticsearch/blob/2.3/rest-api-spec/src/main/resources/rest-api-spec/api/update_by_query.json

**Comment by Tezd** [comment]
Hi again. I created [pull request](https://github.com/elastic/elasticsearch-php/pull/420) for 2.3 support. There are a lot of changes to Endpoint parameters. Some endpoint are no longer supported so I will post here about them:
- [Delete By Query](https://www.elastic.co/guide/en/elasticsearch/plugins/current/delete-by-query-usage.html)
- [Cluster Nodes Shutdown](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/cluster-nodes-shutdown.html)
- [Seal](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/seal.html)
- [Indicies Status](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-status.html)
- [Mapping Delete](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/indices-delete-mapping.html)
- [More Like This](
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-more-like-this.html)

I want to know whether I should remove delete_by_query since it is no longer part of API and distributed as plugin?

**Comment by SergeyShcherbin** [comment]
@polyfractal can you please tag my pull request?

**Comment by polyfractal** [comment]
Will tag and release in just a sec

**Comment by polyfractal** [comment]
Tagged as `2.2.0`.

A request if you send another PR in the future:  let's keep the formatting changes separate from the "functional" changes.  The size of the PR made it really difficult to review... most of the changes were small formatting changes, but real changes that needed reviewing were hidden amongst the formatting.  And the formatting would re-arrange/confuse the diffs because stuff was reordered.

Which meant I had to go through line by line and check each change closely.  :(

Next time we can just put the formatting in a secondary PR and it'll be a lot easier to review.  Thanks!
