### ISSUE TITLE
mget API not requiring docs key

### ISSUE THREAD

**Issue by raheelkhan** [elastic/elasticsearch-php#424]
### Unable to use mget API to get multiple documents at once

[](https://www.elastic.co/guide/en/elasticsearch/guide/current/_retrieving_multiple_documents.html)

How can i use mget feature in PHP client. It seems that it does not take `docs` key as stated by the elastic search reference.

```php
$params = [
    'docs' => [
        [
            'index' => 'my_deezer',
            'type' => 'song',
            'id' => 1
        ],
        [
            'index' => 'my_deezer',
            'type' => 'song',
            'id' => 2
        ]
    ]
];

try {
   $response = $client->mget($params); 
    print_r($response);
} catch (Exception $e) {
    echo $e->getMessage();
}


```

### System details

- Operating System - Ubuntu 14.04
- PHP Version - 7
- ES-PHP client version - 2.0
- Elasticsearch version - 1.7.x

**Comment by polyfractal** [comment]
Sorry for the delay, I was on vacation and then a work trip. :)

You'll need to nest the `docs` param inside of the `body` param (because it goes into the request body):

```php
$params = [
    'body' => [    // <---- Here
      'docs' => [
          [
              'index' => 'my_deezer',
              'type' => 'song',
              'id' => 1
          ],
          [
            'index' => 'my_deezer',
            'type' => 'song',
            'id' => 2
          ]
       ]
    ]
];

try {
   $response = $client->mget($params); 
    print_r($response);
} catch (Exception $e) {
    echo $e->getMessage();
}
```

**Comment by rickshawhobo** [comment]
Hi @polyfractal I'm sorry for resurrecting this thread but I could not get to work as you have written. As it turns out there is an error in your code. When I changed 
```
index
type
id
``` 
to 

```
_index
_type
_id
``` 
it worked.

Can you confirm this is the case, if so could you correct this answer for future googlers?

**Comment by polyfractal** [comment]
@rickshawhobo urgh, you're correct, that was a typo on my part.  I'll edit my comment
