### ISSUE TITLE
no alive nodes found in your cluster using laravel  with homestead

### ISSUE THREAD

**Issue by GQwebsites** [elastic/elasticsearch-php#425]
### Summary of problem or feature request

 I keep getting a no alive nodes found in your cluster message when trying to index or search for documents 

### 
```php
            $hosts = ['http://localhost:9200/'];
		$client = Clientbuilder::create()->setHosts($hosts)->build();
	

		$user = User::find(61);

		$params = [
	            'index' => 'twitter',
	            'type' => 'users',
	            'id' => $user->id,
	            'body' => [
	            	'name' =>$user->username,
	            	'email' =>$user->email
	            ]
	        ];

	        $response = $client->index($params);
	        print_r($response);
```

### System details

- Operating System Mac OS 10.9.5
- PHP Version PHP 5.4.45
- ES-PHP client version
- Elasticsearch version v2.2.0

**Comment by polyfractal** [comment]
Sorry for the delay, was getting married and then a work trip :)

I'm assuming the script is running inside the Homestead vagrant box, not from the cli on your native machine?  Can you confirm that ES is accessible from localhost:9200 via a curl?

`$ curl -XGET localhost:9200`

**Comment by GQwebsites** [comment]
It's not accessible  no sever found , I installed it using composer on a laravel project

**Comment by dapangxiaozi** [comment]
I have also experienced this problem，most of this problem is caused by curl client node timeout.please check your  elasticsearch whether is running or is accessible. if the es is running, run the command：netstat -lntp,  you will see the process of  binding 9200 port

**Comment by polyfractal** [comment]
> It's not accessible  no sever found , I installed it using composer on a laravel project

Sorry, this isn't really enough detail for me to help. :(  Do you mean Elasticsearch isn't running?  It's running but you cannot connect via curl?  It's running, you can connect via curl, but not by the client?  Is the script running inside the vagrant instance, or outside the instance?  If it's outside the vagrant instance, you'll have to setup port forwarding to expose the Elasticsearch port to the "outside world".

++ to the command that @dapangxiaozi suggested too

**Comment by GQwebsites** [comment]
How do I check if running, I can't connect via  curl command

**Comment by polyfractal** [comment]
To be honest, I'm not super familiar with Homestead.  So bear with me :)  I'm assuming you installed Homestead with something like this?

```bash
$ composer require laravel/homestead --dev
$ php vendor/bin/homestead make
```

Once Homestead was installed, where did you install Elasticsearch?  Did you do something like:

```bash
# Login into vagrant box
$ vagrant ssh

# Install elasticsearch inside vagrant
...
...
```

?  If you installed Elasticsearch inside of the vagrant machine, you'll need to forward the ports.  I believe this is done in the `homestead.yaml` config file, [based on the documentation](https://laravel.com/docs/5.1/homestead#installation-and-setup):

```
ports:
    - send: 9200
      to: 9200
      protocol: tcp
```

Or did you install Elasticsearch directly on your machine (without running the `vagrant ssh` command)?  If you did this, you'll still have to forward ports but we may also need to modify Elasticsearch's config to allow non-localhost connections.

**Comment by GQwebsites** [comment]
I installed it in my vagrant machine running the vagrant ssh command and
via composer just like the directions on your github
https://github.com/elastic/elasticsearch-php

I forwarded the ports like you said and still get this error : curl: (7)
Failed to connect to localhost port 9200: Connection refused

**Comment by polyfractal** [comment]
Ah, sorry, that explains my confusion.

The Homestead vagrant instance is a pre-rolled image that includes: Laravel, Nginx, PHP 5.6, MySQL, Postgres, Redis, Memcached. You'll need to download and install Elasticsearch separately, you can download it here: https://www.elastic.co/downloads/elasticsearch

So I'd ssh into the vagrant box, download ES and start it up.  If you want to install the deb package and auto-start the service, it would look something like this ([based on the docs here](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html)):

```bash
$ vagrant ssh
$ wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
$ echo "deb https://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
$ sudo apt-get update && sudo apt-get install elasticsearch
$ sudo service elasticsearch start
$ sudo update-rc.d elasticsearch defaults 95 10
```

You should be able to connect locally then:

```bash
curl -XGET localhost:9200/
```

What you installed from this repo is just the client.  It's used to talk to Elasticsearch via PHP... it doesn't provide the actual server, which is why you need to install it separately.

Sorry for my confusion!

**Comment by GQwebsites** [comment]
Thanks, I installed it again separately on my local machine got it working with curl -XGET localhost:9200/.

But i still keep getting this error: No alive nodes found in your cluster when trying to search in larvavel 

I also noticed this error along with a long list of other info that came back in my view:
Failed to connect to localhost port 9200: Connection refused', 'errno' => '7

I indexed the example posted on elastic/elasticsearch github page , was able topmost and  retrieve it using the curl command.

My problem is i can't seem to get elastic search to cooperate with Laravel.

here's the code i used to try to search the example content: 
  
`
        

        $client = Elasticsearch\Clientbuilder::create()->build();

	    $results = $client->search([
		    "index" => "twitter",
		    "type" => "user",
		    "body" => [
		        "query" => [
		            "match" => [
		                "name" => "kimchy"
		            ]
		        ]
		    ]
		]);

		var_dump($results);
`

**Comment by GQwebsites** [comment]
OK finally got it to work! 

I followed the steps provided to install it inside my virtual machine 

<pre>$ vagrant ssh
$ wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch <span class="pl-k">|</span> sudo apt-key add -
$ <span class="pl-c1">echo</span> <span class="pl-s"><span class="pl-pds">"</span>deb https://packages.elastic.co/elasticsearch/2.x/debian stable main<span class="pl-pds">"</span></span> <span class="pl-k">|</span> sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
$ sudo apt-get update <span class="pl-k">&amp;&amp;</span> sudo apt-get install elasticsearch
$ sudo service elasticsearch start
$ sudo update-rc.d elasticsearch defaults 95 10</pre>

the only issue i had was I kept getting set JAVA_HOME path when trying to 
` sudo service elastic search start`

solution for me was to just instal the java sdk
```
sudo apt-add-repository ppa:webupd8team/java 
sudo apt-get update
sudo apt-get install oracle-java8-installer
``` 

i tested it by running
`curl -XGET localhost:9200/`
inside my virtual machine

then inserted some test data
```
curl -XPUT 'http://localhost:9200/twitter/user/kimchy?pretty' -d '{ "name" : "Shay Banon" }'

curl -XPUT 'http://localhost:9200/twitter/tweet/1?pretty' -d '
{
    "user": "kimchy",
    "post_date": "2009-11-15T13:12:00",
    "message": "Trying out Elasticsearch, so far so good?"
}'

curl -XPUT 'http://localhost:9200/twitter/tweet/2?pretty' -d '
{
    "user": "kimchy",
    "post_date": "2009-11-15T14:12:12",
    "message": "Another tweet, will it be indexed?"
}'
```

then pulled that data using my larval app
```
$client = Elasticsearch\Clientbuilder::create()->build();

	    $results = [
		    "index" => "twitter",
		    "type" => "tweet",
		    "body" => [
		        "query" => [
		            "match" => [
		                "user" => "kimchy"
		            ]
		        ]
		    ]
		];

		$response = $client->search($results);
		 print_r($response);
```
i also forwarded the ports in homestead.yaml file, although I'm not sure if that's necessary , But i did it anyway and it works fine
ports:
```
    - send: 9200
      to: 9200
      protocol: tcp
```

everything works fine now!
