### ISSUE TITLE
Password containing a hash sign breaks  connection

### ISSUE THREAD

**Issue by uprise10** [elastic/elasticsearch-php#428]
### Summary of problem or feature request

When using a password, containing a hash sign ( # ), PHP will give a fatal error when creating a connection. The error: 
>Fatal error: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /var/www/app/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51

Changing the password into a alphanumeric one, just works fine. I didn't test any other special characters, but apparently something is going wrong :-)

### Code snippet of problem
```php
<?php

require 'vendor/autoload.php';

$hosts = [
	'https://test:8pJMTX2HBTs#KZXft@connection_url:12345'
];

$client = Elasticsearch\ClientBuilder::create()
	->setHosts($hosts)
	->build();


$params = [
	'index' => 'my_index'
];

$response = $client->indices()->create($params);
print_r($response);
```

### System details
- Operating System: Ubuntu on a vagrant machine
- PHP Version: 7.0.5
- ES-PHP client version: 2.2.0
- Elasticsearch version: 2.1.2 (using Objectrocket.com)

**Comment by polyfractal** [comment]
I suspect this is related to PHP's `parse_url()` method, I've seen [similar behavior in the past](https://github.com/elastic/elasticsearch-php/issues/376#issuecomment-172593919).  If you add a trailing slash (`/`) to the host, does that fix the problem?

If yes, I think I'll add a check which internally adds a slash if missing, since that seemed to fix the quirks with the last incident.

**Comment by uprise10** [comment]
Unfortunetaly, adding the trailingslash doesn't solve it.

**Comment by polyfractal** [comment]
Hrm, ok.  I'll investigate more deeply :)

**Comment by anand-sharma** [comment]
Does the extended host configuration resolve this issue. Please check
https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_configuration.html#_extended_host_configuration

**Comment by polyfractal** [comment]
Extended host config should indeed fix this now.  Closing, feel free to reopen if you still have issues! :)

**Comment by ravenbyron** [comment]
I think this is probably related to  https://bugs.php.net/bug.php?id=73754, thought I would post here to help googlers

**Comment by paulleephp** [comment]
@ravenbyron thank you
