### ISSUE TITLE
Client Handler not replaceable (cURL hardcoded)

### ISSUE THREAD

**Issue by lifeofguenter** [elastic/elasticsearch-php#429]
Certain hardcoded values make it currently impossible to replace the http handler.

Example: https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Connections/Connection.php#L112

This means, when using the RingPHP `StreamHandler` it won't set the http-auth creds correctly.

**Comment by polyfractal** [comment]
Yep, this would cause a problem (and with any user-defined handler).  Will investigate a better alternative, I honestly don't use the stream wrappers much... need to play around with them for a few minutes first :)

**Comment by ezimuel** [comment]
This is something that I'm completely refactoring. I'll release it for the next major (8.0)
