### ISSUE TITLE
Scroll api not working with latest stable version of elasticsearch

### ISSUE THREAD

**Issue by incodemode** [elastic/elasticsearch-php#433]
Hello.

In summary, the need to support scroll api with size parameter because scroll and size are not in the whitelist right now.

For example, this should work:
```php
$query = array(
            'body'=> json_decode('{
                            "query" : { 
                                "match_all" : {} 
                            },
                            "fields": []
                        }', true),
            'index' => $index,
            'type' => $type,
            'scroll' => '60m',
            'size' => 5000
            );
        $elasticsearchData = Elasticsearch::search($query);
        $hits = &$elasticsearchData['hits']['hits'];
        
        do{
            $elasticSearchIndexes = array();
            $data = array(
                'body' => array()
            );
            foreach($hits as &$hit){
                if(!isset($idsOnDb[intval($hit['_id'])])){
                    $data['body'][] = [ 'delete' => array(
                        '_index' => $index,
                        '_type' => $type,
                        '_id' => $hit['_id']
                        )];
                }
            }
            if(!empty($data['body'])){
                Elasticsearch::bulk($data);
            }
            if(!isset($elasticsearchData['_scroll_id'])){
                break;
            }
            $scroll_id = $elasticsearchData['_scroll_id'];
            $elasticsearchData = Elasticsearch::scroll(
                array(
                    "scroll_id" => $scroll_id,
                    "scroll" => "60m"
                )
            );
            $hits = &$elasticsearchData['hits']['hits'];

            
        }while(count($hits) > 0);
        Elasticsearch::clearScroll(array('scroll_id' => $scroll_id));
```

yet it gives error which is fixed by replacing the line 234 of AbstractEndpoint.php to:

```php
$whitelist = array_merge($this->getParamWhitelist(), array('client', 'custom', 'filter_path', 'scroll', 'size'));
```
I already tried to push the change on a new branch yet it won't allow me, so please add it. 
I had to override that class with an alias on laravel for it was the fastest solution.

### System details :

- Operating System: Ubuntu 14.04 Latest update
- PHP Version: 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57) 
- ES-PHP client version:  v2.2.0
- Elasticsearch version: 2.3.3

Incodemode o/
Guatemala.com

**Comment by polyfractal** [comment]
I think something else is going on?  Can you paste the error you are seeing?

The Search endpoint already whitelists ["scroll"](https://github.com/elastic/elasticsearch-php/blob/v2.2.0/src/Elasticsearch/Endpoints/Search.php#L81) and ["size"](https://github.com/elastic/elasticsearch-php/blob/v2.2.0/src/Elasticsearch/Endpoints/Search.php#L83).  And the Scroll endpoint whitelists ["scroll"](https://github.com/elastic/elasticsearch-php/blob/v2.2.0/src/Elasticsearch/Endpoints/Scroll.php#L84)

**Comment by incodemode** [comment]
Never mind, I found the error in my code:

> [2016-07-12 10:08:29] local.ERROR: exception 'Elasticsearch\Common\Exceptions\UnexpectedValueException' with message '"scroll" is not a valid parameter. Allowed parameters are: "ignore_unavailable", "allow_no_indices", "expand_wildcards", "min_score", "source", "preference", "routing", "q", "df", "default_operator", "analyzer", "lowercase_expanded_terms", "analyze_wildcard", "lenient", "lowercase_expanded_terms", "client", "custom", "filter_path"' in /var/www/api.mau.dev/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php:247
Stack trace:

> #0 /var/www/api.mau.dev/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(98): Elasticsearch\Endpoints\AbstractEndpoint->checkUserParams(Array)
> #1 /var/www/api.mau.dev/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(342): Elasticsearch\Endpoints\AbstractEndpoint->setParams(Array)
> #2 [internal function]: Elasticsearch\Client->count(Array)
> #3 /var/www/api.mau.dev/vendor/cviebrock/laravel-elasticsearch/src/Manager.php(135): call_user_func_array(Array, Array)
> #4 /var/www/api.mau.dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Cviebrock\LaravelElasticsearch\Manager->__call('count', Array)
> #5 /var/www/api.mau.dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Cviebrock\LaravelElasticsearch\Manager->count(Array)
> #6 /var/www/api.mau.dev/app/Console/Commands/V2DirectoryImport.php(574): Illuminate\Support\Facades\Facade::__callStatic('count', Array)
> #7 /var/www/api.mau.dev/app/Console/Commands/V2DirectoryImport.php(574): Cviebrock\LaravelElasticsearch\Facade::count(Array)
> #8 /var/www/api.mau.dev/app/Console/Commands/V2DirectoryImport.php(434): App\Console\Commands\V2DirectoryImport->validate_listings_in_elasticsearch_insertions('api_db_v2_1')
> #9 /var/www/api.mau.dev/app/Console/Commands/V2DirectoryImport.php(71): App\Console\Commands\V2DirectoryImport->validate_data_insertions()
> #10 [internal function]: App\Console\Commands\V2DirectoryImport->handle()
> 

I comes from calling:
´´´php
$query = array(
                    'index' => $index,
                    'type' => $type,
                    "scroll" => "30s",
                    "size" => 5000
                );
$elasticsearchData = Elasticsearch::count($query);
´´´
It is a count and not a search... Thanks

**Comment by polyfractal** [comment]
Ah, that'd do it.  Glad you resolved it! :)
