### ISSUE TITLE
 Client error response 400 Bad Request 

### ISSUE THREAD

**Issue by sakshigargit15** [elastic/elasticsearch-php#434]
ClientErrorResponseException in BadResponseException.php line 43:
    Client error response
    [status code] 400
    [reason phrase] Bad Request
    [url] https://api.infusionsoft.com/token

### Code snippet of problem
       $client = new \Guzzle\Http\Client();

        $request = $client->post('https://api.infusionsoft.com/token', [], array(
                        'client_id' => config('infusionsoft.client_id'),
                        'client_secret' => config('infusionsoft.client_secret'),
                        'code' => 'code',
                        'scope' => 'full',
                        'redirect_uri' => $root . '/callback'));
        $tokenInfo = $request->send($request);

**Comment by polyfractal** [comment]
I think you're looking for the [Guzzle Repository](https://github.com/guzzle/guzzle)?  This is the repo for Elasticsearch-PHP client library :)
