### ISSUE TITLE
php client's reIndex method may not working.

### ISSUE THREAD

**Issue by lanlin** [elastic/elasticsearch-php#437]
### When 'body' element in the params array, this method return error message.

"body" is not a valid parameter. Allowed parameters are: "refresh", "timeout", "consistency", "wait_for_completion", "client", "custom", "filter_path"

### In src/Elasticsearch/Client.php line 1585

```php
    public function reIndex($params = [])
    {
        /** @var callback $endpointBuilder */
        $endpointBuilder = $this->endpoints;

        /** @var \Elasticsearch\Endpoints\ReIndex $endpoint */
        $endpoint = $endpointBuilder('Reindex');
        $response = $endpoint->setParams($params)->performRequest();

        return $endpoint->resultOrFuture($response);
    }
```

The setBody() method has not been called.

- PHP Version 5.6.23
- ES-PHP client version 2.2
- Elasticsearch version 2.3.4

**Comment by polyfractal** [comment]
Thanks!  Fixed in 21ca68b5670d6aee85b27d8706c1830bf36dca0d, tagged in `v2.2.1`
