### ISSUE TITLE
routing param is not white listed on bulk endpoint

### ISSUE THREAD

**Issue by lordcoste** [elastic/elasticsearch-php#439]
As you can see here: http://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Bulk.php#L62-L69

**Comment by polyfractal** [comment]
Yep, that's because bulks themselves are not routed; rather, the individual bulk items are routed inline with their JSON: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-routing

E.g.

```json
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1", "_routing": "foo" } }
{ "field1" : "value1" }
{ "delete" : { "_index" : "test", "_type" : "type1", "_id" : "2", "_routing": "bar" } }
{ "create" : { "_index" : "test", "_type" : "type1", "_id" : "3", "_routing": "baz" } }
{ "field1" : "value3" }
```

Note the `"_routing"` values in each "action" line.

**Comment by lordcoste** [comment]
Thanks for your reply, I was fooled by this line comment: http://github.com/elastic/elasticsearch-php/blob/2.0/src/Elasticsearch/Client.php#L838

Now I see that was removed from master.

So, if I want to bulk index a 2nd level children and want those document to be on the same shard of the grandfather I should set "_routing" for each document, am I correct?

```php
// like this (post > comment > mention)
$params = [
    'index'   => 'facebook',
    'type'    => 'mention',
    'body'    => [],
];

foreach($comment->mentions as $mention) {
    $params['body'][] = [
        'index' => [
            '_parent' => $comment->id,
            '_routing' => $post->id,
        ]
    ];

    $params['body'][] = [
        'id'   => $mention->id,
        'name' => $mention->name,
        'type' => $mention->type,
    ];
}

$elastic->bulk($params);
`

**Comment by polyfractal** [comment]
You'll need to set the _routing of the grand-children (and any subsequent levels) to be the same as the original parent.  As an example:

- Parent: `id: 123`
- Child: `id: abc`, `_parent: 123` 
- Grand-child: `id: xyz`, `_parent: abc`, `_routing: 123`
