### ISSUE TITLE
MGet Endpoint Class is not found due to different case "Mget.php"

### ISSUE THREAD

**Issue by goelrishabh09** [elastic/elasticsearch-php#440]
### Summary of problem or feature request

MGet Endpoint Class is not found due to different case "Mget.php"

### Suggested changes:

elasticsearch-php/src/Elasticsearch/Endpoints/Mget.php
to MGet.php

### System details
~ centOS

**Comment by polyfractal** [comment]
Yepp, that'd probably do it.  Want to send a PR?  If not I'll take care of this in a bit :)

Thanks!

**Comment by goelrishabh09** [comment]
I don't know why i have filename `Mget.php` but ClassName `MGet` 
while `v2.2.1` release and `master` branch here have both things same.

I have version 2.2.1.

Might have happened due to case insensitive FS on OSX.
So closing this issue.
