### ISSUE TITLE
Elasticsearch doesn't update document

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [elastic/elasticsearch-php#441]
I've built Elasticsearch into one of my apps. I implemented it straight into the model. When I save the model it automatically adds it to ES, however when I update it it doesn't update the model. When I `var_dump()` the response, it doesn't throw any errors. Might this be a bug?

```php
public function afterSave()
{
    $client = \Elasticsearch\ClientBuilder::create()->build();
    $params = [
        'index' => 'testindex',
        'type' => 'user',
        'id' => $this->id,
        'body' => [
            'id' => $this->id, 
            'name' => $this->firstname.' '.$this->lastname, 
            'email' => $this->email, 
            'test' => ''
        ]
    ];
         
    $response = $client->index($params);
}

public function afterUpdate()
{
    $client     =   \Elasticsearch\ClientBuilder::create()->build();
    $params     =   [
        'index' => 'testindex',
        'type' => 'user',
        'id' => $this->id
    ];

    $params['body']['doc']  =   [
        'test' => 'test2'
    ];
         
    $response = $client->update($params);
    var_dump($client->update($params));
    var_dump($response);
}
```

**Comment by polyfractal** [comment]
What's the update response look like?  Can you also do a `$client->get()` for the document before/after update and print out those results?

Also, what version of ES and ES-PHP are you using?

**Comment by Sjoerdjanssenen** [comment]
I'm sorry, this was caused by Phalcon calling `afterSave()` on both `save()` and `update()`. I'm closing this issue now.
