### ISSUE TITLE
Problem with script_score

### ISSUE THREAD

**Issue by xjpphp** [elastic/elasticsearch-php#458]
Hi,how to use param "function_score",I get a blow error:
Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message '{"error":{"root_cause":[{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"},{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"},{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"document","node":"StCJxH54RO2W767-5FreCA","reason":{"type":"query_parsing_exception","reason":"script_score the script could not be loaded","index":"document","line":1,"col":107,"caused_by":{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"}}},{"shard":0,"index":"news","node":"StCJxH54RO2W767-5FreCA","reason":{"type":"query_parsing_exception","reason":"script_

****Operating System:window 7 64 bit
PHP Version:5.4
ES-PHP client version:2.0
Elasticsearch version:2.3.4**
code:**
<?php
header("Content-type:text/html;charset=utf-8");
include '../vendor/autoload.php';
use Elasticsearch\ClientBuilder;
$hosts=array('http://localhost:9200');
$client = ClientBuilder::create()           // Instantiate a new ClientBuilder
                    ->setHosts($hosts)      // Set the hosts
                    ->build(); 
               
$randomScore = new \stdClass();
//$randomScore->seed = 5;
$script_score=new stdClass();
$script_score->script="_score * doc['search_class_id'].value";
$qry = array(
    'query' => array(
        'function_score' => array(
            'functions' => array(
                array ("script_score"=>$script_score),
            ),
            'query' => array('match_all' => array())
        )
    )
);

$searchParams['body'] = $qry;

$retDoc = $client->search($searchParams);
print_r($retDoc);

exit;

**Comment by jacdobro** [comment]
> {"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"

You need to configure your elasticsearch.
Add script.engine.groovy.inline.search: on to elasticsearch.yml configuration file and restart the node.

**Comment by polyfractal** [comment]
Closing, since the answer provided by @jacdobro is correct.  Please feel free to reopen if oyu have questions, or [pop over to the forums](https://discuss.elastic.co/) for more general help
