### ISSUE TITLE
Old filtered method should be removed in the manual

### ISSUE THREAD

**Issue by dangyuluo** [elastic/elasticsearch-php#460]
### Summary of problem or feature request

In file `search-operations.asciidoc` on line 182, there's still sample code using filtered method to filter out data, as in old version ES. 

### System details

- Operating System
- PHP Version
- ES-PHP client version
- Elasticsearch version

**Comment by dangyuluo** [comment]
Sorry, I wrongly misunderstood it.

**Comment by polyfractal** [comment]
Oh, no, you're right.  That `filtered` query is deprecated in ES now, and should be replaced with a `bool` using a `filter` clause.

Reopening!  I'll commit a fix in a bit... currently digging out of my inbox :)

**Comment by dangyuluo** [comment]
Well, then I truly misunderstood it. Thank you.
