### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by BenHarris** [elastic/elasticsearch-php#462]
### Summary of problem
Code dies out with "No alive nodes found in your cluster" (repeated over and over) after successfully inserting some data (~40k items). Immediately running it again allows the process to start again, but ends up with the same problem again. I have experienced the same thing using futures and bulk inserts. I've tried setting retries to 100 and timeouts of 5 minutes, although this seems to have had no impact.

### Code snippet of problem
I've simplified the following right down

```php
$client = Elasticsearch\ClientBuilder::create()
  ->setHosts(['https://RANDOMCHARS.eu-west-1.es.amazonaws.com:443'])
  ->setRetries(100)
  ->build();

$limit = 1000;
$offset = 0;
while( $items = get_data($limit, $offset) )
{
  $futures = [];
  foreach( $items as $item )
  {
    $item_id = $item->id;
    unset($item->id);
            
    try {
      $futures[] = $client->index([
        'index'  => 'items',
        'type'   => 'item',
        'id'     => $item_id,
        'body'   => (array)$item,
        'client' => [
          'future' => 'lazy',
          'timeout' => 300,
          'connect_timeout' => 300
        ]]);
    } catch (Exception $e){
      echo $e->getMessage();
    }
  }
  // Resolve futures
  $futures[sizeof($futures)-1]->wait();

  // Increment offset
  $offset += $limit;
}
```
-->

### System details
AWS Elasticsearch Service 2.3(.2) with 2x m3.large.elasticsearch nodes

#### Client
CentOS 7.1
PHP 5.6
ES-PHP: 2.2.1

**Comment by BenHarris** [comment]
Just wanted to update that after countless hours of tweaking, testing and re-testing, I have found a solution. I'm not sure exactly where the problem lies, but I'm happy to help debug if you think it is within the scope of this project. After reading over similar issues (https://github.com/elastic/elasticsearch-php/issues/300), I tried using the singleHandler. This seemed to complete successfully. I tried switching back to the default multi handler, but set the number of handles to 20 (well below the default 100), and it is now running well.

**Comment by polyfractal** [comment]
Sorry for the delay, was traveling all last week for work and have been trying to unbury my inbox this week :)

Do you see any long GC warnings in your server logs?  Is your indexing threadpool full and/or rejecting?

I'm thinking this is a case where the node becomes swamped with work and starts GCing hard, which causes the connection to timeout in the client.  If it times out, the node is marked as dead and the backoff timer starts.  The next node is tried, but if it is also swamped with work it'll be marked dead too.  Once all the nodes are marked dead at the same time (and before their timeouts are up), the client will bail since the cluster is "down".

I'm thinking this may be the case, since you're not seeing the same problem with the SingleHandler, or with a smaller pool w/ MultiHandle.  Aka you're reducing the instantaneous load on the servers, so they aren't timing out any more.

Side note: you should use a single bulk request instead of individual indexing requests.  Should help with performance, and potentially alleviate problems like this.

One thing you can try is changing to the [SimpleConnectionPool](https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_connection_pool.html#_simpleconnectionpool).  This pool doesn't track live/deadness, so it'll keep blindly retrying until either the request goes through, or you run out of retries:

```php
$client = ClientBuilder::create()
  ->setHosts(['https://RANDOMCHARS.eu-west-1.es.amazonaws.com:443'])
  ->setRetries(100)
  ->setConnectionPool('\Elasticsearch\ConnectionPool\SimpleConnectionPool', [])
  ->build();
```

If this alleviates the problem, it's likely due to GC or other load issues on the nodes themselves.

**Comment by BenHarris** [comment]
Hi @polyfractal thanks for the quick reply :-)

It's set up on the AWS Elasticsearch Service, so I don't believe I can access the logs? I thought I might be swamping the server, but I'm not pushing that much data in the grand scheme of things. As I mentioned in my opening post, I had experienced the same problem with bulk indexes.

I've switched to using the SimpleConnectionPool, and set the max_handles up to 50 and it hasn't died out since, so it looks like we're good. Appreciate the support!

**Comment by polyfractal** [comment]
Ah, not sure to be honest... I don't have any experience with the AWS ES service.  You could periodically poll the Node Stats API and see if the new gen/old gen GC count is inching up over time.  That'd also be an indicator.

The main problem with "instantaneous load" isn't so much the processing or volume of data, it's just the sudden influx of data that needs to be buffered.  Netty (the networking layer in ES) allocates direct buffer space for this, and then there is a slew of small object allocations to accommodate the indexing process.

Under normal circumstances this isn't a problem, but large influxes can create more objects than the new-gen is sized for (the JVM dynamically sizes newgen according to historical and heuristics).  This causes the new-gen to GC (which causes stop-the-world pauses) and tenure objects to old-gen sooner than it should, which then puts pressure on the old-gen.  And leads to old-gen GCs, which also STW and are slower.    

I see the `m3.large.elasticsearch` has 7.5gb of RAM... how much of that is heap?  Or is that the heap size?  I'm not super familiar with how the ES service works

Glad the SimpleConnectionPool is working for you!  Just keep in mind that under "normal" circumstances, it'll hammer a dead node even when it's really dead.  E.g. if one of five nodes is dead, every 5th request will still try that node, fail, then retry elsewhere.


*Also, oops, missed your point about bulk :)  Bulk is still recommended, although you should reduce the concurrency of your ingest if you use bulk.

**Comment by BenHarris** [comment]
I'll have a look at the node stats, although given I'm not having the problem any more, I don't have too much incentive to revert my code just to verify the theory :-p

You can "set a percentage of heap space that is allocated to fielddata", but it defaults to "unbounded".

I've moved all the indexing code to use bulk now, using the SimpleConnectionPool and stopped using the futures stuff. I've run it 30 or so times without problems and it's going pretty speedily (bottleneck is getting the data from MySQL now). Thanks for the great work and support :-)

**Comment by polyfractal** [comment]
Great!  I'm going to close this ticket for now, feel free to re-open if you run into more problems in the future (or open a new ticket).  :)

**Comment by mohdbashir** [comment]
I have found this error and solved it by following steps:

1. Comments the plugin setting on app/etc/env.php file.

        'system' => [
        'default' => [
          /* 'smile_elasticsuite_core_base_settings' => [
         'es_client' => [
          'servers' => 'node-1:9200,node-2:9200',
          'enable_https_mode' => '0',
          'enable_http_auth' => '0',
          'http_auth_user' => '',
          'http_auth_pwd' => ''
           ]
          ] */
         ]
        ]

2. Start the server.
3. upgrade magento 

        php bin/magento setup:upgrade
