### ISSUE TITLE
Docs: incorrect path to Namespaces/Indices.php

### ISSUE THREAD

**Issue by joostvanderborg** [elastic/elasticsearch-php#469]
### Summary of problem or feature request

The docs seem to refer to Namespaces/Indices.php, which should be Namespaces/IndicesNamespace.php . I'd be happy to edit myself and submit a pull-request, but the contributor guidelines say to submit an issue, so here it is.

### System details

Not relevant
- ES 2.4 (ES-PHP client 2.0)

**Comment by polyfractal** [comment]
Whoops!  Go ahead and send a PR, I'll merge when I get a chance (on the go atm).

Also ++ for reading the contributor guidelines, so few do! :)

**Comment by polyfractal** [comment]
Closing since the PR was merged.  Thanks :)
