### ISSUE TITLE
Search operations returning null

### ISSUE THREAD

**Issue by Sladix** [elastic/elasticsearch-php#472]
### Summary of problem

Whenever i try do do a search, the response is `null`. As described in [this SO question](http://stackoverflow.com/questions/39690745/elasticsearch-php-sdk-search-returning-null-on-match-all-query), I tried several ways but none of them worked for me.

I **do** see the results with a curl or with a http get using `https://mydomain:8081/ingredients/aliment/_search?size=350&pretty`

### Code snippet of problem

I looked at the issues from Github and stumbled upon an answer that I tried

```php
$searchParams = array();
$searchParams['index'] = 'ingredients';
$searchParams['type'] = 'aliment';
$searchParams['body']['query']['match_all'] = array();
    
$output = $client->search($searchParams);
```

Note that with the type 'aliments' that does not exist, I get a valid output : `{"took":2,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}`
But with a valide type ('aliment') the output is `null`

### System details

- OS : Ubuntu 14.04.3 LTS
- PHP Version : 5.5.9-1ubuntu4.17 (cli)
- ES-PHP client version : 2.0
- Elasticsearch version : 2.4.0

Thanks for reading

**Comment by polyfractal** [comment]
Hrm, could you execute the plain curl command and paste the JSON response?

e.g.

```bash
curl -XGET localhost:9200/ingredients/aliment/_search -d '{
  "query" : { "match_all": {} }
}'
```

I'm thinking that there is perhaps a bad document somewhere in your index, which has invalid JSON.  There was a period of time where ES would happily index invalid JSON (usually a second JSON document appended to the first).  If one of the docs has invalid JSON, that'll make the JSON deserialization (potentially) barf, which might return `null`

**Comment by Sladix** [comment]
Hey, here is the output you asked for : 

`{"took":4,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":240,"max_score":1.0,"hits":[{"_index":"ingredients","_type":"aliment","_id":"AVczTzD}]}}sladix:~/workspace $ ,"_type":"aliment","_id":"AVczTzDG2Gb89I5DKKwf","_score":1.0,"_source":{name:"Gourgane",type:"",description:""}ption:""}iption:""}`

**Comment by polyfractal** [comment]
Hm, yeah, there's not a ton the client can do here because it assumes ES returns valid JSON.

If this is an isolated incident (e.g. accidentally indexed this doc from some typo on the command line, rather than a problem in your app), the easiest solution would be to just remove/fix that one document.

Go ahead and paste your indexing code, we can take a look.  Because of that `sladix:~/workspace $ ` I'm hoping it's just a cli typo :)

**Comment by Sladix** [comment]
Here is the complete file : 
`{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Abricot",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Agneau (mouton)",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Agneau et mouton",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Ail",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Algue",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Algues",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Alkékenge (cerise de terre)",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Amande",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Ambérique et dolique",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Ananas",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Aneth",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Arachide",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Argousier",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Artichaut",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Asperge",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Aubergine",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Avocat",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Avoine",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Baie de goji",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Banane",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Banane et banane plantain",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Basilic",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Bette à carde",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Betterave",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Beurre",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Blé",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Bleuet",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Boeuf",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Boulghour",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Brocoli",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"butternut",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Café",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Calmar",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Calmar, pieuvre et seiche",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Canard",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Canneberge",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Cannelle",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Canola (huile)",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Carotte",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Cassis",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Céleri",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Céleri-rave",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Cerise",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Cerise de terre (groseille du Cap)",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Champignon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Champignons",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Châtaigne (marron)",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Châtaigne et marron",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Chicorée et endive",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Chocolat et cacao",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Chou",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Chou chinois",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Chou-fleur",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Chou-rave",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Ciboulette",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Citron",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Citron et lime",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Citrouille",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Citrouille et potiron",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Clémentine",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Clémentine, mandarine et tangerine",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Coing",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Concombre et Cornichon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Concombre et cornichon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Coriandre",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Courge",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Courges",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Courgette",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Courgette et pâtisson",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Crabe",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Crème fraîche",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Cresson",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Crevette",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Crosne",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Crosse de fougère",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Curcuma",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Datte",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Dinde",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Echalote",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Échalote",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Endive",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"épeautre",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Épinard",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Epinards",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Estragon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Fenouil",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Fève des Marais",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Fève des marais",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Figue",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Fraise",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Framboise",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Framboise et mûre",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Fromage",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Fruit de la passion",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Gingembre",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Gombo",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Gourgane",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Goyave",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Grenade",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Groseille",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Hareng",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Haricot commun frais",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Haricot vert",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Haricots secs",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Homard",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Huile de colza",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Huile de palme",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"huiles végétales",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Huiles végétales",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Huître",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Igname",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Kaki",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Kale",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Kiwi",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Lait",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Laitue",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Lapin",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Lentille",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Lentilles",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Lime et citron",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Litchi",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Luzerne",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"maca",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Mâche",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Maïs",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Mangue",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Maquereau",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Marjolaine et origan",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Marron",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Melon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Menthe",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Mérou",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Miel",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Millet",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Morue",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Morue (cabillaud)",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Moule",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Moutarde",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Mûre et framboise",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Myrtille",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Navet",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Navet et rutabaga",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Nectarine et pêche",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Noisette",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Noix",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Noix de cajou",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Noix de coco",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Noix de pécan",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Oeuf",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Oie",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Oignon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Oignon vert",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Olive",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Olive et huile d'olive",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Omble chevalier",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Orange",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Orange et bigarade",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Orge",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Origan",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Origan et marjolaine",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Oseille",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pacane",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pain",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Palourde",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pamplemousse",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pamplemousse et pomélo",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Panais",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Papaye",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pastèque",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Patate douce",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pêche",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pêche et nectarine",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Persil",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Petits pois",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pétoncle",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Physalis",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pignon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Piment",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pistache",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pleurote",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pleurotes",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Poire",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Poireau",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pois cassé",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pois chiche",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pois frais",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pois sec",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Poivron",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pomme",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Pomme de terre",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Porc (viande)",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Porc et sanglier",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"potimarron",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Poulet",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Prune et pruneau",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Quinoa",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Radis",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Raifort",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Raifort et wasabi",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Raisin",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Rhubarbe",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Riz",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Riz sauvage",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Roquette",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Rutabaga et navet",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Salicorne",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Salsifis",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Salsifis et scorsonère",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sardine",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sarrasin",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sarriette",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sauge",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Saumon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Seigle",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Semoule",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sésame",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Shiitake",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"simili-viande",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sirop d'Erable",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sirop d'érable",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Soja",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sole",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Sole et plie",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Tangerine, mandarine, clémentine",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Tête de violon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Thé",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Thon",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Thym",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Tilapia",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"tofu",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Tomate",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Topinambour",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Tournesol",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Truite",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Veau",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Viande de gibier",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Vin",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Vinaigre",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Vivaneau",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Yaourt",type:"",description:""}
{ "index" : { "_index" : "ingredients", "_type" : "aliment" } }
{name:"Yogourt",type:"",description:""}`

Thanks a lot for helping !

**Comment by Sladix** [comment]
Well, I figured out that my requests file was malformed.

Instead of `{name:"Yaourt",type:"",description:""}` , I wrote `{"name":"Yaourt","description":""}`.
Surrounding the fields names by quotes solved the issue !

Thanks again for looing !
