### ISSUE TITLE
Bug on reindex casing still present on v2.2.1 (Bug/reindex casing #466) 

### ISSUE THREAD

**Issue by gioialorusso** [elastic/elasticsearch-php#475]
Hi, I have an issue with ReIndex API. In the Client.php file, row 1593, the endpointBuilder method is called with parameter 'Reindex', but the file in the FS is called "ReIndex.php". I know that this issue was fixed, but why in my version (v. 2.2.1) is still present?
In my composer I have this version required: 
    "elasticsearch/elasticsearch" : "~2.0"
Thanks,
Gioia

**Comment by polyfractal** [comment]
Hey, sorry for the delay... been pulled into other projects.

It looks like I never tagged and released a new 2.x which has that fix.  Let me skim through the other outstanding issues and make sure there isn't something simple that should go in, then I'll cut a release.

I'll ping this thread once it's tagged.

**Comment by polyfractal** [comment]
Tagged and released `v2.2.2`, which should fix this :)
