### ISSUE TITLE
What is query check exist document?

### ISSUE THREAD

**Issue by hatienkma** [elastic/elasticsearch-php#485]
I want to check exist document before index new document.

I use search param but it not success.
## 

$params = [
                'index' => $indexDB,
                'type' => $typeDB,
                'body' => [
                    'query' => [
                        'match' => [
                            'email' => $email
                        ]
                    ]
                ]
##        ];

Any one can recommend query check exists documents?
### System details
- Operating System: CentOS
- PHP 5.6
- "version" : {
  "number" : "2.4.1",
  "lucene_version" : "5.5.2"
  },

**Comment by dcarbone** [comment]
https://github.com/elastic/elasticsearch-php/blob/v2.2.2/src/Elasticsearch/Namespaces/IndicesNamespace.php#L31 is probably what you want.

```php
$exists = $client->indices()->exists(['index' => 'your-index-name']);
```

**Comment by polyfractal** [comment]
Do you know the documents ID?  You can use the [Exists API](https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/ElasticsearchPHP_Endpoints.html#Elasticsearch_Clientexists_exists) if you know the index/type/id of a doc.

**Comment by polyfractal** [comment]
Oops, just saw @dcarbone reply.  Note: that method (`$client->indices()->exists([...])`) is for determining if an entire index exists, where as the other exists (`$client->exists([...])`) is for checking individual documents

**Comment by dcarbone** [comment]
Ah, thanks for the clarification :)

**Comment by polyfractal** [comment]
Closing, @hatienkma  feel free to reopen if you need more help :)

**Comment by sy92** [comment]
I am trying the achieve the same functionality with a different way. Can you please take a look and give me a hint what changes I should make? Here is the [post](https://discuss.elastic.co/t/php-client-check-input-before-indexing/119511).
