### ISSUE TITLE
Did v5.0 elasticsearch-php has the "delete by query" method? 

### ISSUE THREAD

**Issue by lanlin** [elastic/elasticsearch-php#487]
### I can't find where has this method.

[Elasticsearch 5.0 Document APIs delete by query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html)

But i can't find it in elasticsearch-php.

### System details

- MacOS 10.12.1
- PHP 7.0.12
- ES-PHP 5.0
- Elasticsearch 5.0

**Comment by phpnt43** [comment]
https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_breaking_changes_from_2_x.html
"DeleteByQuery endpoint has been removed." - they removed method.
May I ask how you solved your problem?

**Comment by polyfractal** [comment]
DBQ was [added back in ES-PHP 5.1.0](https://github.com/elastic/elasticsearch-php/blob/5.0/CHANGELOG.md#release-510): https://github.com/elastic/elasticsearch-php/blob/5.0/src/Elasticsearch/Client.php#L299
