### ISSUE TITLE
Fatal error: Can only throw objects in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 539

### ISSUE THREAD

**Issue by ssjjh888** [elastic/elasticsearch-php#488]
`
	error_reporting(-1);
	ini_set("display_errors", 1);

	require 'vendor/autoload.php';

	$host = ['ip'];

	$clientBuilder = Elasticsearch\ClientBuilder::create();
	$clientBuilder->setHosts($host);
	$client = $clientBuilder->build();

	$Params = array();
	// index that we will be using
	$Params['index'] = 'books';

	// optional if omitted this will be autogenerated
	$Params['id'] = '1';

	// fields
	$Params['body'] = array(
		'title' => '20.000 miles under the sea',
		'author' => 'Jules Verne',
		'description' => 'A longer description of the book',
		'genre' => 'Adventure'
	);

	// type of document
	$Params['type'] = 'book';

	// add document to the index
	$response = $client->index($Params);
`

error message 

Fatal error: Can only throw objects in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 539

server is aws

- PHP Version 5.5.9
- Elasticsearch version 2.0

**Comment by polyfractal** [comment]
What version of Elasticsearch-PHP are you using?  You will need the 2.0 branch for Elasticsearch 2.0:

```json
{
    "require": {
       "elasticsearch/elasticsearch": "~2.0"
   }
}
```

**Comment by polyfractal** [comment]
Closing, feel free to reopen if the above didn't solve your problem :)

**Comment by pankajmalkani** [comment]
hello sir,
this is pankaj malkani a senior development. I even have tried to implement the version of elasticsearch : "~2.0" in composer.json, but still it's throwing error Fatal error: Uncaught Error: Can only throw objects in C:\wamp64\www\customcms-master\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:539 Stack trace: #0 C:\wamp64\www\customcms-master\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(208): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array) #1 C:\wamp64\www\customcms-master\class\vendor\react\promise\src\FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #2 C:\wamp64\www\customcms-master\class\vendor\guzzlehttp\ringphp\src\Future\CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #3 C:\wamp64\www\customcms-master\class\vendor\guzzlehttp\ringphp\src\Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #4 C:\wamp64\www\customcms-master\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(229): GuzzleHttp\R in C:\wamp64\www\customcms-master\class\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php on line 539. Please let me know the solution of the same ASAP.

**Comment by polyfractal** [comment]
@pankajmalkani make sure your version of Elasticsearch matches the branch of Elasticsearch.
