### ISSUE TITLE
require php5-json > 1.3.6-1

### ISSUE THREAD

**Issue by coraxster** [elastic/elasticsearch-php#498]
### Summary of problem or feature request

require php5-json > 1.3.6-1

methods index and bulk does not work with default php5-json 1.3.6-1, drops error 400
need php5-json update to 1.3.7

- Debian
- PHP Version 5.6.27
- 5.0
- 5.0

**Comment by abravorus** [comment]
The same problem.

Where did you find amd64 debian package php5-json 1.3.7 for Debian jessie (stable) with PHP Version 5.6.27 ?

**Comment by coraxster** [comment]
i used unstable sip.

add to /etc/apt/sources.list
`deb http://ftp.de.debian.org/debian unstable main contrib non-free`

```
apt-get update
apt-get -t unstable install php5-json
```

**Comment by abravorus** [comment]
Thanks!

I've seen it in unstable but decided that version 1.3.9 is too new :)

No conflicts with stable PHP version 5.6.27 ?

**Comment by coraxster** [comment]
My tests passed. Works fine.

**Comment by abravorus** [comment]
Works fine for me too. Thanks!

**Comment by polyfractal** [comment]
Sorry for the delay, been away on holiday.  I'll update the min requirements and add something to the docs about it.  Thanks!

**Comment by polyfractal** [comment]
Added version requirement to the composer file, will try to add some helpful docs in a bit.  I need to scrounge up the procedure for the various popular platforms, since it's packaged differently on redhat, etc.
