### ISSUE TITLE
Missing JSON_ERROR_ constant mapping in JsonErrorException

### ISSUE THREAD

**Issue by mfn** [elastic/elasticsearch-php#499]
### Summary of problem 
PHP7 introduced two new `JSON_ERROR_*` constants. They are currently **not** [documented at php.net](http://php.net/manual/en/function.json-last-error.php) ([see bug report](https://bugs.php.net/bug.php?id=73525)).

These are:
```SH
$ php -v
PHP 7.0.12-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
$ php -r 'var_dump(JSON_ERROR_INVALID_PROPERTY_NAME);'
int(9)
$ php -r 'var_dump(JSON_ERROR_UTF16);'
int(10)
```

This numbers are currently not handled in `\Elasticsearch\Common\Exceptions\Serializer\JsonErrorException`, leading to a generic e.g. `10 is not a valid JSON error code.` message (which today I received due some weird ES response).

### System details
- PHP Version: PHP 7

**Comment by polyfractal** [comment]
Argh, thanks for the report!  Added the new error codes, and tweaked the message that's thrown when the code is unknown (since I'm sure this will happen again sometime).  Makes it a little less ominous :)

**Comment by mfn** [comment]
Awesome, thanks!
