### ISSUE TITLE
How to make URI Search

### ISSUE THREAD

**Issue by grokify** [elastic/elasticsearch-php#500]
### Summary of problem or feature request

Regarding the one-to-one mapping with REST API, is there a way to make a [URI Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html) via the SDK such as the following from the API docs, including support for all the other query string parameters:

`GET twitter/tweet/_search?q=user:kimchy`

I reviewed the various `Endpoint` classes and nothing jumped out at me as supporting this, which could be done using something like `$endpoint->setURI(...)` or via setting the query string params.

### Code snippet of problem

When following code from the docs, the `body` param follows the Search DSL. Is there a way to use URI Search with this SDK?

```php
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [
        'query' => [
            'match' => [
                'testField' => 'abc'
            ]
        ]
    ]
];

$response = $client->search($params);
print_r($response);
```

**Comment by polyfractal** [comment]
Yep, it's possible.  It's not immediately obvious how (sorry about that!), mostly because the URI method is generally a shorthand for commandline searches, not so much for programmatic clients.  But it's definitely possible!

You can do it by calling the search endpoint and [specifying a `q` param](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Search.php#L75):

```php
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'q' => 'user:kimchy'
];
$response = $client->search($params);
```

**Comment by grokify** [comment]
Sounds good. Will this work for (all) the other params supported by URI search, e.g. `df`, `analyzer`, `lowercase_expanded_terms`, `analyze_wildcard`, `default_operator`, etc.?

**Comment by polyfractal** [comment]
Yep!  Any parameter that would go in the URI can be added as a "top-level" parameter in the $params object.  So just keep adding the ones you're interested in:

```php
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'q' => 'user:kimchy',
    'analyzer' => 'foo'  // etc
];
$response = $client->search($params);
```

**Comment by grokify** [comment]
Very cool! Much thanks!

**Comment by polyfractal** [comment]
np, happy to help! :)
