### ISSUE TITLE
parsing_exception: bool query does not support [query]

### ISSUE THREAD

**Issue by huangxiaoye** [elastic/elasticsearch-php#501]
### System details
```php
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [
        'query' => [
            'bool' => [
                'filter' => [
                    'term' => [ 'my_field' => 'abc' ]
                ],
                'query' => [
                    'match' => [ 'my_other_field' => 'xyz' ]
                ]
            ]
        ]
    ]
];
$results = $client->search($params);
```
When excute above then occur error (this code from the offical docs https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_search_operations.html)

[Elasticsearch\Common\Exceptions\BadRequest400Exception] parsing_exception: bool query does not support [query]

#1  F:\www\newjkl\wwwplatform\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:659
#2  F:\www\newjkl\wwwplatform\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:579
#3  F:\www\newjkl\wwwplatform\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:261
#4  F:\www\newjkl\wwwplatform\vendor\react\promise\src\FulfilledPromise.php:25
#5  F:\www\newjkl\wwwplatform\vendor\guzzlehttp\ringphp\src\Future\CompletedFutureValue.php:55
#6  F:\www\newjkl\wwwplatform\vendor\guzzlehttp\ringphp\src\Core.php:341
#7  F:\www\newjkl\wwwplatform\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:282
#8  F:\www\newjkl\wwwplatform\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:159
#9  F:\www\newjkl\wwwplatform\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php:107
#10 F:\www\newjkl\wwwplatform\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Client.php:1346

- Operating System
windows
- PHP Version
5.6
- ES-PHP client version
5.0
- Elasticsearch version
5.0

**Comment by polyfractal** [comment]
The boolean query doesn't have a `query` clause.  The clauses it supports are: `filter`, `must`, `must_not` and `should`.  Try this instead:

```php
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [
        'query' => [
            'bool' => [
                'filter' => [
                    'term' => [ 'my_field' => 'abc' ]
                ],
                'must' => [
                    'match' => [ 'my_other_field' => 'xyz' ]
                ]
            ]
        ]
    ]
];
$results = $client->search($params);
```

**Comment by huangxiaoye** [comment]
Got it thanks.but how can I use "minimum_should_match" in this code,I checked the offical doc but not found any demo.
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [
        'query' => [
            'bool' => [
                'filter' => [
                    'term' => [ 'my_field' => 'abc' ]
                ],
                'must' => [
                    'match' => [ 'my_other_field' => 'xyz' ]
                ]
            ]
        ]
    ]
];

**Comment by polyfractal** [comment]
```php
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [
        'query' => [
            'bool' => [
                'filter' => [
                    'term' => [ 'my_field' => 'abc' ]
                ],
                'must' => [
                    'match' => [ 'my_other_field' => 'xyz' ]
                ],
                'minimum_should_match' => '20%'  // <-- add it here
            ]
        ]
    ]
];
```

The body follows the JSON exactly, so you can just translate a JSON request body into PHP array syntax :)  You can read more about the syntax here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html
