### ISSUE TITLE
Use httpful instead guzzle

### ISSUE THREAD

**Issue by insign** [elastic/elasticsearch-php#51]
Hi, looking inside of the elasticseach-php, I saw that guzzle is used, but I think that httpful (32k zip) can do the same, and is very smaller in comparation to guzzle (1M~ zip).

https://github.com/nategood/httpful

**Comment by MrHash** [comment]
Looks like memory management is an [issue](https://github.com/amphp/artax/issues/77) in Artax so wouldn't want to see this affecting the ES php libs!

**Comment by jeabakker** [comment]
also guzzle/guzzle is abandoned see https://packagist.org/packages/guzzle/guzzle

**Comment by polyfractal** [comment]
We don't use Guzzle anymore.  The client uses [RingPHP](https://packagist.org/packages/guzzlehttp/ringphp): https://github.com/elastic/elasticsearch-php/blob/master/composer.json#L15

I'm going to close this issue, as I'm perfectly happy with RingPHP and don't really see a need to changeup the underlying HTTP lib.  If someone wants to use Httpful, Artrax or some other library, they can [write a simple Ring handler shim](https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_configuration.html#_configure_the_http_handler) and plug it into the client. :)

**Comment by macnibblet** [comment]
@polyfractal I agree, the reason i recommend something other than guzzle back in 2014 was because they were one of the first libraries to support async operations. But now that everything pretty much does, I agree it's rather pointless.

**Comment by polyfractal** [comment]
@macnibblet agreed!  At the time it was a very good suggestion, and honestly it's a shame I didn't get around to implementing it (the guzzle major version upgrade dance has been fatiguing).  Alas, I didn't :(

**Comment by jeabakker** [comment]
> We don't use Guzzle anymore. The client uses RingPHP: https://github.com/elastic/elasticsearch-php/blob/master/composer.json#L15

maybe in master but not in 1.x

**Comment by polyfractal** [comment]
@jeabakker Correct, it isn't used in the 1.x branch.  But that branch is effectively unmaintained now, short of a hideous bug that breaks everything.  The main reason for the version bump was actually converting core from Guzzle to RingPHP, largely due to Guzzle3 being unmaintained :)

I'll add a note to the docs / readme, since it isn't super clear that 1.x is effectively EOL now.
