### ISSUE TITLE
PHP Fatal error when using DeleteByQuery

### ISSUE THREAD

**Issue by Stevad** [elastic/elasticsearch-php#524]
### Summary of problem or feature request

Cannot use DeleteByQuery.

Got error:
```
PHP Fatal error:  Access level to Elasticsearch\Endpoints\DeleteByQuery::getParamWhitelist() must be public (as in class Elasticsearch\Endpoints\AbstractEndpoint)
```

### Code snippet of problem

Any call to Elasticsearch\Client::deleteByQuery() method. 

### System details

- Operating System: Ubuntu 16.04
- PHP Version: 5.6
- ES-PHP client version: 5.1.0
- Elasticsearch: 5.0

**Comment by mxp100** [comment]
#527 i created pull request... wait

**Comment by polyfractal** [comment]
Merged.  I want to do a few other housekeeping chores then I'll tag a bugfix release.  Will update this thread once it's been released.

**Comment by polyfractal** [comment]
This is now in `v5.1.1` :)
