### ISSUE TITLE
Wrong route _status instead of _stats in 

### ISSUE THREAD

**Issue by dbarty** [elastic/elasticsearch-php#533]
### Summary of problem or feature request

It seems that the Elasticsearch\Endpoints\Indices\Status class uses the wrong endpoint for ES ver. 5. As I understood the documentation it should be _stats instead of _status (https://www.elastic.co/guide/en/elasticsearch/reference/5.1/indices-status.html).

### Code snippet of problem

    public function getURI()
    {
        $index = $this->index;
        $uri   = "/_stats";

        if (isset($index) === true) {
            $uri = "/$index/_stats";
        }

        return $uri;
    }

### System details

- Operating System: Linux
- PHP Version: 5.6.29
- ES-PHP client version: 5.0
- Elasticsearch version: 5.1.2

**Comment by valVk** [comment]
And why this issue has been closed? Is there any solutions?

**Comment by dbarty** [comment]
As I remember after this long time, I used the wrong method and both exists. it was my mistake, because I missed the code I needed was already there.

**Comment by polyfractal** [comment]
Yep.  Status is here: https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/IndicesNamespace.php#L969

And Stats is here: https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/IndicesNamespace.php#L168

:)

**Comment by valVk** [comment]
My issue was with massive search bundle.
https://github.com/massiveart/MassiveSearchBundle/blob/develop/Search/Adapter/ElasticSearchAdapter.php#L320

Missed the documentation https://github.com/massiveart/MassiveSearchBundle/blob/ad34fd8f188522d9b1f5125036b1a8fa18f654dd/Resources/docs/search_adapters.rst

So issue not related to the elastic search explicitly
