### ISSUE TITLE
write a  php script  for array's indexing with Elasticsearch

### ISSUE THREAD

**Issue by Zankour** [elastic/elasticsearch-php#540]
I'm new with Elasticsearch.
working on my laptop .I'm trying to write a  php code for indexing an array 
, i followed blogs and elastic.co and that's what i wrote ,

`<?php

require 'vendor/autoload.php'; 
use Elasticsearch\ClientBuilder;
$client = ClientBuilder::create()->build();

//creation d'un tableau d'etudiants

$tab_a_indexer=array();

$tab_a_indexer[0]=array(
                     'name' => 'houssem',
                     'age' => 25,
                     'specialité' => 'GT' 
                     );
$tab_a_indexer[1]=array(
                     'name' => 'Raouf',
                     'age' => 23,
                     'specialité' => 'GT' 
                     );
$tab_a_indexer[2]=array(
                     'name' => 'BMZ',
                     'age' => 24,
                     'specialité' => 'GT' 
                     );

//indexer le tableau d'etudiants

for ($i = 0; $i <= count($tab_a_indexer); $i++) {
$params = array();
$params['body'][]  = $tab_a_indexer[$i];
$params['index'] = 'Personne';
$params['type']  = 'Etudiant';
$params['id'] = 'Etudiant'.$i+1;

$result = $client->index($params);
}`

and i got this error :

Fatal error: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /opt/lampp/htdocs/elasticsearch-php-master/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51 Stack trace: #0 /opt/lampp/htdocs/elasticsearch-php-master/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(72): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection() #1 /opt/lampp/htdocs/elasticsearch-php-master/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(90): Elasticsearch\Transport->getConnection() #2 /opt/lampp/htdocs/elasticsearch-php-master/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(239): Elasticsearch\Transport->performRequest('PUT', '/Personne/Etudi...', Array, '[{"name":"houss...', Array) #3 /opt/lampp/htdocs/elasticsearch-php-master/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure} in /opt/lampp/htdocs/elasticsearch-php-master/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51

**Comment by kamerynn** [comment]
The error `No alive nodes found in your cluster` hints that the library tried to send the request to Elasticsearch, but there was a connection error.

In order to connect to Elasticsearch, you have to set the host configuration for your cluster (whether it's running on your local machine, or a remote server)

https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_configuration.html#_inline_host_configuration

**Comment by polyfractal** [comment]
Closing!
