### ISSUE TITLE
Default host is ignored

### ISSUE THREAD

**Issue by cardosojorge** [elastic/elasticsearch-php#547]
### Summary of problem or feature request

Hi,
I'm using the elasticsearch.php config file and have defined the default  hosts parameter there and it never gets used when you are building the client. This worked fine while working on testing machines but failed in production as database instance is not the same machine as the code.

### Code snippet of problem
this what I have on the config file
```php
'hosts' =>[
                env('ELASTIC_HOST','localhost:9200')],


```

and this is the reason why it fails:
####ClientBuilder.php
```php
private function getDefaultHost()
    {
        return ['localhost:9200'];
    }
```
in laravel this could be changed to
```php
return config('elasticsearch.connections.default.hosts', 'localhost:9200');
```

so my workaround was by adding a trait with a getClient method that gets it
```php
public function getClient(){

        $hosts = config('elasticsearch.connections.default.hosts', 'localhost:9200');
        return $client = ClientBuilder::create()
            ->setHosts($hosts)
            ->setRetries(2)
            ->build();
    }
```

 I understand this must work for any php framework or no framework at all but it only makes sense to have a config file with a default value if you're going to use it by default. 
What can be done?
### System details

- MacOSX; Ubuntu
- PHP 7.0
- ES-PHP client version v2.1.5 
- Elasticsearch version 2.1.1

**Comment by polyfractal** [comment]
I think this may be a confusion about what the Laravel package provides, and what this client does.

E.g. the client doesn't have a "default config file"... all parameters must be set on the ClientBuilder at runtime.  If there's a default config file, it's something that the Laravel package is providing.  I suggest you poke the maintainers of that package with your question. :)

**Comment by cardosojorge** [comment]
@polyfractal 
Probably I confused both as I've installed both initially but then kept using just this one and the config stayed there as a left-over. That explains why nothing gets used at all from the config file.
thanks

**Comment by polyfractal** [comment]
👍  Np, lemme know if you have any more questions!  Happy to help :)
