### ISSUE TITLE
Dependency Injection needs: getTransport(), getEndpoint(), getRegisteredNamespacesBuilds() for invocation of Client()

### ISSUE THREAD

**Issue by MichaelBrenden** [elastic/elasticsearch-php#550]
### Summary of problem or feature request

ClientBuilder() returns a Client() object.

But dependency injection containers that operate by class name (such as Tom Zombie's DICE) need to invoke Client() directly, using pre-requisites (e.g., Transport, Endpoint, RegNS) generated by ClientBuilder().

Besides, having setter methods without getter methods is bad form, no?

### Code snippet of problem

// Two steps required:

// 1
// setup the rule that Dice uses when invoking ClientBuilder() (which we only need to do once, because we need to get the Transport, Endpoint and RegNS to feed to Client() -- Client() is then automatically invoked in every model class by Dice)
$dicerule_elasticsearch_clientbuilder = [
	'inherit'			=> false,
	'shared'			=> true,
	'call'	=> [
		[ 'create', [] ],
		[ 'setHosts', [ [ 'localhost:9200', ] ] ],
		[ 'setRetries', [ 33 ] ],
	],
];
// attach the dice rule for the clientBuilder
$dice->addRule( 'Elasticsearch\ClientBuilder', $dicerule_elasticsearch_clientbuilder );
// tell Dice to create the CB
$ESCB = $dice->create( 'Elasticsearch\ClientBuilder' );
// tell ClientBuilder() to build a Client()
// this creates the desired (default) Transport, Endpoints, RNS that are needed by Client::__construct()
$ESCli = $ESCB->build(); // the returned object from build() IS the Elasticsearch\Client()

// 2
// setup the rule that Dice uses when invoking Client(), which Dice will automagically do in every model class whose constructor contains \\namespace\Elasticsearch\Client)
$dicerule_elasticsearch_client = [
	'shared'			=> true,
	'constructParams'	=> [
		$ESCB->getTransport(), // here is where we get the Transport, Endpoint, RNS
		$ESCB->getEndpoint(),
		$ESCB->getRegisteredNamespacesBuilders()
	],
];
// attach the dice rule for the client
$dice->addRule( 'Elasticsearch\Client', $dicerule_elasticsearch_client );
// tell dice to create a shared instance of Client() -- this is the object that will be shared amongst all model classes
$ESC = $dice->create( 'Elasticsearch\Client' );

// quick example search query
$params['query']['firstName']='Allison';
$results = $ESC-search( $query);

--------------------------------------

proposed addition to Elasticsearch/ClientBuilder.php

    /**
     * Can supply first parm to Client::__construct() when invoking manually or with dependency injection
     * @return this->ransport
     *
     */
    public function getTransport()
    {
        return $this->transport;
    }

    /**
     * Can supply second parm to Client::__construct() when invoking manually or with dependency injection
     * @return this->endpoint
     *
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Can supply third parm to Client::__construct() when invoking manually or with dependency injection
     * @return this->registeredNamespacesBuilders
     *
     */
    public function getRegisteredNamespacesBuilders()
    {
        return $this->registeredNamespacesBuilders;
    }

**Comment by polyfractal** [comment]
Closing since the associated PR merged :)
