### ISSUE TITLE
No way to get stored fields?

### ISSUE THREAD

**Issue by iborodikhin** [elastic/elasticsearch-php#554]
### Any ability to get stored fields' values?
In ES prior to 5.0 there was parameter `fields` in search to get stored fields.

```json
    {
        "index" : "index",
        "type" : "type",
        "fields" : ["id"],
        "body" : {
            …
        }
    }
```

In ES 5.0+ parameter was renamed to `stored_fields`. By the way trying to request these parameters end with error «"fields" is not a valid parameter. Allowed parameters are…» or «"stored_fields" is not a valid parameter. Allowed parameters are…»

### Code snippet of problem

```php
$client = ElasticClientBuilder::fromConfig(['hosts' => $config['hosts']]);
try {
    var_dump($client->search([
        "index" => "my_index",
        "type" => "my_type",
        "fields" => ["id"], // or "stored_fields" => ["id"]
    ]));
} catch (\Exception $e) {
    var_dump($e->getMessage());
}
```

### System details

- PHP Version 5.6.18
- ES-PHP client version 5.1.3
- Elasticsearch version 5.2.2

**Comment by polyfractal** [comment]
Fixed in c0242e3, thanks for the report!
