### ISSUE TITLE
Put template not working

### ISSUE THREAD

**Issue by hermevf** [elastic/elasticsearch-php#567]
### Summary of problem or feature request

Put template function not working. The problem is on the file src/Elasticsearch/Endpoints/Template/Put.php line 48, the uri is wrong. it should be 

$uri  = "/_template/$templateId";

instead of 

$uri  = "/_search/template/$templateId";

### System details

- Operating System: Linux
- PHP Version: 5.6
- ES-PHP client version: 5.3
- Elasticsearch version: 5.2

**Comment by polyfractal** [comment]
Perhaps your local copy is on an old branch or something?  The endpoint appears to be correct at the moment: 

[Endpoints/Template/Put](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Template/Put.php#L48): `$uri  = "/_search/template/$templateId";`

**Comment by polyfractal** [comment]
Oh, I see.  You are probably wanting the Indices Template API.  That's under Endpoints/Indices/Templates/Put and is used:

```php
$client->indices()->putTemplate([...])
```
