### ISSUE TITLE
Issues with Scroll API after upgrade to 5.3

### ISSUE THREAD

**Issue by marv2097** [elastic/elasticsearch-php#573]
I have been using the scroll API with php client 5.0 and ES 5.2.1 with no issues. Since upgrading ES to 5.3 it now fails with the following error:

`
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse request body"}],"type":"illegal_argument_exception","reason":"Failed to parse request body","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token 'DnF1ZXJ5VGhlbkZldGNoHAAAAAAADUvZFnJJOXRndmI3UUVLVmdmX1RHaG10UlEAAAAAAArkWxZoQ1pFc3NJd1JDdVlVZXVxRU5xa3dRAAAAAAAKhKYWQmRjUkpOVXdSNjJkNjIzclRCX0NzQQAAAAAACih2Fl9IVFVUR1hWU0YtZ1lMTzg4dDVYWncAAAAAAAoimxZCNzZKcGdTcFJybUR2elNQM2p5YTNRAAAAAAAJkrUWeVdzTUhwQ0FUX3Vq...': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@148d95a1; line: 1, column: 257]"}},"status":400} in /usr/share/wsc/dev/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:610`

I have seen reports of other clients having similar issues with scroll in ES 5.3, see [here](https://github.com/elastic/elasticsearch-js/issues/522)

To recreate the issue, I created a simple script to based on the example code in the docs referenced in this link: https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_search_operations.html#_scrolling

The first request appears to work correctly but the subsequent call to the scroll api fails.

```php
#!/usr/bin/php
<?php

require_once("../vendor/autoload.php");

$client = Elasticsearch\ClientBuilder::create()
    ->setConnectionPool('\Elasticsearch\ConnectionPool\SniffingConnectionPool', [])
    ->setHosts(["1.2.3.4"])
    ->build();

$params = [
    "scroll" => "30s",          // how long between scroll requests. should be small!
    "size" => 50,               // how many results *per shard* you want back
    "index" => "my_index",
    "body" => [
        "query" => [
            "match_all" => new \stdClass()
        ]
    ]
];

// Execute the search
// The response will contain the first batch of documents
// and a scroll_id
$response = $client->search($params);

// Now we loop until the scroll "cursors" are exhausted
while (isset($response['hits']['hits']) && count($response['hits']['hits']) > 0) {

    // **
    // Do your work here, on the $response['hits']['hits'] array
    // **

    // When done, get the new scroll_id
    // You must always refresh your _scroll_id!  It can change sometimes
    $scroll_id = $response['_scroll_id'];

    // Execute a Scroll request and repeat
    $response = $client->scroll([
            "scroll_id" => $scroll_id,  //...using our previously obtained _scroll_id
            "scroll" => "30s"           // and the same timeout window
        ]
    );
}

?>
```
 
### System details

- Ubuntu 14.04.4 LTS
- PHP 7.0
- ES-PHP 5.0
- ES 5.3

**Comment by polyfractal** [comment]
Are you on ES-PHP 5.0 exactly?  Please try to upgrade to `v5.2.0` and report back, there were fixes to the scroll API recently: https://github.com/elastic/elasticsearch-php/commit/59b3c08

**Comment by marv2097** [comment]
Just checked the changelog and im using 5.1.3 so I will upgrade and see if the changes fix things. Cheers.

**Comment by marv2097** [comment]
Just checked the changelog and im using 5.1.3 upgrading to 5.2.0 has resolved the issues. Thanks @polyfractal

**Comment by polyfractal** [comment]
Great, happy to hear!  Closing! :)
