### ISSUE TITLE
Issue with scan/scroll search: size parameters not considered

### ISSUE THREAD

**Issue by gioialorusso** [elastic/elasticsearch-php#574]
Hi there,
I have a problem with scan search. Basically, it does not paginate results, returning to me all the hits. It is like it doesn't care about the size param. After the code, there are the details about my installation.
This is my code:
`

        $searchParams = array();
        $searchParams['index'] = 'my_index';
        $searchParams['body']        = $json_query;         //query with must - should
        $searchParams['search_type'] = 'scan';             
        $searchParams['scroll'] = '30s';              
        $searchParams['size'] = 10;              
        
        $response = $client->search($searchParams);       
         
        $hits_count = $response['hits']['total'];      //it says 82 (for example)

        while($hits_count > 0){
            $scrollParams = array(
                'scroll_id' => $response['_scroll_id'],
                'scroll'    => '30s'
            );
            $response = $client->scroll($scrollParams);
            $hits_count = count($response['hits']['hits']);
            if(!empty($response['hits']['hits'])){       //they are 82 records!
                    //do my things
            }

`
Details:
- OS: Ubuntu 12.04.5 LTS
- PHP version : 5.6
- ES-PHP client version: 2.2.2
- Elasticsearch version 1.5.2

**Comment by ezimuel** [comment]
This should be fixed with version 7.0.
