### ISSUE TITLE
Bulk Indexing crashes with exception

### ISSUE THREAD

**Issue by michaelrenda** [elastic/elasticsearch-php#577]
### Summary of problem or feature request

I'm trying to do bulk indexing of 1.2 million documents and tune the process for performance.
When I send bulk inserts in batches of 10,000, the entire set is indexed but performance is slow.  If I set the batch size to 15,000, indexing performance shows a 50% improvement.  But about 600k documents into the set, the function throws an exception.

Exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message ''

in /var/www/html/ecs-ingestion/project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:610

Stack trace:
#0 /var/www/html/ecs-ingestion/project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(273): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /var/www/html/ecs-ingestion/project/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /var/www/html/ecs-ingestion/project/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /var/www/html/ecs-ingestion/project/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /var/www/html/ecs-ingestion/project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(294): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#5 /var/www/html/ecs-ingestion/project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(171): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /var/www/html/ecs-ingestion/project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(100): Elasticsearch\Connections\Connection->performRequest('POST', '/_all/_bulk', Array, '{"index":{"_ind...', Array, Object(Elasticsearch\Transport))
#7 /var/www/html/ecs-ingestion/project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1503): Elasticsearch\Transport->performRequest('POST', '/_all/_bulk', Array, '{"index":{"_ind...', Array)
#8 /var/www/html/ecs-ingestion/project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(711): Elasticsearch\Client->performRequest(Object(Elasticsearch\Endpoints\Bulk))
#9 /var/www/html/ecs-ingestion/project/models/ForMDArticle.php(546): Elasticsearch\Client->bulk(Array)
#10 /var/www/html/ecs-ingestion/project/modules/formd/commands/IngestController.php(63): app\models\ForMDArticle->index_bulk_add_docs('formd_index', '5_Content_Artic...', Array)
#11 [internal function]: app\modules\formd\commands\IngestController->actionIndex('0', '45000', '15000')
#12 /var/www/html/ecs-ingestion/project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/html/ecs-ingestion/project/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/html/ecs-ingestion/project/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#15 /var/www/html/ecs-ingestion/project/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('', Array)
#16 /var/www/html/ecs-ingestion/project/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('formd/ingest', Array)
#17 /var/www/html/ecs-ingestion/project/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('formd/ingest', Array)
#18 /var/www/html/ecs-ingestion/project/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 /var/www/html/ecs-ingestion/project/yii(20): yii\base\Application->run()
#20 {main}

**Comment by polyfractal** [comment]
Hey, sorry for the delay.  Do you happen to have the exception message that ES is returning?

A 400 level exception means Elasticsearch thinks the request is bad in some capacity (usually syntax or similar).  There may be a bad document in there, or perhaps some edge-case that's causing the bulk's syntax to be bad?

**Comment by polyfractal** [comment]
Closing, feel free to reopen if you can provide some more details.
