### ISSUE TITLE
Argument must be an instance of Elasticsearch

### ISSUE THREAD

**Issue by OctaneInteractive** [elastic/elasticsearch-php#578]
### Summary of problem or feature request

When attempting to create an index, I'm getting the following error:

> Argument 1 passed to Elasticsearch\Client::__construct() must be an instance of Elasticsearch\Transport, array given, called in /redacted/Under-Cloud/application/modules/api/models/elasticsearch_model.php on line 23 and defined

> Argument 2 passed to Elasticsearch\Client::__construct() must be callable, none given, called in /Library/WebServer/Documents/development/PhpstormProjects/Under-Cloud/application/modules/api/models/elasticsearch_model.php on line 23 and defined

> Argument 3 passed to Elasticsearch\Client::__construct() must be of the type array, none given, called in /Library/WebServer/Documents/development/PhpstormProjects/Under-Cloud/application/modules/api/models/elasticsearch_model.php on line 23 and defined

All 3 are for:

> Filename: Elasticsearch/Client.php
> Line Number: 91

Then:

> Message: Undefined variable: endpoint
> Filename: Elasticsearch/Client.php
> Line Number: 94

With the same error for lines 95 to 101.

Then:

> Message: Undefined variable: registeredNamespaces
> Filename: Elasticsearch/Client.php
> Line Number: 102

### Code snippet of problem

I'm using the [Elasticsearch class provided by Auriga](https://www.aurigait.com/how-to-use-elastic-search-with-php-tutorial/), attempting to get it working with CodeIgniter 2.

In the root `index.php` file, I have:

```
require_once 'vendor/autoload.php';

use Elasticsearch\ClientBuilder;

if ( class_exists( 'ClientBuilder' ) )
	$client = ClientBuilder::create()->build();
```

I've tried several variations of the namespace and none have worked.

As for the error itself, line 23 is the last line of this method in the class file:

```
	public function connect() {
		$params = array();
		$params['hosts'] = array('localhost:9200');
		$params['connectionParams']['auth'] = array('USERNAME', 'PASSWORD', 'Basic');
		$this->_client = new Elasticsearch\Client($params);
	}
```
### System details

- Operating System: OS X El Capitan 10.11.6
- PHP Version: 5.6
- ES-PHP client version: ~5.0 (according to `composer.json`)
- Elasticsearch version: 5.3.0

**Comment by polyfractal** [comment]
Sorry for the delay on this.

I think the problem is the `connect()` function. It looks like that article was written with the older, 2.x version of the client.  In 5.x, the creation of a client has changed to using the builder that you have in your first snippet.

E.g. you just need to do:

```php
$hosts = ['192.168.1.1:9200'];              // Replace with your host
$client = ClientBuilder::create()           // Instantiate a new ClientBuilder
                    ->setHosts($hosts)      // Set the hosts
                    ->build();              // Build the client object

$response = $client->search([...]);  // Execute a search with the new client
```

You instantiate the client by using `ClientBuilder`.  You don't construct the client directly anymore using the constructor directly (e.g. `new Client(...)`).  It's technically possible to do that way, but it's an expert option because you have to instantiate all the internal bits (endpoints, transport, connection pool, etc)

**Comment by nkorojoseph** [comment]
```
<?php 

require_once 'vendor/autoload.php';
use Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()->build();

?>
```
