### ISSUE TITLE
Response missing arrays

### ISSUE THREAD

**Issue by D3faIt** [elastic/elasticsearch-php#580]
### Info

I followed this [Video](https://youtu.be/3xb1dHLg-Lk?t=4m12s) as a guide to get elasticsearch up and running with PHP, but reinstalled once I realized Elasticsearch had a version 5. I am unable to print or view the whole result. I can print the raw data, but i'm unable to go any deeper.

I'm running two servers. One main server (Webserver, PHP) and one secondary server (Calculations and searching, Elasticsearch).
If I'm correct, the searching server itself doesn't need PHP, cURL, or JSON. Main server is the one who needs it.
I installed it with the composer and followed the instructions here on github.
Database contains 689525 documents confirmed with POSTMAN application.

### To the code..

browse.php (users are accessing this file):
```
require_once('app/init.php');

$query = [
    'index' => '*',
    'type' => '*',
    'body' => [
        'query' => [
            'match' => [
                'title' => 'Whatever is written here will give the output below'
            ]
        ]
    ]
];

$raw = $client->search($query);
print_r($raw);
```

For some reason, the output seam to stay like this for whatever string I search for:

`Array ( [took] => 2 [timed_out] => [_shards] => Array ( [total] => 30 [successful] => 30 [failed] => 0 ) [hits] => Array ( [total] => 0 [max_score] => [hits] => Array ( ) ) )`

init.php (Had to add allowBadJSONSerialization() because of error):

```
use Elasticsearch\ClientBuilder;

require 'vendor/autoload.php';

$hosts = [
    "192.168.1.130:9200"
];
$client = ClientBuilder::create()
    ->setHosts($hosts)
    ->allowBadJSONSerialization()
    ->build();
```
### Summarize

I have tried many different type of searches in this PHP document, and also tried $results = $raw['hits']['hits']['source']['title']; but only got a blank screen. I've tried running PHP7, which didn't help and have looked through the installation guide enough now.
I've been doing this all day and don't know if it's just me, or if more people have experienced this. However, I can't say the installation went fully clean, because of the tutorial on youtube. So I reinstalled it and looked closely to the installation guide on this page.

Is it something I am missing or something else I can do to list 40 documents properly?

### Server 1

- Operating System: Debian 8 (Jessie)
- PHP Version: 5.6.30
- ES-PHP client version: 5.2.0
- Elasticsearch: Not installed

### Server 2

- Operating System: Debian 8 (Jessie)
- PHP Version: 5.6.29
- ES-PHP client: Not installed
- Elasticsearch: 5.4.0

## UPDATE

Thank god I atleast figured out SOMETHING about the issue. It seems like it didn't like that i put * as index and type. So to either remove them, or change them to a working index,type will fix the problem.
For anyone else having this problem, this is the basic fix:
```
$query = [
    'body' => [
        'query' => [
            'match' => [
                'title' => 'Your search'
            ]
        ]
    ]
];
```
or
```
$query = [
    'index' => 'your valid index',
    'type' => 'your valid type',
    'body' => [
        'query' => [
            'match' => [
                'title' => 'Your search'
            ]
        ]
    ]
];
```

**Comment by polyfractal** [comment]
Multi-index search docs are here: https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

For search, you can use `_all` instead of `*` if you want to search all the indices.  Or don't include 'index'.
