### ISSUE TITLE
verifyNotNullOrEmpty method filter not clear

### ISSUE THREAD

**Issue by Xieyongmin** [elastic/elasticsearch-php#587]
In the src/Elasticsearch/Client.php file

```php
private function verifyNotNullOrEmpty($name, $var)
    {
        if ($var === null) {
            throw new InvalidArgumentException("$name cannot be null.");
        }

        if (is_string($var)) {
            if (strlen($var) === 0) {
                throw new InvalidArgumentException("$name cannot be an empty string");
            }
        }

        if (is_array($var)) {
            if (strlen(implode("", $var)) === 0) {
                throw new InvalidArgumentException("$name cannot be an array of empty strings");
            }
        }
    }
```

if $var is '      '，strlen($var) === 0 is not true.
and if $var is array('', ' ', '   ', '          '), strlen(implode("", $var)) === 0 is not true

# Solution

strlen( **trim(** $var)) === 0

strlen( **trim(** implode("", $var))) === 0

**Comment by polyfractal** [comment]
We can't trim strings because it's a legitimate character that Elasticsearch will accept.  So `' '` (space) is distinct from `''` (no space).
