### ISSUE TITLE
Bad Request 400 Failed while creating indexer in azure search..

### ISSUE THREAD

**Issue by chackri** [elastic/elasticsearch-php#588]
{"error":{"code":"","message":"Data source does not contain column 'id', which is required because it maps to the document key field 'id' in the index 'chackri'. Ensure that the 'id' column is present in the data source, or add a field mapping that maps one of the existing column names to 'id'."}}

**Comment by polyfractal** [comment]
Azure Search uses Elasticsearch internally, but the API that it exposes is not the same API that Elasticsearch uses.  So this client won't work for you... you'll need to find a client/library that is designed for Azure Search specifically.

Sorry!
