### ISSUE TITLE
How to use guzzle mock responses to do proper unit testing with this library?

### ISSUE THREAD

**Issue by pwaterz** [elastic/elasticsearch-php#589]
Can you use guzzle mock responses to do unit testing with this library?

**Comment by polyfractal** [comment]
I don't know, to be honest.  Probably not.  

This client doesn't really use Guzzle as most folks know, it uses [RingPHP](https://github.com/guzzle/RingPHP), a sub-component of Guzzle 5.0.  I doubt Guzzle 6 mock responses will work with RingPHP responses.

**Comment by pwaterz** [comment]
It appears you can use mock responses with Ring, http://docs.guzzlephp.org/en/5.3/handlers.html. Going to give it a shot, will report back with my findings.

**Comment by pwaterz** [comment]
Figured it out, this should be documented.
```
// The connection class requires 'body' to be a file stream handle
// Depending on what kind of request you do, you may need to set more values here
$handler = new MockHandler([
  'status' => 200, 
  'transfer_stats' => [
     'total_time' => 100
  ], 
  'body' => fopen('somefile.json')
]);
$builder = ClientBuilder::create();
$builder->setHosts(['somehost']);
$builder->setHandler($handler);
$client = $builder->build();
// Do a request and you'll get back the 'body' response above 
```

**Comment by phayes** [comment]
Re-opening for documentation that should be added to the elasticsearch-php library

**Comment by polyfractal** [comment]
Wanna send a PR?  :)

**Comment by pwaterz** [comment]
https://github.com/elastic/elasticsearch-php/pull/591/files

**Comment by polyfractal** [comment]
Merged!  Thanks! :)

**Comment by pwaterz** [comment]
woot!
