### ISSUE TITLE
WARN Content type detection for rest requests is deprecated

### ISSUE THREAD

**Issue by erikvanderschaaf** [elastic/elasticsearch-php#593]
I'm seeing a lot of these warnings in our logs

> [2017-06-21T09:36:18,650][WARN ][org.elasticsearch.deprecation.rest.RestController] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

We're running Elastic version 5.3.2 in the cloud, with elasticsearch-php version 5.2.0

This issue is created as a request from @polyfractal here:
https://discuss.elastic.co/t/warn-content-type-detection-for-rest-requests-is-deprecated/90269

**Comment by polyfractal** [comment]
Can you show your code that creates the client, and perhaps the section of code that is sending the requests which trigger this warning?

**Comment by erikvanderschaaf** [comment]
Ofcourse, but it's nothing fancy, just create the builder with one host:

`Elasticsearch\ClientBuilder::create()->setHosts( [ $sUrl ] )->build();`

**Comment by polyfractal** [comment]
Ok, I'll dig into this to see if I can recreate locally.  Do you happen to know which endpoints are throwing this? All endpoints?  Just search?

**Comment by erikvanderschaaf** [comment]
No idea which endpoints ar throwing this, I don't see the warning in my own scripts. They only appear in the cluster logs in the elastic cloud.

**Comment by rubendob** [comment]
Hi

we are seeing the same issues here in an environment with all packages involved updated up to 5.4.X where we have beaver + redis + logstash + elasticsearch as workflow. And we are getting same logs.

Just to help to detect the issue guys.

Regards,
R

**Comment by polyfractal** [comment]
Roger, thanks.  I must have something incorrect with the header syntax, or a regression of some sort.  This is on my todo list for today, will update as I find out more :)

**Comment by polyfractal** [comment]
Hmm, well I think it's going to take some more sleuthing.  I can recreate this locally if I remove the content-type headers manually (https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ClientBuilder.php#L476-L490).  Otherwise, the server doesn't complain about missing headers.

This was tagged in ES-PHP 5.1.2.  Can you confirm you're on that version or greater?

I'll spin up a cloud instance to see if there is something going on there.

Is it possible there is something else that is accessing the cluster?  Like an old version of Kibana, or a script manually curl'ing, nagios setup, etc that might not be sending the right headers?

**Comment by erikvanderschaaf** [comment]
There is one script that's running each day at 1:05 (with our timezone that would be 23:05 in the logs), that does `shell_exec( 'curl -s ' . $url . '/_aliases' )`, but this is not giving that warning.

Actually the last time the warning occured was june 28th as 13:13.

**Comment by erikvanderschaaf** [comment]
And about 50 minutes after that comment they were back ;')

**Comment by arconen** [comment]
@polyfractal Are you sure that it should be a 'Content-type'? Seems to me it must be 'Content-Type'.
https://tools.ietf.org/html/rfc7231#section-3.1.1.5
It looks familiar I guess. Bad typing 😸

**Comment by arconen** [comment]
@polyfractal Welcome ;)

**Comment by polyfractal** [comment]
Changed here: b8ad96cec1d7cdf877e9448bd155d84010d9e82b

**Comment by lulco** [comment]
can you merge this also to version 5.3?

**Comment by ezimuel** [comment]
Solved by @polyfractal with commit https://github.com/elastic/elasticsearch-php/commit/b8ad96cec1d7cdf877e9448bd155d84010d9e82b
