### ISSUE TITLE
Add new node to the cluster

### ISSUE THREAD

**Issue by devika514** [elastic/elasticsearch-php#596]
Hi,
Currently I am running elasticserch cluster with one master node in localhost:9200, I want to add new data node in the same system under same cluster.Do we need to add multiple elsacticsearch.yml files to add multiple nodes?what are the configuration changes need to do in current elasticsearch.yml file? I referred tons of sites but still I am not getting clear idea to create a new node in a cluster.Please help

**Comment by polyfractal** [comment]
I think this question would be best asked on the Elasticsearch forums: https://discuss.elastic.co/c/elasticsearch

Issues here should revolve around the ES-PHP client :)
