### ISSUE TITLE
MsearchTemplate endpoint implementation

### ISSUE THREAD

**Issue by arconen** [elastic/elasticsearch-php#599]
### MsearchTemplate endpoint implementation

/_msearch/template is a beautiful and useful feature in Elasticsearch 5.x, and I have no idea why this endpoint isn't implemented yet here.

**Comment by polyfractal** [comment]
++ Looks like it was just an oversight.  I'll try to add it soon :)

**Comment by arconen** [comment]
I've got an error when I was trying to call msearchTemplate method
```php
$request = [
	'body' => [
		[
                    'index' => 'base'
                ],
                [
                    'file' => 'basetmpl',
                    'params' => [
			'baselist' => [
                        	'baseid' => [
                            		['value' => 1],
                            		['value' => 2, 'isLast' => true]
                        	]
                    	]
		    ]
                ],
                [
                    'index' => 'target'
                ],
                [
                    'file' => 'targettmpl',
                    'params' => [
			'targetlist' => [
                        	'targetid' => [
                            		['value' => 11],
                            		['value' => 12, 'isLast' => true]
                        	]
                    	]
		    ]
                ]
	]
];
$result = $this->client->msearchTemplate($request);
```

Too few arguments to function Elasticsearch\Endpoints\MsearchTemplate::__construct(), 0 passed in .../vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 531 and exactly 1 expected

Seems you forgot to change one line in ClientBuilder. 
[ClientBuilder.php#L512](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ClientBuilder.php#L512)
```php
                if ($class === 'Bulk' || $class === 'Msearch' || $class === 'MPercolate') {
                    return new $fullPath($serializer);
                } else {
                    return new $fullPath();
                }
```
should be
```php
                if ($class === 'Bulk' || $class === 'Msearch' || $class === 'MsearchTemplate' || $class === 'MPercolate') {
                    return new $fullPath($serializer);
                } else {
                    return new $fullPath();
                }
```
Am I right?

**Comment by polyfractal** [comment]
Argh, yep, you're right.  Wanna send a PR?

If not, I'll take care of this tomorrow.  Sorry about that!

**Comment by arconen** [comment]
@polyfractal I've sent two PR as you mentioned above, but they are still open. Something wrong?

**Comment by polyfractal** [comment]
I'm just bad, that's all :(  Sorry for the delay, been very busy around here.  Merged!  Thanks again
