### ISSUE TITLE
Not tracking on NewRelic

### ISSUE THREAD

**Issue by brayann** [elastic/elasticsearch-php#600]
### Summary of problem or feature request

I'm not really sure if this is something regarding your library (I'm sorry if it isn't), but for some reason NewRelic doesn't consider requests made to the elastic search as an External Service or just as a DB. 
It does recognize for example our Redis instance as a DB, which is external (Elasticache), and also other external services that we call using either curl or guzzle.
I searched for it on the issues and didn't find anything related, it might be a dumb question but I'm really not sure how to do it. I'm considering using Newrelic's functions on my PHP code to try to track it down manually.

### System details

- Operating System: Ubuntu
- PHP Version: 7.0.1
- ES-PHP client version: 5.1.3
- Elasticsearch version: 5.1.2 (we use http://elastic.co)

**Comment by polyfractal** [comment]
Hey, sorry for the delay (was out of town and then got sick).

To be honest, I really have no idea.  I'll do some reading to see if there is something that the client needs to do to show up as to NewRelic.  It may be something that they do internally, like watching curl requests and classifying them based on protocol/content/etc. 

Not sure, sorry :/  I'll let you know if I discover anything

**Comment by brayann** [comment]
No worries, thanks for looking into it.

**Comment by fedeisas** [comment]
I've been digging into this. Guzzle wraps curl connections and it's been a know issue with Newrelic for a long time. But now, the New Relic team added a `guzzle` feature on their agent, which I think tracks requests from objects extending from the `GuzzleHttp\Client`. Instead of using the Guzzle client, this library calls the handlers directly:

```
if (extension_loaded('curl')) {
    $config = array_merge([ 'mh' => curl_multi_init() ], $multiParams);
    if (function_exists('curl_reset')) {
        $default = new CurlHandler($singleParams);
        $future = new CurlMultiHandler($config);
    } else {
        $default = new CurlMultiHandler($config);
    }
} else {
    throw new \RuntimeException('Elasticsearch-PHP requires cURL, or a custom HTTP handler.');
}
```

I guess the fix is to use _plain_ Guzzle.

**Comment by fedeisas** [comment]
Found this to be relevant: https://lukewaite.ca/posts/2017/07/15/php-newrelic-instrumentation-elasticseach.html

**Comment by brayann** [comment]
Oh that's awesome thanks @fedeisas I'll dig into it. One question though, where do you use/put the code you pasted on your first comment?

**Comment by fedeisas** [comment]
@brayann that code is actually from this package's source code. But if you go to the link I posted on the previous message, you'll find a library and the snippet to use Guzzle with a RingPHP wrapper.

**Comment by ezimuel** [comment]
Solved [here](https://lukewaite.ca/posts/2017/07/15/php-newrelic-instrumentation-elasticseach.html). I'm refactoring `elasticsearch-php` for version 8 to use PSR-7 and PSR-18 standards. That means, this issue will not be relevant anymore.

**Comment by fedeisas** [comment]
@ezimuel could [this release](https://github.com/elastic/elasticsearch-php/releases/tag/v7.5.2) related to this issue? I can no longer use the [lukewaite/ringphp-guzzle-handler](https://github.com/lukewaite/ringphp-guzzle-handler) because it requires `guzzlehttp/ringphp` 😢

**Comment by ezimuel** [comment]
@fedeisas unfortunately [guzzlehttp/ringphp](https://github.com/guzzle/RingPHP) is an abanoned project. I fork it into [ezimuel/ringphp](https://github.com/ezimuel/ringphp) and from `elasticsearch-php 7.5` we are using it as replacement.

**Comment by fedeisas** [comment]
Are you still moving away from RingPHP on the next version? I’ll be glad to contribute.

**Comment by ezimuel** [comment]
@fedeisas yes, I'm moving away from RingPHP. I' would like to support PSR standards, see https://github.com/elastic/elasticsearch-php/issues/990 for comments and feedback. If you want to contribute you are more than welcome. I'll start working on it soon, on the master branch that is for the next major version Elasticsearch 8. Thanks!
