### ISSUE TITLE
update_all_type not working

### ISSUE THREAD

**Issue by nevercodealone** [elastic/elasticsearch-php#601]
Hi,

i am using the actual version. When i do an update

```
$params = [
                    'index' => $index,
                    'type' => $fileName,
                    'body' => [
                        'update_all_types' => true,
                        $fileName => [
                            '_source' => [
                                'enabled' => true
                            ],
                            'properties' => [
                                'title' => [
                                    'type' => 'text',
                                    'fielddata' => true
                                ]
                            ]
                        ]
                    ]
                ];
```

`$this->client->indices()->putMapping($params);`

It is not working on kibana

```
PUT akeneo/_mapping/kp?update_all_types
{
  "properties": {
    "title": { 
      "type":     "text",
      "fielddata": true
    }
  }
}
```

Works fine. How can i use the update_all_type param?

**Comment by polyfractal** [comment]
Since the parameter is in the query string (`PUT akeneo/_mapping/kp?update_all_types`), you need to supply that parameter outside of the "body" field, not inside.  E.g.:

```
```
$params = [
    'index' => $index,
    'type' => $fileName,
    'update_all_types' => true,  // <--- here
    'body' => [
        $fileName => [
            '_source' => [
                'enabled' => true
            ],
            'properties' => [
                'title' => [
                    'type' => 'text',
                    'fielddata' => true
                ]
            ]
        ]
    ]
];
```
```

**Comment by nevercodealone** [comment]
I also tried that i mean but i check tomorrow

**Comment by polyfractal** [comment]
Closing, feel free to reopen if you have more info about your problem.
