### ISSUE TITLE
why i can't use match for multiple fields?????

### ISSUE THREAD

**Issue by chaotianwww** [elastic/elasticsearch-php#602]
### System details

- Operating System  windows 10
- PHP Version    7
- ES-PHP client version  ^5.2
- Elasticsearch version  5.4.3

{"query":{"bool":{"should":{"match":{"nick_name":"\\u6444\\u5f71","alias":"nsywx"}}}}}

why??????
it give me the error that it is {"error":{"root_cause":[{"type":"parsing_exception","reason":"[match] query doesn't support multiple fields, found [nick_name] and [alias]","line":1,"col":73}],"type":"parsing_exception","reason":"[match] query doesn't support multiple fields, found [nick_name] and [alias]","line":1,"col":73},"status":400}

**Comment by nmz787** [comment]
I'm also experiencing this... can't understand the top hits on Google that try to answer how to use multiple terms in a match. Strange why the "discover" syntax is so different from the JSON.

**Comment by polyfractal** [comment]
@nmz787 the syntax isn't any different from the JSON, barring a few exceptions around how empty objects are handled.

If you paste your PHP code and I can help find the problem.
