### ISSUE TITLE
Not able to skip the content from elastic search 

### ISSUE THREAD

**Issue by aankitkumar31** [elastic/elasticsearch-php#603]
i am using elastic search to get the content but when i set from its not skipping the records whereas size is working fine

$params["body"]["from"] = 150; // set from
$params["body"]["size"] = 20; //set size

$results = $this->_client->search($params);
$result = $this->get_elastic_data($results);
$total = $this->get_elastic_total_data($results);

please help me to get rid out of it.

**Comment by polyfractal** [comment]
Can you show the query you are executing?  How are you determining that it isn't skipping documents?

**Comment by polyfractal** [comment]
Closing, feel free to reopen with more details. :)
