### ISSUE TITLE
Consider dropping HHVM support

### ISSUE THREAD

**Issue by mhujer** [elastic/elasticsearch-php#611]
I propose removing HHVM from the TravisCI build matrix because:
- The 5.0 build does [not run on HHVM at all](https://travis-ci.org/elastic/elasticsearch-php/jobs/255754000).
- The library itself probably [cannot be installed in HHVM (Travis' Ubuntu Trusty)](https://travis-ci.org/mhujer/elasticsearch-php/jobs/261278633)
- not many people [use HHVM anyway](https://seld.be/notes/php-versions-stats-2017-1-edition) (from those who use Composer)

Big frameworks are also dropping support for HHVM: 
- Symfony (https://symfony.com/blog/symfony-4-end-of-hhvm-support)
- Zend Framework (https://framework.zend.com/blog/2017-06-06-zf-php-7-1.html)
- Doctrine (https://github.com/doctrine/doctrine2/issues/6424)

What is your opinion on this @polyfractal ?

**Comment by polyfractal** [comment]
:+1: I'm for it.  I haven't talked to anyone using ES-PHP with HHVM, either in person or via an issue.  And it's never been a priority to support (obviously, given the failing build :) )

Let's drop it.

**Comment by mhujer** [comment]
I've created PRs for `5.0` (#615) and for `master` (#616)

**Comment by polyfractal** [comment]
Merged!
