### ISSUE TITLE
Add helper function to escape query

### ISSUE THREAD

**Issue by tomsommer** [elastic/elasticsearch-php#620]
As per https://stackoverflow.com/questions/33845230/escape-elasticsearch-special-characters-in-php it would be nice with an 'official' and maintained function to help escape reserved characters

**Comment by polyfractal** [comment]
I'm not against such a thing, but I must admit I'm a bit confused what they are trying to escape?  Field names?  Index names?  Characters in query string?

E.g. you can absolutely have braces (`{`) in an index name and a query_string query.  You can have `&` in query_string but not index name.  `OR` is a reserved term in query_string but unimportant anywhere else, etc etc.

That list just looks like a random collection to me :)

To your question though, we could maybe consider a function escape `query_string` strings.  There's no such escaping for index or field names though, as Elasticsearch rejects the character itself and there's no way to escape it.

**Comment by tomsommer** [comment]
I was thinking escaping characters in a query_string

**Comment by polyfractal** [comment]
Ah gotcha. That's doable. I'll add something when I get a chance, unless you want to submit a PR first :)

**Comment by hlorofos** [comment]
If someone is going to implement this, just keep in mind

https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-query-string-query.html
> < and > can’t be escaped at all. The only way to prevent them from attempting to create a range query is to remove them from the query string entirely.

So, the answer from Stackoverflow might be not 100% correct

**Comment by bhglove** [comment]
I would love this

**Comment by preeteshjain** [comment]
A function like this works:

```php
function escapeElasticReservedChars($query) {
    $regex = "/[\\+\\-\\=\\&\\|\\!\\(\\)\\{\\}\\[\\]\\^\\\"\\~\\*\\<\\>\\?\\:\\\\\\/]/";
    return preg_replace($regex, addslashes('\\$0'), $query);
}
```

Found here: https://stackoverflow.com/a/33846134

**Comment by ezimuel** [comment]
I'll add this feature in 8.0.0 version.

**Comment by Fossil01** [comment]
Please add this feature :-)

**Comment by arnisjuraga** [comment]
Just a quick note. In PHP You must pass or define string variable with single quotes, otherwise it will be decoded incorrectly for e.g. backslashes (obviously).

instead of 

```php
 $query = "windows\sytem";
```

must be 

```php
 $query = 'windows\sytem';

escapeElasticReservedChars($query);
```

**Comment by mikkorantalainen** [comment]
See fixed escape function at https://stackoverflow.com/a/68389722/334451

**Comment by mikkorantalainen** [comment]
Note that **Elasticsearch has two different query escape formats**:
- "Simple query string" syntax: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-syntax
- "Query string" syntax: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-query-string-query.html#_reserved_characters

**Comment by mikkorantalainen** [comment]
I think "query string" should be encoded like this:
```
function escapeElasticSearchReservedChars(string $string): string
{
    return preg_replace(
        [
            '_[<>]+_',
            '_[-+=!(){}[\]^"~*?:\\/\\\\]|&(?=&)|\|(?=\|)_',
        ],
        [
            '',
            '\\\\$0',
        ],
        $string
    );
}
```

but "simple query string" should be encoded like this:
```
function escapeElasticsearchSimpleQueryString(string $s)
{
	# https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-syntax
	#
	#	The simple_query_string query supports the following operators:
	#
	#	+ signifies AND operation
	#	| signifies OR operation
	#	- negates a single token
	#	" wraps a number of tokens to signify a phrase for searching
	#	* at the end of a term signifies a prefix query
	#	( and ) signify precedence
	#	~N after a word signifies edit distance (fuzziness)
	#	~N after a phrase signifies slop amount
	#
	#	To use one of these characters literally, escape it with a preceding backslash (\).
	return preg_replace(
		'#[-+|"*()~\\\\]#',
		'\\\\$0',
		$s
	);
}
```
