### ISSUE TITLE
How do I set the curl option?

### ISSUE THREAD

**Issue by ztj1993** [elastic/elasticsearch-php#621]
I tried to set the curl option, and checked all the documents and searched for issues, but found no relevant documentation for setting up curl. I need to configure proxy in my curl.

                        'CURLOPT_PROXY' => '0.0.0.0',
                        'CURLOPT_PROXYPORT' => 6001,
                        'CURLOPT_PROXYUSERPWD' => 'user:pwd'

The above content comes from software translation!

**Comment by polyfractal** [comment]
Sorry, it's not well documented at the moment.  You can do it on a per-request basis by using the `['client']['curl']` param:

```php
$client = Elasticsearch\ClientBuilder::create()->build();
$params = [
    'index' => 'test',
    'type' => 'test',
    'body' => [
        'query' => [
            'match_all' => []
        ]
    ],
    'client' => [
        'curl' => [
            CURLOPT_PROXY => '0.0.0.0',
            CURLOPT_PROXYPORT => 6001,
            CURLOPT_PROXYUSERPWD => 'user:pwd'
        ]
    ]
];
$client->search($params);
```

Or set it globally using:

```php
$clientOptions = [
    'client' => [
        'curl' => [
            CURLOPT_PROXY => '0.0.0.0',
            CURLOPT_PROXYPORT => 6001,
            CURLOPT_PROXYUSERPWD => 'user:pwd'
        ]
    ]
];
$client = Elasticsearch\ClientBuilder::create()
  ->setConnectionParams($clientOptions)
  ->build();

```

**Comment by ztj1993** [comment]
@polyfractal Thank you!
