### ISSUE TITLE
[TEST] Unit tests should not depend on running cluster

### ISSUE THREAD

**Issue by mhujer** [elastic/elasticsearch-php#625]
They should be mocked instead - see https://github.com/elastic/elasticsearch-php/pull/618#issuecomment-323816444

**Comment by polyfractal** [comment]
Beat me to it :)

**Comment by polyfractal** [comment]
Moved one of the tests to a dedicated file, although it would still be good to have similar mocked tests.

**Comment by ezimuel** [comment]
Outdated issue
