### ISSUE TITLE
Sniffing function not working properly

### ISSUE THREAD

**Issue by ProFire** [elastic/elasticsearch-php#629]
### Summary of problem

The sniff function isn't picking the other nodes in the cluster when the connectionpool is set to \Elasticsearch\ConnectionPool\SniffingConnectionPool

The server is returning the host as 172.25.120.23:9200 format whenever a sniff function is done on Elasticsearch\Connections\Connection::sniff()

When Elasticsearch\ConnectionPool\SniffingConnectionPool::parseClusterState() is executed, the host and port is not properly captured due to wrong $pattern.

### Code snippet of problem

The wrong pattern on line 131 of Elasticsearch\ConnectionPool\SniffingConnectionPool
```php
$pattern       = '/\/([^:]*):([0-9]+)\]/';
```

Results in preg_match not matching the hosts 172.25.120.23:9200 on line 137 of Elasticsearch\ConnectionPool\SniffingConnectionPool
```php
if (preg_match($pattern, $node[$schemaAddress], $match) === 1) {
```
Regex Example: http://regexr.com/3gjoo

### Proposed Change

I propose a change of regex on line 131 of Elasticsearch\ConnectionPool\SniffingConnectionPool
```php
$pattern       = '/([^:]*):([0-9]+)/';
```
Regex Example: http://regexr.com/3gjor

### Environment
ElasticSearch: 2.0.2
PHP: 7.1

**Comment by polyfractal** [comment]
What version of Elasticsearch-PHP are you using?

It does look like the format has changed slightly. Would you mind posting the output of your Node Info API (feel free to sanitize addresses/sensitive details)?  I'd like to see if the output is different from 5.x, and how far changes need to be backported.

**Comment by ProFire** [comment]
Here's the sample of the sanitized output

{
	"cluster_name": "es2_digital",
	"nodes": {
		"bIeDcsdfv7JRo": {
			"name": "g123",
			"transport_address": "172.25.120.23:9300",
			"host": "172.25.120.23",
			"ip": "172.25.120.23",
			"version": "2.0.2",
			"build": "6abf5d8",
			"http_address": "172.25.120.23:9200",
			"attributes": {
				"master": "false"
			}
		},
	}
}

I'm using the 5.x version of elasticsearch-php

**Comment by ProFire** [comment]
Here's the sample of the sanitized output

{
	"cluster_name": "es2_digital",
	"nodes": {
		"bIeDcsdfv7JRo": {
			"name": "g123",
			"transport_address": "172.25.120.23:9300",
			"host": "172.25.120.23",
			"ip": "172.25.120.23",
			"version": "2.0.2",
			"build": "6abf5d8",
			"http_address": "172.25.120.23:9200",
			"attributes": {
				"master": "false"
			}
		},
	}
}

I'm using the 5.3 version of elasticsearch-php

**Comment by ProFire** [comment]
I downgraded elasticsearch-php to 2.3.0 and noticed that the code is the same. I still can't sniff.

**Comment by polyfractal** [comment]
This should be fixed. I'll tag a release in a bit... need to look after something else first.
