### ISSUE TITLE
Multiple Indices queries

### ISSUE THREAD

**Issue by titlebaby** [elastic/elasticsearch-php#630]
### Summary of problem or feature request

Multiple Indices queries，I want to use wildcards, for example: 
```test* or  *test or te*t or *test*```, but I get a error.
```
"error:{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [taddress_m*], must not contain the following characters [ , \", *, \\, <, |, ,, >, /, ?]","index_uuid":"_na_","index":"taddress_m*"}],"type":"invalid_index_name_exception","reason":"Invalid index name [taddress_m*], must not contain the following characters [ , \", *, \\, <, |, ,, >, /, ?]","index_uuid":"_na_","index":"taddress_m*"},"status":400}"
```
### Code snippet of problem
 ```
 $params['index'] = 'taddress_m*';
 $params['type'] = "taddress_m";
 $params['_id'] = $id;
```
For now, use " $params['index'] ='_all'" ??? 

### System details
```
array:4 [
  "index" => "taddress_m*"
  "type" => "taddress_m"
  "_id" => "5680a5f7b7522a0448b5d7c2"
  "body" => array:1 [
    "doc" => array:1 [
      "Z010001" => 1
    ]
  ]
]
```

- Operating System centos
- PHP Version 7.1
- ES-PHP client version 
- Elasticsearch version 6.0.0

**Comment by polyfractal** [comment]
Can you show the full search request code?  I think you may be accidentally trying to create an index rather than search it.

Multi-index search with wildcards should be allowed: https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

**Comment by jihadadulrazaqjasim** [comment]
I have a question regarding this, there might be multiple matches while I am searching multiple indices, how to get the index names that the search matches with its field.

E.g. I have 3 different schools (3 indices), each has some students inside (each student is a document), I have a field called "student name" in each document and I want to search for the student names in all documents, if I found it then I want to know the index name.

please your support it's important for me
