### ISSUE TITLE
terminate_after not allowed in Count endpoint

### ISSUE THREAD

**Issue by brstgt** [elastic/elasticsearch-php#631]
### Summary of problem or feature request

terminate_after in the count api is supported by ES (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html) but not allowed in the PHP client.

### Code snippet of problem

Suggested fix (sorry, working on code managerd by composer):

```
Index: vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/Count.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/Count.php	(revision f0854e03ef588a5940281181822eb42c22ed24e2)
+++ vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/Count.php	(revision 0785ac139cd421a45f18399b67cc8a75fb1be72c)
@@ -72,7 +72,8 @@
             'lowercase_expanded_terms',
             'analyze_wildcard',
             'lenient',
-            'lowercase_expanded_terms'
+            'lowercase_expanded_terms',
+            'terminate_after'
         );
     }
```

**Comment by polyfractal** [comment]
++ want to send a PR?

If not I'll take care of it later today or tomorrow when I get a chance.

**Comment by brstgt** [comment]
I would but I don't wanna sign a contract for a one-liner.

2017-08-23 15:28 GMT+02:00 Zachary Tong <notifications@github.com>:
