### ISSUE TITLE
Sorting does not work

### ISSUE THREAD

**Issue by glodov** [elastic/elasticsearch-php#637]
### Summary of problem or feature request

Sorting function does not work.
Without sorting it does work.

You can get my code from [https://github.com/glodov/elastic-wrapper](https://github.com/glodov/elastic-wrapper)

To set it up run:
```
php tests/index.php
php tests/sorting-issue.php
```

### Code snippet of problem

Here is my query:

```json
{
    "index": "indexed-auto",
    "type": "auto",
    "body": {
        "query": {
            "bool": {
                "must": {
                    "multi_match": {
                        "query": "mini",
                        "fields": [
                            "vendor",
                            "model"
                        ]
                    }
                },
                "filter": {
                    "terms": {
                        "year": [
                            2010,
                            2011,
                            2012
                        ]
                    }
                }
            }
        },
        "sort": [
            {
                "year": "asc"
            },
            "_score"
        ]
    }
}
```

### System details

MacOS Sierra
Php 7.0.20
ES php ^5.3
ES 5.5.1

**Comment by polyfractal** [comment]
Hi, I'm afraid I don't have the bandwidth to download and run your code to find the problem.  I can help if you provide the full PHP request that you are executing with the client (e.g the `$params` you are passing to `$client->search($params)`.

Also, can you define "not work" ?  No hits returned?  Hits aren't sorted?

You likely have a syntax error with your sort parameter.  Note that it is an array of objects, so you'll have to construct it similarly in PHP. See: https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/php_json_objects.html#_arrays_of_objects

**Comment by glodov** [comment]
Not working means error:
```
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: 
{
  "error":
    {
      "root_cause":
        [
          {
            "type": "parsing_exception",
            "reason": "request does not support [sort]",
            "line": 1,
            "col": 134
          }
        ],
      "type": "parsing_exception",
      "reason": "request does not support [sort]",
      "line": 1,
      "col": 134
    },
  "status":400
} 
in /Users/yaroslav/Sites/yaro/elastic-wrapper/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:610
```

The query params:
```json
{
  "index": "indexed-auto",
  "type": "auto",
  "body": {
    "query": {
      "bool": {
        "must": {
          "multi_match": {
            "query": "mini",
            "fields": [
              "vendor",
              "model"
            ]
          }
        },
        "filter": {
          "terms": {
            "year": [
              2010,
              2011,
              2012
            ]
          }
        }
      }
    },
    "sort": [
      {
        "year": "asc"
      },
      "_score"
    ]
  }
}
```

**Comment by polyfractal** [comment]
Can you show the complete snippet of code where you are executing the search?  The search endpoing does indeed support `sort` parameter, so there must be something else going on here.

The 400 coming back from Elasticsearch essentially means that whatever endpoint you're calling, it doesn't support `sort`.  So the code must be calling a different endpoint entirely is my guess.

Or there is a really terrible bug in the client, but the tests are passing which should have turned up something as big as sorting being broken :)

**Comment by glodov** [comment]
This is why I added script on github, so if you get clone and go through
instructions you can face this bug.
Everything you need is in repository: database (CSV file) which will be
indexed by elastic and script to search with sort which SHOULD throw an
error.

------------------------------

Yaroslav Glodov
E-mail: glodov@gmail.com

**Comment by glodov** [comment]
You can get my code from [https://github.com/glodov/elastic-wrapper](https://github.com/glodov/elastic-wrapper)

To set it up run:
```
php tests/index.php
php tests/sorting-issue.php
```

**Comment by polyfractal** [comment]
Like I said before, I really don't have time to debug other people's code.  I'm happy to help assist with problems if you can present debugging information on the ticket, but that's a lot different from sifting through a repository of unfamiliar code trying to find a problem.

If I were to guess, the problem is that you're calling the [Count API](https://github.com/glodov/elastic-wrapper/blob/master/src/Search.php#L43) with [sorting parameters](https://github.com/glodov/elastic-wrapper/blob/master/src/Search.php#L170).  Count does not support sorting because no hits are returned.

If you need any further assistance, please provide the relevant information: the snippet of code where the error is occurring, the `$params` that went into the API, the `verbose` output from the response, etc.  Thanks :)

**Comment by glodov** [comment]
Sorry, but I did not get what you mean by a snippet of code, because I've posted it.
And you absolutely right - it is counting issue.

Thanks a lot!

**Comment by polyfractal** [comment]
Happy to help :)
