### ISSUE TITLE
Updating and adding documents is very slow

### ISSUE THREAD

**Issue by zohaib055** [elastic/elasticsearch-php#639]
i have setup elasticsearch on ubuntu 17.04 and when i try to update and add new documents it takes lots of time well it works fast on my remote machine which has ubuntu 16.04 and anybody tell me or figure out this that why is this so ?

**Comment by polyfractal** [comment]
Is this related to the ES-PHP client?

This sounds like a general question about Elasticsearch configuration and optimization.  These kinds of questions are better suited to the general [Elasticsearch forums](https://discuss.elastic.co/c/elasticsearch)
