### ISSUE TITLE
expecting array or json ,but get code 500 ; why?

### ISSUE THREAD

**Issue by zouxiaozhu** [elastic/elasticsearch-php#642]
require 'vendor/autoload.php';
$params = [
    'index' => 'my_index',
    'body' => [
        'settings' => [
            'number_of_shards' => 2,
            'number_of_replicas' => 0
        ]
    ]
];

$response = $client->indices()->create($params);
print_r($response);

expecting array or json ,but get code 500 ; why?

**Comment by polyfractal** [comment]
500-level errors are "server-related" errors, meaning something went wrong on the server.  

What exception message did you get?

**Comment by zouxiaozhu** [comment]
@polyfractal  i am already resolve this problem,   i am new obj get 500 error ; so i  have run composer install  for four times ,then success. thank you !
