### ISSUE TITLE
highlight does not display when content is '- -'

### ISSUE THREAD

**Issue by svolence** [elastic/elasticsearch-php#643]
```php
'body'  => [
                'size'        => 50, 
                'from'        =>1,
                'highlight'   => [
                    'pre_tags'            => ["<i  class='highlight'>"],
                    'post_tags'           => ["</i>"],
                    'fragment_size'       => 50,
                    'number_of_fragments' => 1,
                    'no_match_size'       => 100,
                    'fields'              => [
                        'content' => ["fragment_size" => 2000],
                    ]
                ],
]
```
There is no highlight tag in the returned result

**Comment by zouxiaozhu** [comment]
can U help me reslove the problem about when I new a elastic object no error .while i call method create() get 500 error

**Comment by polyfractal** [comment]
@zouxiaozhu Please don't spam other tickets with your issue.  We can deal with your problems in your ticket :)

@svolence When you say "no highlight tag", do you mean that the response doesn't have a highlight section at all?  Or that the highlighted fragments don't have the `<i  class='highlight'></i>` tags?

**Comment by svolence** [comment]
**I have solved the problem**
