### ISSUE TITLE
Setting a type on an updateByQuery call has no effect

### ISSUE THREAD

**Issue by fredrlx** [elastic/elasticsearch-php#652]
When setting both an index and a type in a call to updateByQuery, the uri value is overwriten, and the type is lost. Which means that all of the index will be impacted by the call which could cause issues.

https://github.com/elastic/elasticsearch-php/blob/cb3b2438faac3fb4480a9af89a2a45bcb5049741/src/Elasticsearch/Endpoints/UpdateByQuery.php#L54-L60

**Comment by polyfractal** [comment]
What version are you using?  This was fixed in 5.0+

**Comment by fredrlx** [comment]
Our servers still run Elasticsearch 2.x, so we're using the 2.0 branch of elasticsearch-php.

**Comment by polyfractal** [comment]
2.x is EOL.  If you want to open a PR for the 2.x branch I'll merge and release at some point, but I'd really recommend upgrading to at least 5.x.

**Comment by ezimuel** [comment]
Outdated issue
