### ISSUE TITLE
SSL connection throws error `Received fatal alert: unknown_ca`

### ISSUE THREAD

**Issue by asolopovas** [elastic/elasticsearch-php#653]
### Summary of problem or feature request

Hi I am strugling to setup ssl connection with my elasticsearch server via PHP client. I have generated self signed certificated which consist of two files ca.key and ca.cert Server is running as I can connect to it via browser
### Elasticsearch.yml
```
xpack.security.transport.ssl.enabled: true 
xpack.security.http.ssl.enabled: true 
xpack.ssl.key:                     /etc/elasticsearch/ssl/ca.key 
xpack.ssl.certificate:             /etc/elasticsearch/ssl/ca.crt 
```
### Php Client
```php
$client = ClientBuilder::create()
                   ->setHosts(["https://elastic:changeme@server.com"])
                   ->setSSLVerification('path/ssl/ca.crt')     
                   ->build() ;
```
The problem that I get is that when I try to connect via php client I am getting an error in `/var/elasticsearch/elasticsearch.log` 
`io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca` 

The ca.crt inside the client is the same as the file used by elasticsearch configuration. Could someone please help me as I can't get my head around these settings.

`curl https://elastic:changeme@server.com -k` also works wihtout an issue.

### System details

- Operating System Centos 6.9
- PHP Version 7.1.9
- ES-PHP client version 5.3.0
- Elasticsearch version  5.2.0

**Comment by polyfractal** [comment]
As a disclaimer, I'm not an expert on setting up SSL (it's super tricky as you've discovered :( ), but I think you're missing the `certificate_authorities` CA line on your server (following: https://www.elastic.co/guide/en/x-pack/current/ssl-tls.html#installing-node-certificates)

```
xpack.ssl.key:                     /home/es/config/x-pack/node01.key 
xpack.ssl.certificate:             /home/es/config/x-pack/node01.crt 
xpack.ssl.certificate_authorities: [ "/home/es/config/x-pack/ca.crt" ]
```

And on the client side, I think curl only accepts CAs that are in the `.pem` format.  To do that I believe you can execute this to convert the `.crt` to `.pem`:

```
openssl x509 -in <cert> -inform d -outform PEM -out ca.pem 
```
then set it in the client:

```php
$builder->setSSLVerification('path/ssl/ca.pem')    
```
I'm not 100% positive about any of the above, but I think that might work :)

As an aside, here are the various SSL options in the client:

- `$builder->setSSLVerification()` == [CURLOPT_CAINFO](https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html), "path to Certificate Authority (CA) bundle"
- `$builder->setSSLCert()` == [CURLOPT_SSLCERT](https://secure.php.net/manual/en/function.curl-setopt.php), "The name of a file containing a PEM formatted certificate. "
- `$builder->setSSLKey()` == [CURLOPT_CURLOPT_SSLKEY](https://secure.php.net/manual/en/function.curl-setopt.php), "The name of a file containing a private SSL key. "

**Comment by ezimuel** [comment]
Solved by @polyfractal
