### ISSUE TITLE
ping()-Method throws exception

### ISSUE THREAD

**Issue by bretrzaun** [elastic/elasticsearch-php#655]
### Summary of problem or feature request

Using version 2.3.1 when executing the ping() function to detect the cluster being available I get an Elasticsearch\Common\Exceptions\NoNodesAvailableException saying "No alive nodes found in your cluster" instead of the expected return value of "false".

### Code snippet of problem

```php
$clientBuilder = ClientBuilder::create();
$clientBuilder->setHosts(['foo']);
$client = $clientBuilder->build();
$client->ping();
```

### System details

- Operating System: Ubuntu 16.04
- PHP Version: 7.0
- ES-PHP client version: 2.3.1
- Elasticsearch version: 2.3.1

**Comment by ParitoshBh** [comment]
Did you try passing empty array to `ping()`?

I am using ES-PHP version 5.3.0 with ElasticSearch version 5.6.1 with the following code,

```
    $params = []; 
    $response = $client->ping($params);
```

and its working as expected.

**Comment by ezimuel** [comment]
Outdated issue.
