### ISSUE TITLE
Unable to install elasticsearch-php v5.3.1 via Composer

### ISSUE THREAD

**Issue by jsnod** [elastic/elasticsearch-php#662]
### Summary of problem or feature request

v5.3.1 does not appear to be available via Composer.  According to https://github.com/elastic/elasticsearch-php/blob/5.0/CHANGELOG.md it is available, but I do not see it here: https://packagist.org/packages/elasticsearch/elasticsearch

Was it ever officially released?

### Code snippet of problem

```
> php composer.phar --ignore-platform-reqs require elasticsearch/elasticsearch 5.3.1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package elasticsearch/elasticsearch 5.3.1 exists as elasticsearch/elasticsearch[0.4.x-dev, 1.0.x-dev, 2.0.x-dev, 5.0.x-dev, 6.0.x-dev, dev-loekvangool-patch-1, dev-master, dev-sarwarbhuiyan-patch-1, dev-sarwarbhuiyan-patch-2, dev-sarwarbhuiyan-patch-2-1, dev-travis, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v1.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.4.0, v1.4.1, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3, v2.0.0-beta4, v2.0.0-beta5, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.3.0, v2.3.1, v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.2.0, v5.3.0, v6.0.0-beta1] but these are rejected by your constraint.


Installation failed, reverting ./composer.json to its original content.

```

### System details

- Operating System: CentOS 7.3
- PHP Version: 5.6.30
- ES-PHP client version: 5.3.1
- Elasticsearch version: 5.4

**Comment by mhujer** [comment]
I think was not released yet - it is not even in the tagged versions in https://github.com/elastic/elasticsearch-php/tags

**Comment by polyfractal** [comment]
Yep, I'm just bad.  Did all the work for the release but forgot to tag it.  I just pushed `v5.3.1` tag: https://github.com/elastic/elasticsearch-php/blob/v5.3.1/CHANGELOG.md

Thanks for the note, sorry about that!
