### ISSUE TITLE
"post_filter" is not a valid parameter

### ISSUE THREAD

**Issue by hkirsman** [elastic/elasticsearch-php#664]
How do you use post_filter with elasticsearch-php?

"post_filter" is not a valid parameter. Allowed parameters are "_source", "_source_exclude", "_source_include", "allow_no_indices", "analyze_wildcard", "analyzer", "batched_reduce_size", "client", "custom", "default_operator", "df", "docvalue_fields", "expand_wildcards", "explain", "fielddata_fields", "filter_path", "filter_path", "from", "human", "ignore_unavailable", "indices_boost", "lenient", "lowercase_expanded_terms", "preference", "q", "query_cache", "request_cache", "routing", "scroll", "search_type", "size", "slice", "sort", "source", "stats", "stored_fields", "suggest_field", "suggest_mode", "suggest_size", "suggest_text", "terminate_after", "timeout", "typed_keys", "version"

This happened when I tried to add this to the root of the of the parameters in the search() function. I also tried to put post_filter into the body key, but got different error.

**Comment by polyfractal** [comment]
`post_filter` is a top-level element of the body, so you'll add it along side your `query`, `aggregations`, `sort`, etc.  See: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-post-filter.html

If you paste up the code where you tried to add it to the body, I can help find the problem :)

**Comment by hkirsman** [comment]
This is the error I get from browser console:

    {"error":{"root_cause":[{"type":"parsing_exception","reason":"[term] malformed query, expected [END_OBJECT] but found [FIELD_NAME]","line":1,"col":159}],"type":"parsing_exception","reason":"[term] malformed query, expected [END_OBJECT] but found [FIELD_NAME]","line":1,"col":159},"status":400}

This is variable I pass to search() function:

    Array
    (
    [index] => simple_elasticsearch
    [type] => simple_elasticsearch_content_index
    [body] => Array
        (
            [query] => Array
                (
                    [term] => Array
                        (
                            [language] => et
                        )

                )

            [post_filter] => Array
                (
                    [term] => Array
                        (
                            [field_news_subject] => ASO
                        )

                )

            [aggs] => Array
                (
                    [type-filter3] => Array
                        (
                            [filter] => Array
                                (
                                    [term] => Array
                                        (
                                            [field_news_subject] => ASO
                                        )

                                    [match_all] => Array
                                        (
                                            [boost] => 1
                                        )

                                )

                            [aggs] => Array
                                (
                                    [field_news_subject] => Array
                                        (
                                            [terms] => Array
                                                (
                                                    [field] => field_news_subject
                                                    [size] => 50
                                                    [order] => Array
                                                        (
                                                            [_term] => asc
                                                        )

                                                )

                                        )

                                    [field_news_subject_count] => Array
                                        (
                                            [cardinality] => Array
                                                (
                                                    [field] => field_news_subject
                                                )

                                        )

                                )

                        )

                    [years-filter4] => Array
                        (
                            [filter] => Array
                                (
                                    [term] => Array
                                        (
                                            [field_news_subject] => ASO
                                        )

                                    [match_all] => Array
                                        (
                                            [boost] => 1
                                        )

                                )

                            [aggs] => Array
                                (
                                    [year_when_created] => Array
                                        (
                                            [terms] => Array
                                                (
                                                    [field] => year_when_created
                                                    [size] => 50
                                                    [order] => Array
                                                        (
                                                            [_term] => desc
                                                        )

                                                )

                                        )

                                    [year_when_created_count] => Array
                                        (
                                            [cardinality] => Array
                                                (
                                                    [field] => year_when_created
                                                )

                                        )

                                )

                        )

                )

        )

    [size] => 10
    [_source] => Array
        (
            [0] => title
            [1] => simple_elasticsearch_teaser
        )

    )

This is proxy I have for Searchkit.co. It takes the original header and puts some variables under 'body', then passes the whole variable to search() function. Also in the middle there's this empty match_all fix. I found some issues like https://github.com/elastic/elasticsearch-php/issues/495 ,  but not sure if that's the correct way.

    <?php
    use Elasticsearch\ClientBuilder;
    
    require('settings.php');
    
    
    $m = $_SERVER['REQUEST_METHOD'];
    
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
      ini_set("allow_url_fopen", TRUE);
    
      require 'vendor/autoload.php';
    
      header("Content-type:application/json");
    
      $hosts = [
        $host,
      ];
    
      $client = \Elasticsearch\ClientBuilder::create()
        ->setHosts($hosts)
        ->build();
    
      $put_params = file_get_contents('php://input');
    
      $request_body = json_decode($put_params, TRUE);
    
      $params = array(
        'index' => $index,
        'type'  => $type,
        'body' => [],
      );
    
      $allowed_keys_in_root = array(
        "_source",
        "_source_exclude",
        "_source_include",
        "allow_no_indices",
        "analyze_wildcard",
        "analyzer",
        "batched_reduce_size",
        "client",
        "custom",
        "default_operator",
        "df",
        "docvalue_fields", "expand_wildcards", "explain", "fielddata_fields", "filter_path", "filter_path", "from", "human", "ignore_unavailable", "indices_boost", "lenient", "lowercase_expanded_terms", "preference", "q", "query_cache", "request_cache", "routing", "scroll", "search_type", "size", "slice", "sort", "source", "stats", "stored_fields", "suggest_field", "suggest_mode", "suggest_size", "suggest_text", "terminate_after", "timeout", "typed_keys", "version");
    
      // Add all values to $params['body'] if they are not allowed as root in $params.
      foreach($request_body as $key => $var) {
        if (!in_array($key, $allowed_keys_in_root)) {
    //      if ($key == 'aggs') {
    //        array_walk_recursive(
    //          $var,
    //          function (&$value, $key) {
    //            if ($key == 'match_all') {
    //              $value = array("boost" => 1.0);
    //            }
    //          }
    //        );
    //      }
    
          $params['body'][$key] = $var;
          unset($request_body[$key]);
        }
      }
    
      // Something with the empty match_all giving errors so trying this.
      if (empty($params['body']['aggs']['type-filter3']['filter']['match_all'])) {
        $params['body']['aggs']['type-filter3']['filter']['match_all'] = array("boost" => 1.0);
      }
      if (empty($params['body']['aggs']['years-filter4']['filter']['match_all'])) {
        $params['body']['aggs']['years-filter4']['filter']['match_all'] = array("boost" => 1.0);
      }
    
      // Add rest of the query parameters as first level to $params.
      $params = array_merge($params, $request_body);
    
    // ok
    // @todo: Add _source field to query? Does it work?
      try {
        $response = $client->search($params);
        print json_encode($response);
      }
      catch (Exception $e) {
        print_r($e->getMessage());
      }
    }

These are the original headers Searchkit.co is sending and it works with pure elasticsearch:

    {"query":{"term":{"language":"et"}},"post_filter":{"term":{"field_news_subject":"ASO"}},"aggs":{"type-filter3":{"filter":{"term":{"field_news_subject":"ASO"}},"aggs":{"field_news_subject":{"terms":{"field":"field_news_subject","size":50,"order":{"_term":"asc"}}},"field_news_subject_count":{"cardinality":{"field":"field_news_subject"}}}},"years-filter4":{"filter":{"term":{"field_news_subject":"ASO"}},"aggs":{"year_when_created":{"terms":{"field":"year_when_created","size":50,"order":{"_term":"desc"}}},"year_when_created_count":{"cardinality":{"field":"year_when_created"}}}}},"size":10,"_source":["title","simple_elasticsearch_teaser"]}

**Comment by polyfractal** [comment]
Hey, sorry for the long delay, got called up to give some training and it ate up all my time.

I'm a little confused.  The JSON that you list at the end ("original headers Searchkit is sending") is a JSON query that works fine?  But the PHP object you pasted doesn't work?

Can you do a `print_r(json_encode($params, JSON_PRESERVE_ZERO_FRACTION));` of the final PHP object so we can see what the JSON representation is?  I don't see anything wrong after a quick glance, but sometimes it's hard to tell with PHP objects.

Re: empty match_all, adding the boost is fine.  Or doing `(object)[]` or `new stdClass()`

**Comment by polyfractal** [comment]
Ping?  Gonna close this soon otherwise.  New years cleanup and all that :)

**Comment by hkirsman** [comment]
I don't remember how it was solved but the site is in prod :)
