### ISSUE TITLE
Unable to push geoip data to the right Type

### ISSUE THREAD

**Issue by david-vde** [elastic/elasticsearch-php#666]
Hello

I'm trying to use the client but I'm unable to setup the correct data type for a geoip.location field.

I put the format at <lat, lng> but it does not works... it is always imported as a string.

What is the right way to do this with the PHP client?

In my process the index does not exists yet.

Thanks

**Comment by polyfractal** [comment]
This sounds more like a general question regarding how to configure mappings in Elasticsearch.  I'd read through how to add mappings when you create the index (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#mappings) and mappings in general (https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html).

We try to keep this repo mainly to bugs/issues about the client, or very specific PHP questions.  More general ES questions can go do the discuss forums: https://discuss.elastic.co/c/elasticsearch
