### ISSUE TITLE
How to get UNIX timestamp(1501414588) to @timestamp(2017-07-30T11:37:23.285) in Elastic-PHP

### ISSUE THREAD

**Issue by satishmehta** [elastic/elasticsearch-php#667]
### Summary of problem or feature request

I want to get the @timestamp(2017-07-30T11:37:23.285) format in my elastic search result, in my elastic index the "created" time is stored in UNIX timestamp(1501414588). How can i get the Year/week/month from UNIX timestamp.

### Code snippet of problem
![ques](https://user-images.githubusercontent.com/11812875/32165326-6496ada0-bd88-11e7-8081-f28afca4eb57.jpg)

"_index" : "voice-incoming",
        "_type" : "data",
        "_id" : "AV2TSVZ4GPA2Tma5Q5yX",
        "_score" : 1.0,
        "_source" : {
          "units_isd" : 0,
          "agent_name" : null,
          "dtmf" : "",
          "units_local" : 0,
          "call_from" : "9176206219",
          "units" : 0,
          "call_to" : "4433870001",
          "duration" : 0,
          "bill_sec" : 0,
          "price_isd" : 0,
          "fkserviceid" : 3,
          "credits" : 0,
          "provider" : "VODAFONE",
          "bridge_number" : "4433870001",
          "@version" : "1",
          "modified" : 1501414624,
          "id" : "100852192597dc4de0011d",
          "fkagentid" : "",
          "fk_number_id" : 4505,
          "recording_id" : "",
          "cost" : 0,
          **"created" : 1501414622,**
          "custom" : "",
          "end_time" : 0,
          "fkivr_id" : 22323,
          "fk_channel_id" : 33,
          "server_id" : 12,
          "cost_pulse" : 0,
          "cost_units" : 0,
          **"start_time" : 1501414622,**

### System details

- Operating System - UNIX
- PHP Version- 7.0
- ES-PHP client version- 5.6
- Elasticsearch version- 5.6

**Comment by polyfractal** [comment]
If you just need to convert between formats in PHP, there are built-in PHP functions to help:

`strtotime`: http://de.php.net/manual/en/function.strtotime.php
`DateTime::createFromFormat`: https://secure.php.net/manual/en/datetime.createfromformat.php
