### ISSUE TITLE
ES compatibility 

### ISSUE THREAD

**Issue by prabhat2k15** [elastic/elasticsearch-php#672]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- elasticsearch/elasticsearch v5.3.0 requires php ^5.6|^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- elasticsearch/elasticsearch v5.2.0 requires php ^5.6|^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- elasticsearch/elasticsearch v5.1.3 requires php ^5.6|^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- elasticsearch/elasticsearch v5.1.2 requires php ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- elasticsearch/elasticsearch v5.1.1 requires php ^5.6.6|^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- elasticsearch/elasticsearch v5.1.0 requires php ^5.6.6|^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- elasticsearch/elasticsearch v5.0.0 requires php ^5.6.6|^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- elasticsearch/elasticsearch 5.0.x-dev requires php ^5.6|^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- Installation request for elasticsearch/elasticsearch ~5.0 -> satisfiable by elasticsearch/elasticsearch[5.0.x-dev, v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.2.0, v5.3.0].

I am unable to install it on my ubuntu server.This is what(above) i am getting on codeship . 
My php version is 7.0 
elasticserver version 5.0
ubuntu version 16.04

kindly help me asap...

**Comment by mhujer** [comment]
if you check the output again, you can see this:
> ... your PHP version (5.5.38)  ....

It looks like that either :
1) you don't actually have PHP 7.0 on the server
2) you have locked the composer to 5.5.38 in `composer.json` in `config.platform` field.

**Comment by prabhat2k15** [comment]
That problem is solved. But now when i am adding data to ES  i get this as response.
Array
(
    [took] => 60001
    [errors] => 1
    [items] => Array
        (
            [0] => Array
                (
                    [index] => Array
                        (
                            [_index] => products
                            [_type] => product
                            [_id] => 1
                            [status] => 503
                            [error] => Array
                                (
                                    [type] => unavailable_shards_exception
                                    [reason] => [products][2] Not enough active copies to meet write consistency of [QUORUM] (have 1, needed 2). Timeout: [1m], request: [BulkShardRequest to [products] containing [1] requests]

**Comment by mhujer** [comment]
I think that you don't have enough shards available for writing.

It looks like a generic Elasticsearch question, not related to the `elasticsearch-php` library itself. Please take questions like this to the [Elasticsearch Discuss Forums](https://discuss.elastic.co/c/elasticsearch), since they are better suited for that sort of question.
