### ISSUE TITLE
Cannot use object of type Elasticsearch\Common\Exceptions\Missing404Exception as array

### ISSUE THREAD

**Issue by suchman** [elastic/elasticsearch-php#676]
Hi, first of all thanks for awesome library! But I found problem after updating on v5.3.1. When I try to check if document exists, error "Cannot use object of type Elasticsearch\Common\Exceptions\Missing404Exception as array" is shown on src\Elasticsearch\Transport.php row 118. $response varible contains object not an array ... 
Is it bug or Am I doing something wrong?

Thanks for reply!

**Comment by polyfractal** [comment]
Argh, this is a bug.  I made a change in master which works on PHP 7 but not PHP 5.6, then backported the change to 5.x

I'll fix and push/tag in a minute, sorry about that!

**Comment by polyfractal** [comment]
Tagged `v5.3.2`, which includes the previously committed (but not tagged) fix: https://github.com/elastic/elasticsearch-php/commit/c5db567d5a843a2c9778c7b74863357879abd34f

Thanks for the bug report!

**Comment by suchman** [comment]
Works perfectly!
Thank you for quick fix :)

**Comment by jkocour** [comment]
Hi, can you please apply the bugfix to v6.0?
