### ISSUE TITLE
msearch does not seem to work, testing with 5.0 client and both 5.1.1 and 5.6.4 elasticsearch server

### ISSUE THREAD

**Issue by digirave** [elastic/elasticsearch-php#677]
### Summary of problem or feature request

msearch does not seem to work with 5.3.0 latest php client and both 5.1.1 and 5.6.4 elasticsearch server

I am using the exact example from https://discuss.elastic.co/t/elasticsearch-5-0-php-msearch/66716/2

### Code snippet of problem

`
try  {
	$responses = $client->msearch([
  'body'  => [
    [
      'index' => 'indexA', 
      'type' => 'typeA'],
    [
      'query' => [
          'match_all' => [],
      ],
    ],
    [
      'index' => 'indexB',
      'type' => 'typeB'
    ],
    [
      'size'  => 0,
      'query' => [
          'match_all' => [],
      ],
      'aggs'  => [
          'max_sequence' => ['max' => ['field' => 'sequence']],
      ],
    ],
  ],
]);
}
catch(Exception $e) {
	var_dump($e);
	print "error\n";
	exit;
}
`

Results in lots of errors including
`
                        ["body"]=>
                        string(277) "{"error":{"root_cause":[{"type":"parsing_exception","reason":"[match_all] query malformed, no start_object after query name","line":1,"col":23}],"type":"parsing_exception","reason":"[match_all] query malformed, no start_object after query name","line":1,"col":23},"status":400}
`

### System details

- Operating System
CentOS 7
- PHP Version
php 5.6 and php 7.1
- ES-PHP client version
5.3.0
- Elasticsearch version
tested with both 5.1.1 and 5.6.4
error occurs before connection

**Comment by digirave** [comment]
Just in case I tested with ES-PHP client version 5.0.0 and 5.2.0
Same problem occurs.

I am not sure if the example is the problem or the library.
However, the example seems to be from an official elasticsearch developer.

**Comment by digirave** [comment]
I found the solution,
the example above seems to have a problem with the current elasticsearch API.
All the [] should be new \stdClass()

I am not sure if the above example worked in prior versions and is a bug or not.
So I will leave this issue open.

**Comment by polyfractal** [comment]
Yep, it's a known issue with PHP.  See the docs here:  https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/php_json_objects.html

I'll go edit that forum post to the correct syntax.  IIRC I just typed it up long-hand without actually testing it. :)

You can also use `(object)[]` instead of `stdClass`, since casting an array to an object is basically the same.  You're preference :)
