### ISSUE TITLE
Unit testing using elasticsearch-php

### ISSUE THREAD

**Issue by PezCoder** [elastic/elasticsearch-php#678]
- Operating System - mac osx sierra
- PHP Version - 7.0.4
- ES-PHP client version - 5.1.3
- Elasticsearch version - 1.5.2

#### What 
I wanted to write test cases for a wrapper i wrote around elasticsearch-php in my application that creates a proper query format that needs to be passed to elasticsearch-php to query for the data.

The method that's suggested in the [documentation, says](https://github.com/elastic/elasticsearch-php#unit-testing-using-mock-a-elastic-client) to mock elasticsearch, but if I mock the response I'll never know that that the input query passed resulted in a correct response on not, because the query never ran.

#### Need your suggestion
I can think to two ways of testing this scenario: 
1. For my wrapper search function, test by matching the body that's passed to the elasticsearch-php client, i.e to know if the function resulted in creating the correct input for this library.
Assuming if the input is passed correctly, then the output will match too.
2. Create a test elasticsearch index & for every test case scenario, create indexes (using this library) that's needed for that particular test & test for the resulted document.

For point **1** > I think the disadvantage would be, the test would be difficult to read as the comparison would be between the array structures that's passed to the library i.e
```php
[
    'body' => [
        'query' => [
            'match' => [
                'testField' => 'abc'
            ]
        ]
]
```
should match the result of my custom function.
Also it would be difficult to write this query, for every test as well.

I found approach **2** to be better as the data is easier to deal with i.e if the ES contains
documents with testField xyz & abc, only abc should be returned.

#### Shortly
I would like your advice on how the clients consuming this wrapper should test their applications ?

**Comment by polyfractal** [comment]
As you noted, it depends on what you want to test.  

If you want to test the interaction between your application and Elasticsearch under "correct conditions", you can mock that relationship in a unit test.  That assumes your query syntax and mocked response are correct.  But it allows you test the "flow" of your application.  E.g. after a query, do we process the results correctly?  


If you need to test the actual syntax and response, you'll need an integration test that actually talks to an Elasticsearch server.  The benefit is that you get real requests/responses, but the downside is that you need an actual Elasticsearch server running.  This slows things down, forces you to deal with resetting the cluster after/in between tests to keep the state clean, etc.

Most projects do a combination of both (for example, ES-PHP has both unit and integration tests).  Unit tests are used where you can isolate the logic.  Given input A the output should be Z.  Integration tests are used to test the whole stack from end to end.

**Comment by PezCoder** [comment]
I think i got my answer, I want to test the syntax for the query that's being generated by my function & passed to elasticsearch-php. Integration test cases should be the right choice here with a elastic search server running.
I'll also take a look at how `es-php` does it.
Thank you !
