### ISSUE TITLE
Uncaught exception 'Elasticsearch\Common\Exceptions\UnexpectedValueException' with message '"body" is not a valid parameter

### ISSUE THREAD

**Issue by aankitkumar31** [elastic/elasticsearch-php#679]
Hello all,
I am new to elastic search I tried to search the document using 

```

`$params = [
    'index' => 'pokemon',
    'type' => 'pokemon_trainer',
    'body' => [
        'query' => [
            'match' => [
                'name' => 'ankit'
            ]
        ]
    ]
];

$result = $client->get($params);`

```
but its not worked as expected it throws an error like
Uncaught exception 'Elasticsearch\Common\Exceptions\UnexpectedValueException' with message '"body" is not a valid parameter. Allowed parameters are "_source", "_source_exclude", "_source_include", "client", "custom", "fields", "filter_path", "human", "parent", "preference", "realtime", "refresh", "routing", "stored_fields", "version", "version_type"' in E:\Projects\elastic_demo\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Endpoints\AbstractEndpoint.php:237 Stack trace: #0

**Comment by rsaf** [comment]
any solution to this? @aankitkumar31 how did you solve it? I'm having the same issue.

**Comment by gleb-svitelskiy** [comment]
With get method you can retrieve the document by document id.
You are trying to perform search request.
You can use search method instead.
```
$params = [
    'index' => 'pokemon',
    'type' => 'pokemon_trainer',
    'body' => [
        'query' => [
            'match' => [
                'name' => 'ankit'
            ]
        ]
    ]
];

$result = $client->search($params);
```
Or use get method in proper way.
```
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id'
];

// Get doc at /my_index/my_type/my_id
$response = $client->get($params);
```

**Comment by polyfractal** [comment]
Yep, exactly what @gleb-svitelskiy said.  The GET method doesn't support a body, since it is just retrieving a document directly by ID.

The search method is what you're looking for.

**Comment by rsaf** [comment]
@gleb-svitelskiy Thanks a lot. The search method is the one to use.

**Comment by sfdsfdsfdesfdsghefasefs** [comment]
Same issue, i'm facing ...
