### ISSUE TITLE
Elastic search configurations not working in laravel v5.3

### ISSUE THREAD

**Issue by rizwanmcs** [elastic/elasticsearch-php#684]
I have setup new laravel v5.3 project and install elastic search driver to implement elastic search via composer. But when I reload my page then I always receive This page isn’t working even the elastic search is running on my system below is my complete code that I code.

composer.json
```
"require": {
        "php": ">=5.6.4",
        "elasticsearch/elasticsearch": "^6.0",
        "laravel/framework": "5.3.*"
    }
```
and controller
```
<?php
namespace App\Http\Controllers;    
class ElasticSearch extends Controller
    {

        // elastic
        protected $elastic;
        //elastic cliend
        protected $client;

        public function __construct(Client $client)
        {
            $this->client = ClientBuilder::create()->build();
            $config = [
                'host' =>'localhost',
                'port' =>9200,
                'index' =>'people',
            ];
            $this->elastic = new ElasticClient($config);
        }

        public function addPeopleList(){
            echo "<pre>";
            print_r($this->$elastic);
            exit;
        }
    }
```
But when I refresh the page then This page isn’t working i received this message and page not loaded one thing that I want to let you know that I made no changes in app.php file of configuration. Please eduacate to solve this issue.

Operating System => ubuntu 14.04
PHP version => 7.0.24

**Comment by mhujer** [comment]
@rizwanmcs this was caused the same thing as the one in https://github.com/elastic/elasticsearch-php/issues/516#issuecomment-346586231 ?

If so, please close this issue.

**Comment by mhujer** [comment]
@rizwanmcs ping?

**Comment by polyfractal** [comment]
Gonna close this due to inactivity, feel free to re-open if you can provide more details @rizwanmcs.  I suspect it was due to https://github.com/elastic/elasticsearch-php/issues/516#issuecomment-346586231 as well :)
