### ISSUE TITLE
putTemplate in client is not working according to docs

### ISSUE THREAD

**Issue by seliver** [elastic/elasticsearch-php#686]
### Summary of problem or feature request

After upgrading to ES 6.0 from 5.4, every time I try to add a search template, this error happens: 
```
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_search], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_search"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_search], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_search"},"status":400}
``` 
 

### Code snippet of problem
My code where I'm calling the ES API:

```php
$this->elasticsearchConnection->putTemplate([
                'id' => $this->search_template_id,
                'body' => file_get_contents($this->search_template_file)
            ]);
```

### System details

- Operating System: Ubuntu Server 16.04
- PHP Version: 7.1
- ES-PHP client version: 6.0
- Elasticsearch version: 6.0

If I do some var_dump's inside the ES-PHP client, performRequest method, this is what I get:

> method: PUT
> URI: /_search/template/my_template_name

If we're to look at the API, there is no PUT method, and _search is only used to search.

**Comment by seliver** [comment]
Yep, just tested my solution. Worked fine.

**Comment by polyfractal** [comment]
I need to actually remove the `putTemplate` endpoint, it's no longer valid in ES 6.0.  Sorry for the confusion.

In ES 6.0, the search template system has changed over to stored scripts.  Check out the breaking changes docs here: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_scripting_changes.html#_stored_search_template_apis_removed

So you'll now store scripts using the [`$client->putScript()` endpoint](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Client.php#L1261) and search using the [`$client->searchTemplate()`](
https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Client.php#L994) api as before 

And then I need to go remove `$client->putTemplate()`.  I'm busy today, but will spend tomorrow working on PHP backlog :)

**Comment by seliver** [comment]
I tried using the putScript, but it won't work. I emulated the request on Dev Tools:
```
PUT _scripts/mustache/my_template_name
{
  "query": {
    #my query
  },
  "size" : "{{size}}{{^size}}20{{/size}}"
}
```
 and it returned: 
```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "failed to parse/compile stored script [mustache]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "failed to parse/compile stored script [mustache]",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Unknown context [my_template_name]"
    }
  },
  "status": 400
}
```
If I try to do it according to the documentation:
```json
POST _scripts/my_template_name
{
    "script": {
        "lang": "mustache",
        "source": {
            "query": {
                #my query
            }
        }
    }
}
```
It works. But when I try to make a query with the template:
```
GET _search/template
{
    "id": "my_template_name'", 
    "params": {
        #my params
    }
}
```
it returns: 
```
{
  "error": {
    "root_cause": [
      {
        "type": "resource_not_found_exception",
        "reason": "unable to find script [my_template_name'] in cluster state"
      }
    ],
    "type": "resource_not_found_exception",
    "reason": "unable to find script [my_template_name'] in cluster state"
  },
  "status": 404
}
```

What am I doing wrong?

**Comment by polyfractal** [comment]
Yes, you're right about the lang portion of the endpoint.  I'll fix this bug in a moment

**Comment by polyfractal** [comment]
Should be fixed in https://github.com/elastic/elasticsearch-php/commit/19638e5a6af7b00aea95049a2c20fd419d7a5bba.  I have a few other things to do first, then I'll release a bugfix `v6.0.1`

You can use the putScript endpoint like this once the fix released:

```php
$response = $client->putScript([
    'id' => 'foo',
    'body' => [
        'script' => [
            'lang' => 'mustache',
            'source' => [
                'query' => [
                    'match' => [
                        'f1' => '{{f1}}'
                    ]
                ]
            ]
        ]
    ]
]);
print_r($response);

$response = $client->searchTemplate([
    'body' => [
        'id' => 'foo',
        'params' => [
            'f1' => 'some text'
        ]
    ]
]);
print_r($response);
```

**Comment by polyfractal** [comment]
FYI this was just released as part of `v6.0.1` :)

**Comment by seliver** [comment]
Cool! Next time I'll give 6.0.1 a try.

**Comment by MerwaneHAMADI** [comment]
For people browsing : 
This is how you would render this search template : 
$response = $client->searchTemplate([
          'body' => [
                'id' => 'foo',
                'params' => [
                    'f1' => 'random value',
                ]
            ],
 ]);
print_r($response);

It took me some time to find it.
