### ISSUE TITLE
Docs on putScript 

### ISSUE THREAD

**Issue by morphers82** [elastic/elasticsearch-php#688]
how do i setup the params for $client->putScript()?

the Docs don't help much

The following doesn't work.

$params = [
"id"=>"script_name",
"lang"=> "painless",
"body"=> "painless javascript here"
];
$response = $client->putScript($params);

In Kibana: this works:

POST _scripts/script_name
{
"script": {
"lang": "painless",
"source": "painless javascript here"
}
}

**Comment by polyfractal** [comment]
See: https://github.com/elastic/elasticsearch-php/issues/686#issuecomment-348212032

There was a bug, just fixed and will be released as `v6.0.1` shortly.

**Comment by polyfractal** [comment]
FYI this was just released as part of `v6.0.1` :)
