### ISSUE TITLE
Elasticsearch\Serializers\RuntimeException not found

### ISSUE THREAD

**Issue by whdckszxxx** [elastic/elasticsearch-php#689]
Hi.

I'm continuously getting Elasticsearch\Serializers\RuntimeException not found Error. So I couldn't get what the real problem is.

I've looked into it a bit and I found RuntimeException is used in SmartSerializer but not imported in use statement.

I think you should put 

> use Elasticsearch\Common\Exceptions\RuntimeException;

at the top of SmartSerializer.php

**Comment by mhujer** [comment]
Thanks for the report. I've already fixed it in #675 (which is waiting for review and merge)

**Comment by whdckszxxx** [comment]
got it thank you

**Comment by polyfractal** [comment]
Fixed in master (via #675) and 6.0 (01063512e9ca45f7515b4797c3e78c40dec36c19).  Just tagged `v6.0.1` which includes this fix.  Thanks for your patience :)
