### ISSUE TITLE
PHP Fatal error:  Uncaught exception

### ISSUE THREAD

**Issue by mokrea** [elastic/elasticsearch-php#704]
### Summary of problem or feature request
After I restarted elasticsearch service when I run the php code below I get a error

the php code:
```php
$client = ClientBuilder::create()->setHosts(['http://127.0.0.1:9200'])->build();
$params = [
        'index' => 'produtos',
        'type'  => 'produto',
        'body' => [
                'from' => 0, 'size' => 50,
                'query' => [
                        'bool'=> [
                                'must' => [
                                        [ 'query_string' => [
                                                'query' => "gibson" 
                                        ] ],
                                        [ 'match' => [ 'storeName' => "Americanas" ] ]
                                        [ 'match' => [ 'idItem' => 6  ] ]
                                ]
                        ]
                ]
        ]
];
$response = $client->search($params);
```
The Error:

```
PHP Fatal error:  Uncaught exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message '{"error":"Content-Type header [] is not supported","status":406}' in /opt/crawlers/classificador/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:686
Stack trace:
#0 /opt/crawlers/classificador/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(659): Elasticsearch\Connections\Connection->tryDeserializeError(Array, 'Elasticsearch\\C...')
#1 /opt/crawlers/classificador/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(579): Elasticsearch\Connections\Connection->tryDeserialize400Error(Array)
#2 /opt/crawlers/classificador/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(261): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#3 /opt/crawlers/classificador/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Ar in /opt/crawlers/classificador/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 686
```

but the curl command line works:
curl -XPOST 'localhost:9200/produtos/_search?pretty' -H 'Content-Type: application/json' -d '{ 
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "guitarra"
          }
        },
        {
          "match": {
            "idItem": 6
          }
        },
        {
          "match": {
            "storeName": "Americanas"
          }
        }
      ]
    }
  }
}'

and

```
curl 'localhost:9200/_cat/indices?v'health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   produtos dFDt3MFqRYCD-3xckUZe_A   5   1         95            0      445kb          445kb

```

Environment:
compose.json
{
    "require": {
        "wyndow/fuzzywuzzy": "^0.6.0",
        "elasticsearch/elasticsearch": "5.0"
    }
}

php version
PHP 5.6.32-1~dotdeb+7.1 (cli) (built: Nov  2 2017 18:55:13) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

elasticsearch version
"lucene_version" : "7.0.1"

linux:
2.6.32-042stab123.9 #1 SMP Thu Jun 29 13:01:59 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by polyfractal** [comment]
What version of Elasticsearch are you using?  Can you show the complete output of `curl -XGET localhost:9200/` (or whatever your elasticsearch server address is)?

**Comment by mokrea** [comment]
{
  "name" : "U6dNi8C",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "5aC3wTNyS1CbObOIhJrN5Q",
  "version" : {
    "number" : "6.0.0",
    "build_hash" : "8f0685b",
    "build_date" : "2017-11-10T18:41:22.859Z",
    "build_snapshot" : false,
    "lucene_version" : "7.0.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by polyfractal** [comment]
Ah, you're on Elasticsearch 6.0.  You'll have to use the Elasticsearch-PHP 6.0 branch... branches are synced, such that when you upgrade a major version in Elasticsearch, the PHP client has to upgrade as well.

**Comment by mokrea** [comment]
great!
thanks @polyfractal.. now is working.
