### ISSUE TITLE
Generate CSV automatically with the PHP Client

### ISSUE THREAD

**Issue by david-vde** [elastic/elasticsearch-php#706]
Hello Since ES6 and Kibana 6 We are able to generate a CSV from a saved search... 

I'm working on a PHP script to generate CSV automatically from a saved search, but I'm unable to find how to create easely the job by using the PHP client.

All I can do is to copy past the link displayed in the reporting like : 

`https://****/api/reporting/generate/csv?jobParams=(conflictedTypesFields:!(),fields:!........`

The thing is I'm forced to define each field, I wan't to export all fields and not being worried about new added field in the future.

Anyway My question is, is there  a way to ask elastic search to trigger the CSV generation Job with an API call with only a saved search ID as input data?

searchID -> PHP Client -> Call API -> Launch CSV Generation Job

Thank you

**Comment by polyfractal** [comment]
Hmm, I'm afraid I don't know to be honest.  The ES-PHP client only supports the API of Elasticsearch itself, not kibana.  As Kibana grows into more of a middleware and has a larger API footprint, I expect that the language clients will start to support it.  But right now, we just support the ES APIs.

**Comment by ashishtiwari1993** [comment]
@david-vde @polyfractal I have wrote one library on top of the ES-PHP SDK which use scroll API and dump data into CSV file. Kindly go through this. Even I am using in my system. Hope this can help you guys. [https://github.com/ashishtiwari1993/elasticsearch-csv-export](https://github.com/ashishtiwari1993/elasticsearch-csv-export) . Please suggest me if you find any improvement.

**Comment by ezimuel** [comment]
Closing this issue, @ashishtiwari1993 suggested a solution for that.
