### ISSUE TITLE
[script] unknown field [source], parser not found

### ISSUE THREAD

**Issue by VincentMolinie** [elastic/elasticsearch-php#708]
### Summary of problem or feature request
I'm trying to use script with updateByQuery but I keep getting this error.
What am I doing wrong ?

### Code snippet of problem
```php
        $params = [
            'index' => $index,
            'type' => $type,
            'body' => [
                'query' => [
                    'ids'=> [
                        'values' => ['my_id', 'my_id2']
                    ]
                ],
                'script' => [
                    'inline' => 'if (ctx._source.matches.contains(params.test_id)) { ctx._source.matches.remove(ctx._source.matches.indexOf(params.test_id)); }',
                    'lang' => 'painless',
                    'params' => [
                        'test_id' => 'guerhgherhu'
                    ]
                ]
            ]
        ];
 $client->updateByQuery($params)
```

### System details

- PHP Version
7.0
- ES-PHP client version
5.3.2
- Elasticsearch version
5.2.0

**Comment by VincentMolinie** [comment]
There was a breaking change in minor version: 5.6 https://github.com/olivere/elastic/commit/3c424ca8458cd544edee9e16f798d99fcb61e373#diff-dfc827036953b6615f2165f673c4d874R91

**Comment by polyfractal** [comment]
Can you paste the full exception message?

The `inline` vs `source` change is just a deprecation... `inline` still works in 5.6+

**Comment by ezimuel** [comment]
Outdated issue. @VincentMolinie if this is still an issue I'll reopen it.
