### ISSUE TITLE
Implement analyze interface

### ISSUE THREAD

**Issue by mfdgood** [elastic/elasticsearch-php#714]
### Summary of problem or feature request

I want add the analyze method within class Client, thus it can easy to trace how the tokens break the text.

### System details

- Operating System
- PHP Version
- ES-PHP client version
- Elasticsearch version

**Comment by polyfractal** [comment]
Thanks for the PRs @mfdgood.  There's already an analyze endpoint under the indices namespace however:  

`$client->indices()->analyze([...])`
https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/IndicesNamespace.php#L821

Thanks for the PRs though, happy to look at future ones!
