### ISSUE TITLE
ConnectionPoolInterface::scheduleCheck() documentation

### ISSUE THREAD

**Issue by nospoon** [elastic/elasticsearch-php#727]
Could the ConnectionPoolInterface::scheduleCheck() method be documented in a sensible way? It's impossible to figure out what is supposed to happen there or when it should be triggered.

**Comment by polyfractal** [comment]
Sorry, agreed that is confusing.  I'll add some proper docs soon.

Essentially, `scheduleCheck()` is invoked when the transport runs into a situation where it thinks a connection pool may want to update its internal pool of connections.  E.g. if the client encounters a 500-level error, that indicates something went wrong on the server and so the [transport invokes a check](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Transport.php#L124).  

In such a situation, the sniffing connection pool may decide to sniff the cluster state to get a fresh list of nodes, or the [pinging connection pool](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ConnectionPool/StaticConnectionPool.php#L68) may do a new round of pings to verify existing nodes.  The method is purely for the convenience of the connection pool, so if your pool doesn't need this functionality [it can be a no-op](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php#L54)

**Comment by ezimuel** [comment]
Outdated issue, solved by @polyfractal. @nospoon I'm closing this issue, let me know if this is still relevant, thanks!
