### ISSUE TITLE
"Incorrect HTTP method for uri" when trying to create an index

### ISSUE THREAD

**Issue by opeadeyomoye** [elastic/elasticsearch-php#731]
### Summary of problem or feature request
Trying to create an elasticsearch index via the PHP client throws this exception:
```
Exception: {"error":"Incorrect HTTP method for uri [//main_index] and method [PUT], allowed: [POST]","status":405} in [/var/www/html/project/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php, line 615]
```

### Code snippet of problem
```php
use Elasticsearch\ClientBuilder;

...

$index = ['index' => Configure::read('Elasticsearch.mainIndex')];
$client = ClientBuilder::create()->setHosts(['http://elastic:password@localhost/'])->build();

$client->indices()->create($index);
```

### System details

- Operating System: **Kali GNU/Linux Rolling**
- PHP Version: **7.0.27-1**
- ES-PHP client version: **v6.0.1**
- Elasticsearch version: **6.1.2**

**Comment by toki030** [comment]
I had the same problem.
The problem is the trailing `/` in your host URL. The error message is not helpful at this point. I think the `setHosts()` method should handle this better.

**Comment by opeadeyomoye** [comment]
Thanks a lot @toki030 . Removing the trailing forward-slash worked!

**Comment by kolosek** [comment]
@toki030 Thanks! That worked.

**Comment by sellomkantjwa** [comment]
My issue was specifying a body with the get. removed that and it worked
