### ISSUE TITLE
Unknown key for a VALUE_STRING in [search_type].

### ISSUE THREAD

**Issue by vikram0460** [elastic/elasticsearch-php#739]
### Summary of problem or feature request

https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_search_operations.html#_scrolling
Problem with scroll api, as per the scrolling api I have passed the parameters it is giving like 'Unknown key for a VALUE_STRING in [search_type].' 

But if I modify the code in Elasticsearch/Endpoints/Search.php file(https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Search.php), getURI() method like this then it is working. 

    public function getURI()
    {
        $index = $this->index;
        $type = $this->type;
        $uri   = "/_search?scroll=1m";
        if (isset($index) === true && isset($type) === true) {
            $uri = "/$index/$type/_search?scroll=1m";
        } elseif (isset($index) === true) {
            $uri = "/$index/_search?scroll=1m";
        } elseif (isset($type) === true) {
            $uri = "/_all/$type/_search?scroll=1m";
        }

        return $uri;
    }

Can you please give me documentation to add scrolling directly while calling search.

Even I went though this documentation still no luck 
https://github.com/elastic/elasticsearch-php/commit/9bcc6e196e9a158aa13e26b839fed4dfbba4877a

### System details

- Operating System CentOS 7.4
- PHP Version 7.2.3
- ES-PHP client version 6.0
- Elasticsearch version 6.2.2

**Comment by polyfractal** [comment]
Hmm, can you paste your code?  `search_type` is a very old parameter that has been removed since 2.x or so.  I think that's the issue, not the scrolling.  I believe the docs are correct with regards to scrolling:

```php
$params = [
    "scroll" => "30s",          // how long between scroll requests. should be small!
    "size" => 50,               // how many results *per shard* you want back
    "index" => "my_index",
    "body" => [
        "query" => [
            "match_all" => new \stdClass()
        ]
    ]
];

$response = $client->search($params);
```

will configure the `scroll=30s` as a query string parameter ([whitelisted here](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Search.php#L79)), and then the next portion of the docs:

```php
// Execute a Scroll request and repeat
    $response = $client->scroll([
            "scroll_id" => $scroll_id,  //...using our previously obtained _scroll_id
            "scroll" => "30s"           // and the same timeout window
        ]
    );
```
Uses the Scroll endpoint ([e.g. `/_search/scroll`](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Scroll.php#L81))

**Comment by vikram0460** [comment]
It's my bad. Thanks for the help actually I have tried passing like this 

```
$body = [
            'query' => [
                'bool' => [
                    'must' => [
                        ['match_phrase' => ['name' => $name]]
                    ]
                 ]
             ],
             'size' => $size,
            "scroll" => "30s",
        ];
$params = [
    "index" => "my_index",
    "body" => $body
];
```
Kindly close the bug thanks for your time.
