### ISSUE TITLE
Way to set refresh=wait_for

### ISSUE THREAD

**Issue by wuuti** [elastic/elasticsearch-php#745]
### Summary of problem or feature request

I currently don't see a way to set the refresh=wait_for strategy on e.g. an index-query. According to https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html I wanted to use that strategy but the client seems not to support that, instead it only supports boolean true/false for the refresh parameter to be set. 

Is this somehow supported, perhaps with using custom client parameters?

**Comment by polyfractal** [comment]
Hmm, what troubles did you run into?  Can you paste your code and/or exception?

You should be able to do this:

```php
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
    'refresh' => 'wait_for',   // <-- here
    'body' => ['testField' => 'abc']
];

$response = $client->index($params);
print_r($response);
```

The client only validates that parameters are whitelisted (e.g. [here](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Index.php#L87)), but doesn't actually check what the value of the parameters are

**Comment by wuuti** [comment]
@polyfractal You are right. It works. I was puzzled by the phpdoc in the client class, which states that a boolean is expected for the refresh. It was not clear to me that the params are passed 'as is', so that the value _wait_for_ is accepted here.

**Comment by polyfractal** [comment]
Ah I see... yes, that phpdoc is incorrect and out of date.  I'll reopen this issue so I don't forget to fix it.  Sorry about that!  Incorrect comments are arguably worse than no comments at all.

I've been buried in another project lately, but should have some free time soon to give the PHP client a bit more love than it's been getting lately.  Thanks!

**Comment by ezimuel** [comment]
Outdated issue.
