### ISSUE TITLE
es new client builder was created but not working on search, index creation queries

### ISSUE THREAD

**Issue by divya757** [elastic/elasticsearch-php#746]
es new client builder was created but not working on search, index creation queries

i am working on aws es 6.2 and laravel

my code

$hosts=[
        'host' => 'localhost(here i am using aws end point)' 
         // Only host is required
                 ];

         $client = ClientBuilder::create()           // Instantiate a new ClientBuilder
                    ->setHosts($hosts)      // Set the hosts
                    ->build();        
         dump($client);

$json = '{
    "query" : {
        "match" : {
            "title" : "phone"
        }
    }
}';

$params['index'] = 'sainikad';
$params['type']  = 'ads';
$params['body']  = $json;

$results=$client->search($params);

the error i was getting is

Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\sainik\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php:90

and dump clientbuilder was getting response as

Client {#419 ▼
  +transport: Transport {#417 ▶}
  #params: null
  #indices: IndicesNamespace {#420 ▶}
  #cluster: ClusterNamespace {#421 ▶}
  #nodes: NodesNamespace {#422 ▶}
  #snapshot: SnapshotNamespace {#423 ▶}
  #cat: CatNamespace {#424 ▶}
  #ingest: IngestNamespace {#425 ▶}
  #tasks: TasksNamespace {#426 ▶}
  #remote: RemoteNamespace {#427 ▶}
  #endpoints: Closure {#418 ▶}
  #registeredNamespaces: []
}

- windows
- above 7
- ES-PHP client version
- 6.2

**Comment by divya757** [comment]
ping is also not working, the error i was getting is when i ping

Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\sainik\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php:90

**Comment by raheelkhan** [comment]
Did you check your AWS policies ? Is your instance allowed to be connected from outside AWS ?

**Comment by polyfractal** [comment]
Closing, ticket has gone stale.  Feel free to provide more info and we can keep debugging :)
