### ISSUE TITLE
Laravel Unresolvable dependency resolving [Parameter #0 [ <required> $retries ]] in class Elasticsearch\Transport

### ISSUE THREAD

**Issue by wespiremedia** [elastic/elasticsearch-php#750]
### Summary of problem or feature request

I'm using this library in my Laravel project and getting the `Unresolvable dependency resolving [Parameter #0 [ <required> $retries ]] in class Elasticsearch\Transport` error after initializing the `ClientBuilder`

### Code snippet of problem

My Service Provider looks like this: 
```
    public function register()
    {
        //
        $this->app->bind(Elastic::class, function ($app) {
            $client = Elasticsearch\ClientBuilder::create()
                ->build();
            return $client;
        });
    }
```

I've tried different things:
- Manually set hosts and retries,
- Different namespaces of the class,
- Start it with `new` and without, 

The error suggests a required paramater is missing, but according to the manual it is not necessary to set parameters and `ClientBuilder::create()->build();` should be enough. 

### System details

Ubuntu 14.04 
PHP 7.0.8
Laravel 5.4.36
ES 6.2.3
6.0 branch of this repository

**Comment by wespiremedia** [comment]
@polyfractal Thank you for reply. 

- Tested it with either the 6.0.0 and 6.0.1 version, same problem in both versions. 
- The SO answer is about starting the GeocodeService class, the ES class is loaded in `app->bind`
- Makes sense, I've removed the Laravel code and initialized the ClientBuilder as described in the readme: `$client = ClientBuilder::create()->build();` (`use Elasticsearch\ClientBuilder; on top of the document), but the same problem occurs.

**Comment by wespiremedia** [comment]
My bad. The code was right, but I was requesting it in the wrong way. Nevermind!

**Comment by mcambal** [comment]
@wespiremedia How did you solve it?

**Comment by wespiremedia** [comment]
@mcambal I created a separate SearchController and initialized ES in the constructor:

```
public function __construct(){
        
        // Set up Elastic connector
        $this->ES = ClientBuilder::create()->build();
    
    }
```

To run a search request: 

```
$response = $this->ES->search([
            'index' => $search_index,
            'q' => '*' . $search_query . '*',
            'size' => $no_items
        ]);
```

Hopefully this will help you!

**Comment by hdwivedi9** [comment]
@wespiremedia can you show your AppServiceProvider class in the fixed version?

**Comment by wespiremedia** [comment]
@hdwivedi9 My AppServiceProvider isn't changed, the above code is added in a custom controller.

**Comment by kikkauz** [comment]
Working service provider for me:


    namespace App\Providers;
    use Illuminate\Support\ServiceProvider;
    use Elasticsearch\Client;
    use Elasticsearch\ClientBuilder;

    class ElasticsearchClientServiceProvider extends ServiceProvider
    {
        /**
         * Register services.
         *
         * @return void
         */
        public function register()
        {
            

            $this->app->singleton(Client::class, function ($app) {
                $elasticUrl = config('elasticsearch.protocol')."://".config('elasticsearch.host').":".config('elasticsearch.port');
                
                return ClientBuilder::create()->setHosts([$elasticUrl])->build();
            });
        }

        /**
         * Bootstrap services.
         *
         * @return void
         */
        public function boot()
        {
            //
        }
    }



I landed on this page as I got the same error, that I simply solved by registering the provider in the config/app.php laravel file

**Comment by alevani** [comment]
In case my "solution" my help out someone: 
I had the same errors because I forgot to register the provider in `app.php`.
