### ISSUE TITLE
how to search many index

### ISSUE THREAD

**Issue by 775397252** [elastic/elasticsearch-php#751]
### Summary of problem or feature request

i want to search many index but not all, how can i do?

- PHP Version :7.0
- ES-PHP client version:6.0
- Elasticsearch version:6.1

**Comment by polyfractal** [comment]
You can search multiple indices using comma-delimited lists, or with wildcard patterns.  See the documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

In PHP, it would look like this:

```php
$params = [
    'index' => 'index1,index2,index3,index_pattern-*', // <-- here
    'type' => '_doc',
    'body' => [
        'query' => [
            'match' => [
                'testField' => 'abc'
            ]
        ]
    ]
];

$response = $client->search($params);
```

General questions like this are best answered at the Elasticsearch discuss forums, we try to keep tickets here about bugs and feature requests, or at least PHP-specific client questions.  You can find the forums here: https://discuss.elastic.co/
