### ISSUE TITLE
ls

### ISSUE THREAD

**Issue by ssanchezromero** [elastic/elasticsearch-php#753]
### System details

- Operating System
- PHP Version
- ES-PHP client version
- Elasticsearch version

**Comment by polyfractal** [comment]
Hi @ssanchezromero, were you wanting to ask a question/file a bug?  The issue text is blank :)

**Comment by ssanchezromero** [comment]
Hi,


Yes, but I'm not sure that this problem is only with elasticsearch...


I'm trying to install bitnami akeneo image on vm virtualbox (Ubuntu 16.04). Akeneo is an application that uses elasticsearch. Do you know?

https://docs.akeneo.com/2.3/install_pim/manual/system_requirements/system_install_ubuntu_1604.html


Well, first I have problem in active the elasticsearch service but finally is active (systemctl status elasticsearch). But when I make a:

CURL -X GET 'http://localhost:9200'

an error "Failed to connect to localhost port 9200: connection refused" is displayed.

I don't know if the problem is elasticsearch or anything else... Any suggestion?

Thanks in advance!
Sergi

________________________________
De: Zachary Tong <notifications@github.com>
Enviado: martes, 17 de abril de 2018 15:15
Para: elastic/elasticsearch-php
Cc: ssanchezromero; Mention
Asunto: Re: [elastic/elasticsearch-php] ls (#753)


Hi @ssanchezromero<https://github.com/ssanchezromero>, were you wanting to ask a question/file a bug? The issue text is blank :)

**Comment by ssanchezromero** [comment]
Sorry, now I've noticed that if I ask status (elasticsearch) twice the second time it fails...


[cid:2f5336fb-535e-4270-8b2f-bb150031bbbd]



________________________________
De: Sergi Sánchez Romero <ssanchez_romero@hotmail.com>
Enviado: martes, 17 de abril de 2018 16:20
Para: elastic/elasticsearch-php
Asunto: Re: [elastic/elasticsearch-php] ls (#753)


Exactly, the error when I'm trying to install akeneo ($ bin/console pim:install --force --symlink --clean --env=prod) is:

In StaticNoPingConnectionPool.php line 51:
No alive nodes found in your cluster


Thanks!



________________________________
De: Sergi Sánchez Romero <ssanchez_romero@hotmail.com>
Enviado: martes, 17 de abril de 2018 15:47
Para: elastic/elasticsearch-php
Asunto: Re: [elastic/elasticsearch-php] ls (#753)


Hi,


Yes, but I'm not sure that this problem is only with elasticsearch...


I'm trying to install bitnami akeneo image on vm virtualbox (Ubuntu 16.04). Akeneo is an application that uses elasticsearch. Do you know?

https://docs.akeneo.com/2.3/install_pim/manual/system_requirements/system_install_ubuntu_1604.html


Well, first I have problem in active the elasticsearch service but finally is active (systemctl status elasticsearch). But when I make a:

CURL -X GET 'http://localhost:9200'

an error "Failed to connect to localhost port 9200: connection refused" is displayed.

I don't know if the problem is elasticsearch or anything else... Any suggestion?

Thanks in advance!
Sergi

________________________________
De: Zachary Tong <notifications@github.com>
Enviado: martes, 17 de abril de 2018 15:15
Para: elastic/elasticsearch-php
Cc: ssanchezromero; Mention
Asunto: Re: [elastic/elasticsearch-php] ls (#753)


Hi @ssanchezromero<https://github.com/ssanchezromero>, were you wanting to ask a question/file a bug? The issue text is blank :)

**Comment by polyfractal** [comment]
Afraid I'm not familiar with Akeneo.  That error would suggest that either the ES server is shutting down and no longer available, or perhaps not exposing the 9200 port.  Maybe the Akeneo service has configured a different HTTP port?  Alternatively, if it uses the java transport client exclusively, it may have disabled the HTTP port entirely.

**Comment by polyfractal** [comment]
Closing, don't think this is a client issue and the ticket has gone stale.  Feel free to provide some more info and we can continue debugging :)
