### ISSUE TITLE
How do I add login validation

### ISSUE THREAD

**Issue by PuShaoWei** [elastic/elasticsearch-php#754]
### Summary of problem or feature request

Hello guys:

[wiki](https://www.elastic.co/guide/en/elasticsearch/client/php-api/6.0/ElasticsearchPHP_Endpoints.html#Elasticsearch_ClientBuildersetHosts_setHosts) Didn't explain the specific parameters, how should I through login authentication??

### Code snippet of problem

```
       $builder = ClientBuilder::create();
        $builder->setHosts(array ('http://127.0.0.1:9630'));
        $client = $builder->build();
        $params  = array (
            "search_type" => "scan",
            'index'       => 'aires_all',
            'body'        => array (
                "query" => array (
                    "match_all" => array ()
                )
            )
        );
        $indices = $client->search($params);
```

```
Elasticsearch\Common\Exceptions\BadRequest400Exception : Unauthorized
```

### System details

- Operating System
- PHP Version： `PHP 7.1.11`
- ES-PHP client `>= 6.0`
- Elasticsearch version`6.0`

**Comment by PuShaoWei** [comment]
Wow! Thank you for your，This is what I want

**Comment by polyfractal** [comment]
Happy to help :)  Goodluck!
