### ISSUE TITLE
Probleme indexing a document using 'timestamp' field

### ISSUE THREAD

**Issue by enumanc** [elastic/elasticsearch-php#756]
### Summary of problem or feature request

Using Elasticsearch-PHP version 6.0 I got the following error:

Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/domaines.nc/_doc] contains unrecognized parameter: [timestamp]"}],"type":"illegal_argument_exception","reason":"request [/domaines.nc/_doc] contains unrecognized parameter: [timestamp]"},"status":400} in /var/www/html/utnc/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:615 Stack trace: #0 /var/www/html/utnc/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(279): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array) #1 /var/www/html/utnc/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #2 /var/www/html/utnc/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #3 /var/www/html/utnc/vendor/guzzlehttp/ringphp/src/Core.php(341): in /var/www/html/utnc/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 615

### Code snippet of problem

 public function indexDocument($client, $domain)
  {
    $params = [
    'index' => 'domaines.nc',
    'type' => '_doc',
    'routing' => 'company_xyz',
    'timestamp' =>  "2018-05-03T00:00:01.000Z",
    'body' => ['nom' => $domain]
  ];

  $response = $client->index($params);
  print_r($response);

### System details
- Operating System: CentOS 7
- PHP Version 7.2
- ES-PHP client version 6.0
- Elasticsearch version 6.2.4-1

**Comment by polyfractal** [comment]
Elasticsearch doesn't have a `timestamp` URL parameter.  Were you wanting to add that as part of the document as a field?

```php
 public function indexDocument($client, $domain)
  {
    $params = [
    'index' => 'domaines.nc',
    'type' => '_doc',
    'routing' => 'company_xyz',
    'body' => [
       'nom' => $domain,
       'timestamp' =>  "2018-05-03T00:00:01.000Z"
     ]
  ];

  $response = $client->index($params);
  print_r($response);
```

**Comment by polyfractal** [comment]
Well, I should say, ES doesn't have a `timestamp` URL parameter _any more_. :)

There used to be a timestamp param to be used with TTL (https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-timestamp-field.html), but that was 2.0 and earlier.  It has since been removed.

**Comment by enumanc** [comment]
Thanks, it works, BR

**Comment by MattBianco** [comment]
> 
> 
> Well, I should say, ES doesn't have a `timestamp` URL parameter _any more_. :)
> 
> There used to be a timestamp param to be used with TTL (https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-timestamp-field.html), but that was 2.0 and earlier. It has since been removed.

The documentation for 6.0 still refers to it:
https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_indexing_documents.html

**Comment by gnumoksha** [comment]
See https://discuss.elastic.co/t/-timestamp-deprecated/38514 and https://github.com/elastic/elasticsearch/issues/15644
