### ISSUE TITLE
Range selector is causing malformed query?

### ISSUE THREAD

**Issue by lucasjkr** [elastic/elasticsearch-php#758]
### Summary of problem or feature request

New to this, so most likely the problem is with me, but I throw errors when trying to use match and range in the same query.

### Code snippet of problem

These Params **work**:

    $params = [
            'index' => MESSAGE_INDEX,
            'type' => 'doc',
            'body' => [
                'query' => [
                    'match' => [
                        'chat_uuid' => $chat_uuid,
                    ],
                ],
                'sort' => [
                    'datetime' =>'asc',
                    ]
                ]
            ];

And these **work**:

        $params = [
            'index' => MESSAGE_INDEX,
            'type' => 'doc',
            'body' => [
                'query' => [

                    'range' => [
                        'datetime' => [
                            'gt' => 1525405082633,
                        ]
                    ],
                ],

                'sort' => [
                    'datetime' =>'asc',
                    ]
                ]
            ];

**But combining the two throws an error:**

        $params = [
            'index' => MESSAGE_INDEX,
            'type' => 'doc',
            'body' => [
                'query' => [
                    'match' => [
                        'chat_uuid' => $chat_uuid,
                    ],
                    'range' => [
                        'datetime' => [
                            'gt' => 1525405082633,
                        ]
                    ],
                ],

                'sort' => [
                    'datetime' =>'asc',
                    ]
                ]
            ];

The Exception I'm receiving is:

**BadRequest400Exception (400)**
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[match] malformed query, expected [END_OBJECT] but found [FIELD_NAME]","line":1,"col":38}],"type":"parsing_exception","reason":"[match] malformed query, expected [END_OBJECT] but found [FIELD_NAME]","line":1,"col":38},"status":400}

I'm not sure how I managed to malform it?

(Don't mind the MESSAGE_INDEX - it's set elsewhere by a constant).

### System details

Two VM's 

**VM 1:**
Ubuntu 16.04
Apache
PHP 7.1.14
Laravel 5.6
Elasticsearch/Elasticsearch library v 6.0.1

**VM 2:**
Ubuntu 16.04
Elasticsearch 6.2.4

### Lastly

I apologize in advance if this turns out to be a total newbie question, and will keep on playing with it to see if I can find my solution!

**Comment by polyfractal** [comment]
Heya, np with the question :)

You'll need to put those two queries inside of a "compound" query that knows how to combine them.  The most common compound query is the boolean query.  Try this:

```php
    $params = [
        'index' => MESSAGE_INDEX,
        'type' => 'doc',
        'body' => [
            'query' => [
                'bool' => [ 
                  'must' => [
                    [
                      'match' => [
                          'chat_uuid' => $chat_uuid,
                      ]
                    ],
                    [
                      'range' => [
                          'datetime' => [
                              'gt' => 1525405082633,
                          ]
                       ]
                    ]
                ]
            ],
            'sort' => [
                'datetime' =>'asc',
                ]
            ]
        ]
   ];
```

The boolean's "must" clause says that both of the `match` and `range` queries _must match_ for a document to be returned as a hit.

You could also use a "filter" clause in this situation, which does the same function except it doesn't affect the score.  Filtering is faster since it can skip scoring, it's just a boolean yes/no match rather than assigning "goodness" to the document and trying to rank.

**Comment by lucasjkr** [comment]
Hi! Thank you for writing back so fast!

Yeah, I don't need scoring, just need to check for new chat messages, where the chat id is known and the microtime() of the last message received is also known, so went with your bool and filter, didn't know about bool for multiple criteria, so that was the problem! I'll have to read more.

Ultimately, these params seem to do the job:

        $params = [
            'index' => MESSAGE_INDEX,
            'type' => 'doc',
            'body' => [
                'query' => [
                    'bool' => [
                        'must' => [
                            'match' => [
                                'chat_uuid' => $chat_uuid,
                            ]
                        ],

                        'filter' => [
                            'range' => [
                                'datetime' => [
                                    'gte' => $timestamp
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ];
 
I'll close this, as it obviously wasn't an issue in your code, just an issue with the object in between the chair and the keyboard!
