### ISSUE TITLE
Search between two dates in all indices

### ISSUE THREAD

**Issue by sewox** [elastic/elasticsearch-php#760]
### Summary of problem or feature request

I need matching dates in the properties.Date field within about 30 indexes. I get an error when doing this.

### Code snippet of problem
  $date1 = $_GET["properties_Date"];
  $date2 = $_GET["properties_Date1"];
  $start = str_replace("_",".",$date1);
  $end = str_replace("_",".",$date2);
  echo $start ."<br>". $end;
  $params['index'] = "*";
  $params['type'] = 'Loglar';
  $params['body']['query']['filtered']['filter']['and'] = [
    [
      'range' => [
        'properties.Date' => [
          'gte' => $start,
          'lte' => $end
        ]
      ]
    ]
  ];

$params['size'] = 100;
$params['sort'] = array('@timestamp:desc');
$sonuc = $client->search($params);

### System details

- Operating System -> Turnkey Linux
- PHP Version -> 7.2.4
- ES-PHP client version  -> 6.0
- Elasticsearch version -> 6.2

**Comment by sewox** [comment]
error code i get

Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"parsing_exception","reason":"no [query] registered for [filtered]","line":1,"col":22}],"type":"parsing_exception","reason":"no [query] registered for [filtered]","line":1,"col":22},"status":400} in /var/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:615 Stack trace: #0 /var/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(279): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array) #1 /var/www/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #2 /var/www/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #3 /var/www/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #4 /var/www/vendor/elast in /var/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 615

**Comment by polyfractal** [comment]
The `filtered` query was deprecated and removed (forget which version, but definitely gone by 6.x).  You'll need to use the `filter` clause in the `boolean` query now.  See: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html for more details.
