### ISSUE TITLE
Delete ElasticSreach Indexing example not working

### ISSUE THREAD

**Issue by hoduckhoa** [elastic/elasticsearch-php#766]
So I have ES-PHP 6.0 installed and I am trying the bulk index example, I am getting error
messages, I don't know what I am doing wrong as I just copied and pasted the example.

The normal indexing works but it is very slow when doing 100k rows.

Version of ElasticSearch I am using is "number" : "6.2.4", "_version" : "5.2.6", 

Error messages:
Elasticsearch\\Common\\Exceptions\\InvalidArgumentException: id cannot be null. in /var/www/html/rbmq/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php:1524\nStack trace:\n#0 /var/www/html/rbmq/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(251): Elasticsearch\\Client->verifyNotNullOrEmpty('id', NULL)\n#1 /var/www/html/rbmq/delete.php(24): Elasticsearch\\Client->delete(Array)\n#2 {main}\n  thrown in /var/www/html/rbmq/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php on line 1524

code.

`<?php
require_once __DIR__ . '/vendor/autoload.php';

use Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()->build();

$params = [
    'index' => $_POST['index'],
    'type' => $_POST['type'],
    'id' => $_POST['id']
];

if ($client->delete($params)){
    echo "delete success";
}else{
    echo "delete fail";
}
?>`

**Comment by polyfractal** [comment]
Can you confirm that `$_POST['id']` is not null?  You can add a `print_r($params)` before the delete API call to manually verify, or add some `isset()` or `is_null()` checks in there 

You said you're trying to use the Bulk API... but the above code is for the single deletes.  Are you having issues with single deletes or with bulks?

**Comment by polyfractal** [comment]
Closing due to lack of info.  Feel free to provide more and we can reopen. :)
