### ISSUE TITLE
nested aggregations

### ISSUE THREAD

**Issue by sewox** [elastic/elasticsearch-php#767]
hi everyone,
i tired searching an trying. 
I need to group the nested fields.
The sql query is as follows
`SELECT p_application_category,Sum(p_recv_bytes) as download,p_date FROM ZLog2 $w group by p_application_category;`

**Comment by polyfractal** [comment]
This would be better asked at the [Elasticsearch Discuss Forums](https://discuss.elastic.co/c/elasticsearch.  You'll need to use the [nested aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-nested-aggregation.html) depending on which field(s) are nested, and a [terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html) for the grouping
