### ISSUE TITLE
Didn't get the data from elastic search using IE browser

### ISSUE THREAD

**Issue by NeelakantanS** [elastic/elasticsearch-php#768]
There are not console errors. 

### System details

- Operating System
- PHP Version
- ES-PHP client version
- Elasticsearch version

**Comment by polyfractal** [comment]
You're going to have to provide more information if you want help.

What didn't work?  What code did you use?  The default issue template has these items for a reason :)

>Summary of problem or feature request
Code snippet of problem
System details

>    Operating System
>    PHP Version
>    ES-PHP client version
>    Elasticsearch version
