### ISSUE TITLE
How to elasticsearch return all hits

### ISSUE THREAD

**Issue by hoduckhoa** [elastic/elasticsearch-php#770]
**Code :** 
`$client = ClientBuilder::create()->build();
$params = [
    'index' => 'rbmq',
    'type' => 'users',
    'body' => [
        'query' => [
            'match' => [
                'email' => [
                    'query' =>'@gmail.com',
                    'operator'=>'and'
                ]
                ],
            ]
        ]
    ];
$results = $client->search($params);
$r=$results["hits"]["hits"];
$total = $results["hits"]["total"];
echo "TOTAL:  ". $total ."<br>";
 foreach ($r as $key ) {
            echo $key["_source"]["email"],"<br>" ;
            echo $key["_source"]["username"];
           echo "<br>";
  }`
**Result:**
TOTAL: 13
**return hits**: 10 hits, WHY??,

**Comment by atakajlo** [comment]
elasticsearch limits the number of records returned by any query to 10 records by default

**Comment by polyfractal** [comment]
Yep.  Increase the `size` parameter, or use the [scroll api](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) to retrieve a very large list of hits.

@hoduckhoa Questions like this are best asked at the [Elasticsearch Discuss Forums](https://discuss.elastic.co/c/elasticsearch).  We try to reserve tickets in this repository for bugs, feature requests and help with the Elasticsearch-PHP client itself, not general Elasticsearch questions.  Thanks!
