### ISSUE TITLE
How to use term suggester of elasticsearch in php ?

### ISSUE THREAD

**Issue by vishwasPHPDots** [elastic/elasticsearch-php#772]
There is no method for sending search request with post method and term  and phrase suggester sends search request with post method so , how to do it in php elasticsearch api? 

- Operating System : Windows 10
- PHP Version : 7.*
- Elasticsearch version : 6.2

**Comment by polyfractal** [comment]
If you're on Elasticsearch 6.x, suggesters are now just part of the regular Search API:  https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html

So you'll need to add a `suggest` parameter to the body of a search request.

```php
$params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'body' => [
        'query' => [
            'match' => [
                'testField' => 'abc'
            ]
        ],
        'suggest' => [
          // Suggester stuff goes here
        ]
    ]
];

$response = $client->search($params);
print_r($response);
```

**Comment by vishwasPHPDots** [comment]
Thank you for the response and sorry for the late reply, but I replied late because I found the exact solution and forgot to post it here.
