### ISSUE TITLE
Elasticsearch v 6.0.1 requires php v7.0 or higher

### ISSUE THREAD

**Issue by adrwer** [elastic/elasticsearch-php#777]
Hello,
I've been trying to update the elastic search package on my local repository using GIT Bash on Windows 10 Home but I get the following error despite uppgrading my version of php to 7.0.29 on wamp 3.1.3

```
 Problem 1
    - elasticsearch/elasticsearch v6.0.1 requires php ^7.0 -> your PHP version (5.6.35) does not satisfy that requirement.
    - elasticsearch/elasticsearch v6.0.0 requires php ^7.0 -> your PHP version (5.6.35) does not satisfy that requirement.
    - Installation request for elasticsearch/elasticsearch ^6.0 -> satisfiable by elasticsearch/elasticsearch[v6.0.0, v6.0.1].

```
Please help

**Comment by polyfractal** [comment]
I'm afraid I don't know much about WAMP, but it sounds like it isn't finding/using the upgraded version of PHP that you installed.  It's still using 5.6.35.

I'd consult with the WAMP developers and see how to get it to find the more modern version of PHP.

**Comment by mhujer** [comment]
@adrwer check if you don't have a "fixed" PHP version in `"platform"` field in `composer.json`.

**Comment by adrwer** [comment]
Thanks  @polyfractal. 
 
I don't have the "`platform`" field in `composer.json`. How should it look like? @mhujer

**Comment by mhujer** [comment]
What is displayed when you run `php -v`?

**Comment by adrwer** [comment]
This is what is displayed
```
PHP 5.6.35 (cli) (built: Mar 29 2018 14:28:58)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

```

**Comment by adrwer** [comment]
I solved the issue. I had to update my path variable on environment variables under system variables.
Thanks @mhujer
