### ISSUE TITLE
HUGE memory leaking

### ISSUE THREAD

**Issue by kiros32** [elastic/elasticsearch-php#779]
In amqp consumer we use elasticsearch client to check if user exists (actually whatever)

With every next call of "exists" method - memory usage grows. If user does not exists - memory usage GROWS LIKE CRAZY.

Here is an example of how memory usage grows if user does not exists

```php
$iter = 1;
while ($iter < 5000) {
    if ($elasticClient->exists([
        'index' => 'subscriber',
        'type' => '_doc',
        'id' => $iter,
    ])) {
        $found++;
    } else {
        $not_found++;
    }

    $iter++;
    if ($iter % 1000 === 0) {
        echo sprintf("Iter %d, found: %d, memory usage: %0.2f MB, time: %0.2f\n", $iter, $found, (memory_get_usage(true) - $memory)/1024/1024, microtime(true) - $ts);
    }
}
```
Result
Iter 1000, found: 0, memory usage: 32.00 MB, time: 1.13
Iter 2000, found: 0, memory usage: 64.00 MB, time: 2.14
Iter 3000, found: 0, memory usage: 98.00 MB, time: 3.18
Iter 4000, found: 0, memory usage: 132.00 MB, time: 4.25
Iter 5000, found: 0, memory usage: 166.00 MB, time: 5.34

version "elasticsearch/elasticsearch": "~6.0"

Please help.

**Comment by polyfractal** [comment]
You have a variable `$memory` which isn't initialized in the snippet, but seems to be used in the memory calculation.  Are you sure this isn't being changed somehow?

E.g. if I run this snippet (no `$memory`) I don't see this behavior at all:

```php
$client = Elasticsearch\ClientBuilder::create()->setHosts(["localhost:9200"])->build();
$found = 0;
$not_found = 0;
$iter = 1;
$ts = microtime(true);
while ($iter < 5000) {
    if ($client->exists([
        'index' => 'subscriber',
        'type' => '_doc',
        'id' => $iter,
    ])) {
        $found++;
    } else {
        $not_found++;
    }

    $iter++;
    if ($iter % 1000 === 0) {
        echo sprintf("Iter %d, found: %d, memory usage: %0.2f MB, time: %0.2f\n",
            $iter, $found, (memory_get_usage(true))/1024/1024,
            microtime(true) - $ts);
    }
}
```

Which yields:

```
Iter 1000, found: 0, memory usage: 12.00 MB, time: 0.89
Iter 2000, found: 0, memory usage: 12.00 MB, time: 1.64
Iter 3000, found: 0, memory usage: 12.00 MB, time: 2.41
Iter 4000, found: 0, memory usage: 12.00 MB, time: 3.18
Iter 5000, found: 0, memory usage: 12.00 MB, time: 3.88
```

What version of PHP are you using?

**Comment by sevlad** [comment]
PHP 7.1.12 + docker - works correct, PHP 7.1.17 + cluster (2 nodes) - problem is reproduced.

**Comment by polyfractal** [comment]
I just spun up a 2 node cluster and got the same results both with PHP 7.2.7 (my previous results) and PHP 7.1.17.

What version of curl is installed and being used by PHP?  Are your nodes configured with SSL/TLS?  There are various reports about curl leaking memory with SSL, depending on version.  Perhaps try upgrading your libcurl version and see if that helps?

My curl is:

```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
```

I think this is a system issue somehow, not the client.  If it's working with the single node docker instance, it should work with the multi-node.  E.g. there's no different execution path if there are multiple nodes, the same response is being processed in both cases.

**Comment by kiros32** [comment]
ok, thanks, we'll check

**Comment by polyfractal** [comment]
Another thought, although unlikely:  is there someplace that GCs are being disabled (either via `gc_disable()` or in the config)?  That could manifest as a memory leak too, since garbage isn't being collected.

I doubt that's the cause... not sure I've ever seen anyone disable GC before, but wanted to mention it :)

**Comment by kiros32** [comment]
@polyfractal absolutely excluded)

**Comment by ezimuel** [comment]
Outdated issue. @kiros32 if you still have the issue let me now, i'll reopen it. Thanks!
