### ISSUE TITLE
bulk update using php gives error script or doc is missing

### ISSUE THREAD

**Issue by rawmaterials** [elastic/elasticsearch-php#784]
### Summary of problem or feature request
i am trying to bulk update using php and followed advice from https://github.com/elastic/elasticsearch-php/issues/452 but when i tried i got 
`{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: script or doc is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: script or doc is missing;"},"status":400}
`

my php code looks like this

```
<?php
require 'vendor/autoload.php';

use Elasticsearch\ClientBuilder;

$elasticsearch = ClientBuilder::create()->build();

$get_updated_records = mysqli_query($conn, "SELECT content_id, uploaders, downloaders FROM content WHERE is_updated = '1' order by uploaders DESC") ;

//create blank array
$results = array();

while($row = mysqli_fetch_assoc($get_updated_records)){
	//put all results in array
	$results[] = $row;
	
}	

//from https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_indexing_documents.html

$params = ['body' => []];

for($i = 0; $i < count($results); $i++) {
    $params['body'][] = [
        'update' => [
            '_index' => $elastcsearch_index,
            '_type' => $elastcsearch_type,
            '_id' => $results[$i]['content_id']
        ]
    ];

    $params['body'][] = [
        'uploaders' => intval($results[$i]['uploaders']) ,
        'downloaders' => intval($results[$i]['downloaders'])
    ];

    // Every 1000 documents stop and send the bulk request
    if ($i % 1000 == 0) {
        $responses = $elasticsearch->bulk($params);

        // erase the old bulk request
        $params = ['body' => []];
		
		//printr($responses) ;
        // unset the bulk response when you are done to save memory
        unset($responses);
		//die;
    }
}

// Send the last batch if it exists
if (!empty($params['body'])) {
    $responses = $elasticsearch->bulk($params);
}


```

- Operating System centos 7 x64
- PHP Version PHP 7.2.6
- ES-PHP client version 
- Elasticsearch version 6.3

**Comment by polyfractal** [comment]
Thanks for the new ticket @rawmaterials, helps me keep track of what needs doing :)

You need to specify a `doc` parameter in the body of the update.  This is basically saying "these are the values I want to update the document with".  It's namespaced under `doc` to differentiate it from `script`.

E.g. you need to do this:

```php
$params['body'][] = [
  'doc' => [        // <-- note the doc parameter
        'uploaders' => intval($results[$i]['uploaders']) ,
        'downloaders' => intval($results[$i]['downloaders'])
    ]
];
```
```

**Comment by rawmaterials** [comment]
Thanks , looking in to it.

**Comment by rawmaterials** [comment]
damn, it replaced original document .

old document was .


{
  "title": "John.Doe.mill.dane",
  "tags": "",
  "category": 100,
  "sub_category": 100,
  "size": 100,
  "uploaders": 100,
  "downloaders": 100,
  "upload_date": "2018-09-25 12:00:05",
  "uploader": "aloha"
}

i did update using above method.

{
  "uploaders": 100,
  "downloaders": 100,
}


now my current document is

{
  "uploaders": 100,
  "downloaders": 100,
}

i am trying to do bulk partial update.

**Comment by ezimuel** [comment]
Outdated issue. @rawmaterials if this is still an issue I'll reopen it.
