### ISSUE TITLE
Can't complete composer installation

### ISSUE THREAD

**Issue by kane1656** [elastic/elasticsearch-php#788]
I can't complete composer installation.
below is message 

> bitnami@ip-172-30-3-5:~/htdocs/elasticsearch-php$ php composer.phar install
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Can only install one of: elasticsearch/elasticsearch[v6.0.0, dev-master].
>     - Can only install one of: elasticsearch/elasticsearch[v6.0.1, dev-master].
>     - Installation request for elasticsearch/elasticsearch dev-master -> satisfiable by elasticsearch/elasticsearch[dev-master].
>     - Installation request for elasticsearch/elasticsearch ~6.0 -> satisfiable by elasticsearch/elasticsearch[v6.0.0, v6.0.1].
> 
> 

### System details
php 7.1.19
apach 2.4

on EC2 @ AWS
bitnami-lampstack-7.1.19-0-linux-ubuntu-16.04-x86_64-hvm-ebs-mp-cb6afd05-a3b2-4916-a3e6-bccd414f5f21-ami-05eea2958f856ec96.4 (ami-674e7e18)

Could someone help me??
thank you.

**Comment by kane1656** [comment]
and (surely?) I can't have 'vendor/autoload.php' too.
I don't have "vendor" folder.

**Comment by okneloper** [comment]
@kane1656  Have you resolved the issue? Looks like the issue was with your `composer.json` rather than `elasticsearch`?

**Comment by ezimuel** [comment]
Outdated issue. @kane1656 if this is still an issue, I'll reopen it.
