### ISSUE TITLE
Can we release v5.3.3, that would point to the latest commit in 5.0 branch?

### ISSUE THREAD

**Issue by antonbormotov** [elastic/elasticsearch-php#797]
### System details

- Operating System
- PHP Version
- ES-PHP client version
- Elasticsearch version

**Comment by antonbormotov** [comment]
@polyfractal We'd be grateful

**Comment by minhtran17** [comment]
Hi, we're really looking forwards to the release, would be grateful. thanks

**Comment by mmoreram** [comment]
Same for version 6.2, please :)

**Comment by ezimuel** [comment]
@antonbormotov, @minhtran17 I don't know if this still relevant for you but we have [5.4.0](https://github.com/elastic/elasticsearch-php/releases/tag/v5.4.0) that points to the latest commit of 5.0 branch. I'm closing this issue, I'll reopen if you want. Thanks!
