### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by sandfoxme** [elastic/elasticsearch-php#798]
PHP 7.3 will deprecate FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED

https://wiki.php.net/rfc/deprecations_php_7_3#filter_flag_scheme_required_and_filter_flag_host_required

[src/Elasticsearch/ClientBuilder.php#L674
](https://github.com/elastic/elasticsearch-php/blob/7241e69095ce52c121fe2e9491fa2a7207be5dcf/src/Elasticsearch/ClientBuilder.php#L674)

```php
    /**
     * @param string $host
     *
     * @return string
     */
    private function prependMissingScheme($host)
    {
        if (!filter_var($host, FILTER_VALIDATE_URL, FILTER_FLAG_SCHEME_REQUIRED)) {
            $host = 'http://' . $host;
        }
        return $host;
    }
```

~~This function probably requires a php version check. In php 7.2 and later the flag can be omitted~~ It's 5.2, not 7.2. Just remove it

**Comment by gregharmontn** [comment]
I'm using this package with a Laravel installation and it seems Laravel is converting the warning to an ErrorException. This may be what Rob is experiencing as well.

**Comment by robtesch** [comment]
@sandfoxme Sorry, yes, i should have provided some more context. As @gregharmontn has mentioned, I am using elasticsearch in a Laravel app in conjunction with [](https://github.com/laravel/scout) and [](https://github.com/babenkoivan/scout-elasticsearch-driver). This combination seems to be converting the deprecation warning to an ErrorException, meaning I cannot use php7.3 at this time if i want to keep using elasticsearch.

**Comment by juherr** [comment]
A pull request is already proposed: https://github.com/elastic/elasticsearch-php/pull/823

**Comment by sandfoxme** [comment]
@gregharmontn @robtesch Thanks. I was afraid there were some more troubles

@juherr seems to be a duplicate of #803. Anyway, neither of them is merged :(

**Comment by robtesch** [comment]
Will patiently await a merge and release then... many thanks for the help so far.

**Comment by polyfractal** [comment]
Merged fix into master, will merge the other branches where appropriate.  Need to do a few other much-needed updates (for recent ES versions), then will tag and release before end of day.

So so sorry for the delay on this!  My dev time has been increasingly pulled away from the client to core ES work, hence the lack of progress here.

But good news, we've hired someone who will be taking over the PHP client (and other client responsibilities), so PHP-land should be getting a lot more love soon.  Thanks for your patience!

**Comment by jonathanpmartins** [comment]
So happy to hear that!

**Comment by polyfractal** [comment]
Hey folks, versions `6.1.0`, `5.4.0`, and `2.4.0` tagged and pushed which include the PHP 7.3 changes.

Thanks again for your patience :)

**Comment by robtesch** [comment]
Hi there @polyfractal, thanks so much for all the work. In my project, the elasticsearch-php package is a sub-dependency, so in order to force an update to 6.1 I tried to simply add it to my dependencies directly, using "^6.1.0" as the version constraint. Unfortunately it doesn't appear that this release is on packagist. Am i perhaps doing something wrong here?

**Comment by polyfractal** [comment]
@robtesch no worries at all, it was a problem on our side (https://github.com/elastic/elasticsearch-php/issues/830).  The repo has/had an outdated webhook which caused Packagist to stop updating.  I kicked off a manual update and we're installing the new webhook now :)

**Comment by OneCodeMonkey** [comment]
"elasticsearch/elasticsearch": "^6.1.0"  ，this works!
