### ISSUE TITLE
No alive nodes found  in your cluster

### ISSUE THREAD

**Issue by passika** [elastic/elasticsearch-php#804]
### Summary of problem or feature request

Always get error about not found nodes, ES setuped correct and works perfect from console.

Laravel

Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found 
in your cluster in /home/forge/api.enigma.ua/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51

### Code snippet of problem

Article::reindex();

-->

### System details

- Operating System UBUNTU 16
- PHP Version 7.1
- ES-PHP client version 
- Elasticsearch version

**Comment by philkra** [comment]
Is this issue still relevant? We're you able to solve it?

**Comment by benanderton** [comment]
Just on the off chance take a look at https://github.com/elastic/elasticsearch-php/issues/509#issuecomment-491825174 @passika

**Comment by ezimuel** [comment]
Solved by @benanderton in https://github.com/elastic/elasticsearch-php/issues/509#issuecomment-491825174
