### ISSUE TITLE
No alive nodes found in your cluster 

### ISSUE THREAD

**Issue by FredrikLodon** [elastic/elasticsearch-php#805]
### Summary of problem or feature request
I have a strange scenario. I have two test environments which my configuration works flawless. But in my live environment I get the "No alive nodes found in your cluster" message.

So this is my two test environments which Elastic Cloud works great.
1. VB-Ubuntu, setup:
- Ubuntu 16.04
- PHP 7.1.22-1+ubuntu16.04.1+deb.sury.org+1
- PHP7.1-curl
- Elasticsearch-php v6.0.1
Note: Above works flawless  - return desired result - both from the code itself and by "curl https://username:pass@myadress" from terminal.

2. MAMP
- MAMP under OSX
- php7.2.1
- curl7.52.1
- Elasticsearch-php v6.0.1
Note: Above works flawless - return desired result - both from the code itself and by "curl https://username:pass@myadress" from terminal.

This is the live-host, which the problem occurs
3. The-trouble-host
- Debian 8.11
- PHP 7.1.22-1+0~20181001133629.6+jessie~1.gbp113f3b
- PHP7.1-curl
- Elasticsearch-php v6.0.1
Note: This is my prod-server. Which returns the error below, Im using row breaks to get it a little bit more clear to look at:

[Fri Oct 05 16:39:28.787535 2018] 
[proxy_fcgi:error] 
[pid 17303:tid 139723339167488] 
[client 85.225.129.215:50158] 
AH01071: 
Got error 'PHP message: PHP Fatal error:  
Uncaught Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException: 
No alive nodes found in your cluster in /srv/www.xxxx.xxxx/htdocs/wp-content/plugins/xxxxxxxx/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51
\nStack trace:\n#0 /srv/www.xxxxx.xxx/htdocs/wp-content/plugins/xxxxx/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(76): 
Elasticsearch\\ConnectionPool\\StaticNoPingConnectionPool->nextConnection()\n#1 /srv/www.xxxx.xxx/htdocs/wp-content/plugins/xxxxx/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(94): 
Elasticsearch\\Transport->getConnection()\n#2 /srv/www.xxxxx.xxxx/htdocs/wp-content/plugins/xxxxx/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(246): 
Elasticsearch\\Transport->performRequest('GET', '/elasticxxxs...', Array, '{"query":{"matc...', Array)\n#3 /srv...\n', referer: https://www.xxxx.xxxx/search/?find=razor

How come I get this problem on this setup?

**Comment by FredrikLodon** [comment]
Im still troubleshooting this and have figured that if this error can come up if some sort of port is blocking the connection? Although this is a long-shot, I can figure out why Im having this problem on the "3. The-trouble-host".

**Comment by nclavaud** [comment]
Did you try the curl command on the faulty host ?

**Comment by gamelife1314** [comment]
Did you set proxy environment (http_proxy, https_proxy) ?

**Comment by benanderton** [comment]
I came across a similar issue regarding the hostname, please see https://github.com/elastic/elasticsearch-php/issues/509#issuecomment-491825174

**Comment by PutziSan** [comment]
In my case it was a problem with SSL certificates (on windows). [This SO response](https://stackoverflow.com/a/34883260/5627010) describes the solution:

1. download an official `cacert.pem` from https://curl.haxx.se/docs/caextract.html and save it where you want
1. add `curl.cainfo = "C:\your\path\cacert.pem"` to your `php.ini`

**Comment by ezimuel** [comment]
@FredrikLodon I'm closing this issue, I'll reopen if still relevant.
