### ISSUE TITLE
Duplicated logic that reassign the same value

### ISSUE THREAD

**Issue by nclavaud** [elastic/elasticsearch-php#807]
### Summary of problem or feature request

While digging through the code I stumbled against what looks like duplicated logic (with no effect at all). Like having a control structure that will reassign the same value to some variable.

### Code snippet of problem

For example, this code block from [Elasticsearch\Endpoints\Indices](https://github.com/elastic/elasticsearch-php/blob/v6.0.1/src/Elasticsearch/Endpoints/Indices/Exists.php#L25-L35) (comments are my own):
```php
    public function getURI()
    {
        if (isset($this->index) !== true) {
            throw new Exceptions\RuntimeException(
                'index is required for Exists'
            );
        }
        $index = $this->index;
        $uri   = "/$index";

        if (isset($index) === true) {    // quite the same logic as the previous isset call
            $uri = "/$index";            // $uri is reassigned the same value
        }

        return $uri;
    }
```

### Proposal
I've started to clean things on my own fork and could open a PR if it ever makes sense:
https://github.com/elastic/elasticsearch-php/compare/master...nclavaud:remove_duplicate_logic?expand=1

**Comment by ezimuel** [comment]
The endpoints has been refactored, these "inconsistences" should not be present anymore.
