### ISSUE TITLE
Strange behaviour after sorting

### ISSUE THREAD

**Issue by ozza** [elastic/elasticsearch-php#808]
### Summary of problem or feature request

Hello,

I'm trying to get first or last n documents of a specified type on my index by using iid (long) or timestamp (date). The code below is working fine:

```php
$client = ClientBuilder::create()->setHosts([
            'host' => 'localhost',
            'port' => '9200',
            'scheme' => 'http'
        ])->build();

$params = [
            'index' => $index,
            'type' => $type,
            'body' => [
                "query" => [
                    "bool" => [
                        "must" => [
                            "match_all" => (object)[]
                        ]
                    ]
                ]
            ]
        ];

        $results = $client->search($params);
```

As expected it returns 10 random (i don't know how it selects) documents. But after adding sort parameter to the code, nothing returns even a response.

```php
$params = [
            'index' => $index,
            'type' => $type,
            'body' => [
                "query" => [
                    "bool" => [
                        "must" => [
                            "match_all" => (object)[]
                        ]
                    ]
                ],
                "sort" => [
                    "iid"
                    //i tried like this too:
                    // "iid" => ["order" => "asc"]
                ]
            ]
        ];
```
I checked for some simple URL searches on the browser and see that they're working. 

```
http://localhost:9200/index/type/_search?sort=iid:asc
```

Am I doing something wrong? Can you suggest me something what to check, what to correct?

Thanks.

### System details

- Operating System: Centos 7
- PHP Version: 7.1
- ES-PHP client version: 5
- Elasticsearch version: 5.3 & 5.6

**Comment by nclavaud** [comment]
According to [the documentation](https://github.com/elastic/elasticsearch-php/blob/v5.3.2/docs/php_json_objects.asciidoc#arrays-of-objects), it looks like an array nesting issue.

Did you try this?
```php
"sort" => [
    ["iid" => ["order" => "asc"]],
],
```

**Comment by ozza** [comment]
Hello @nclavaud,

Thanks for your suggestion.

Increasing memory did the trick. I think sorting 500m documents on 4 gigs of ram is not possible :) But the interesting part is, it's only failing on php code. Simple URL searches and python works. I wonder if it's a timeout like problem.

**Comment by philkra** [comment]
issue solved
