### ISSUE TITLE
Index exists() always true with wildcards

### ISSUE THREAD

**Issue by coffeeburrito** [elastic/elasticsearch-php#809]
### Summary of problem or feature request

When using a wildcard in the 'index' field of params, the indices-scope exists() function always returns true and get() functions return an empty array. Is this intended behaviour?

### Code snippet of problem

```php
function exists($indices, $params) {
	print("\nExists: ");
	if ($indices->exists($params)) {
		print("true");
	} else {
		print("false");
	}
}

function get($indices, $params) {
	print("\nGet: ");
	try {
		$res = $indices->get($params);
		print_r(array_keys($res));
	} catch (\Exception $e) {
		print("Exception!");
	}
}

public function handle() {
	$indices = $this->client->indices();
	$params = [
		'index' => "*"
	];
	$this->exists($indices, $params);
	$this->get($indices, $params);

	$params = [
		'index' => "applications"
	];
	$this->exists($indices, $params);
	$this->get($indices, $params);

	$params = [
		'index' => "bad"
	];
	$this->exists($indices, $params);
	$this->get($indices, $params);

	$params = [
		'index' => "bad*"
	];
	$this->exists($indices, $params);
	$this->get($indices, $params);

	$params = [
		'index' => "b*ad"
	];
	$this->exists($indices, $params);
	$this->get($indices, $params);
}
/*
OUTPUT: 
Exists: true
Get: Array
(
    [0] => applications
)

Exists: true
Get: Array
(
    [0] => applications
)

Exists: false
Get: Exception!
Exists: true <-expected to be false
Get: Array
(
)

Exists: true <-expected to be false
Get: Array
(
)
*/
```

### System details

- Ubuntu 16.04
- PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1 
- ES-PHP client version 6.0.1
- Elasticsearch version 6.2.3

**Comment by coffeeburrito** [comment]
I want to clarify I understand that this is a direct representation of how Elasticsearch handles it (returning a 200 empty array instead of 404), but from a pure usability perspective I feel this could be handled better by elasticsearch-php

**Comment by polyfractal** [comment]
Hm, I'm not sure there's anything the client _can_ do here.  The Exists calls are all HEAD requests, so all we get back is the status code.  There's no empty body to check... we have to just convert the status into a true/false for the user.

I dug a bit and this is a proper bug in ES.  I've opened a PR to fix it on that side: https://github.com/elastic/elasticsearch/pull/34499

**Comment by ezimuel** [comment]
Outdated issue.
