### ISSUE TITLE
Unable to mock ClientBuilder in unit testing due to Monolog dependency inside

### ISSUE THREAD

**Issue by JerryDing2014** [elastic/elasticsearch-php#813]
### Summary of problem or feature request
When mocking ClientBuilder in a unit test, it will throw out a not found exception "Monolog not found".

Looked into the code, found that `defaultLogger()` returns a `\Monolog\Logger\Logger` which is not included in composer.json

Checked the latest ClientBuilder in master branch, the dependency is till and is not included in composer.json even though https://github.com/elastic/elasticsearch-php/pull/674 was in "**merged**" status.

### Code snippet of problem
```php
\Mockery::mock(ClientBuilder::class); //<- throw exception, Monolog not found
```

### System details

- Operating System: centos 7
- PHP Version: 5.6
- ES-PHP client version: 5.0
- Elasticsearch version: 6.4

**Comment by ezimuel** [comment]
@JerryDing2014 sorry for the very long reply on this. You right, this is an old requirement that has been removed with the usage of PSR-3 Logger. Anyway, the `Monolog` is still present in the `use` of `ClientBuilder` code but never used. I'll remove it asap. Thanks and sorry again for the late reply.
