### ISSUE TITLE
SmartSerializer decode error suppression side effects

### ISSUE THREAD

**Issue by retnek** [elastic/elasticsearch-php#819]
### Summary of problem or feature request

We work large elastic index documents in a standard search operation and it's sometimes causes memory limit fatal errors, and instead of we see the error SmartSerializer hides that, and it makes the debugging process harder.

### Code snippet of problem
In SmartSerializer.php line 82:

```php
$result = @json_decode($data, true);
```

Now we create our own serializer class which is exactly the same as SmartSerializer, but without the error suppression operator, and it's shows the fatal errors if it's occurs.

### System details
- debian stretch
- PHP 7.2.9
- ES-PHP client version: 6.0.1
- Elasticsearch version 6.4

**Comment by ezimuel** [comment]
@retnek I'm closing this old issue because I'm not sure if it's still relevant. Now we are also using `JsonException` for PHP 7.3+ to manage errors in json_decode(). Let me know if you want to reopen it. Thanks!
