### ISSUE TITLE
Incorrect uri and required parameters for Client::getScript and Client::deleteScript

### ISSUE THREAD

**Issue by jumandan** [elastic/elasticsearch-php#824]
### Summary of problem or feature request

When I trying to check script existence the PHP client throw exception:

```
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":"Incorrect HTTP method for uri [/_scripts/painless/indexname] and method [GET], allowed: [PUT, POST]","status":405}
```
### Code snippet of problem

```php
$client->getScript(['id' => 'indexname', 'lang' => 'painless']);
```

### Additions
According with [elastic.co](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html) lang isn't required parameter and uri must be:

```
curl -X GET "localhost:9200/_scripts/indexname"
```

There is [#814](https://github.com/elastic/elasticsearch-php/pull/814) for this issue.

**Comment by ezimuel** [comment]
Fixed by #814
