### ISSUE TITLE
Recent release is not available on packagist

### ISSUE THREAD

**Issue by eigan** [elastic/elasticsearch-php#830]
5.4 and 6.1 at least :)

https://packagist.org/packages/elasticsearch/elasticsearch

**Comment by polyfractal** [comment]
Looks like we are using a deprecated web-hook and packagist stopped being notified.  Kicked off a manual update and will change the hook now.

- https://packagist.org/packages/elasticsearch/elasticsearch#v6.1.0
- https://packagist.org/packages/elasticsearch/elasticsearch#v5.4.0
- https://packagist.org/packages/elasticsearch/elasticsearch#v2.4.0

Thanks for the ping!
