### ISSUE TITLE
How would I go about adding AWS v4 signature headers

### ISSUE THREAD

**Issue by mwleinad** [elastic/elasticsearch-php#833]
I have a project with a policy to allow access from specific IPs.
This works correctly but is a PITA to add IP's every time someone decides to work remotely or something.

I'd like to use an IAM user instead.

According to AWS
"To do authentication with Elasticsearch using IAM roles, you have to add AWS v4 signature headers to the requests being sent to Elasticsearch"

But I can't find documentation about it. 
Any idea? Thanks!

**Comment by pittersnider** [comment]
I am also needing this.

**Comment by ezimuel** [comment]
@mwleinad and @pittersnider you can have a look at this library [jeskew/amazon-es-php](https://github.com/jeskew/amazon-es-php) that enables the usage of AWS v4 signature in `elastic/elasticsearch-php`.
