### ISSUE TITLE
No type with reason is FORBIDDEN

### ISSUE THREAD

**Issue by jeremyrncp** [elastic/elasticsearch-php#841]
https://github.com/elastic/elasticsearch-php/blob/0be4afde22689ffaff2324efb7604b522b5a9ccd/src/Elasticsearch/Connections/Connection.php#L703

In my environnment, have no type with reason is FORBIDDEN and get index type throw an error:

dump $root 
``
array(1) {
  [0]=>
  array(1) {
    ["reason"]=>
    string(9) "FORBIDDEN"
  }
}
``

**Comment by polyfractal** [comment]
Sounds like you are trying to access a resource/server that is protected by authorization?

**Comment by jeremyrncp** [comment]
Yes et in that use case, error no contain type

**Comment by polyfractal** [comment]
Yeah, that's not unexpected.  That error handler is there to parse Elasticsearch errors in a specific syntax.  Random HTTP errors from proxies/auth/etc don't fit the ES error syntax and the fields won't be fully populated.

**Comment by ezimuel** [comment]
It seems the question has been answered. I'm closing it. @jeremyrncp let me know if you need or having more questions. Thanks!
