### ISSUE TITLE
PHP v6.1.0 client NoNodesAvailableException

### ISSUE THREAD

**Issue by dlapointeus** [elastic/elasticsearch-php#850]
### Summary of problem or feature request

We are currently running against a 2.4 deployment on Elastic cloud in our production environment, using PHP client.  We want to upgrade to version 6.x, and have created a new deployment on the cloud (v6.6.1), and have installed the PHP 6 client using Composer.  When attempting to make a simple connection on a Windows (7) machine running PHP 7.2.1 we are getting a NoNodesAvailableException when pointing to the new deployment.  When we point to the current deployment, everything seems to work as expected.  When executing the same code from Linux running PHP 7.0.33 against the new deployment, things seem to work as expected.  Code is simply:

$hosts = [
'https://user:pw@91e3da882fc746d9bf237958cd829929.us-east-1.aws.found.io:9243'     
];

$client = Elasticsearch\ClientBuilder::create()->setHosts($hosts)->build();

$info = $client->info();

In addition, using CURL directly from the Windows machine against the new deployment also seems to work as expected.

Are there any known issues with the client and this combination? (Windows - PHP Client 6.x - PHP 7.2.1).  We can continue to troubleshoot, however figured we'd ask the question before spending more time.  Please let us know if there is any additional information that would be helpful and/or if there are ways that we can get better logging to track down the issue.

Thanks!

### System details

- Windows 7 Professional
- PHP 7.2.1 (running in WAMP server 2.5)
- PHP Client 6
- Elasticsearch version v6.6.1 (cloud deployment) v 6.1.0 (Composer install - composer.lock)

**Comment by dlapointeus** [comment]
This issue was resolved by disabling SSL verification, as there was no certificate on the development machine.

**Comment by pittersnider** [comment]
@dlapointeus How did you disabled the SSL verification?

**Comment by dlapointeus** [comment]
Hi - we called the method when instantiating the client (where '$this->hosts' is just an array of connections to the Elastic cloud):
$client = Elasticsearch\ClientBuilder::create()->setHosts($this->hosts)->setSSLVerification(false)->build();

    On Tuesday, March 19, 2019, 4:12:27 PM EDT, João Pedro Viana <notifications@github.com> wrote:  
 
 
@dlapointeus How did you disabled the SSL verification?
