### ISSUE TITLE
How to use use Elasticsearch\ClientBuilder with addProcessor?

### ISSUE THREAD

**Issue by titoff002** [elastic/elasticsearch-php#852]
I would like to add the "AddProcessor" option in a search query (with use Elasticsearch\ClientBuilder;)

I do so:

`    $params = [
        'index' => $index,
        'type' => $type,
        "processors" => [
          [
            "convert" => [
              "field" => "doc.field_pricemax.keyword",
              "type"=> "integer"
            ]
          ]
        ]   ,     
         'body' => [
            'query' => [
                'bool' => [
                    'filter' => [
                      'range' => [
                          'doc.nbp' => [
                              'lte' => $nbp
                          ]
                      ]
                    ],
                    "must_not" => $must_not,
                    "must" => $must_be,
                    "should" => $should_be,
                    "filter" => $filters
                ]
          ]
        ]
    ];
    //Log::debug("PARAMS".print_r($params, true));
    $results = $this->client->search($params);`

But it returns the following errors:
`{"success":false,"msg":"\"processors\" is not a valid parameter. Allowed parameters are \"_source\", \"_source_exclude\", \"_source_include\", \"allow_no_indices\", \"analyze_wildcard\", \"analyzer\", \"batched_reduce_size\", \"client\", \"custom\", \"default_operator\", \"df\", \"docvalue_fields\", \"expand_wildcards\", \"explain\", \"fielddata_fields\", \"filter_path\", \"filter_path\", \"from\", \"human\", \"ignore_unavailable\", \"indices_boost\", \"lenient\", \"lowercase_expanded_terms\", \"pre_filter_shard_size\", \"preference\", \"q\", \"query_cache\", \"request_cache\", \"routing\", \"scroll\", \"search_type\", \"size\", \"slice\", \"sort\", \"source\", \"stats\", \"stored_fields\", \"suggest_field\", \"suggest_mode\", \"suggest_size\", \"suggest_text\", \"terminate_after\", \"timeout\", \"typed_keys\", \"version\""}`

Do you have an idea of ​​how?

**Comment by titoff002** [comment]
My problem is that I would like to make a "range" on a data of my document, but this one is considered like a "String" and thus the "range" with the ltegte does not work.

So, I think to do a "cast" (hence the use of the "processor").

Otherwise do you know how to cast a string to an integer?

**Comment by polyfractal** [comment]
If you're referring to Ingest Processors, those only work when you are indexing documents.  They don't work with the Search API.

The Range query will work on textual fields, although it's alphanumeric ordering.  

There isn't a way to "cast" already-indexed data to a different type.  Internally different types are stored in different data structures, so if you want a different underlying field type you'll need to reindex it to a new field with the correct type.

**Comment by ezimuel** [comment]
Answered by @polyfractal
