### ISSUE TITLE
Can't connect to AWS ES Service (Bad Request)

### ISSUE THREAD

**Issue by pittersnider** [elastic/elasticsearch-php#854]
### Summary of problem or feature request
I am trying to connect to an AWS elastic service through Symfony, as below:  
![image](https://user-images.githubusercontent.com/13719228/54537272-01b0b200-4971-11e9-8107-1f9bbb9050a6.png)  
  
However, I get this error:  
![image](https://user-images.githubusercontent.com/13719228/54537368-20af4400-4971-11e9-832c-906159d47b75.png)  
  
My credentials (from picture #1) are like:  
```
(host) stage-es.lewo.sms
(port) 443
(ssl) 1
(transport) AwsAuthV4
(aws_access_key_id) xxxxxx
(aws_secret_access_key) xxxxxxx
(aws_region) eu-central-1
```

**Note**: I use the same credentials to connect via FOSElastica and it works.

### System details

OS: Linux  
Symfony v3.4.23  
PHP v7.1.26  
ElasticSearch v5.6  
Elasticsearch-php ~5.0

**Comment by philkra** [comment]
@pittersnider, could you please verify if the referenced issue of @y80x86ol is solving your problem? Or generally speaking is this issue still present?

**Comment by ezimuel** [comment]
@pittersnider I replied about this issue [here](https://github.com/elastic/elasticsearch-php/issues/833#issuecomment-527387534). I'll reopen the issue if needed.
