### ISSUE TITLE
Failed to JSON encode: 5 when using unicode emojis in the request body

### ISSUE THREAD

**Issue by najdanovicivan** [elastic/elasticsearch-php#855]
### Summary of problem or feature request

When I try to index document which contains unicode emoji characters in the body I get the error 5 with json encode method

### System details

- Operating System: All OS
- PHP Version: 7.2
- ES-PHP client version: 6.1.0
- Elasticsearch version 6.6.1

**Comment by ezimuel** [comment]
This is solved by #856.
