### ISSUE TITLE
SearchHitIterator key duplicates

### ISSUE THREAD

**Issue by safecat** [elastic/elasticsearch-php#859]
### Summary of problem or feature request

SearchHitIterator will produce duplicate keys when having multiple "pages", the iterator key will be reset to 0 after every scroll be performed. First contributor of this class did write a property `$current_key`, but forgot to use it, that's the actual key to use. see: https://github.com/elastic/elasticsearch-php/blob/7241e69095ce52c121fe2e9491fa2a7207be5dcf/src/Elasticsearch/Helper/Iterators/SearchHitIterator.php#L30

If you trying to reproduce the problem in the master branch now, you will find the first page will be showed twice because of issue #595 , after I fixed that in pr #858 , you'll find bug described in this issue. these two bugs are not related.

### Code snippet of problem

```php
$scroll_iterator = new SearchResponseIterator($client, $search_params);
$hit_iterator = new SearchHitIterator($scroll_iterator);
foreach ($hit_iterator as $key => $record) {
    var_dump("key:{$key} _id:{$record['_id']}");
}
```
shows below when **scroll size is 3 and I have 7 docs**.
```
(iterator performing search request...)
key:0 _id:id1
key:1 _id:id2
key:2 _id:id3
(iterator performing scroll request...)
key:0 _id:id4
key:1 _id:id5
key:2 _id:id6
(iterator performing scroll request...)
key:0 _id:id7
(iterator performing scroll request...)
```

- mac/ubuntu
- 5.6
- 5.4.0
- 5.5

**Comment by ezimuel** [comment]
Hi @safecat, I'm the new maintainer of this library. I'll review this PR soon. Thanks!
