### ISSUE TITLE
Interface enforces constructor

### ISSUE THREAD

**Issue by turkelt0n** [elastic/elasticsearch-php#863]
### Summary of problem or feature request

https://github.com/elastic/elasticsearch-php/blob/8248c9f0886f863d033131ceb9dce1f8b0b093a8/src/Elasticsearch/Connections/ConnectionFactoryInterface.php#L28

I'm having trouble understanding the purpose of a constuctor being defined inside an interface. As I understand the purpose of the interface is to ensure an implementaion of a ConnectionInterface is delivered. As long as this is the case the interface should not telll me what to inject during the construction of the factory.

**Comment by okneloper** [comment]
Agreed, a constructor doesn't make any sense on an interface. It has the opposite effect to the purpose of an interface (which is to abstract things).

**Comment by ezimuel** [comment]
@turkelt0n and @okneloper I'll remove it in 7.0.0. I agree, doesn't make any sense.

**Comment by ezimuel** [comment]
Removed with elasticsearch-php 7.0.0, see [here](https://github.com/elastic/elasticsearch-php/blob/v7.0.0/src/Elasticsearch/Connections/ConnectionFactoryInterface.php).
