### ISSUE TITLE
Slices param in updateByquery function doesn't work 

### ISSUE THREAD

**Issue by Aassifh** [elastic/elasticsearch-php#866]
Hi, 
I'm trying to put a slices param in my params array for the updateByquery function but it does seem to work ?

Help ?

Thanks

**Comment by ezimuel** [comment]
@Aassifh can you try with elasticsearch-php 7.0.0 and let me know? Thanks.

**Comment by ezimuel** [comment]
We added the `slice` parameter for updateByQuery endpoint in 7.0.0 [here](https://github.com/elastic/elasticsearch-php/blob/v7.0.0/src/Elasticsearch/Endpoints/UpdateByQuery.php#L96).
