### ISSUE TITLE
Trailing slashes breaking some operations when using a credential provider

### ISSUE THREAD

**Issue by timoschinkel** [elastic/elasticsearch-php#869]
The exception is thrown in another library - https://github.com/jeskew/amazon-es-php - but maybe the fix should be made in this repository. Therefore I am raising an issue in this repository as well.

For reference, the issue in https://github.com/jeskew/amazon-es-php: https://github.com/jeskew/amazon-es-php/issues/17

When switching Elasticsearch cluster I copied the endpoint uri and received the uri including trailing slash. This led to failed calls for some operations due to an invalid uri exception.

### Reproduction scenario
I have been able to reproduce this issue using https://github.com/jeskew/amazon-es-php, but any handler that "simply" copies a path behind the host it receives might be affected.

```php
$handler = new \Aws\ElasticsearchService\ElasticsearchPhpHandler(
    'eu-west-1', 
    CredentialProvider::defaultProvider()
);
$client = \Elasticsearch\ClientBuilder::fromConfig([
    'hosts' => ['http://host.docker.internal:9200/'], 
    'handler' => $handler
], true);

$client->info()
```

This will lead to an `InvalidArgumentException` with the message "'Unable to parse URI: //'" to be triggered in the creation of a PSR-7 request at https://github.com/jeskew/amazon-es-php/blob/b2b5634e4662f5d620891bda9b6d0af73954043c/src/ElasticsearchPhpHandler.php#L63

The path of the uri is `/`, to get the information of the host `/` is added and thus the uri becomes `//`, which in itself is an invalid uri. I have only seem this issue occur with this operation, since the other operations add something to the path resulting in uris like `//my_index`. Those uris *are* excepted by the `Uri` constructor. 

The easiest solution might be to add a sanitization step to `\Elasticsearch\ClientBuilder::setHosts()` that removes trailing slashes. I am willing to look into making a PR to accomplish that.

### System details
- PHP 7.2
- `jsq/amazon-es-php` version `0.2.3` (latest stable)
- `elasticsearch/elasticsearch` version `6.1.0` (latest stable)
- OS: standard `php:7.2-fpm` Docker container

**Comment by ezimuel** [comment]
@timoschinkel the `hosts` parameter for `Elasticsearch\ClientBuilder` should be specified using `hostname:port` syntax or `https://hostname:port` without the trailing slash, see the documentation [here](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_configuration.html#_inline_host_configuration). If you use trailing slash this is a syntax error.
If you have problem using the `jeskew/amazon-es-php` library please open an issue on that repository.
Thanks.
