### ISSUE TITLE
How to echo data from specific field(s)

### ISSUE THREAD

**Issue by joemsanchez** [elastic/elasticsearch-php#878]
### Summary of problem or feature request

Ok not really a problem, its more of lack of understanding on my part.  Using quickstart, I have a search query below.  The query works great, but I want to build something off that data.  For instance, I want to echo a field labeled "beat,name", and a field labeled "Total".  I assume I could echo it as an array like ```$result['_source']['Total']```.  That method works if i use get instead of search.  Additionally I would filter by most recent timestamp.  What would be the correct way to echo specific field(s) from a search?

### Code snippet of problem
```
$indexParams['index'] = 'filebeat-';
$indexParams['type'] = 'doc';
$indexParams['body']['query']['match']['beat.name'] = 'somehostname';

$results = $client->search($indexParams);
$result = (json_encode($results));
```

### System details

- Operating System
- PHP Version: 5.6.30
- ES-PHP client version: 6.5
- Elasticsearch version: 6.3.1

**Comment by sn01615** [comment]
[https://github.com/elastic/elasticsearch-php/issues/853#issuecomment-501772254](url)

**Comment by ezimuel** [comment]
Answered by @sn01615 in [#853 comment](https://github.com/elastic/elasticsearch-php/issues/853#issuecomment-501772254)
