### ISSUE TITLE
ElasticSearch 7 compatibilty

### ISSUE THREAD

**Issue by petericebear** [elastic/elasticsearch-php#880]
Hi,

Is it possible to use the Elasticsearch PHP module or is it best to wait for a new release?
Any change you can give an estimate of the release for Elasticsearch 7?

Currently I am using the version 6 version, and for what I need is it good enough at this point. Just curious about the timeframe.

Greetings,
Peter

**Comment by ezimuel** [comment]
@petericebear I'm working to release 7.0.0 asap (maybe next week). Today I'll release 6.7.0 to fix some missing changes in the Elasticsearch API.

**Comment by Hyperkubus** [comment]
Any news on the 7.0.0 version?

**Comment by jgorlin** [comment]
I’m also looking for a version compatible with 7.0. Any ETA on availability?

**Comment by ezimuel** [comment]
@Hyperkubus, @jgorlin I'll release the 7.0.0 version later this week.

**Comment by thanhnv37** [comment]
Any updates on the version 7.0? 
Thank you very much for your great work.

**Comment by michaelpetri** [comment]
Is there anyway we can help with the release?

**Comment by ezimuel** [comment]
I'm running some issue with integrational tests, I'm fixing it an it will follow the release.
@michaelpetri thanks for you help, I think at this stage it will be helpful to look for issues or outdated info in the [documentation](https://github.com/elastic/elasticsearch-php/tree/master/docs).
Thanks for your support!

**Comment by StringKe** [comment]
When is the release of the test version, there are many people who are willing to help fix the problem.

**Comment by eXistenZNL** [comment]
Any updates on this? Looking forward to it!

**Comment by ezimuel** [comment]
@eXistenZNL, @StringKe I've almost completed the `elasticsearch-php` 7.0.0. You can find a preview in [feature/7.0.0](https://github.com/ezimuel/elasticsearch-php/tree/feature/7.0.0) branch of my repo `ezimuel/elasticsearch-php`. 

If you see the results of Travis CI, there are still [3 errors](https://travis-ci.org/ezimuel/elasticsearch-php/jobs/541793539#L796) and [12 failures](https://travis-ci.org/ezimuel/elasticsearch-php/jobs/541793539#L905). These are the YAML integration tests provided by Elasticsearch [here](https://github.com/elastic/elasticsearch/tree/v7.0.0/rest-api-spec/src/main/resources/rest-api-spec/test). I'm working to solve it and I'll release the 7.0.0 after.

@michaelpetri if you want to help you can update the phpdoc related to all the endpoints. For instance, this is the documentation of [cat.fielddata](https://github.com/elastic/elasticsearch/blob/v7.0.0/rest-api-spec/src/main/resources/rest-api-spec/api/cat.fielddata.json) endpoint that should be reported [here](https://github.com/ezimuel/elasticsearch-php/blob/feature/7.0.0/src/Elasticsearch/Namespaces/CatNamespace.php#L423-L431). I know, this should be autogenerated by a script. I'm also working on it :-)

Thanks everyone for the support and your patience!

**Comment by willyk** [comment]
Hi @ezimuel,
Congratulate yourself for the work, we just did the tests and it works
We expect the release in the stable branch for productive environments ASAP

**Comment by michaelpetri** [comment]
Thanks for your work!

**Comment by thanhnv37** [comment]
I can confirm that it works well with Elasticsearch 7.0.1.
Thanks for your great work!

**Comment by txj123** [comment]
Thanks for your great work!

**Comment by ezimuel** [comment]
I finally fixed all the integration tests! Now the [tests are passing](https://travis-ci.org/ezimuel/elasticsearch-php/builds/544270647) on Travis CI. I'll release 7.0.0 tomorrow than!

**Comment by ezimuel** [comment]
I just released [elasticsearch-php 7.0.0](https://github.com/elastic/elasticsearch-php/releases/tag/v7.0.0). Thanks to all of you for the support!
