### ISSUE TITLE
Function Missing in ClientBuilder.php file

### ISSUE THREAD

**Issue by WebkulOpencart** [elastic/elasticsearch-php#881]
### Summary of problem or feature request
I have found that defaultLogger() function is missing in this file which used to set the elastic search log file path initialization before calling the setlogger() to set the custom log file to store the elastic search logs.

### System details

- Operating System Linux
- PHP Version 7.1
- ES-PHP client version 6.0
- Elasticsearch version 6.7.1

**Comment by ezimuel** [comment]
@WebkulOpencart the defaultLogger() has been removed with elasticsearch-php v. 6.0, see #674. It is recommended to create the logger object manually, see [here](https://github.com/elastic/elasticsearch-php/blob/master/docs/configuration.asciidoc#enabling-the-logger).
