### ISSUE TITLE
Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true

### ISSUE THREAD

**Issue by LJFPHP** [elastic/elasticsearch-php#883]
I encountered this error when I updated mapping.
My guess is that because of the type change after elasticsearch-7.0, the current version of ES-PHP is not compatible with the latest es version. So how to solve this problem? Modifying the source code is too complicated

This is the first time for me to submit a question in English. Thank you for your reply

- Operating System
- PHP 7.1
- ES-PHP master
- Elasticsearch 7.0

**Comment by tegansnyder** [comment]
I haven't checked this myself, but there is an option to include a custom param:
https://github.com/elastic/elasticsearch-php/blob/master/docs/per-request-configuration.asciidoc#providing-custom-query-parameters

Not tested:
```php
$client = ClientBuilder::create()->build();

$params = [
    'index' => 'some_index',
    'client' => [
        'custom' => [
            'include_type_name' => 'false'
        ]
    ]
];

$response = $client->indices()->getMapping();

print_r($response);
```

**Comment by LJFPHP** [comment]
> 我自己没有检查过，但是可以选择包含自定义参数：[https](https://github.com/elastic/elasticsearch-php/blob/master/docs/per-request-configuration.asciidoc#providing-custom-query-parameters)：
> [//github.com/elastic/elasticsearch-php/blob/master/docs/per-request-configuration.asciidoc#providing-custom -query参数](https://github.com/elastic/elasticsearch-php/blob/master/docs/per-request-configuration.asciidoc#providing-custom-query-parameters)
> 
> 未经测试：
> 
> ```
> $ client  =  ClientBuilder :: create（）- > build（）;
> 
> $ params  = [ 
> ' index ' => ' some_index '，' client ' => [ ' custom ' => [ ' include_type_name ' => false         ]     ] ];      
>      
>          
>               
> 
> 
> 
> 
> $ response  =  $ client - > indices（）- > getMapping（）;
> 
> print_r（$ response）;
> ```


Thank you. It works.Here is the code

 $params = [
            'index' => 'user',
                'custom' => [
                    'include_type_name' => true
            ],
            'type'=>'_doc',
            'body' => [
            'properties' => [
]
]
]
