### ISSUE TITLE
GitException when running RestSpecRunner

### ISSUE THREAD

**Issue by gempir** [elastic/elasticsearch-php#887]
When running the `php util/RestSpecRunner.php` like described here:
https://github.com/elastic/elasticsearch-php/blob/master/.github/CONTRIBUTING.md

I get the following problem:

```
Fatal error: Uncaught GitWrapper\GitException: error: pathspec 'b7e28a7' did not match any file(s) known to git
 in /Users/dpasch/dev/moebel/services/content_api/src/vendor/elasticsearch/elasticsearch/vendor/cpliakas/git-wrapper/src/GitProcess.php:83
```

### System details
- OS macOS 10.14
- PHP 7.2.5
- Version master (0661e83cbfe7f3b548e8cd409028d4575e951cc6) or my branch  https://github.com/gempir/elasticsearch-php/tree/index-closed
- ES 6.5.4

**Comment by ezimuel** [comment]
@gempir you need to run this command before the `RestSpecRunner.php` execution:
```
git submodule update --init --recursive
```
Basically, this command fetch `util/elasticsearch` folder with the submodule. After that, you can run `util/RestSpecRunner.php` to checkout the specific tag version of the running Elasticsearch.
Please note that I updated the integration tests to work with docker, using the script [travis/run_es_docker.sh](https://github.com/elastic/elasticsearch-php/blob/master/travis/run_es_docker.sh).

**Comment by gempir** [comment]
Sorry! That was even documented in the CONTRIBUTION file, I overread it. My bad. Thanks!
