### ISSUE TITLE
WARNING:elasticsearch:POST http://xxxx:9200/_bulk [status:400 request:0.004s]

### ISSUE THREAD

**Issue by xxshazxx** [elastic/elasticsearch-php#893]
I've updated to the latest twint and I'm getting the error message:
WARNING:elasticsearch:POST http://192.168.1.10:9200/_bulk [status:400 request:0.004s]

`            d = twint.Config()
            d.Username = u_twitter
            d.Elasticsearch = "192.168.1.10:9200"
            d.Index_tweets = db_tweets
            d.User_full = False
            d.Since = since_date
            try:
                twint.run.Search(d)`

- Operating System Ubuntu 16.04
- Python 3.7
- Elasticsearch version 
 "version" : {
    "number" : "6.6.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "1fd8f69",
    "build_date" : "2019-02-13T17:10:04.160291Z",
    "build_snapshot" : false,
    "lucene_version" : "7.6.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"

What this could be ?

**Comment by philkra** [comment]
Please note that this is the PHP agent and you are asking a Python specific question, please consult the py client: https://github.com/elastic/elasticsearch-py
