### ISSUE TITLE
Scroll TTL is extracted but not set as a body param., It cause scroll expired, so only second page is available.

### ISSUE THREAD

**Issue by kickenhio** [elastic/elasticsearch-php#906]
https://github.com/elastic/elasticsearch-php/blob/2b9a84d606a21b7be55909fd2ab342fc66642fc8/src/Elasticsearch/Client.php#L1029

**Comment by ezimuel** [comment]
@kickenhio thanks for reporting the issue. Did you try to pass the `scroll` parameter in the body of the request? Let me know, thanks.

**Comment by kickenhio** [comment]
Yes I did and it works. But, still,  its kind of workaround and its not consistent to previous library version or function comment itself.

**Comment by ezimuel** [comment]
@kickenhio I refactored all the endpoints to use the [new API specification](https://github.com/elastic/elasticsearch/tree/v7.0.0/rest-api-spec/src/main/resources/rest-api-spec/api) provided by Elasticsearch 7. I need to double check the `scroll` parameter in this case. I'll update you soon.

**Comment by ezimuel** [comment]
@kickenhio I just sent this PR #907 that fixes the issue. Can you try and let me know? Thanks!

**Comment by ezimuel** [comment]
Feedback provided by @brunogaspar in #907

**Comment by brunogaspar** [comment]
Thanks @ezimuel for the fix!
