### ISSUE TITLE
Consolidate X-Pack into Client

### ISSUE THREAD

**Issue by philkra** [elastic/elasticsearch-php#908]
Please merge the [elasticsearch-x-pack-php](https://github.com/elastic/elasticsearch-x-pack-php) repository into the Client.

**Comment by ezimuel** [comment]
I released XPack endpoints with [elasticsearch-php 7.7.0](https://github.com/elastic/elasticsearch-php/releases/tag/v7.7.0). I will also add the XPack support in `elasticsearch-php 6.8.0`.
