### ISSUE TITLE
Wrong type hint of setBody of Endpoints\Ingest\Pipeline\Put

### ISSUE THREAD

**Issue by franmomu** [elastic/elasticsearch-php#912]
### Summary of problem or feature request

I was testing with [Elastica](https://github.com/ruflin/Elastica/blob/master/test/Elastica/Base.php#L144) library and there were some errors because of [`setBody(string $body)`](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Ingest/Pipeline/Put.php#L21). I've check and all the Endpoints extending `AbstractEndpoint` overriding `setBody` don't have this type hint, but the Put one. Should this be reverted or is it on purpose?

**Comment by Hrezaei** [comment]
I encountered the same problem by calling some thing like this:

```php 
$pipline = [
    'id' => 'my_pipline',
    'body' => [...]
];
  
$es->ingest()->putPipeline($pipline); 
```


The error is:

`Argument 1 passed to Elasticsearch\Endpoints\Ingest\Pipeline\Put::setBody() must be of the type string, array given, called in .../vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IngestNamespace.php on line 94`
