### ISSUE TITLE
Client future lazy is not working with swoole

### ISSUE THREAD

**Issue by leocarmo** [elastic/elasticsearch-php#914]
Im using this package `swooletw/laravel-swoole` with elastic client with future lazy client and nothing happens.

If i remove the `'future' => 'lazy'` from client works.

Working:
```php
$params = [
    'index' => 'swoole',
    'type' => 'doc',
    'body' => $body,
];
```

Not working:
```php
$params = [
    'swoole',
    'type' => 'doc',
    'body' => $body,
    'client' => [
        'future' => 'lazy',
    ]
];
```

- PHP Version: 7.2
- ES-PHP client version: ~6.0
- Elasticsearch version: 6.7.0

**Comment by ezimuel** [comment]
The  [future](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/future_mode.html) features supports only Curl at the moment (using `curl_multi_*` functions). I'm planning to support `swoole` for the next major version (8.0.0).
