### ISSUE TITLE
no query registered for function_score

### ISSUE THREAD

**Issue by nashgao** [elastic/elasticsearch-php#921]
I wanted to run a match query on different fields with weights. I used the function_score method but I kept getting no query registered for function_score. 

This is my code: 

`$params['body'] = [    
                    'from' => "$from",
                    'size' => "$this->size",
                    'query'=>[
                        'function_score' => [
                            'query' => [
                                'match_all' => (object)[], 
                            ],
                            'functions' => [
                                    [
                                        'fitler' => [
                                            'match' => [
                                                'title' => $term,
                                            ]
                                        ],
                                        'weight' => 20,
                                    ],
                                    [
                                        'filter' => [
                                            'match' => [
                                                'content' => $term
                                            ]
                                        ],
                                        'weight' => 10,
                                    ],
                                    [
                                        'filter' => [
                                            'match' => [
                                                'tags' => $term,
                                            ]
                                        ],
                                        'weight' => 65
                                    ]
                            ],
                            "field_value_factor" => [               
                                "field" => "vote",
                                "factor" => 1.2,
                                "modifier" => "sqrt",
                                "missing" => 1
                            ]
                        ]
                    ],
                    'sort' => [
                        '_geo_distance' => [
                            'geo' => [
                                'lat' => $lat,
                                'lon' => $lon
                            ],    
                            'order' => 'asc',
                            'unit' => 'km',
                            'distance_type' => 'plane'       
                        ], 
                    ],
                ];`

I acturally followed the es document for 6.5:
GET /_search
`{
    "query": {
        "function_score": {
          "query": { "match_all": {} },
          "boost": "5", 
          "functions": [
              {
                  "filter": { "match": { "test": "bar" } },
                  "random_score": {}, 
                  "weight": 23
              },
              {
                  "filter": { "match": { "test": "cat" } },
                  "weight": 42
              }
          ],
          "max_boost": 42,
          "score_mode": "max",
          "boost_mode": "multiply",
          "min_score" : 42
        }
    }
}`

I'm running on Ubuntu 16.04 with php7.3, es-php 6.7 and es 6.5.3.

I tried to put the field_value_factor into the "functions" array and it was working. But I'm not sure how to give weight to each field for a fuzzy search.

`Thanks.```

**Comment by ezimuel** [comment]
@nashgao I'm not sure I've understood your question. Do you want to know how to evaluate the weights in order to query in the `function_score`? In this manual page there are some information about weights: https://www.elastic.co/guide/en/elasticsearch/reference/6.5/query-dsl-function-score-query.html
If you can send me more information I can try to help you futher, thanks!

**Comment by philkra** [comment]
@nashgao please note that you have typo, `'fitler'` needs to be `'filter'`. Does that solve your problem?

**Comment by nashgao** [comment]
yeah it is the typo, also I was using field_value_factor when I already defined the functions, that was another issue. Thank you guys for the reply XD

**Comment by junfengwang** [comment]
failed to parse [function_score] query. array [filter] is not supported
my code:
`            'body' => [
                'query' => [
                    "function_score" => [
                        "filter" => [
                            [ 'term' => [ 'sex' => 'F' ] ],
                            [ 'term' => [ 'real_person' => true ]],
                        ],
                        "functions" => [
                            [
                                "filter" => [ "term" => [ "job_region" => "173" ]],
                                "weight" => 1
                            ],
                            [
                                "filter" => [ "term" => [ "is_online" => true ]],
                                "weight" => 2
                            ],
                        ],
                        "score_mode" => "sum",
                    ],
                ],
            ],`
