### ISSUE TITLE
Wrong parameters [7.1.1]

### ISSUE THREAD

**Issue by KaidoRen** [elastic/elasticsearch-php#928]
`Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]])`
at _./vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php_:**632**:

```php
$exception = new ServerErrorResponseException($responseBody, $statusCode);
```

Even exceptions don't help. How to solve this problem?

**Comment by KaidoRen** [comment]
This happens when I access the exists function to check if there is a document with this ID.

```php
$client->exists([
            'index' => 'myindex',
            'type' => 'mytype',
            'id' => 12
        ]
);
```

**Comment by ezimuel** [comment]
@KaidoRen I just tested the following code with `elasticsearch-php 7.1.1` and `Elasticsearch 7.1.1` and it works fine (`$response` is `false`):

```php
require 'vendor/autoload.php';

use Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()->build();

$response = $client->exists([
        'index' => 'myindex',
        'type' => 'mytype',
        'id' => 12
    ]
);
var_dump($response);
```

What version of Elasticsearch are you running? Can you try this snippet code on your side? Thanks!

**Comment by KaidoRen** [comment]
My problem appears here - [click](https://github.com/KaidoRen/elasticquent-lite-search/blob/master/src/Utils/ElasticsearchUtils.php#L108). I put all the parameters in the log, there are no errors

**Comment by ezimuel** [comment]
@KaidoRen it seems you are getting some 5xx error from Elasticsearch server. Are you sure that `$params` [here](https://github.com/KaidoRen/elasticquent-lite-search/blob/master/src/Utils/ElasticsearchUtils.php#L108) contains the array that you suggested, as follows? 

```php
[
    'index' => 'myindex',
    'type' => 'mytype',
    'id' => 12
]
```
The `ServerErrorResponseException` accepts a string as first parameter. For some reason, the response body is `NULL` and it generates the error [here](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Connections/Connection.php#L657). 
Which version of Elasticsearch are you using to test your code?

**Comment by KaidoRen** [comment]
@ezimuel  Yes, I getting 5xx error. I am using 7.1.1 version. In logs this parameter is string

**Comment by ezimuel** [comment]
@KaidoRen did you try `elasticsearch-php 7.2.0`? The 7.1.1 version is only compatible with Elasticsearch from 7.0 to 7.1 included, see version matrix [here](https://github.com/elastic/elasticsearch-php#version-matrix).

**Comment by KaidoRen** [comment]
@ezimuel, unfortunately, nothing has changed. 
![image](https://user-images.githubusercontent.com/29752127/63175280-21055580-c05d-11e9-9d2f-052df393241d.png)
