### ISSUE TITLE
Analyze method of indices() throws invalid parameters error

### ISSUE THREAD

**Issue by alok0590** [elastic/elasticsearch-php#931]
### Summary of problem or feature request

Analyze method of indices() throws invalid parameters error

"analyzer" "text" are not valid parameters. Allowed parameters are 'error_trace', 'filter_path', 'human', 'index', 'pretty', 'source'

### Code snippet of problem

```
$client = ClientBuilder::create()->build();
$response = $client->indices()->analyze([
      'index'    => 'attributes',
      'text'     => $q,
      'analyzer' => 'MyCustomAnalyzer',
    ]);
```

### System details

- PHP Version : 7.2
- ES-PHP client version : 7.1
- Elasticsearch version : 7.0.1

**Comment by ezimuel** [comment]
@alok0590 `text` and `analyzer` values must be part of the `body`, as follows:

```php
$response = $client->indices()->analyze([
    'index'    => 'attributes',
    'body' => [
        'text'     => $q,
        'analyzer' => 'MyCustomAnalyzer'
    ]
]);
```

See the analyze API documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-analyze.html).

**Comment by alok0590** [comment]
@ezimuel thanks for your response. I'll look into this, closing the issue for now.
