### ISSUE TITLE
json_decode() fails with SmartSerializer.php due to a malformed character from Elasticsearch

### ISSUE THREAD

**Issue by emiksk** [elastic/elasticsearch-php#934]
### Summary of problem or feature request
In some rare case, Elasticsearch returns a search result containing a malformed character at the end of the highlight field.
For example, the character at the end of the highlight field can be "\uD83C" if the document contains the emoji of cherry blossom (🌸: \uD83C\uDF38) .
In this case, the elasticsearch-php client can't handle the response. When $client->search() is called, the client throws a JsonErrorException with the message saying "Attempted to decode nonexistent UTF-16 code-point".
https://github.com/elastic/elasticsearch-php/blob/b8e3bc9d1fc54d6a18692df0b74956efe7fe241a/src/Elasticsearch/Serializers/SmartSerializer.php#L82

In case of other clients such as Java, the malformed character is garbled, but it never causes an error.

Could you help me work around this problem?
Thank you.

### Details of my system
- OS: Ubuntu 16.04
- PHP: 7.2.19
- elasticsearch-php: 6.0.1  # so old... I'll upgrade this, but the version is irrelevant to the reproducibility of this problem.
- Elastisearch: 6.8.0

**Comment by ezimuel** [comment]
@emiksk thanks for reporting the issue. Can you give me a complete example to reproduce the issue? In particular, where are located the `\uD83C\uDF38` characters in the HTTP response from ES?
Thanks!

**Comment by emiksk** [comment]
@ezimuel 
Thank you so much for your response.

OK, the followings are the simplified example to reproduce this issue.
In fact, I'm using the own custom analyzer, other highlighting parameters such as fragment_size, and so on.

1. index.json: The settings and mappings for an index
```
{
  "settings": {
    "analysis": {
      "analyzer": {
        "default": {
          "filter": [
            "cjk_bigram_filter"
          ],
          "tokenizer": "standard"
        }
      },
      "filter": {
        "cjk_bigram_filter": {
          "type": "cjk_bigram",
          "ignored_scripts": [],
          "output_unigrams": true
        }
      }
    }
  },
  "mappings": {
    "doc": {
      "dynamic": "strict",
      "properties": {
        "data": {
          "type": "text",
          "term_vector": "with_positions_offsets"
        }
      }
    }
  }
}
```

2. document.json: The document data for testing
```
{
  "data": "【This is the text for reproducing the issue】
【今日の作業】
・10:00-11:30 ミーティング（フリースペース）
・13:00-13:30 🌸タスク🌸:定型データ入力
・13:30-14:00 ..."
}
```

3. search.json: The body to search
```
{
  "query": {
    "bool": {
      "must": {
        "query_string": {
          "query": "\"ミーティング\"",
          "fields": [
            "data"
          ],
          "default_operator": "and"
        }
      }
    }
  },
  "highlight": {
    "pre_tags": [
      "4bde2e4c-58b8-42fc-acaf-cb20f60fec4b"
    ],
    "post_tags": [
      "ea7a3b14-470c-482b-a889-64ad09c26e92"
    ],
    "fragment_size": 52,
    "number_of_fragments": 1,
    "fields": {
      "data": {
        "fragment_size": 52,
        "type": "fvh"
      }
    },
    "highlight_query": {
      "bool": {
        "must": {
          "query_string": {
            "query": "\"ミーティング\"",
            "fields": [
              "data"
            ],
            "default_operator": "and"
          }
        }
      }
    }
  }
}
```

4. You can reproduce the issue by the following procedure.
```
# Elasticsearch v6.8.0 is running on localhost with the default port.
$ curl -XPUT -H 'Content-Type: application/json' localhost:9200/test -d @index.json
$ curl -XPOST -H 'Content-Type: application/json' localhost:9200/test/_doc/1 -d @document.json
$ curl -XPOST -H 'Content-Type: application/json' localhost:9200/test/_search?pretty -d @search.json
# The search result is... 
{
  "took" : 26,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 4.7742524,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "doc",
        "_id" : "2",
        "_score" : 4.7742524,
        "_source" : {
          "data" : "【This is the text for reproducing the issue】【今日の作業】・10:00-11:30  ミーティング（フリースペース）・13:00-13:30 \uD83C\uDF38タスク\uD83C\uDF38:定型データ入力・13:30-14:00 ..."
        },
        "highlight" : {
          "data" : [
            "issue】【今日の作業】・10:00-11:30 4bde2e4c-58b8-42fc-acaf-cb20f60fec4bミーティン グea7a3b14-470c-482b-a889-64ad09c26e92（フリースペース）・13:00-13:30 \uD83C"
          ]
        }
      }
    ]
  }
}
```

The above search result contains the malformed character, "\uD83C", at the end of highlight.data[0].
"data"[0]: "...・13:00-13:30 **\uD83C**"

In this example, I'm using the curl command to search. If I use the search() of elasticsearch-php client with the same parameter as search.json, the client throws a JsonErrorException.

Thanks a lot!

**Comment by emiksk** [comment]
This issue is caused by using `fvh` as highlighter. Ref. elastic/elasticsearch#45771.
I decided to use `unified` highlighter instead of `fvh`.
So I'll close this issue. Thank you for your support.

**Comment by ezimuel** [comment]
Thanks @emiksk for sharing this.
