### ISSUE TITLE
'version' no longer supported in update API

### ISSUE THREAD

**Issue by etlel** [elastic/elasticsearch-php#941]
According to the [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html), it is possible to use the `version` parameter in the update API to specify that the document should only be updated if its version matches the one specified.

But this parameter has recently been removed from the whitelist for update endpoint: 56163ffecd8978804fef2117209b3b9713be8259 (@ezimuel).

Accordingly, using `version` is now triggering an exception.

Version: Elasticsearch 7.3 / Elasticsearch-php 7.2

**Comment by ezimuel** [comment]
@etel according to the API specifications that I use to generate the parameters endpoint, `version` is not allowed anymore, see [here](https://github.com/elastic/elasticsearch/blob/v7.3.0/rest-api-spec/src/main/resources/rest-api-spec/api/update.json#L31-L77).
I just opened https://github.com/elastic/elasticsearch/issues/45961 to check if this a documentation issue or not.

**Comment by ezimuel** [comment]
Just found that we don't support anymore the `version` parameter for Update API, see https://github.com/elastic/elasticsearch/pull/43516. The online documentation must be fixed. I'm working on it, thanks for reporting the issue.
