### ISSUE TITLE
primary_port missing from response?

### ISSUE THREAD

**Issue by pixelplant** [elastic/elasticsearch-php#955]
### Summary of problem or feature request

I just updated to 7.3 and I am trying to index some of my data on an AWS elasticsearch instance. It worked fine with previous versions but now it fails while logging the data. This happens while it calls the *logRequestSuccess* method, and in the $response object the only key inside 'transfer_stats' is *total_time*

### Code snippet of problem
```
 ErrorException  : Undefined index: primary_port

  at /var/www/neho_laravel/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:378
    374|             'Request Success:',
    375|             array(
    376|                 'method'    => $request['http_method'],
    377|                 'uri'       => $response['effective_url'],
  > 378|                 'port'      => $response['transfer_stats']['primary_port'],
    379|                 'headers'   => $request['headers'],
    380|                 'HTTP code' => $response['status'],
    381|                 'duration'  => $response['transfer_stats']['total_time'],
    382|             )

  Exception trace:
```

### System details

Laravel 5.8 using PHP 7.3 and the latest version of elasticsearch-php
On AWS we're using ElasticSearch 7.1

Just commenting this line ```'port'      => $response['transfer_stats']['primary_port']``` makes it work properly. Indexing succeeds and data is properly returned from AWS. Maybe add a simple isset on it?

**Comment by pixelplant** [comment]
Downgraded to 7.0.2 as per the docs

**Comment by cyrnetix** [comment]
Just upgraded my cluster to 7.5.1 and the vendor to 7.4.1 and receiving the same notice.

**Comment by tonyyb** [comment]
Seems fixed with : https://github.com/elastic/elasticsearch-php/commit/0c1e0ca76722a5d4586e7afabe0f37fb1c3885d3

@ezimuel do you plan a release soon please ?

I think that https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Connections/Connection.php#L420 line can be also fixed.
