### ISSUE TITLE
About partial string matching in full text search

### ISSUE THREAD

**Issue by urmila-patel** [elastic/elasticsearch-php#956]
### Summary of problem or feature request

I want partial string match in full text search.

### Code snippet of problem
My current code look like this
'body' => [
                    'query' => [
                        'match' => [
                            '_all' => "$string"
                        ]
                    ]
                ]

Example : If I user **transfer** word as search then it will search only for **transfer** , I want like **transferring** also come in search result

As per documentation I had tried 
 'match' => [
                            '_all' => "*.$string.*"
                        ]
But its not working.

Any solution for this?

### System details

- Operating System
- PHP Version
- ES-PHP client version
- Elasticsearch version

**Comment by csizmazia** [comment]
You need to use an NGram tokenizer:
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-ngram-tokenizer.html

**Comment by ezimuel** [comment]
@urmila-patel I'm closing this issue, let me know if you want to reopen it. Thanks!
