### ISSUE TITLE
Backport/copy .gitattributes into branches

### ISSUE THREAD

**Issue by reedy** [elastic/elasticsearch-php#958]
It's great to see a .gitattributes file in master, but is it possible to get it backported/copied into actively maintained released branches?

It'd be rather useful there too for those of us not using a 7.x version

Thanks in advance

**Comment by reedy** [comment]
Backported/copied into 6.7, 6.5 and 5.0. Let me know if any other branches are useful to have it backported to

**Comment by ezimuel** [comment]
I merged all the PRs. Thanks!
