### ISSUE TITLE
Bulk index of serialized data

### ISSUE THREAD

**Issue by domagoj-orioly** [elastic/elasticsearch-php#963]
### Summary of problem or feature request

If we index documents one by one and set the `body` parameter to be a serialized string, elastic client's serializer is happy with that and returns it as is, however, I can't find a way to do this for bulk requests because it seems bulk requests only accept associative array for document body object.

### Code snippet of problem
Example from: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/indexing_documents.html#_bulk_indexing
```php
    $params['body'][] = [
        'index' => [
            '_index' => 'my_index',
            '_id'    => $i
        ]
    ];

    // Currently:
    $params['body'][] = [
        'my_field'     => 'my_value',
        'second_field' => 'some more values'
    ];

    // Proposed:
    $params['body'][] = '{}' // serialized string - won't work - parse error - expected object
    $params['body'][] = [ (object) '{}' ] // Won't work, casting the parent array also won't work

```

```php
// Indexing one by one works with serialized data
 $client
            ->index(
                [
                    'index' => $index,
                    'id' => $id,
                    'body' => '{}' // This works
                ]
            );
```

-->

### System details

- Operating System: Debian
- PHP Version: 7.3
- ES-PHP client version: 7.4
- Elasticsearch version: 7.4

**Comment by ezimuel** [comment]
@domagoj-orioly I'm trying to reproduce the issue but it seems possible to use serialized string in bulk.
Are you using the default `SmartSerializer` of `ClientBuilder`? Here the code that I'm using:
```php
for($i = 0; $i < 100; $i++) {
    $params['body'][] = [
        'index' => [
            '_index' => 'my_index',
	]
    ];
    $params['body'][] = '{ \'my_field\': \'my_value\', \'second_field\': \'some more values\' }';
}
$responses = $client->bulk($params);
```
Can you report the error message that are you receiving? Thanks.

**Comment by domagoj-orioly** [comment]
Just a quick follow-up, I didn't forget about the issue, I will check back in with required info as soon as I get a chance to test this again.

**Comment by ezimuel** [comment]
@domagoj-orioly ok, l'll wait an update from you. Let me know if I can help in some way, thanks!

**Comment by ezimuel** [comment]
@domagoj-orioly I'm closing this issue. Let me know if you want to reopen it. Thanks!
