### ISSUE TITLE
"No alive nodes found in your cluster" when try to update mapping [7.4]

### ISSUE THREAD

**Issue by kispusi89** [elastic/elasticsearch-php#974]
### Summary of problem or feature request

Hello! I always get this exception, but only when use putMapping().
`$client->indices()->exists($params)`, `$client->indices()->create($params)`, `$client->indices()->delete($params)`, `$client->indices()->getMapping($params)`
work as expected, but when try `$client->indices()->putMapping($params)`, I've got this error message: 

> Elasticsearch\Common\Exceptions\NoNodesAvailableException  : No alive nodes found in your cluster

### System details

- Operating System: CentOS 7
- PHP Version: 7.2.22
- Elasticsearch version: 7.4.2 (official docker container)

**Comment by klimis** [comment]
Same as @kispusi89. I am getting the 

>    Elasticsearch\Common\Exceptions\NoNodesAvailableException  : No alive nodes found in your cluster

> 
only with putMapping. Everything else works fine

**System details**

- Operating System: Ubunti 19.04

- PHP Version: 7.2.24

- Elasticsearch version: 7.3

**Comment by ezimuel** [comment]
@kispusi89 and @klimis which version of `elasticsearch-php` are you using?

**Comment by klimis** [comment]
@ezimuel  I was using elasticsearch-php 7.4. I just updated to 7.4.1 and it seems ok now

**Comment by ezimuel** [comment]
@klimis ok, the issue seems to be related with #970. 
@kispusi89 did you try to use `elaticsearch-php` version `7.4.1`?

**Comment by ezimuel** [comment]
@kispusi89 I'm closing it. Let me know if you want to reopen it. Thanks!
