### ISSUE TITLE
Elastic search 7.5.0

### ISSUE THREAD

**Issue by luhuiya** [elastic/elasticsearch-php#981]
The new version of elastic search has release. Will it became problem if i continue using 7.4 php library version when the server is elastic search 7.5.0

**Comment by philkra** [comment]
Hi @luhuiya , you can use the `7.4.1` version of the client with Elasticsearch `7.5.0`. But, once a `7.5.x` client is available, it's highly encouraged for you to hop on the latest version. The only problem you encounter is, if you want to use endpoints introduced in Elasticsearch `7.5.0` as the client is not aware of these (yet).

**Comment by luhuiya** [comment]
noted thanks

**Comment by luhuiya** [comment]
Noted. thank you
