### ISSUE TITLE
No alive nodes found in your cluster when creating Index (7.0.2, windows 10)

### ISSUE THREAD

**Issue by jhob101** [elastic/elasticsearch-php#994]
### Summary of problem or feature request

I am working with the AWS Elastic Search service.  When trying to create an index on my local windows development environment it returns the error

`No alive nodes found in your cluster `

This sounded similar to #993 and I applied the fix suggested there so that the port is passed to the request, but the error remains.

This issue only occurs on my local machine, on the remote staging site it works fine.

```
$client = Elasticsearch\ClientBuilder::create()
  ->setHosts( [ 'https://search-xxx-xxxxxxxxxxxxxx.eu-west-2.es.amazonaws.com:443' ] )
  ->build();
$client->indices()->create( [ 'index' => 'test' ] );
```

The equivalent unathenticated cURL request works:

`curl -X PUT "https://search-xxx-xxxxxxxxxxxxxx.eu-west-2.es.amazonaws.com:443/test"`

### System details

- Operating System: Windows 10
- PHP Version: 7.2.27
- ES-PHP client version: 7.0.2
- Elasticsearch version: 7.1

**Comment by jhob101** [comment]
Related to certificate issue, now resolved

**Comment by emaillenin** [comment]
@jhob101 How did you resolve the certificate issue?
